### ISSUE TITLE
[BUG] ocsigen-toolkit.2.5.0 fails to compile after upgrade to js_of_ocaml.3.6.0

### ISSUE THREAD

**Issue by MdeLv** [ocsigen/js_of_ocaml#1005]
so, ocsigen-start can't be installed.

It looks like the eliomdep command fails:
```
### output ###
# mkdir -p _deps
# mkdir -p _deps/src/widgets/
# mkdir -p _deps/src/widgets/
# eliomdep -server -ppx -package calendar -package lwt_ppx -package js_of_ocaml-ppx.deriving -eliom-inc src/widgets/ src/widgets/ot_swipe.eliom > _deps/src/widgets/ot_swipe.eliom.server
# Fatal error: exception Fl_package_base.No_such_package("js_of_ocaml-ppx.deriving", "")
# Makefile:178: .depend: No such file or directory
# make: *** [Makefile:189: _deps/src/widgets/ot_swipe.eliom.server] Error 2
```

I'm not enough aware of `js_of_ocaml-ppx.deriving` internals, and of the syntax of the command.
In opam, I can see js_of_ocaml-ppx (and js_of_ocaml-ppx_deriving_json).

Is it an opam error or an ocsigen error?
Thanks.

**Comment by hhugo** [comment]
The command line should refer to `js_of_ocaml-ppx_deriving_json` instead of `js_of_ocaml-ppx.deriving`

**Comment by MdeLv** [comment]
Thanks. 
I just sent 2 PR for ocsigen-toolkit and ocsigen-start (same problem).

BTW
I tried to edit `.opam-switch/sources/ocsigen-toolkit.2.5.0/Makefile.options` then `opam upgrade` but it failed. It seems that opam downloads the source specified in .opam/repo/default/packages/ocsigen-toolkit/ocsigen-toolkit.2.5.0/opam (https://github.com/ocsigen/ocsigen-toolkit/archive/2.5.0.tar.gz). So it overrides any local change.

Do you know a simple way to tell opam to use a local version of a file instead of the one within the archive?

Thank you.

**Comment by hhugo** [comment]
You should use `opam pin`
