### ISSUE TITLE
[BUG] getting Warning: Consider passing '-g' option to ocamlc.

### ISSUE THREAD

**Issue by bikallem** [ocsigen/js_of_ocaml#1008]
**Describe the bug**
I am trying to build a small hello world jsoo app with dune. My dune file is as follows:
```
(executable
 (name jsoo_todomvc)
 (modes js)
 (flags
  (:standard (-g)))
 (libraries js_of_ocaml js_of_ocaml-lwt js_of_ocaml-tyxml)
 (preprocess
  (pps js_of_ocaml-ppx js_of_ocaml-ppx_deriving_json)))

(alias
 (name default)
 (deps index.html))
```
However, I keep getting the following warnings on build. 
```
js_of_ocaml .js/reactiveData/reactiveData.cma.js
Warning: '--source-map' is enabled but the bytecode program was compiled with no debugging information.
Warning: Consider passing '-g' option to ocamlc.
```
How do I get rid of this warning? I have already tried setting flags via dune ```ocamlc_flags``` but to no avail. Not sure if this is dune error or jsoo error.

**Expected behavior**
No warnings

**Versions**
ocamlc - 4.10.0
js_of_ocaml - 3.6.0
dune - 2.5.1

**Comment by hhugo** [comment]
reactiveData is not build with debug info.
You can fix it by using the master branch: `opam pin add reactiveData --dev` 
Please open an issue  https://github.com/ocsigen/reactiveData asking to release a new version on opam.

**Comment by bikallem** [comment]
Reposted to https://github.com/ocsigen/reactiveData/issues/26. Closing this one.
