### ISSUE TITLE
Optimization flag

### ISSUE THREAD

**Issue by drjdn** [ocsigen/js_of_ocaml#1025]
I recently updated to version 3.6.0 and dune was complaining about the flag "--opt=3".  This makes sense as:
```bash
js_of_ocaml build-runtime --help
```
doesn't document the `--opt=[NUM]` option.  Removing the option from dune fixes the issue.  Anyways, I'm not sure this is a bug as perhaps "--opt=3" doesn't do anything in this case.

**Comment by chenyan2002** [comment]
I have the same question. `--opt` is in `Cmd_arg.options`, but not `Cmd_arg.options_runtime_only`. Is opt=3 enabled for building runtime anyway?

**Comment by hhugo** [comment]
I believe this issue needs to be fixed while addressing https://github.com/ocaml/dune/issues/1613

**Comment by hhugo** [comment]
`opt=3` do anything when building the runtime for separate compilation
