### ISSUE TITLE
[BUG] graphics bindings (open_canvas) work only when built with "dune build --release"

### ISSUE THREAD

**Issue by adept** [ocsigen/js_of_ocaml#1029]
**Describe the bug**

1. Clone the project https://github.com/adept/ocaml-canvas-test

2. Build it with `dune build canvas.bc.js`

3. Run it with index.html supplied

4. Observe runtime error
```
     canvas.bc.js:164237 Uncaught ReferenceError: caml_gr_state_create is not defined
     at open_canvas (canvas.bc.js:164237)
     at caml_call1 (canvas.bc.js:164415)
     at onload (canvas.bc.js:164438)
     at caml_call1 (canvas.bc.js:152942)
     at canvas.bc.js:154769
``` 

Indeed, there is no `caml_gr_state_create` in scope (but there is `jsoo_runtime.caml_gr_state_create`)

5. Build the project with "dune build --release canvas.bc.js"

6. Observe that it is working now.

**Expected behavior**
Non-release build should work as well

**Versions**
- ocamlc 4.09.1
- js_of_ocaml 3.6.0

**Comment by dbuenzli** [comment]
It seems `graphics` is using an [`at_exit` handler](https://github.com/ocsigen/js_of_ocaml/blob/d1f3c616352e7116fefde2e6af70102d4f82bcee/lib/lwt/graphics/graphics_js.ml#L129) I didn't look into the details (the error is a bit weird) but I suspect you are running into https://github.com/ocsigen/js_of_ocaml/issues/1033.

**Comment by hhugo** [comment]
Graphics_js is using Js.Unsafe.variable instead of external to refer to stubs
