### ISSUE TITLE
[BUG] JavaScript parse error (rest parameters ...)

### ISSUE THREAD

**Issue by victor-dumitrescu** [ocsigen/js_of_ocaml#1031]
**Describe the bug**
A parse error (`Error: cannot parse file`) is thrown for this piece of code, particularly on the rest parameters in the first line:
```
      api_obj[key_module][key_func] = function(...args) {
        return checkIfInitialized().then(function() {
          return callWithProto(api_json[key_module][key_func], args);
        });
      };
```
Removing the rest parameters notation makes the parsing succeed. This code is part of the [hacl-wasm](https://www.npmjs.com/package/hacl-wasm) npm package.

**Versions**
* ocamlc 4.09.1
* js_of_ocaml 3.6.0

**Comment by hhugo** [comment]
Spread support was added in https://github.com/ocsigen/js_of_ocaml/pull/937 for applications.
One we need to do similar changes for rest parameters.
