### ISSUE TITLE
[BUG] Mention std_exit in separate compilation instructions

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#1033]
Separate compilation instructions should mention that to get exactly the same results as what is done by whole program compilation one should add a compilation of `std_exit` at the end of the link instruction. Otherwise [`do_at_exit`](https://github.com/ocaml/ocaml/blob/10cb814a17b5eac7d849f55c1ed72eea8a8379f5/stdlib/stdlib.ml#L560) will not be called which means `at_exit` functions won't either. 

This may not be a problem if you don't use `Sys.at_exit` handlers but it may lead to different visible program behaviour: in particular the `Stdlib.flush_all` funcction won't be called at program exit.

Whole program:

```shell
> echo "let () = print_string {|bla|}" > main.ml
> ocamlc -o main.byte main.ml 
> js_of_ocaml -o main.js main.byte 
> node main.js
bla
>
```

Separate compilation (according to current instructions):

```shell
> js_of_ocaml build-runtime -o ocaml-rt.js 
> js_of_ocaml compile -o stdlib.js $(opam var lib)/ocaml/stdlib.cma
> js_of_ocaml compile -o main.js main.cmo 
> js_of_ocaml link -o a.js ocaml-rt.js stdlib.js main.js 
> node a.js
> 
```
Adding a compilation of std_exit.cmo: 

```shell
> js_of_ocaml compile -o std_exit.js $(opam var lib)/ocaml/std_exit.cmo 
> js_of_ocaml link -o a.js ocaml-rt.js stdlib.js main.js std_exit.js    
> node a.js
bla
```

**Comment by hhugo** [comment]
One should also fix dune compilation rules

**Comment by dbuenzli** [comment]
Yes I opened an issue there. See the cross refs.
