### ISSUE TITLE
[BUG] Error: Multiple rules generated

### ISSUE THREAD

**Issue by Yann-Kaelig** [ocsigen/js_of_ocaml#1035]
**Describe the bug**
Failed bulding js_of_ocaml with dune version 2.1.0

```
dune build @install @default -j1

Error: Multiple rules generated for
_build/.aliases/default/compiler/tests-jsoo/runtest-35bbbc336be45723611745d39daa46eb:
- compiler/tests-jsoo/dune:6
- compiler/tests-jsoo/dune:6
```

**Versions**
Gentoo:
dune 2.1.0
ocaml 4.10.0
js_of_ocaml 3.6.0 and also tested with the master branch

**Logs**
[js_of_ocaml-3.6.0.log](https://github.com/ocsigen/js_of_ocaml/files/4911996/js_of_ocaml-3.6.0.log)

**Others**
I'm pretty new on ocaml stuff, please feel free to let me know if you need more info or test.
Thx

**Comment by hhugo** [comment]
js_of_ocaml requires `dune >= 2.5`. Can you try to upgrade environment.
```shell
opam update
opam upgrade
```

**Comment by Yann-Kaelig** [comment]
Hi hhugo.

I'm sorry but I can't. I do not use opam on Gentoo but only ocaml and dune with the new dune.eclass which make the ocaml softwares build a lot more easier than before.

**Comment by hhugo** [comment]
What is it that you're trying to do ?

There are multiple solutions:
- Get a newer version of dune (especially if you want to hack on the js_of_ocaml codebase)
- Just install what you need, don't run the tests (e.g. `dune build -p js_of_ocaml-compiler`)
- Remove the tests that are not working with dune 2.1

**Comment by Yann-Kaelig** [comment]
Thx hhugo

I decided to go with a newer version of dune. However I take note of the other possibilities if I encounter problems with the newer version of dune during the build of my others ocaml softwares.

**Comment by hhugo** [comment]
:+1: reopen if you have more issues
