### ISSUE TITLE
Question on weak semantic

### ISSUE THREAD

**Issue by Ngoguey42** [ocsigen/js_of_ocaml#1038]
I recently discovered in the documentation that `Weak semantic cannot be implemented using JavaScript. A dummy implementation is provided`.

Could it be implemented using javascript's `WeakMap` and `WeakSet`?

**Comment by hhugo** [comment]
`WeakMap` and `WeakSet` are less powerful than weak references in OCaml. In particular, JavaScript engine don't let you observe the garbage collector. The API provided by the Weak module in OCaml would break that principle.
```ocaml
val get : 'a t -> int -> 'a option
val set : 'a t -> int -> 'a option -> unit 
```

The WeakMap API does not allow one to observe the GC

**Comment by EduardoRFS** [comment]
@hhugo why would that be the case? Isn't that exactly what the WeakMap.get does?

```ocaml
(* JS WeakMap *)
val get : ('k, 'v) t -> 'k -> 'v option
```

Isn't that a superset of the one defined by OCaml?

**Comment by dbuenzli** [comment]
I think [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/WeakRef) could be used but it's not supported on Safari at the time of writing.

**Comment by dboris** [comment]
@dbuenzli `WeakRef` is now supported on Safari (as of 14.1 on Mac, 14.7 on iOS).
