### ISSUE TITLE
[BUG] Type typ is not compatible with type Ppxlib.core_type

### ISSUE THREAD

**Issue by Yann-Kaelig** [ocsigen/js_of_ocaml#1040]
**Describe the bug**
Failed to build js_of_ocaml 3.6.0 and branch master

> File "ppx/ppx_deriving_json/lib/ppx_deriving_json.ml", line 776, characters 42-51:
> 776 |   let deriver = Ppxlib.Deriving.add name ~extension
>                                                 ^^^^^^^^^
> Error: This expression has type
>          loc:Warnings.loc -> path:Ppxlib__Import.string -> typ -> expression
>        but an expression was expected of type
>          loc:Warnings.loc ->
>          path:Ppxlib__Import.string -> Ppxlib.core_type -> Ppxlib.expression
>        Type typ is not compatible with type Ppxlib.core_type

**Logs**
[js_of_ocaml-3.6.0.log](https://github.com/ocsigen/js_of_ocaml/files/4920360/js_of_ocaml-3.6.0.log)
[js_of_ocaml-git-master.log](https://github.com/ocsigen/js_of_ocaml/files/4920361/js_of_ocaml-git-master.log)

**Versions**
ocaml 4.10.0
dune 2.6.1
js_of_ocaml 3.6.0 and branch master

**Comment by hhugo** [comment]
Jsoo is not compatible with ppxlib 0.14 yet. See https://github.com/ocsigen/js_of_ocaml/commit/5c8b0933c059ddab28668934bd684421be07420d

**Comment by Yann-Kaelig** [comment]
Ok, thx.
Sorry, I really have trouble with the list of dependencies and their versions.

**Comment by hhugo** [comment]
Are you trying to package stuff for Gentoo ?
You should probably extract deps and version constraint from opam even if you don't want to use it.
