### ISSUE TITLE
[BUG] Missing `caml_sys_time_include_children` on toplevel creation.

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#1047]
**Describe the bug**
There's a missing primitive when you compile toplevels: 
```
There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives:
  caml_sys_time_include_children
```
It's because of [this bit](https://github.com/ocaml/ocaml/blob/trunk/utils/profile.ml#L20) in the compiler. Implementing in terms of `jsoo`'s [`caml_sys_time`](https://github.com/ocsigen/js_of_ocaml/blob/db758adbd02dd3e0e85cfddff5c772153c416929/runtime/sys.js#L129) wouldn't harm.

**Expected behavior**
My clear and concise description of what I expect to happen is to have no missing primitive when I compile toplevels :-)

**Versions**
```
> ocamlc -version     
4.09.0
> js_of_ocaml --version                                      
3.6.0
```

**Comment by hhugo** [comment]
Note that there is no missing primitive when building a toplevel inside the jsoo codebase.
I suspect the reason is that we prune the executable and do not force the link of all of compiler-libs. (see the `--export` flag given to js_of_ocaml)

**Comment by dbuenzli** [comment]
How do you know what you have to prune ?

**Comment by hhugo** [comment]
You should pass all the unit names you want your toplevel to have access to (using --export)

**Comment by hhugo** [comment]
Theses units will be fully linked and available. The rest might be affected by deadcode elimination.

**Comment by dbuenzli** [comment]
I see. But what is it that is needed for a standard OCaml toplevel only `Toplevel`, `Topdirs` and `Stdlib` ?

**Comment by dbuenzli** [comment]
(Also a bit of doc about making toplevels would be awesome, maybe that's what this issue should be turned into)

**Comment by hhugo** [comment]
I guess you'll need `stdlib` and maybe `js_of_ocaml-toplevel`. 
Here is what's included in the default jsoo toplevel.
```
(rule
 (targets export.txt)
 (deps
   (package js_of_ocaml-ppx)
   (package js_of_ocaml)
   (package js_of_ocaml-lwt)
   (package js_of_ocaml-tyxml)
   (package js_of_ocaml-toplevel)
 )
 (action (run
    jsoo_listunits -o %{targets}
      stdlib
      graphics
      str
      js_of_ocaml-lwt.graphics
      js_of_ocaml-ppx.as-lib
      js_of_ocaml.deriving
      lwt bigarray
      tyxml.functor
      tyxml.functor:html_types.cmi
      react reactiveData
      js_of_ocaml js_of_ocaml-lwt
      js_of_ocaml-tyxml
      js_of_ocaml-toplevel
      dynlink
      )))
```
