### ISSUE TITLE
[BUG] Checking for constant overflow only work in whole program compilation 

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#1051]
```ocaml
let () = Printf.printf "%nx" 0xffffffffn;;
```
generate the following warning in whole program compilation
```
Warning: integer overflow: integer 0xffffffff (4294967295) truncated to 0xffffffff (-1); the generated code might be incorrect.
```

The same warning should trigger with separate compilation.

As an extension, we could imagine only warning if the problematic constant ends up being used in the generate javascript and give a chance to the deadcode elimination to do its job

**Comment by hhugo** [comment]
cc @xclerc

**Comment by xclerc** [comment]
Tentative fix in https://github.com/ocsigen/js_of_ocaml/pull/1052.
