### ISSUE TITLE
[BUG] SIGKILL and integer overflow in release profile

### ISSUE THREAD

**Issue by chenyan2002** [ocsigen/js_of_ocaml#1057]
**Describe the bug**
I'm trying to compile a project with js_of_ocaml, and it works fine in the default `dev` profile. But when I use the release profile, it gets a SIGKILL and lots of integer overflow warnings.
```
dune build --profile=release _build/default/js/mo_js.bc.js
 js_of_ocaml js/mo_js.bc.js (got signal KILL)
(cd _build/default/js && /nix/store/gqc27bfabhrksc60db6j6a91yaxdgh4x-ocaml4.08.1-js_of_ocaml-compiler-3.5.2/bin/js_of_ocaml -o mo_js.bc.js --no-runtime /nix/store/gqc27bfabhrksc60db6j6a91yaxdgh4x-ocaml4.08.1-js_of_ocaml-compiler-3.5.2/lib/ocaml/4.08.1/site-lib/js_of_ocaml-compiler/runtime.js /nix/store/2q9c1ib0mx0hmmyy5x8b7lwm7c2m24q8-ocaml4.08.1-base-0.12.2/lib/ocaml/4.08.1/site-lib/base/runtime.js /nix/store/pywjxcpw5irmzfcwyyg5s5xghzkxz8jb-ocaml4.08.1-bigstringaf-0.6.0/lib/ocaml/4.08.1/site-lib/bigstringaf/runtime.js mo_js.bc)
Warning: integer overflow: integer 0xffffffff (4294967295) truncated to 0xffffffff (-1); the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 (2147483648) truncated to 0x80000000 (-2147483648); the generated code might be incorrect.
Warning: integer overflow: integer 0x100000000 (4294967296) truncated to 0x0 (0); the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 (2147483648) truncated to 0x80000000 (-2147483648); the generated code might be incorrect.
Warning: integer overflow: integer 0x100000000 (4294967296) truncated to 0x0 (0); the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 (2147483648) truncated to 0x80000000 (-2147483648); the generated code might be incorrect.
Warning: integer overflow: integer 0xffffffff (4294967295) truncated to 0xffffffff (-1); the generated code might be incorrect.
make: *** [Makefile:53: moc.js] Error 1
```

**Expected behavior**
The integer overflow only appears in release profile. Does it mean a js_of_ocaml compiler bug? I am also not sure where the SIGKILL comes from. The memory usage is reasonable. Maybe the SIGKILL comes from dune, but why? 
The project is large, and the generated js file is 20M in dev profile, so it's a bit hard to minimize, but I can dig deeper if you can provide me some suggestions.

**Versions**
ocamlc: 4.08.1
js_of_ocaml: 3.5.2

**Comment by hhugo** [comment]
The difference between dev and release should have been fixed on master thanks to #1052

**Comment by chenyan2002** [comment]
I see. Thanks! Do you know what may cause the SIGKILL? It happens after running for about 20min without OOM.

**Comment by hhugo** [comment]
Can you try the latest version of js_of_ocaml-compiler ? See if you can reproduce

**Comment by chenyan2002** [comment]
0.3.7 does fix the problem! JS file size reduced from 20M to 1M! very impressive!
