### ISSUE TITLE
[BUG] TypeError only in dune's `release` mode

### ISSUE THREAD

**Issue by smondet** [ocsigen/js_of_ocaml#1059]
> **Describe the bug**

This is the project:
https://github.com/smondet/comevitz/

when `dune build src/client/index.html` it all works fine

when adding `--profile release`, I get a:

```
Uncaught TypeError: Cannot read property 'length' of undefined
```

It seems to happen with this async Lwt code (the exception breaks the loop):
https://github.com/smondet/comevitz/blob/0855ad34cc2b8d087910e4c9d42e9a570ac9839f/src/client/main.ml#L631-L660

(code pretty-printed by chromium:)
![screenshot-20200915-112444](https://user-images.githubusercontent.com/617111/93230848-22182300-f746-11ea-9d92-f9b11e25ba1f.png)

> **Expected behavior**

`--profile release` should make things faster and lighter, not change the functional behavior :)

> **Versions**
Version of packages used to reproduce the bug
(ocamlc, js_of_ocaml, ..)

```
 $ ocamlc -version
4.09.1
 $ js_of_ocaml --version
3.7.0
 $ dune --version
2.6.1
```

**Comment by smondet** [comment]
Using `choose` instead of `pick` does not fix the problem, but removing the whole `pick` does:

```ocaml
    catch
      (fun () ->
        (* pick
          [ ( Js_of_ocaml_lwt.Lwt_js.sleep 5.
            >>= fun () ->
            return (Non_responsive "Time-out while getting status")
          ); *) (Node.ping nod >>= fun res ->
              dbgf "%s returned to start_update_loop"nod.name;
              return res) (* ] *)
      )
      (fun e ->
        return (Non_responsive (Fmt.str "Error: %a" Exn.pp e)))
```

**Comment by smondet** [comment]
adding this also bypasses the problem:

```
  (js_of_ocaml (flags --no-inline))
```

(inspired by https://github.com/ocsigen/js_of_ocaml/issues/393 )

**Comment by hhugo** [comment]
Would you be able to provide a smaller repro case or even a minimal example ? I'm unable to compile comevitz on my machine because of system deps
```
The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    epel-release hidapi-devel
```

**Comment by smondet** [comment]
@hhugo Wow did you get the opam deps with `./please.sh ensure setup`? `hidapi` should not be needed (but it is indeed a dependency of some vendored-but-not-used libraries)

**Comment by smondet** [comment]
@hhugo this branch is much more minimal and reproduces the problem: https://github.com/smondet/comevitz/tree/repro-jsoo-1059

```scheme
(executable
  (name main)
  (modes js)
  ;;(js_of_ocaml (flags --no-inline))
  (preprocess (pps js_of_ocaml-ppx))
  (libraries  fmt base js_of_ocaml-tyxml js_of_ocaml-lwt re.posix
             ;;tezos-contract-metadata digestif.ocaml
             ;; tezos-crypto → does not work in JS
             ;;base58
             )
  )
```

**Comment by hhugo** [comment]
can you try #1061 and confirms it fixes you issue ?

**Comment by smondet** [comment]
Indeed it does fix the issue :)

```
opam pin add js_of_ocaml-compiler \
     "https://github.com/ocsigen/js_of_ocaml.git#revert-1013"
```

(OOC, is it a JSOO actual bug or is it just breaking a low-level assumption of `Lwt`?)
