### ISSUE TITLE
[Question] jsoo_link vs js_of_ocaml link?

### ISSUE THREAD

**Issue by rgrinberg** [ocsigen/js_of_ocaml#1060]
What is the difference between the `jsoo_link` binary and the `js_of_ocaml link` subcommand?

I see `jsoo_link` being advertised as what is used for separate compilation [here](https://ocsigen.org/js_of_ocaml/3.5.1/manual/separate-compilation), but we don't actually use this binary in dune.

**Comment by hhugo** [comment]
`jsoo_link` is the old name for `js_of_ocaml link`.

The latest doc references  `js_of_ocaml link` (see https://ocsigen.org/js_of_ocaml/3.7.0/manual/separate-compilation)

**Comment by rgrinberg** [comment]
Thanks! What do you think about officially deprecating `jsoo_link` then?

**Comment by hhugo** [comment]
What does deprecating mean here ?

**Comment by rgrinberg** [comment]
Perhaps make the jsoo_link binary write to stderr a message that recommends users to switch to using js_of_ocaml link instead.

Rudi.
