### ISSUE TITLE
[BUG] unexpected behavior with boolean wrapped in data type

### ISSUE THREAD

**Issue by jnfoster** [ocsigen/js_of_ocaml#1070]
**Describe the bug**
Consider the following program:
```
open Core_kernel
open Js_of_ocaml
type b = B of bool
let eq x1 x2 = B Bigint.(equal x1 x2)
let _ =
  Js.export "Petr4"
    (object%js
       method bug _ =
         match eq Bigint.one Bigint.zero with 
         | B true -> "Wrong"
         | B false -> "Ok"
     end)
```
It does the following
- Invokes an equality test (`eq`) on two different `Bigint.t` values
- Wraps the resulting boolean in a data type (`b`) with a single constructor (`B`)
- Pattern matches on the resulting `b` value and returns `"Ok"` if the value contains `false` or `"Wrong"` if it contains `true`.

If I execute `bug` in the Chrome browser, I get `Wrong`. 

**Expected behavior**
I would expect to get `"Ok"` because `Bigint.equal Bigint.one Bigint.zero` is `false`.

More confusing,  if I replace the `eq` function with the following version,
```
let eq x1 x2 = if Bigint.equal x1 x2 then B true else B false
```
then I do get `"Ok"`, as expected.

**Versions**
- ocamlc version 4.09.0
- js_of_ocaml version 3.6.0
- core_kernel version v0.13.1
- bignum version v0.13.1
- Chrome version 86.0.4240.193 (Official Build) (x86_64)

**Comment by hhugo** [comment]
I believe this is a bug in zarith (javascript) stubs that was fixed few days ago by the following commit https://github.com/janestreet/zarith_stubs_js/commit/7c5a500f2b63957a1267e493635b92c32dd647ea

**Comment by hhugo** [comment]
`ml_z_equal` was returning a javascript boolean (true,false) instead of returning an ocaml one ( represented as 1 and 0)

**Comment by jnfoster** [comment]
Amazing! I'll update and confirm.

Thank you.
