### ISSUE TITLE
How to tackle a JavaScript function that returns a JS `Promise`?

### ISSUE THREAD

**Issue by jayesh-bhoot** [ocsigen/js_of_ocaml#1073]
From what I understand, while `lwt` provides a counterpart to JS `Promise`, it doesn't have a mechanism to mix those two (like translating js Promise into lwt).

**Comment by TyOverby** [comment]
Js_of_ocaml doesn't have official support for the promise API.  You'll need to use a library like https://github.com/mnxn/promise_jsoo

**Comment by jayesh-bhoot** [comment]
Thank you.

**Comment by jayesh-bhoot** [comment]
Update: I opted for `promise_jsoo`, but the following commands (as recommended in the manual):

```
>  ocamlfind ocamlc -package js_of_ocaml,js_of_ocaml-ppx,promise_jsoo -linkpkg -o bg.byte bg.ml

>  js_of_ocaml bg.byte
```

fail to include `promise_jsoo` in the compiled file (https://github.com/mnxn/promise_jsoo/issues/2). 

Dune works, however.

Am I missing anything in the above commands?

**Comment by TyOverby** [comment]
you need to pass the path to `indirect_promise.js` to the js_of_ocaml invocation.

if i were you, id stick to using Dune though

**Comment by jayesh-bhoot** [comment]
Your suggestion worked!

```
js_of_ocaml +promise_jsoo/indirect-promise.js bg.byte
```

compiled bg.js with its dependencies.

dune, even with release profile, produces a js file of 2.2MB. The above command generated an output of 40KB. That’s a drastic difference. Unless there is a way to drastically cut down the output size of dune, I see much value in the latter solution.

**Comment by TyOverby** [comment]
> dune, even with release profile, produces a js file of 2.2MB. The above command generated an output of 40KB

I think that's because Dune includes the "--sourcemap-inline" command in it's invocation of js_of_ocaml.  I don't know how you turn that off, but you can check to see what the difference would be by deleting the last line (it should be a comment) in the .js file

**Comment by jayesh-bhoot** [comment]
Sorry I got time to inspect further today. Anyway, quoting myself from https://github.com/ocaml/dune/issues/4030#issuecomment-743981495:

```
That's not the case. The last line is not a sourcemap comment in bg.bc.js file.

That inspired me to try another command:

ocamlfind ocamlc -g -package js_of_ocaml,js_of_ocaml-ppx,promise_jsoo -linkpkg -o bg.byte bg.ml

js_of_ocaml --source-map-inline +promise_jsoo/indirect_promise.js bg.byte

With --source-map-inline, js_of_ocaml adds a sourcemap comment starting with //# sourceMappingURL=data:application/json;base64,...., and so produces a larger file, but only with a size of 544K (still smaller than dune's 2.2M).
```

**Comment by hhugo** [comment]
The size issue has been resolved by https://github.com/mnxn/promise_jsoo/commit/174d490d6a1c016499f5688e1781481d206fa8e3

The answer to this issue is to use promise_jsoo. I'll create an issue to document this fact and close this issue.
