### ISSUE TITLE
Generated .js code fail to load local files 

### ISSUE THREAD

**Issue by yanruyu126** [ocsigen/js_of_ocaml#1074]
I tried building the examples, but it seems that the javascript code cannot load the local files properly. For example, with hypertree, the console shows: 

messages.json: No such file or directory.

Features other than loading files worked properly. What would the possible issue be? Thank you so much!

**Comment by Becky-Hu-2001** [comment]
yea i have the same issues

**Comment by angelaloh09** [comment]
it seems like i have been facing the same problem

**Comment by hhugo** [comment]
Can you try building with the release profile ? There might be an issue with separate compilation

**Comment by dbuenzli** [comment]
I suspect there's something wrong with `dune`'s separate compilation, I hadn't the time to investigate but see https://github.com/dbuenzli/brr/issues/9#issuecomment-743104268

**Comment by dbuenzli** [comment]
> I suspect there's something wrong with `dune`'s separate compilation, I hadn't the time to investigate but see [dbuenzli/brr#9 (comment)](https://github.com/dbuenzli/brr/issues/9#issuecomment-743104268)

Not  `dune` or `js_of_ocaml`'s fault there.

**Comment by hhugo** [comment]
@yanruyu126, @Becky-Hu-82, @angelaloh09, I'm not able to reproduce the issue. Can you say more about the way you compile examples ? what's you're setup ? can you provide a reproduction ?.

**Comment by elzibus** [comment]
I also have the issue when I try to compile and run the hyperbolic tree example.

```
ocamlc -version       :     4.13.1
js_of_ocaml --version :     3.11.0
```

I have reduced the source size to the following to illustrate the issue:

```
(*
 * tiny example to illustrate .json file loading issue
 *
 * The error from the Firefox (94.0 (64-bit)) Console reads:
 * Fatal error: exception Sys_error("./messages.json: No such file or directory")
 * Same error in Chromium:
 * Version 95.0.4638.69 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)
 *)

open Js_of_ocaml
open Js_of_ocaml_lwt

let ( >>= ) = Lwt.bind

let json : < parse : Js.js_string Js.t -> 'a > Js.t = Js.Unsafe.pure_js_expr "JSON"

let http_get url =
  XmlHttpRequest.get url
  >>= fun r ->
  let cod = r.XmlHttpRequest.code in
  let msg = r.XmlHttpRequest.content in
  if cod = 0 || cod = 200 then Lwt.return msg else fst (Lwt.wait ())

let getfile f = try Lwt.return (Sys_js.read_file ~name:f) with Not_found -> http_get f

let load_messages () =
  getfile "./messages.json" >>= fun s -> Lwt.return (json##parse (Js.string s))

let all_messages = load_messages ()

````

I compiled with:

````
ocamlfind ocamlc -package js_of_ocaml-lwt -package js_of_ocaml -package js_of_ocaml-ppx -linkpkg -o tiny.byte tiny.ml
js_of_ocaml --opt=3 tiny.byte
````

I modified the hyperbolic tree `index.html` to include `tiny.js` instead.
Upon navigating to the URL where the files have been deployed, I get the same error as for the hyperbolic tree example:

`Fatal error: exception Sys_error("./messages.json: No such file or directory")`

If I point directly to the json file in my browser, I can see that the file is in fact there.

**Comment by hhugo** [comment]
Your example is trying to read a file from the jsoo pseudo file system but you don't include the file when you call js_of_ocaml. See the `--file` flag from the dune file of the hyperbolic example

**Comment by elzibus** [comment]
Thank you for your answer. I used the instructions from https://github.com/ocsigen/js_of_ocaml#usage but they seem to apply to simpler examples only. Looks like I have some reading to do..

**Comment by hhugo** [comment]
I'll close for now, reopen if you can provide more context.
