### ISSUE TITLE
int_size when compiling to jsoo

### ISSUE THREAD

**Issue by c-cube** [ocsigen/js_of_ocaml#1079]
in [this container issue](https://github.com/c-cube/ocaml-containers/issues/346) we have a problem because some code uses integer literals that fit in 2^62 bits (being compiled by ocamlc on x86_64), but then jsoo truncates them. Is it possible, at least on paper, to set `int_size` to 53 rather than 63 somewhere in the compilation process when compiling via jsoo?

**Comment by hhugo** [comment]
`int_size` is runtime specific. You can compile a bytecode program on a 64bit arch but run it on a 32bit arch or even on a javascript environment. In an practice, it can be 63, 31 or 32

**Comment by c-cube** [comment]
Thank you, that makes sense then. I have to pick at runtime.
