### ISSUE TITLE
int_size warning when compiling ints greater than 32 bits

### ISSUE THREAD

**Issue by stevebleazard** [ocsigen/js_of_ocaml#1080]
Related to #1079: Integers larger than 32 bits are truncated to 32 bits with the warning:

`$ dune build`
...
`js_of_ocaml lib/.foo.objs/foo.cma.js`
`Warning: integer overflow: integer 0x1fffffffffffff (9007199254740991) truncated to 0xffffffff (-1); the generated code might be incorrect.`

However, javascript only supports doubles for numbers as such no truncation appears to be necessary.

**Comment by hhugo** [comment]
Jsoo uses 32bit ints to implement ocaml integers as there is no native support for 64bits integer in javascript.

Javascript has 64bit floats that could represent integers accurately up to 53bit. Even if we were to use 53bits (we don't), truncation would be necessary.

**Comment by stevebleazard** [comment]
Understood, I guess the question is: Can the truncation be to 53 bits or is the 32bit truncation an internal limitation

**Comment by hhugo** [comment]
We use 32bit as javascript bits operations give us the correct overflow semantic for free. Making use of all 53bits while preserving the overflow semantic will most likely be very costly.

**Comment by stevebleazard** [comment]
Ok, makes sense
