### ISSUE TITLE
Question: How to convert a number into a 32 bit integer.

### ISSUE THREAD

**Issue by hbr** [ocsigen/js_of_ocaml#1091]
In the jsoo documentation it is written that ocaml int and float are represented by javascript numbers. I assume that jsoo is doing 32bit arithmetic on ocaml int.

However if I get a javascript number from javascript, I do not know, if it can be represented as a 32 bit integer. In javascript I would just do `if (n | 0 == n) {...} else {...}`. How can I do the same via jsoo?

**Comment by hhugo** [comment]
See one way to do it there 
https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/javascript.ml#L77
