### ISSUE TITLE
Question: How to compare javascript objects for physical equality?

### ISSUE THREAD

**Issue by hbr** [ocsigen/js_of_ocaml#1093]
Sometimes I need to compare two javascript objects of the type `'a Js.t` for physical equality. E.g. when I have a dom node I want to walk up the parents to the root and find out, if the dom node belongs to `window.document`.

In javascript this is easy. I just write `node1 === node2`. How can I achieve this in jsoo? Is the ocaml operator `==`  compiled to the javascript `===`? I have read the jsoo documentation carefully but have not found an answer to this question, therefore I post the question here. Hopefully this is not a too silly question.

Thanks for any help
Helmut

**Comment by TyOverby** [comment]
`==` performs physical equality in OCaml, and it compiles down to the JavaScript `===` operator.

**Comment by hbr** [comment]
Thanks for the clear answer. Can I assume as well that ocaml's equality operator `=` compiles down to the javascript operator `==`? I.e. can I use ocaml's `=` operator to compare javascript strings `js_string Js.t` for equality?

**Comment by hhugo** [comment]
> Thanks for the clear answer. Can I assume as well that ocaml's equality operator `=` compiles down to the javascript operator `==`? I.e. can I use ocaml's `=` operator to compare javascript strings `js_string Js.t` for equality?

Ocaml `=` operator does not translate to the javascript `==`.
To compare javascript strings, you can use physical equality as well.

**Comment by dbuenzli** [comment]
@hbr basically `===` is `==` but it doesn't attempt at performing type conversions. The MDN pages are useful to peruse: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality

regarding what `js_of_ocaml` does you may find [this section](https://erratique.ch/software/brr/doc/ffi_manual.html#equality) of brr's FFI manual useful (even if you don't use brr).

**Comment by hbr** [comment]
Thanks Daniel. I have mixed up javascript's strict equality with reference equality. It seems that javascript's strict equality is reference equality for objects, but *normal* equality for primitive values like numbers and strings. For programmers in ocaml any type conversion before comparison (i.e. javascript `==`) is not interesting anyhow. So the rule seems to be

- Do not compare objects!
- For comparison of numbers, booleans and strings wrapped in `.. Js.t` use javascript's `===` i.e. ocaml's `==`.
