### ISSUE TITLE
Unconditional exception during module initialization

### ISSUE THREAD

**Issue by pmwhite** [ocsigen/js_of_ocaml#1094]
My js_of_ocaml app is throwing an exception immediately when the page loads. The exception comes from a module that is bundled in the output, but not actually used by the program (not yet, at least), so my guess is that the exception happens when the module is being initialized. To further support this guess, I'm seeing something like following in my *.cma file

```javascript
var module_name =  [list, of, identifiers, in, module];
caml_register_global(2419, module_name, "module_name");
throw runtime.caml_exn_with_js_backtrace(Stdlib[8],0?1:0)
```

My interpretation is that immediately after putting the module in global scope, the code throws an exception. This seems very strange to me. Is this a bug? Or just something I don't understand about the compiler.

For context, I'm attempting to compile ocamlformat. I have successfully compiled, but now running the code is causing the problem I've described above. Specifically, the module causing problems is [parser-wyc](https://github.com/ocaml-ppx/ocamlformat/blob/master/vendor/parse-wyc/lib/lexer.mll). Strangely, the error seems to be pointing at [line 105](https://github.com/ocaml-ppx/ocamlformat/blob/master/vendor/parse-wyc/lib/lexer.mll#L105) (via the sourcemap), which initializes a `Buffer.t`.

**Comment by hhugo** [comment]
Have you figured out what was going on ?

**Comment by pmwhite** [comment]
No, but I realized the root cause, and this issue just seemed like a poor description. I suppose I should have just added some extra detail instead of closing the issue, since I still think there is a bug of some sort.

I can run the following command on `parser.mly` in parser-wyc:

```
menhir --strict --inspection --unused-tokens \
       --table --cmly parser.mly \
       --base parser__mock \
       --infer-write-query parser__mock.ml
```

The resulting file is never used, but is generated purely to get the compiler to autogenerate an mli which can be passed to menhir via `--infer-read-reply` to generate the actual module that will be used.

Even though `parser__mock` is never used, it's still included in the binary (that's probably bad, but that's a different discussion). **The problem is that the generated `parser__mock.ml` includes a top-level `raise Not_found` expression, which means that if the module ever gets loaded, the program will crash**.

For native binaries, there is no issue, since the module never gets loaded. However, js_of_ocaml must be loading it, because it crashes immediately (the error is described in the original issue).

**Comment by hhugo** [comment]
This must only be an issue when using separate compilation as all compilation units are included in the final JS.
When doing whole program compilation, ocamlc is responsible for the linking phase and should drop this unused unit.

**Comment by pmwhite** [comment]
It's the process described [here](http://gallium.inria.fr/~fpottier/menhir/manual.html#sec%3Abuild%3Ainfer%3Aindirect). I think it is not unexpected for Menhir to make the module unusable, since the module is presumably not intended to every be included in a binary.
