### ISSUE TITLE
Is 'wrap_callback' necessary?

### ISSUE THREAD

**Issue by hbr** [ocsigen/js_of_ocaml#1095]
I have always wrapped my callback functions. I was very surprised that this wrapping does not seem to be necessary. E.g. the following code works perfectly.

    open Js_of_ocaml

    type timer

    let set (f: unit -> unit) (ms: int): timer =
        Js.Unsafe.global##setTimeout f ms

    let clear (t: timer): unit =
        Js.Unsafe.global##clearTimeout t

The callback function `f` in `set` is not wrapped.

Is this by accident? When is it necessary to wrap callback functions?

I have been experimenting with other callbacks with actual arguments as well. It seems to be that javascript fills all missing arguments with `undefined` and ignores superfluous arguments.

**Comment by hhugo** [comment]
wrapping callbacks takes care of currification.

For example, try
```ocaml
Js.Unsafe.global##.myAddition := fun x -> (); fun y -> x + y;;
```
vs
```ocaml
Js.Unsafe.global##.myAddition := Js.wrap_callback (fun x -> (); fun y -> x + y);;
```

and call `myAddition(3,4)` on the javascript side.

The first version will discard the second argument and return you a function while the second version will return 7 as expected

**Comment by hbr** [comment]
Well explained. Thank you.

I.e. as long as I declare the functions on the ocaml side with the same number of arguments as they are called from the javascript side, the wrapper is not necessary.

This is exactly my use case, because I code only ocaml functions as javascript callbacks where I know how they are called from the javascript side. Therefore my code works well without the wrapper.

Thanks for the info.
Helmut
