### ISSUE TITLE
[BUG] Js.to_array mixes Typedarrays with arrays 

### ISSUE THREAD

**Issue by mimoo** [ocsigen/js_of_ocaml#1101]
I am writing code that expects an array of Uint8Arrays. I wrote it like this:

```ocaml
type 'a array_js = 'a Js.js_array Js.t
type u8_array_js = Js_of_ocaml.Typed_array.uint8Array Js.t

let some_function (array_of_blobs : u8_array_js array_js) = ...
```

In javascript I can call it like this:

```js
let blob = Uint8Array.from(Buffer.from(hexString, 'hex'));
someFunction([blob]);

// this shouldn't work, but it does:
someFunction(blob);
```

The problem I believe is that TypedArrays are treated like arrays: `Js.to_array` works on both arrays and typedarrays.

**Comment by hhugo** [comment]
Js_of_ocaml doesn't validate values coming from JavaScript. If you expect arbitrary value will be given to your function, you should validate it yourself.
