### ISSUE TITLE
ocamlfind: Package `js_of_ocaml.ppx' not found

### ISSUE THREAD

**Issue by chengtie** [ocsigen/js_of_ocaml#1119]
I have a project which worked perfectly. `makefile` contains `OCAMLC = ocamlfind ocamlc -unsafe-string -package js_of_ocaml.ppx -package ppx_deriving_yojson -package re -package core_kernel -package ppx_deriving.std -package containers`.

I just updated opam and upgraded opam. Then, the compilation of the project returned the error `ocamlfind: Package 'js_of_ocaml.ppx' not found`.

The current ocaml version is `4.07.1` and opam version is `2.0.2`.

Does anyone know how to fix the error?

**Comment by dbuenzli** [comment]
The `js_of_ocaml` install structure changed quite a bit over time, unfortunately I don't think it was ever written in the release notes. It's likely that you need change that `js_of_ocaml.ppx`, to `js_of_ocaml-ppx`. In any case `ocamlfind list` should give you the name of installed ocamlfind packages.

**Comment by chengtie** [comment]
> The `js_of_ocaml` install structure changed quite a bit over time, unfortunately I don't think it was ever written in the release notes. It's likely that you need change that `js_of_ocaml.ppx`, to `js_of_ocaml-ppx`. In any case `ocamlfind list` should give you the name of installed ocamlfind packages.

Indeed, changing `js_of_ocaml.ppx` to `js_of_ocaml-ppx` works for me. Thank you.

**Comment by hhugo** [comment]
The change happened in version 3.0.
There is a quick mention of it in the changelog but it's definitely not informative enough (split "js_of_ocaml in multiple packages")
