### ISSUE TITLE
What are the pros and cons of using the "js-string" option?

### ISSUE THREAD

**Issue by TyOverby** [ocsigen/js_of_ocaml#1122]
I understand what the option does, and I intend to turn it on for all of my projects, but is there a risk?  Why is it not the default?

**Comment by hhugo** [comment]
- requires safe string
- I was unable to show any performance difference between the two.
- it's still unclear to me whether it makes debugging easier or more confusing. When enabled, ocaml strings and js ones share the same representation but cannot be used

**Comment by hhugo** [comment]
If you're certain your js stubs dont make any assumption on the memory representation of ocaml string and you use safe string. I don't see any "risk" turning the option on.

**Comment by TyOverby** [comment]
Surely there’s an impact on memory usage if you’re not allocating an extra object per string?

**Comment by TyOverby** [comment]
Thanks for the advice; I’ll start gradually switching things over!
