### ISSUE TITLE
[FEATURE REQUEST] Make git_version more resilient

### ISSUE THREAD

**Issue by phated** [ocsigen/js_of_ocaml#1139]
**Is your feature request related to a problem? Please describe.**

When trying to use esy to link in-progress JSOO work into the Grain compiler, the project fails to build. This is due to `esy build` not operating inside a git repository.

**Describe the solution you'd like**

I believe the call to `git` inside of the project's root dune file (https://github.com/ocsigen/js_of_ocaml/blob/master/dune#L20) can be made more resilient so it will just fallback to an empty string instead of failing.

**Describe alternatives you've considered**

For my testing, I just created a new branch with the git command removed. I don't think that's a desirable solution though.

**Comment by hhugo** [comment]
I must be missing something. We only call git if there is a `.git` directory. Can you show the error you get ?

**Comment by phated** [comment]
@hhugo I'll investigate this error more today

**Comment by phated** [comment]
Some cursory investigation seems to show that the `.git` directory is copied into the esy sandbox, but not actually any of the contents of the directory. So the current implementation finds the git directory but crashes on trying to run the git command
