### ISSUE TITLE
cannot load shared library dlljs_of_ocaml_stubs

### ISSUE THREAD

**Issue by chengtie** [ocsigen/js_of_ocaml#1144]
I have a bytecode of OCaml, which worked previously well. Today, I'm trying to run it, I get an error

```
Fatal error: cannot load shared library dlljs_of_ocaml_stubs
Reason: dlopen(dlljs_of_ocaml_stubs.so, 10): image not found
Abort trap: 6
```

I guess it is related to js_of_ocaml, does anyone know what's wrong?

**Comment by hhugo** [comment]
- js_of_ocaml is not installed maybe ?
- a bytecode that depend on js_of_ocaml is not supposed to execute correctly as bytecode but is supposed to be compiled to JavaScript. Are you sure you were able to run the bytecode previous ?

**Comment by chengtie** [comment]
Indeed, js_of_ocaml was not properly installed. Installing js_of_ocaml and other packages fixs the problem.

Thank you
