### ISSUE TITLE
[FEATURE REQUEST] Small runtime library to improve binding libraries interoperability

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#1146]
Over the time two other FFI alternatives emerged out of the `js_of_ocaml` project itself to provide alternative binding strategies to JavaScript (based on abstract data types rather than phantom typing of JavaScript objects). 

These projects do not make use of the `js_of_ocaml.cma` library. All the projects are perfectly able to interoperate together except for one thing, the exception registered to represent the JavaScript exception. For reference here is where this registration happens: 

* [`Brr`](https://github.com/dbuenzli/brr/blob/41580885f40bfd184c3d8e5be2ddd56b0712b411/src/jv.ml#L227-L231)
* [`js_gen_api`](https://github.com/LexiFi/gen_js_api/blob/377d58632d4b34aaf54a3e2f3c80741cc1ab2044/lib/ojs_exn.ml)
* [`js_of_ocaml`](https://github.com/ocsigen/js_of_ocaml/blob/cde86b2cba215344a6f81b1db28b922b80c7b55a/lib/js_of_ocaml/js.ml#L672)

As discussed in https://github.com/dbuenzli/brr/issues/2 a simple answer to this problem would be to provide a simple runtime OCaml library seperate from `js_of_ocaml.cma` against which `js_of_ocaml` compiled programs must link; this would also be a good place to add the C primitive stubs so that the byte code can be linked without `-no-check-prims` in both `js_gen_api` and `brr` (these primitives are currently in the `js_of_ocaml.cma` library). 

This OCaml runtime library should only have this module:
```ocaml
module Js_error : sig
  type t 
  exception Exn of t
end = struct
   type t (* Voluntarily left abstract, this is a javascript object. *)
   exception Exn of t 
   let () = Callback.register_exception "jsError" (Exn (obj [||]))
end
```
Each of the API can then simply expose its own exception implemented as being equal to `Js_error.Exn`. For example the [current Brr API](https://erratique.ch/software/brr/doc/Jv/index.html#exns) could just change its signature to: 

```ocaml
module Error : sig
   type t = Js_error.t (* <--- this is the only visible external change *)
   val name : t -> Jstr.t
   ...
end
exception Error of Error.t
```
implemented as: 
```ocaml
module Error = struct
   type t = Js_error.t
   let name e = to_jstr (get (Obj.magic e) "name")
   ...
end
exception Error = Js_error.Exn
```

/cc @mlasson

**Comment by smorimoto** [comment]
@cannorin You'll probably want to see this in advance for the tool you're working on.

**Comment by hhugo** [comment]
Can we know more about "the tool" ? :)

**Comment by cannorin** [comment]
It's a tool called `ts2ocaml` which can generate OCaml bindings for `gen_js_api` from TypeScript definition files (`*.d.ts`).

It can even parse the TypeScript standard libraries and generate a complete binding from them.
* `ts2ocaml` has its own standard library, so this issue is relevant to me too.
* I think `ts2ocaml` can help generating such runtime library automatically from TS standard libraries?

**Comment by hhugo** [comment]
Keeping track of solutions proposed on the Brr issue.

> FWIW we would be happy to use in gen_js_api a shared library to register the exception (even more if this library contains the c-stubs !).

> If this library contain a bit more (something a bit like your "jv" module) to completly replace our "ojs" module that could be even better for interop !

**Comment by dbuenzli** [comment]
Thanks @hhugo !
