### ISSUE TITLE
implement (better) pseudo filesystem 

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#116]
a unix-like fs where one can mount "devices" to path
  - `/remote/myserver/` mapping file on whatever server using XmlHttpRequest
  - `/remote/https/github.com/ocsigen/js_of_ocaml`
  - `/storage/local` -> localStorage
  - `/storage/session` -> sessionStorage
  - `/storage/cookie` ?

**Comment by hhugo** [comment]
The following is available in the toplevel and will fetch the file transparently 
```
let ic = open_in "/http/ocsigen.org/js_of_ocaml/dev/files/toplevel/index.html";;
val ic : in_channel = <abstr>
input_line ic;;
- : string = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
input_line ic;;
- : string = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\""
```

**Comment by sagotch** [comment]
@hhugo could you point the code where this is implemented?
