### ISSUE TITLE
[FEATURE REQUEST] Improved development env repeatability

### ISSUE THREAD

**Issue by cdaringe** [ocsigen/js_of_ocaml#1162]
**Is your feature request related to a problem? Please describe.**

On my development machine, I receive unexpected side-effects when building and running the project. Such effects are surely unrelated to my changeset(s). Examples include:

1. Missing cmi

```sh
❯ make all
dune build @all
jsoo_listunits toplevel/examples/lwt_toplevel/export.txt
Could not find cmi Dynlink_compilerlibs.cmi or dynlink_compilerlibs.cmi in /Users/myuser/.opam/4.12.0/lib/ocaml
```

2. Formatting changes

```diff
diff --git a/compiler/tests-compiler/mutable_closure.ml b/compiler/tests-compiler/mutable_closure.ml.corrected
index 44fdad6658..d79b020dda 100644
--- a/compiler/tests-compiler/mutable_closure.ml
+++ b/compiler/tests-compiler/mutable_closure.ml.corrected
@@ -158,7 +158,7 @@ let%expect_test _ =
         var
          _c_=indirect[1],
          _d_=function(f){return caml_call1(f,0)},
-         indirect$0=caml_call2(Stdlib_List[19],_d_,_c_),
+         indirect$0=caml_call2(Stdlib_list[19],_d_,_c_),
```

3. Undefined symbols

```txt
Undefined symbols for architecture x86_64:
  "_caml_acosh_float", referenced from:
      _camlJsoo_testsuite__Test_floats__p_1443 in jsoo_testsuite.a(jsoo_testsuite__Test_floats.o)
      _camlJsoo_testsuite__Test_floats__1 in jsoo_testsuite.a(jsoo_testsuite__Test_floats.o)
  "_caml_asinh_float", referenced from:
      _camlJsoo_testsuite__Test_floats__p_1453 in jsoo_testsuite.a(jsoo_testsuite__Test_floats.o)
      _camlJsoo_testsuite__Test_floats__1 in jsoo_testsuite.a(jsoo_testsuite__Test_floats.o)
  "_caml_atanh_float", referenced from:
```

...and a few others which have occurred over the passed few days.

**Describe the solution you'd like**

I desire a recipe for reproducible & successful development, where libraries & binaries are known stable/working.

Ideas:

1. `docker` development image that is hydrated with the current dependencies, ready to work in. [remote containers](https://code.visualstudio.com/docs/remote/containers), maybe? haven't tried it. probably limited audience though--this community iirc is emacs intensive

<details>
<summary>Dockerfile.dev</summary>

```Dockerfile
# Develop using a known working environment.
# @usage
# run `make dev_container`
FROM ocaml/opam:ubuntu-18.04-ocaml-4.12
USER root
RUN apt-get update && apt-get install -y libgmp-dev pkg-config
USER opam
RUN opam install --deps-only js_of_ocaml js_of_ocaml-lwt js_of_ocaml-compiler js_of_ocaml-ocamlbuild js_of_ocaml-toplevel js_of_ocaml-ppx js_of_ocaml-ppx_deriving_json js_of_ocaml-tyxml
RUN opam install lwt reactiveData tyxml ppxlib cohttp-lwt-unix menhir ppx_expect yojson sexplib 
RUN opam install ocp-indent graphics
RUN curl -fsSL https://fnm.vercel.app/install | bash
ENV PATH=/home/opam/.fnm:$PATH
RUN eval "`fnm env`" && fnm install 16
# ideally, these install steps move to `opam install . --deps-only --locked`, to more rigorously keep dependencies stable
```

```make
docker_dev_image:
	docker build -f Dockerfile.dev -t jsoo_dev .

dev_container: docker_dev_image
	docker run -it --rm -v $$PWD:/js_of_ocaml --workdir=/js_of_ocaml jsoo_dev

.PHONY: all dev_container docker_dev_image tests test runtest runtests doc clean installdoc
```
</details>

2. a `nix` env, ready to work in
3. pinned dependencies, ideally using [a lockfile](https://discuss.ocaml.org/t/lightweight-ocaml-docker-images-created-by-dune-with-multi-stage-builds/7958/2?u=cdaringe)
4. a pinned switch/compiler version to develop with

**Describe alternatives you've considered**

See above :)

**Comment by hhugo** [comment]
- 1: expected
- 2: not a re-formatting issue (the casing is different), use ocaml 4.13
- 3: use ocaml 4.13

While jsoo supports many versions of the ocaml compiler, tests are run on one version only.
