### ISSUE TITLE
[BUG] js_of_ocaml is not aware of the BigInt API

### ISSUE THREAD

**Issue by msprotz** [ocsigen/js_of_ocaml#1168]
**Describe the bug**
Spurious warnings about free variables in my overrides:

```
warning: free variables in primitive code "uint128_mul" (/Users/jonathan/Code/mls-proposals/_build/default/js/overrides.js:520)
vars: BigInt
```

**Expected behavior**
js_of_ocaml should have a built-in knowledge of the BigInt object, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Versions**
3.9.1
4.11.1

Thanks,

Jonathan

**Comment by hhugo** [comment]
You can always use `joo_global_objet.BigInt`

**Comment by msprotz** [comment]
Ah that's a good workaround for the time being; thanks!

**Comment by hhugo** [comment]
PR welcome, just add an entry in `compiler/lib/reserved.ml`
