### ISSUE TITLE
add namespace when converting to js files

### ISSUE THREAD

**Issue by chengtie** [ocsigen/js_of_ocaml#1171]
I use js_of_ocaml to convert an analyzer coded in OCaml to `analyzejs.js`. Then I use `<script src="analyzejs.js"></script>` in my website to load it, and call the wrapped functions on the website.

Now, I have a new version of the analyzer, let's say `analyzejs-new.js`. I want some part of the website to use the wrapped functions of `analyzejs-new.js`, and some part of the website to use the wrapped functions of `analyzejs.js`. As functions in `analyzejs-new.js` and `analyzejs.js` share the same name, I would need namespaces to specify if I want to use `f()` of `analyzejs-new.js` or `f()` of `analyzejs.js`.

It seems that it is complicated to add namespaces on the side of the website, when loading these 2 files. I would like to know if it is possible to add namespaces on the side of js_of_ocaml when these 2 files are being converted.

Could anyone help?

**Comment by hhugo** [comment]
How do you export `f` in `analyze.js` ?

I tried adding an example doing what you want in 
https://github.com/ocsigen/js_of_ocaml/pull/1201/commits/c51a1612ecbadc5990734d6cc2e1125f3dd3e1a0.

Ideally, the logic should be much simpler, I'm working on it.

**Comment by chengtie** [comment]
@hhugo Normally, I use `Js.Unsafe.global##.f := Js.wrap_callback(fun ...)` to export `f` in `analyze.js`.

**Comment by hhugo** [comment]
Can you take a look at the example in https://github.com/ocsigen/js_of_ocaml/pull/1201 and tell me if that is what you're looking for ?

Note that `Js.Unsafe.global##.f := (...)` is not going to work if you use `--wrap-with-fun`, you should use `Js_of_ocaml.Js.export "f" (...)` instead
