### ISSUE TITLE
compatibility issues?

### ISSUE THREAD

**Issue by jrochel** [ocsigen/js_of_ocaml#1182]
In https://github.com/ocsigen/ocsigen-start/runs/4335406860?check_suite_focus=true the compilation of js_of_ocaml fails for ubuntu-latest 4.09.x and 4.10.x. It works fine however for >= 4.11.x. Is there some version constraint missing somewhere?

**Comment by SGrondin** [comment]
I'm seeing the same problem on 4.10.0

**Comment by hhugo** [comment]
Could be an issue with a new release of menhir packages

**Comment by SGrondin** [comment]
@hhugo I have no idea if this datapoint helps: it works on 4.11.2 and OPAM 2.1, and it used to work on 4.10.0 until recently.
