### ISSUE TITLE
Release build performs considerably worse compared to dev build due to inlining

### ISSUE THREAD

**Issue by linoscope** [ocsigen/js_of_ocaml#1185]
I have been using `js_of_ocaml` to run [my game boy emulator](https://github.com/linoscope/CAMLBOY) in the browser, and one thing I noticed is the release build (built with `dune build --profile=release` where js_of_ocaml compiles without separate compilation) performs considerably worse, in terms of speed, compared to the dev build (built with `dune build` where js_of_ocaml compiles with separate compilation). With some investigation ([thread in discuss.ocaml.org](https://discuss.ocaml.org/t/js-of-ocaml-output-performs-considerably-worse-when-built-with-profile-release-flag/8862/14)), we found that the cause is inlining and that adding `--no-inline` to the release build improves the performance by a lot.

I have measured the FPS of my emulator (without UI) for each of the cases in my local environment (`i7-8665U CPU @ 1.90GHz`, `Ubuntu 20.04.2`, `Google Chrome Version 95.0.4638.69`), and summarized the results in the following chart:
![jsoo_compare](https://user-images.githubusercontent.com/24925588/143675245-0627152d-9596-4b1f-88cb-b9f19e686287.png)

Also, I have hosted the emulator, both with UI and without UI, in the following URLs to demonstrate the FPS difference:

- Dev build: [with UI](https://linoscope.github.io/CAMLBOY/dev?throttled=false), [without UI](https://linoscope.github.io/CAMLBOY/dev/bench.html)
- Release build: [with UI](https://linoscope.github.io/CAMLBOY/release?throttled=false), [without UI](https://linoscope.github.io/CAMLBOY/release/bench.html)
- Release build with `--no-inline`: [with UI](https://linoscope.github.io/CAMLBOY/release-no-inline?throttled=false), [without UI](https://linoscope.github.io/CAMLBOY/release-no-inline/bench.html)

The version of my `js_of_ocaml` and `ocamlc` is as follows:

```sh
$ js_of_ocaml --version
3.11.0
$ ocamlc --version
4.13.1
```

**Questions:**

Is this expected behavior? It is pretty surprising that the release build performs so much worse than the dev build (although this can be due to `dune`'s default config) and that inlining causes such a performance hit.

And are there any improvements we can make to avoid the negative impact of inlining without having to resort to completely disabling it?

**Comment by linoscope** [comment]
One unique characteristic of my emulator (or I guess emulators in general) is that it contains pretty long functions with large match statements (like [this](https://github.com/linoscope/CAMLBOY/blob/21f0d3ad0fde216650b16d0cf51ab52491656855/lib/cpu/fetch_and_decode.ml#L34) and [this](https://github.com/linoscope/CAMLBOY/blob/21f0d3ad0fde216650b16d0cf51ab52491656855/lib/cpu/cpu.ml#L37)), and it looks like the release build is inlining these. Not sure if this is related though.

**Comment by smorimoto** [comment]
In general, JavaScript code minification does not significantly impact runtime performance. I don't know why it's getting slower as a result of inlining here, since I haven't taken a close look at it, but this is common. For example, if you do that with a tool that's already popular in the JavaScript world, such as Terser, it's very unlikely that you will get better runtime performance. This is because they are basically only intended to reduce the size. On the other hand, a tool like Prepack is focused on better runtime performance, and it's actually quite easy for us to build something like it on top of jsoo, but we will need an option to choose whether to prioritise size or runtime performance.

**Comment by alainfrisch** [comment]
@smorimoto : I'm only following the discussion here as an outsider participant, but I'm confused by your reply.  Inlining is usually a way to get better runtime performance when we accept a increase of the code size. But here we do get the increased code size, but a (serious) *degradation* of the runtime performance. I can imagine that the JS engine stops optimizing very long functions, or the shape of the inlined code is less idiomatic and thus less friendly to the optimizer. Anyway, it would be good to understand the phenomenon, hopefully leading to better inlining heuristics (faster code *and* better runtime performance compare to today's default).

**Comment by linoscope** [comment]
@alainfrisch 
> Inlining is usually a way to get better runtime performance when we accept a increase of the code size. But here we do get the increased code size, but a (serious) degradation of the runtime performance.

For the "inlining usually increase of the code size" part, actually, inlining **decreases** the code size (75.5KB -> 71.7KB) in this case (at the expense of performance degradation). This is probably because `js_of_ocaml` inlines functions only if it is used exactly once (if things haven't changed since [the original paper](https://www.irif.fr/~balat/publications/vouillon_balat-js_of_ocaml.pdf)) hence it removes the bytes used for the function declaration without additional size increase.

For the "inlining usually improve performance" part, yes I also expected inlining would, at least for small functions, improve performance. I especially thought so since `js_of_ocaml` inserts length checks on arguments (like ` f.length==2`) on every function invoation to avoid unnecessary currying. The cost of these length checks seems nonnegligible; when I run with `--no-inline` ~10% of my emulator runtime is consumed by these `f.length`s:
![get_length_performance](https://user-images.githubusercontent.com/24925588/144458448-ea8f8c52-ca83-4146-ba60-0add29a5eef0.png)

(I also found [this post in discuss.ocaml](https://discuss.ocaml.org/t/optimize-js-of-ocaml-function-call/8336) related to `f.length`)

> Anyway, it would be good to understand the phenomenon, hopefully leading to better inlining heuristics (shorter code and better runtime performance compare to today's default).

Yeah, it is also my guess that inlining heuristics can improve the situation a lot, but I have no idea how hard it would be to implement/verify/maintain such heuristics.

Anyway, it would be nice if someone knowledgeable can take a look!

**Comment by smorimoto** [comment]
@alainfrisch Indeed, I did omit some explanation. I certainly intended what you wrote. The key point here is how much the results of the benchmark will be different for each browser engine. I think the greatest thing you can do is explore this issue in depth, but seeing the differences between browser engines can be a relatively quick way to help you understand what's going on.

**Comment by hhugo** [comment]
related to https://github.com/ocsigen/js_of_ocaml/issues/226

**Comment by linoscope** [comment]
For the record, I have confirmed that https://github.com/ocsigen/js_of_ocaml/pull/1220 indeed fixes the issue raised here.

I re-ran my emulator's benchmark after upgrading js_of_ocaml to `4.1.0`; the result is below. The version **without** `--no-inline` runs faster now, i.e. inlining no longer hurts the performance of my emulator.

- With `--no-inline` (deployed [here](https://linoscope.github.io/CAMLBOY/bench.html)): `322.7866822`
- Without `--no-inline` (deployed [here](https://linoscope.github.io/CAMLBOY/no-inline/bench.html)): `421.0012771`

Thanks!
