### ISSUE TITLE
[BUG] `--toplevel` flag unavailable when building with dune

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#1188]
**Describe the bug**
i am trying to build a jsoo project that uses toplevel. dune file looks like:
```dune
(executable
  (name entry)
  (modes js)
  (flags :standard -safe-string)
  (js_of_ocaml (flags :standard --toplevel --linkall +toplevel.js +dynlink.js))
  (preprocess (pps js_of_ocaml-ppx))
  (libraries
    engine
    js_of_ocaml-compiler
    js_of_ocaml-toplevel)
  (link_flags (:standard -linkall))
)
```

but when I run `dune build ./src/entry.bc.js`  I get `js_of_ocaml: unknown option '--toplevel'`.

**Expected behavior**
I would expect the `--toplevel` flag to be available when building with dune. I know I can use `(mode byte)` and then call `js_of_ocaml` binary manually, but then things like dune profiles become unavailable.

**Versions**
OCaml 4.13.1
dune 2.9.1
js_of_ocaml 3.11.0+git-27d3869-dirty

**Comment by hhugo** [comment]
Two issues here:
- A dune issue. One cannot specify flags per jsoo command (fixed by https://github.com/ocaml/dune/pull/5049). In your case, --toplevel is not a valid option for `js_of_ocaml build-runtime`

- Toplevel doesn't work with separate compilation yet, see https://github.com/ocsigen/js_of_ocaml/issues/901.

**Comment by jchavarri** [comment]
thanks @hhugo. So, I understand that the issue would be fixed once Dune releases a version with https://github.com/ocaml/dune/pull/5049 right? Do you know if that's planned for v3.0?

> Toplevel doesn't work with separate compilation yet

Sorry, I fail to see how separate compilation is connected to this issue. In this case, I was mostly interested about `profile=release` to get minified code out of js_of_ocaml and not use a separate JS minifier. But separate compilation is helping rather to have faster builds (and more incremental), isn't that right?

**Comment by jchavarri** [comment]
Btw feel free to close of course if there is nothing actionable really, besides waiting for new Dune version :)

**Comment by hhugo** [comment]
> Sorry, I fail to see how separate compilation is connected to this issue

You're trying to build a jsoo Toplevel with the dev dune Profile `dune build ./src/entry.bc.js` but you won't get a working Toplevel this way.

The `--toplevel` flag can already be used in dune but only with the  release profile
