### ISSUE TITLE
[BUG] Printf runtime included in bundle just by defining a module with similar name

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#1189]
**Describe the bug**
I was attempting to define a module to prevent the usage of `Printf`, in order to avoid bloating the resulting JS bundle (`Printf` adds almost 40KB of minified code) using the following code at the top of my module:

```ocaml
module Printf = struct
  let [@warning "-32"] sprintf = `Printf_runtime_puts_a_lot_javascript_in_the_resulting_bundle_size__Use_string_concat_instead
end
```

**Expected behavior**
I expected this module to not cause the inclusion of stdlib `Printf` runtime in the bundle, as the `sprintf` function is not used anywhere, and the module implementation does not refer to any of the original stdlib `Printf` module, except by name.

If I change either the module name or the function name, the problem doesn't happen.

**Versions**
jsoo 3.10.0

**Comment by hhugo** [comment]
That's very surprising. Can you create minimal reproduction case ?
Note that `Printf` is also used by other modules of the stdlib.

**Comment by hhugo** [comment]
Please also describle the compilation method. dune ? profile ?

**Comment by jchavarri** [comment]
Sorry, I am puzzled, I can't reproduce now 😕 . 

The setup was an application project that had a local pin to a library. And I was tweaking the library, then calling `opam upgrade some_lib -w` and then rebuilding the app with dune (using `profile=release`). Then doing some checks on bundle size. 

Maybe at some point I was looking at a bundle size, but it was not the result of the input I was assuming.

In general, I find hard to understand how changes in a project (dependencies, ppx, general build setup) affect bundle size. Sometimes I will see some bundle size after experimenting with local pins that seems too large (e.g 75KB for just a call to `Firebug.console##log`). Then recreate the same project under a new opam local switch and the bundle goes down to 19KB or so.

I will close, as I'm not able to provide a consistent repro.

**Comment by hhugo** [comment]
Most probable causes
- using `opam pin -k git` vs `opam pin -k path`
- dune build profile (dev vs release)

Using `Firebug.console##log` will force Js_of_ocaml.Js to be linked. The Js module registers exception printers using Printexc which rely on printf. So yes, `console##log` alone results in a big bundle.
