### ISSUE TITLE
Dynlink Failure

### ISSUE THREAD

**Issue by philzook58** [ocsigen/js_of_ocaml#1196]
I'm trying to `Dynlink.loadfile` a .cmo file and not having much luck. Any advice would be much appreciated.

I'm aware of some very similar questions, which were helpful. I'm wondering if perhaps the situation has changed since they were written or perhaps I am failing to understand what I am doing differently.
https://github.com/ocsigen/js_of_ocaml/issues/450
https://github.com/zoggy/jsoo-dynload-test

I made my own simple example repo here
https://github.com/philzook58/jsoo_dynload

I've tried a number of variations, but currently I'm attempting to compile on ocaml 4.12.1 jsoo 3.11.0 using
```
ocamlfind ocamlc -g  -package js_of_ocaml,js_of_ocaml-toplevel -linkpkg dynlink.cma mymain.ml -o mymain.o
js_of_ocaml --pretty --toplevel --dynlink +toplevel.js +dynlink.js -I . mymain.o -o mymain.js
node mymain.js
```

If I try to just use `--dynlink +dynlink.js` I get the following error

```
>> Fatal error: Toplevel bytecode executable is corrupted
Fatal error: exception Dynlink_compilerlibs.Misc.Fatal_error
```

If I try to include toplevel with `--toplevel +toplevel.js`

```
Fatal error: exception Failure("Toplevel not initialized (toplevelCompile)")
```

If I initialize Jsoo.toplevel

```
Fatal error: exception Invalid_argument("The dynlink.cma library cannot be used inside the OCaml toplevel")
```

This example is part of a larger task of trying to get pieces of [BAP working in browser](https://gist.github.com/philzook58/6501f86082954f795812b50181d014bf) which I don't know if it will ultimately be possible. BAP is heavily plugin based and it seemed like Dynlink is where I'm currently failing.

Thanks!

**Comment by ejgallego** [comment]
Hi @philzook58 , we got it to work fine in jsCoq, let us know in jsCoq's gitter if you have any question .

**Comment by hhugo** [comment]
```
Fatal error: exception Invalid_argument("The dynlink.cma library cannot be used inside the OCaml toplevel")
```

You can work around this error message by setting `Sys.interactive := false`.

I'm adding a test for dynlink in https://github.com/ocsigen/js_of_ocaml/pull/1197

**Comment by philzook58** [comment]
That works. Thanks!
