### ISSUE TITLE
[BUG] Hexadecimal float representation not working

### ISSUE THREAD

**Issue by math-gout** [ocsigen/js_of_ocaml#1202]
Doing ```let a = 0x1.1``` doesn't work, although it is valid according to https://ocaml.org/manual/lex.html
I used js_of_ocaml 3.11 and ocaml 4.13.1

**Comment by hhugo** [comment]
What do you mean by it doesn't work ? The js_of_ocaml testsuite contains floats in hexadecimal form and run without any issues.

**Comment by hhugo** [comment]
Fixed by #1202
