### ISSUE TITLE
Cannot build the examples

### ISSUE THREAD

**Issue by jserot** [ocsigen/js_of_ocaml#1233]
I'm not able to build the examples.

Invoking `dune build cubes.js` in `examples/cubes` for ex gives

```
File "lib/gen_stubs/gen_stubs.ml", line 34, characters 18-26:
34 |     [ "--except", Rest_all (fun l -> except_mls := l), "" ]
                       ^^^^^^^^
Error: This variant expression is expected to have type Arg.spec
       The constructor Rest_all does not belong to type Arg.spec
```

Versions:
- `ocamlc` : 4.10.0 
- `js_of_ocaml` : 3.9.0
- `js_of_ocaml-compiler` : 3.9.1

The examples are taken from the git repo (on which the `VERSION` says 3.9.11.
Could it be the examples for version 3.9.11 do not work with 3.9.0 ?
In this cas, where can i find the examples for version 3.9.0 ? 
I cannot upgrade to 3.9.11 due to other dependencies.
I

**Comment by 4y8** [comment]
You will need to update OCaml itself, as the constructor `Rest_all` has been added in version `4.12.0`.

**Comment by jserot** [comment]
Ok. Thanks.
Then the dependencies in the `opam` package description should probably be updated.
It currently says : 
```
depends      "ocaml" {>= "4.02.0"}
```

**Comment by hhugo** [comment]
> The examples are taken from the git repo (on which the VERSION says 3.9.11.

You surely mean 3.11

**Comment by hhugo** [comment]
Try passing the `--ignore-promoted-rules` flag to dune when compiling with older ocaml compiler version. Js_of_ocaml is compatible with ocaml.4.04 at least (checked by the CI)

**Comment by jserot** [comment]
Yes, 3.11 - sorry.

I don't understand the `--ignore-promoted-rules` proposed workaround.

IIUC, starting from - let say - `cubes.ml`, the first step is to generate `cubes.bc` (to be passed to `js_of_ocaml`. 
This is this step which fails:
```
$ dune build cubes.bc
Entering directory '/build/js_of_ocaml'
File "lib/gen_stubs/gen_stubs.ml", line 34, characters 18-26:
34 |     [ "--except", Rest_all (fun l -> except_mls := l), "" ]
                       ^^^^^^^^
Error: This variant expression is expected to have type Arg.spec
       The constructor Rest_all does not belong to type Arg.spec
```

IIUC, again, trying to compile `cubes.ml` triggers the compilation of `../../lib/gen_stubs/gen_stubs.ml`. The latter should have been compiled when `js_of_ocaml` was _installed_ by `opam`, shouldn't it ?

If this file could not be compiled by `ocaml 4.10`, why didn't the installation of `js_of_ocaml`failed ??

**Comment by hhugo** [comment]
`dune build cubes.bc --ignore-promoted-rules` should not attempt to build lib/gen_stubs/gen_stubs.exe

**Comment by jserot** [comment]
```
$ dune build cubes.bc --ignore-promoted-rules
Entering directory '/build/js_of_ocaml'
      ocamlc examples/cubes/.cubes.eobjs/byte/dune__exe__Cubes.{cmi,cmti} (exit 2)
(cd _build/default && /Users/jserot/.opam/4.10.0/bin/ocamlc.opt --ignore-promoted-rules -g -bin-annot -I examples/cubes/.cubes.eobjs/byte -I /Users/jserot/.opam/4.10.0/lib/bytes -I /Users/jserot/.opam/4.10.0/lib/lwt -I /Users/jserot/.opam/4.10.0/lib/result -I /Users/jserot/.opam/4.10.0/lib/seq -I /Users/jserot/.opam/4.10.0/lib/uchar -I lib/js_of_ocaml/.js_of_ocaml.objs/byte -I lib/lwt/.js_of_ocaml_lwt.objs/byte -I lib/runtime/.jsoo_runtime.objs/byte -no-alias-deps -opaque -o examples/cubes/.cubes.eobjs/byte/dune__exe__Cubes.cmi -c -intf examples/cubes/cubes.pp.mli)

/Users/jserot/.opam/4.10.0/bin/ocamlc.opt: unknown option '--ignore-promoted-rules'.
```

Seems the `--ignore-promoted-rules` is passed to the `ocamlc` compiler :/

**Comment by hhugo** [comment]
> ```
> $ dune build cubes.bc --ignore-promoted-rules
> Entering directory '/build/js_of_ocaml'
>       ocamlc examples/cubes/.cubes.eobjs/byte/dune__exe__Cubes.{cmi,cmti} (exit 2)
> (cd _build/default && /Users/jserot/.opam/4.10.0/bin/ocamlc.opt --ignore-promoted-rules -g -bin-annot -I examples/cubes/.cubes.eobjs/byte -I /Users/jserot/.opam/4.10.0/lib/bytes -I /Users/jserot/.opam/4.10.0/lib/lwt -I /Users/jserot/.opam/4.10.0/lib/result -I /Users/jserot/.opam/4.10.0/lib/seq -I /Users/jserot/.opam/4.10.0/lib/uchar -I lib/js_of_ocaml/.js_of_ocaml.objs/byte -I lib/lwt/.js_of_ocaml_lwt.objs/byte -I lib/runtime/.jsoo_runtime.objs/byte -no-alias-deps -opaque -o examples/cubes/.cubes.eobjs/byte/dune__exe__Cubes.cmi -c -intf examples/cubes/cubes.pp.mli)
> 
> /Users/jserot/.opam/4.10.0/bin/ocamlc.opt: unknown option '--ignore-promoted-rules'.
> ```
> 
> Seems the `--ignore-promoted-rules` is passed to the `ocamlc` compiler :/

I'm pretty sure you've added the flag to a dune file (inside `(flags ..)` maybe).

```
$ dune build examples/cubes/cubes.js
File "lib/gen_stubs/gen_stubs.ml", line 34, characters 18-26:
34 |     [ "--except", Rest_all (fun l -> except_mls := l), "" ]
                       ^^^^^^^^
Error: This variant expression is expected to have type Arg.spec
       The constructor Rest_all does not belong to type Arg.spec
$ dune build examples/cubes/cubes.js --ignore-promoted-rules
```

Note that when building the example inside the js_of_ocaml git repo, dune will ignore installed packages that are also available in the repo / dune project. The error you're seeing is because dune tries to build js_of_ocaml and update "promoted" files. Passing the flag will just make dune ignore rules used to promote files.

**Comment by jserot** [comment]
> I'm pretty sure you've added the flag to a dune file (inside (flags ..) maybe).

Exactly ! Sorry, i forgot to remove it after trying :/

Everything's ok now.
Thanks for the help and the explanations !
