### ISSUE TITLE
Returning an option type value from OCaml to JavaScript

### ISSUE THREAD

**Issue by chengtie** [ocsigen/js_of_ocaml#1235]
In my `wrap.ml`, i have defined the following function which returns an array:

```
Js.Unsafe.global##.test := Js.wrap_callback (
    fun s ->
        Js.array (Array.of_list [1;2;3])
)
```

Now, I would like the function to return an option type value: either `Some anArray` or `None`, is it possible? On the side of JavaScript, how could we deal with a data of this type?

**Comment by hhugo** [comment]
I don't understand what you want, can you be more specific ?

if you want to expose to js a function that return either a js array or null , you can do
```ocaml
Js.Unsafe.global##.test := Js.wrap_callback (
    fun s ->
        Js.Opt.option (Some (Js.array [| 1;2;3|]))
)
```

**Comment by chengtie** [comment]
> I don't understand what you want, can you be more specific ?
> 
> if you want to expose to js a function that return either a js array or null , you can do
> 
> ```ocaml
> Js.Unsafe.global##.test := Js.wrap_callback (
>     fun s ->
>         Js.Opt.option (Some (Js.array [| 1;2;3|]))
> )
> ```

That's what I want, thank you.
