### ISSUE TITLE
[BUG] Memory keeps growing with `Buffer` and js_of_ocaml

### ISSUE THREAD

**Issue by tcoopman** [ocsigen/js_of_ocaml#1238]
Running the following piece of code with `js_of_ocaml` crashes the node environment (it generates a too large string, and memory consumption grows unbounded). Running the same code as a binary directly doesn't have this behavior.

```ocaml
let () =
  let ob = Buffer.create 2096 in
  let oc = open_out "test-file" in
  let seq =
    Seq.unfold
      (fun b ->
        if b < 100 * 100 * 100 * 100 then Some (b, b + 1) else None)
      0
  in
  let () =
    Seq.iter
      (fun _v ->
        Buffer.add_string ob ("output");
        Buffer.output_buffer oc ob;
        Buffer.clear ob)
      seq
  in
  close_out oc
```

It's possible to fix this, by flushing the output channel regularly (for example `if i mod n = 0 then flush oc`).

**Expected behavior**
I expect the js_of_ocaml behavior to be the same as the executable, namely that the memory consumption doesn't grow, even if the output channel is not flushed manually.

Some more information can be found here:
* https://github.com/ocaml-community/yojson/pull/133#issuecomment-1035980421
* https://discuss.ocaml.org/t/memory-keeps-growing-with-buffer-and-js-of-ocaml/9299

**Versions**
* ocaml 4.13.1
* js_of_ocaml 4.0.0

**Comment by hhugo** [comment]
The current implementation flushes automatically on newline. I was implemented this way because it behaves better when outputting to the js console.

The logic is in https://github.com/ocsigen/js_of_ocaml/blob/master/runtime/io.js#L381
in case you want to send a fix.

**Comment by tcoopman** [comment]
Oh, ok interesting. I would say the problem with this implementation is that it's a lot slower.
The following code:

```ocaml
let () =
  let ob = Buffer.create 2096 in
  let oc = Stdlib.open_out "test-file" in
  let seq =
    Stdlib.Seq.unfold
      (fun b -> if b < 100 * 100 * 100 * 5 then Some (b, b + 1) else None)
      0
  in
  let () =
    Stdlib.Seq.iter
      (fun _v ->
        Stdlib.Buffer.add_string ob "output";
        Stdlib.Buffer.output_buffer oc ob;
        Stdlib.Buffer.reset ob)
      seq
  in
  Stdlib.close_out oc
```

I've executed this code 2 times, once with `output` and once with `output\n`:
```
# without \n
________________________________________________________
Executed in    1,72 secs    fish           external
   usr time    1,82 secs  220,00 micros    1,82 secs
   sys time    0,29 secs  131,00 micros    0,29 secs

# with \n

________________________________________________________
Executed in   14,32 secs    fish           external
   usr time    4,74 secs  257,00 micros    4,74 secs
   sys time    9,94 secs  155,00 micros    9,94 secs
```

A more performant approach might be to only flush after so much has been written already? Looking at the code something like:

```js
  var length = chan.buffer.length + jsstring.length;
  if(length < max_length_before_flush)
    chan.buffer+=jsstring;
  else {
    var todo = calculate the remaining length before flushing
    chan.buffer+=jsstring.substr(0,todo);
    caml_ml_flush (chanid);
    chan.buffer += jsstring.substr(todo);
  }
  return 0;
```

if that looks like a sensible approach, an you have an idea about what might be a good `max_length_before_flush` I'm willing to try to create a PR.

**Comment by hhugo** [comment]
The native runtime flushes when the buffer is full, it has size
```
#define IO_BUFFER_SIZE 65536
```

**Comment by hhugo** [comment]
Your approach would I think replicate what's done in the native runtime.

I'd like to keep some logic for the case where the channel prints to the console and avoid flushing in the middle of a line if possible. We can probably keep an extra bit of information and dispatch based on that.

Related, OCaml 4.14 adds two functions `Out_channel.set_buffered` and `Out_channel.is_buffered` to control the buffering mode of output channels. It's currently not properly implemented in jsoo.
Maybe we can use/extend that to control the behavior: buffered, unbuffered, buffered_for_the_console

**Comment by tcoopman** [comment]
> The native runtime flushes when the buffer is full, it has size
> 
> ```
> #define IO_BUFFER_SIZE 65536
> ```

That's strange, running my code without flushing and can result in:

```
/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:1082
throw a}function
^

RangeError: Invalid string length
    at xL (/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:970:53)
    at kE (/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:1576:58)
    at /home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:5315:151
    at b (/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:1086:27)
    at x$ (/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:1210:8)
    at /home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:5315:126
    at Object.<anonymous> (/home/thomas/Workspace/playing-with-projections/generator_reason/_esy/default/build/default/bin/Generator.bc.js:5315:295)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

if the output grows too big, if the native runtime flushes, then this should not happen I believe?
(That's the same error as 
```js
let x = "";
for (let i = 0; i < 100 *100 * 100 * 100 * 100 ; i++) { x+= "output" }
> Uncaught RangeError: Invalid string length
```
)

**Comment by hhugo** [comment]
I'm talking about the C (native) runtime ! You show errors using jsoo.

**Comment by tcoopman** [comment]
Ah, I was thinking you meant `node` itself. Thanks for the clarification.

So, would a PR be welcome where we look at first `\n` and then the limit of `65536`?

**Comment by hhugo** [comment]
A PR would be very welcome, yes.

**Comment by hhugo** [comment]
fixed by https://github.com/ocsigen/js_of_ocaml/pull/1270
