### ISSUE TITLE
[FEATURE REQUEST] Unsafe apply annotation (avoiding caml_call)

### ISSUE THREAD

**Issue by wlitwin** [ocsigen/js_of_ocaml#1246]
**Is your feature request related to a problem? Please describe.**
Js_of_ocaml's implementation of `caml_callN` is very costly because it calls `f.length` to check for partial application (I believe?). It seems Js_of_ocaml can properly eliminate these caml_calls when inside the same module/library, but across library boundaries it has issues. For some of my projects I have tight loops and this `f.length` is causing a lot of performance problems.

**Describe the solution you'd like**
I'd like some annotation I can add to an application to inform Js_of_ocaml that it should generate a normal application, and not a call to caml_call. E.g.:

```ocaml
let lib_fun1 t =
    (t.intf.fun1 t.impl)[@js_of_ocaml.unsafe_apply]
```

Right now it would generate the following code:
```javascript
    function lib_fun1(t){return caml_call1(t[1][2],t[2])}
```

when I would like:
```javascript
    function lib_fun1(t){return t[1][2](t[2])}
```

**Describe alternatives you've considered**
From what I gather it's difficult to get some of this information due to how Js_of_ocaml works, so this seems like a decent middle ground. I'm open to other solutions.

----

I'm also willing to put in the work to make this happen, but a small description/introduction to what places I would need to modify would be helpful.

**Comment by wlitwin** [comment]
I see, I apologize for my naivety. It seems my issue is not library/module boundaries, but indirection. The case I'm trying to optimize is abstracting over two implementations. For example the architecture looks something like this:

```mermaid
flowchart TD
A[Userland Lib] --> B[Backend 1 Common]
A --> C[Backend 2 Common]
B --> D[Backend 1 Web]
B --> E[Backend 1 Desktop]
C --> F[Backend 2 Web]
C --> G[Backend 2 Desktop]
```

Originally I was using functors, but that proved to be too heavy, and then I tried first class modules and records of functions, but I can't seem to get rid of the caml_calls in the intermediate libraries. Flambda (for desktop) removed them in almost all the cases, but I'm trying to coax Js_of_ocaml to do the same.

Here's a simplified example of what I was trying to do: https://github.com/wlitwin/caml_call_example In this example the functions in `Lib` have to go through `caml_call` when calling the implementations. Maybe there's a better way to go about this?

**Comment by hhugo** [comment]
#1358 should have fixed the perf issue.
