### ISSUE TITLE
Optimizer breaks some code

### ISSUE THREAD

**Issue by phated** [ocsigen/js_of_ocaml#1247]
I'm working on some Binaryen stuff again and I found that the JSOO optimizer breaks some of the code.

In particular, it changes:
```js
"object" == typeof window && window
```
into
```js
typeof"object"==window&&window
```
Which isn't correct and actually fails when the script tries to run in an env without Window (in this specific case).

I had to hunt for while to figure out why `--pretty` didn't fail, but a normal build kept crashing.

**Comment by phated** [comment]
It looks like this is related to `share_constant`. When I disable that optimization, the reorganization doesn't happen.

**Comment by hhugo** [comment]
I think there is a typo in your issue.
You say it translates to 
`typeof"object"==window&&window`. Is this really what you meant to write ?

**Comment by phated** [comment]
Yes, that's the mistake the optimizer produces.

**Comment by hhugo** [comment]
The issue comes from this line https://github.com/ocsigen/js_of_ocaml/blob/49e1aa56de10f82f59f2dae98606d113f233958f/compiler/lib/js_traverse.ml#L204.

**Comment by phated** [comment]
Thanks ❤️
