### ISSUE TITLE
Missing Intl.DateTimeFormat options

### ISSUE THREAD

**Issue by glennsl** [ocsigen/js_of_ocaml#1251]
There's several options missing in `Intl.DateTimeFormat.options`, such as `dateStyle`, `timeStyle` and `calendar`. I also see from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) that some of these are not supported by IE, and wonder if that's why they're not included. Then again, `timeZoneName` is included despite also not being supported on IE.

My question then is, what is the criteria for which APIs to include and which not to include? Then once I know that I can make a PR to fix this.

**Comment by hhugo** [comment]
IE is not really an issue anymore. I'm happy to include whatever is supported widely by major browsers.

**Comment by glennsl** [comment]
Cool. Look forward to a PR in the near future then!
