### ISSUE TITLE
[FEATURE REQUEST] Trim some fat off Printf by removing rarely used features

### ISSUE THREAD

**Issue by glennsl** [ocsigen/js_of_ocaml#1253]
A few months ago on the OCaml forums [@gasche mentioned](https://discuss.ocaml.org/t/blog-post-js-of-ocaml-a-bundle-size-study/9211/14?u=glennsl):

> I did a small experiment removing `%{ fmt %}`, `%( fmt %)` and conversion between formats and runtime strings, and I get a 40% size reduction (from 56Kio to 36Kio) of minified js. (Edit: in fact 16Kio, so a 70% size reduction.)

Just figured I'd bring this up here too, so it's not forgotten.

**Comment by hhugo** [comment]
We can't do much within jsoo. Closing.
