### ISSUE TITLE
Question: generating js for non-web, embedded interpreters?

### ISSUE THREAD

**Issue by gantsevdenis** [ocsigen/js_of_ocaml#1254]
I was thinking of opportunity of using `js_of_ocaml` to generate JS used as AI-scripts, in a game engine. Am I completely dreaming, or is it something that is possible? (I really do not want write Javascript by hand)

After a quick try, I couldn't find my own ocaml functions inside generated `main.js` file, which I suppose is totally normal because it's not called anywhere; however, game engine would call these functions itself.

So I concluded, my usecase is not possible?

**Comment by joprice** [comment]
Does `Js.export`/`Js.export_all` work for you https://ocsigen.org/js_of_ocaml/latest/manual/rev-bindings?

**Comment by gantsevdenis** [comment]
@joprice that looks like it, indeed. At least, I can correctly export whatever I want. Thanks!!
