### ISSUE TITLE
weak semantics again?

### ISSUE THREAD

**Issue by c-cube** [ocsigen/js_of_ocaml#1266]
The docs say that jsoo doesn't support weak semantics. However, now, javascript has [weak maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) and weak sets that, as  far as I can tell, are close to OCaml's ephemerons. My question is: is the lack of weak semantics due to historical reasons (predating JS weak containers), or are there still reasons to not support it today?

**Comment by hhugo** [comment]
I think answers in https://github.com/ocsigen/js_of_ocaml/issues/1038 still applies. Tell me if I'm wrong

**Comment by TyOverby** [comment]
[Looks like WeakRef is supported on Safari now ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/WeakRef)

**Comment by hhugo** [comment]
Weak is now properly supported (modulo bugs). Thanks for the ping.

**Comment by c-cube** [comment]
wow, amazing. Thank you!
