### ISSUE TITLE
Help catching a heisenbug with string comparison

### ISSUE THREAD

**Issue by johnwhitington** [ocsigen/js_of_ocaml#1282]
I don't want to suggest this is a miscompilation yet, but I am all out of ideas. It will take a lot of effort to try to get a minimal case, so I am filing the preliminary bug to see if you have some debugging ideas for me.

Deep inside about 10Mb of js_of_ocaml-compiled JavaScript, is the following function:

```
let replace_special k' v l =
  let rec replace_inner r k' v = function
    | [] -> flprint "E"; raise Not_found
    | (k, _)::t when k = k' -> flprint "F"; List.rev_append r ((k', v)::t)
    | h::t -> flprint "C"; replace_inner (h::r) k' v t
  in
    replace_inner [] k' v l
```

This is a function to replace an entry in an association list. For debug purposes, it prints 'E' for Empty when it reaches the end,  "F" for Found when it finds the entry to replace, and "C" for Continue when it is still looking.

We wish to replace the entry with key /Rotate in our association list. We pre-check the string comparisons in the calling function:

```
|/Contents| is equal to |/Rotate|: false
|/Rotate| is equal to |/Rotate|: true
|/MediaBox| is equal to |/Rotate|: false
|/Resources| is equal to |/Rotate|: false
|/Parent| is equal to |/Rotate|: false
|/Type| is equal to |/Rotate|: false
```

All good. But our replace function cannot find the key, and prints instead!

CCCCCCE

In other words, the k = k' when-guard never triggers for k = k' = "/Rotate".

But here's the strangest thing. Add in some debug printing, and it works just fine:

```
let replace_special k' v l =
  let rec replace_inner r k' v = function
    | [] -> flprint "E"; raise Not_found
    | (k, _)::t when (Printf.printf "|%s| = |%s|? %b\n" k k' (k = k'); k = k') -> flprint "F"; List.rev_append r ((k', v)::t)
    | h::t -> flprint "C"; replace_inner (h::r) k' v t
  in
    replace_inner [] k' v l
```

Here is the correct output produced:

```
|/Contents| is equal to |/Rotate|: false
|/Rotate| is equal to |/Rotate|: true
|/MediaBox| is equal to |/Rotate|: false
|/Resources| is equal to |/Rotate|: false
|/Parent| is equal to |/Rotate|: false
|/Type| is equal to |/Rotate|: false

|/Contents| = |/Rotate|? false
C|/Rotate| = |/Rotate|? true
```

So, adding debug printing affects whether two strings are equal or not!

The new key is created with `caml_string_of_jsstring` in JavaScript, and looks like this:

```
MlBytes { t: 9, c: '/Rotate', l: 7 }
```

Perhaps you can suggest a way for me to show the string of the old key in JavaScript format from within OCaml, so we can see if that has something to do with it? But I don't see why, because the comparison in the debug-printer works ok!

I am stumped! The entirety of the rest of my codebase, compiled with js_of_ocaml, works fine, and passes all of our test suite. This is the only remaining bug...

Any ideas?

**Versions**

OCaml 4.13.1
js_of_ocaml 4.0.0

**Comment by dbuenzli** [comment]
Looks like your function is fully polymorphic. When you add the `printf` it's no longer. Maybe try to compare with `String.equal` to see if that also solves the problem. This would narrow down the problem, maybe there's a bug in the polymorphic comparison function.

**Comment by johnwhitington** [comment]
Thanks. If I leave it polymorphic, but test what String.equal would give also:

```
let replace_special k' v l =
  let rec replace_inner r k' v = function
    | [] -> flprint "E"; raise Not_found
    | (k, _)::t when
        (Printf.printf "%i %i %b %b\n"
          (String.length (Obj.magic k))
          (String.length (Obj.magic k'))
          (String.equal (Obj.magic k) (Obj.magic k')
          (k = k');
         k = k') ->
        flprint "F"; List.rev_append r ((k', v)::t)
    | h::t -> flprint "C"; replace_inner (h::r) k' v t
  in
    replace_inner [] k' v l
```

We get the bug back again, but we can see String.equal gives the correct result:

```
|/Contents| is equal to |/Rotate|: false
|/Rotate| is equal to |/Rotate|: true
|/MediaBox| is equal to |/Rotate|: false
|/Resources| is equal to |/Rotate|: false
|/Parent| is equal to |/Rotate|: false
|/Type| is equal to |/Rotate|: false
Camlpdf: the Dictionary case
9 7 false false
C7 7 true false           <------------- String.equal true, polymorphic equality false
C9 7 false false
C10 7 false false
C7 7 false false
C5 7 false false
```

**Comment by hhugo** [comment]
> Deep inside about 10Mb of js_of_ocaml-compiled JavaScript

I'm assuming this is with separate separate compilation / with the dev dune profile. 
Have you tried searching for the generated replace_special function in the JS files ?

**Comment by johnwhitington** [comment]
Thanks Hugo. I'm neither using dune, nor separate compilation. Here is my command line (once OCaml has finished its work):

```
js_of_ocaml --extern-fs -I . --file=hello.pdf -q --pretty --debuginfo \
	--source-map-inline sjcl.js nodestubs.js cpdfzlib.js cpdfcrypt.js cpdflib.byte
```

I don't find the string `replace_special` in the generated file `cpdflib.js`. Do I need to add another flag to keep the names?

**Comment by hhugo** [comment]
You can use `--disable inline` to prevent inlining.

**Comment by johnwhitington** [comment]
Ok, I did that, and added some `console.logs`, and we see:

```
k' =  MlBytes { t: 0, c: '/Rotate', l: 7 }  <---- caml_equal doesn't think these are equal
k =  MlBytes { t: 9, c: '/Rotate', l: 7 }   <---- but String.equal does
```

`k'` is the one which is built by `caml_string_of_jsstring`, `k` is a native OCaml string...

**Comment by hhugo** [comment]
Can you copy the generated code here ?

**Comment by hhugo** [comment]
I mean the code generated for the function

**Comment by johnwhitington** [comment]
```
    function replace_special(k,v,l)
     { /*<<pdfutil.ml 452 2>>*/ function replace_inner(r,k,v,param)
       {var r$0=r,param$0=param;
        for(;;)
         {if(param$0)
           {var h=param$0[1],t=param$0[2],k$0=h[1];
             console.log('k\' = ', k$0);
             console.log('k = ', k);
             /*<<pdfutil.ml 455 8>>*/ if
             ( /*<<pdfutil.ml 455 8>>*/ caml_equal(k$0,k))
              /*<<pdfutil.ml 461 25>>*/ return  /*<<pdfutil.ml 461 25>>*/ rev_append
                     (r$0,[0,[0,k,v],t]);
             /*<<pdfutil.ml 462 31>>*/ var
              /*<<pdfutil.ml 462 31>>*/ param$1=param$0[2],
              /*<<pdfutil.ml 462 31>>*/ r$1=[0,h,r$0],
             r$0=r$1,
             param$0=param$1;
            continue}
           /*<<pdfutil.ml 453 29>>*/ throw Not_found}}
       /*<<pdfutil.ml 452 2>>*/ return  /*<<pdfutil.ml 452 2>>*/ replace_inner
              (0,k,v,l) /*<<pdfutil.ml 464 27>>*/ }
```

**Comment by hhugo** [comment]
Just to confirm, the generated code you copied is the one used when you see the bug ?

**Comment by johnwhitington** [comment]
Yes, correct. I can happily supply the full `cpdflib.js` and instructions to trigger the bug if you like.

Equally, I can supply the whole thing for you to compile yourself - there are no dependencies.

Just let me know whatever you need.

**Comment by hhugo** [comment]
The whole thing with instructions would be better.

**Comment by hhugo** [comment]
I cannot reproduce so far. It seems like you have two definition of the MlBytes function and
```
k' =  MlBytes'1 { t: 0, c: '/Rotate', l: 7 }
k =  MlBytes'2 { t: 9, c: '/Rotate', l: 7 }
```
The jsoo runtime, in caml_equal, checks if a value is an instance of MlBytes. If you give it a value created from another version of MlBytes it wont work.

**Comment by johnwhitington** [comment]
Yes, that must be it! Although, it seems odd that nothing else in the whole testsuite fails.

Tomorrow I will upload the code anyway, it the hope that you can advise me how to remove the need to include mlBytes.h separately in my wrapper code.

**Comment by hhugo** [comment]
@johnwhitington, were you able to investigate further ? Have you fixed your issue ?

**Comment by johnwhitington** [comment]
@hhugo Here's the code: https://www.coherentpdf.com/tmp/jsoo1282.tar.bz2

Instructions in readme.txt.

You can see the reason for the double-mlbytes in ./build.

What I am trying to build is a version of my PDF library to be used from JavaScript (both in node, and in the browser, but I'm sorting out node first).

The only way I have managed to do this is by having js_of_ocaml build almost all the code, and then writing my JavaScript shims around it separately, like this:

```
function fromFile(filename, userpw)
{
  var r = 
    cpdflib.cpdflib.fromFile(caml_string_of_jsstring(filename), caml_string_of_jsstring(userpw));
  return r
}
```

Then the user can just do:

```
const cpdf = require('./cpdf.js')

var pdf = cpdf.fromFile('hello.pdf', '')
```

When I tried to have js_of_ocaml compile everything, including the shim, I ended up having to write things like `cpdf.cpdflib.fromFile', or seeing two sets of exports (cpdf and cpdflib) rather than a nice set of clean exports. (You can see we already need to write cpdflib.cpdflib.fromFile in the shim, but that is not a real problem).

So this is why I had to cat mlbytes.js (and bigarray.js and fail.js) into the wrapper cpdfsource.js - because otherwise it would not have access to functions like caml_string_of_jsstring.

There might be two kinds of solution I can think of:

a) Get it all compiled together with js_of_ocaml, but find a way to get completely clean exports when we use 'require'.
b) Find a way for my shims to access functions like caml_string_of_jsstring within the existing js_of_ocaml-compiled code.

Bear in mind I know almost nothing about JavaScript, so there may be fundamental misunderstandings to what I have done.

You can run the test suite with ./run, and the whole thing works except for the replaceDictEntry function, which is how we got here!

**Comment by hhugo** [comment]
After a very quick look at the code, I suspect the issue is that you export  the wrong signature to js.
I don't think you should export function that manipulate ocaml `string` or `array` because their memory representation is not idiomatic in js.
For instance,
instead of exporting 
```
method getLastErrorString = Cpdflib.getLastErrorString ()
method mergeSimple a = Cpdflib.mergeSimple a

```  
you should export
```
method getLastErrorString = Js.string (Cpdflib.getLastErrorString ())
method mergeSimple a = Cpdflib.mergeSimple (Js.array a)
```

> tried to have js_of_ocaml compile everything, including the shim, I ended up having to write things like `cpdf.cpdflib.fromFile', or seeing two sets of exports (cpdf and cpdflib) rather than a nice set of clean exports. (You can see we already need to write cpdflib.cpdflib.fromFile in the shim, but that is not a real problem).

I don't understand the difference cpdflib and cpdf.
Regarding the two sets of export: if you compile everything with jsoo in a single js file, I don't see why you would export two set of functions.
If you want to have both cpdflib and cpdf compiled to js, just make sure to not include `exports.ml` in the bytecode of cpdf.

**Comment by johnwhitington** [comment]
I think it will be ok. I have not yet converted the whole API into the form you suggest, but I’ll close this now and reopen if I run into any problems.

Thanks everyone for the help.
