### ISSUE TITLE
cmdliner 1.1.1 and js-of-ocaml 4.0.0

### ISSUE THREAD

**Issue by SnarkBoojum** [ocsigen/js_of_ocaml#1286]
I was trying to update cmdliner to 1.1.1 in Debian, but it looks they aren't compatible:
```
File "compiler/lib-cmdline/arg.ml", line 43, characters 8-12:
43 |   Term.(pure List.flatten $ arg)
             ^^^^
Error (alert deprecated): Cmdliner.Term.pure
Use Term.const instead.
File "compiler/lib-cmdline/arg.ml", line 51, characters 8-12:
51 |   Term.(pure List.flatten $ arg)
             ^^^^
Error (alert deprecated): Cmdliner.Term.pure
Use Term.const instead.
File "compiler/lib-cmdline/arg.ml", line 59, characters 8-12:
59 |   Term.(pure List.flatten $ arg)
             ^^^^
Error (alert deprecated): Cmdliner.Term.pure
Use Term.const instead.
File "compiler/lib-cmdline/arg.ml", line 90, characters 4-8:
90 |     pure (fun debug enable disable pretty debuginfo noinline quiet werror c_header ->
         ^^^^
Error (alert deprecated): Cmdliner.Term.pure
Use Term.const instead.
```

**Comment by dbuenzli** [comment]
They are. Why do you compile with warning as errors enabled ?

**Comment by SnarkBoojum** [comment]
Well, I see both warnings and errors, so I don't think I have warning-as-errors enabled...

**Comment by dbuenzli** [comment]
In what you have posted I see only deprecation alerts. Deprecation alerts are not errors by any means. See [the manual](https://v2.ocaml.org/manual/alerts.html).

**Comment by SnarkBoojum** [comment]
I had a better look at the full log: it looks like the compilation goes through with "Alert deprecated" warnings, but when building the docs, those become  "Error (alert deprecated)"... really errors, that's what I quoted. 

The Debian package is running `$(MAKE) doc` to get the doc, and that gives `dune build @doc-manual --cache=disabled --force`, and it's this line which gives the failures.

**Comment by dbuenzli** [comment]
I think `dune` has this stupid set of defaults where in `dev` mode it makes everything an error in `dev` mode. Maybe try to compile with `--dev=profile` (or something like that, look at the `dune` manual I'm not familiar with it) to see if that improves things.

**Comment by dbuenzli** [comment]
`--profile=release` !

**Comment by SnarkBoojum** [comment]
I tried to run `dune build @doc-manual` by hand, and it fails.

Indeed, if I use `dune build @doc-manual --profile=release`, there's no problem.

The default profile is dev, and that's the only command which has that... why?!

**Comment by SnarkBoojum** [comment]
By "the only command which has that", I meant that I have to patch a single line to add `--profile=release`, the rest didn't need it.

And nothing was fixed on the Debian side: I added a patch to js-of-ocaml's Makefile, see [here](https://salsa.debian.org/ocaml-team/js-of-ocaml/-/blob/master/debian/patches/fix_cmdliner_1.1.1.patch) ; it's a workaround, not a fix.

Why would Debian using js-of-ocaml's Makefile see a problem and nobody else see it?

**Comment by dbuenzli** [comment]
Given the current makefile I'm not sure I understand why it works in the other cases. 

According to `dune --help`, `dev` (which has warnings as errors) is the default profile and I don't see `DUNE_PROFILE` being set in the makefile. 

Do maybe set that variable elsewhere except when you build the docs ?

**Comment by hhugo** [comment]
The build rules in debian don't use the makefile as far as I see. https://salsa.debian.org/ocaml-team/js-of-ocaml/-/blob/master/debian/rules. only building the  documentation uses the makefile
