### ISSUE TITLE
Would jsoo generate the *same* js output everytime its given the *same* ml code as input?

### ISSUE THREAD

**Issue by jayesh-bhoot** [ocsigen/js_of_ocaml#1297]
In other words, would `dune build --profile=release` always generate the same JS output for a same `ml` input?

So far, `diff build_1/file.bc.js build_2/file.bc.js` has always produced zero diff. But I am not sure whether this is a coincidence or a guarantee from js_of_ocaml.

To give a counter-example, clojurescript which uses google closure compiler, does **not** produce the same js output everytime for the same clojurescript code in release mode. The variables may be named differently, and so on.

Personally, I don't care about this, but Firefox Add-on submission rules demand that if the submitted code is transpiled js, then the same input files must always produce the same transpiled js everytime.

**Comment by smorimoto** [comment]
If I remember correctly, I don't think any of jsoo's optimisations would introduce any randomness.

**Comment by jayesh-bhoot** [comment]
Much of the randomness could come from choosing arbitrary variable names while renaming the variables during optimization phase, if any. If that does not happen, then I could just go ahead.

**Comment by hhugo** [comment]
Js_of_ocaml produces JS from  ocaml bytecode and uses debug info (from the bytecode) to recover  variable names. The renaming algo is deterministic. You should expect the jsoo build to be reproducable.

**Comment by jayesh-bhoot** [comment]
That answers my question. Thank you.
