### ISSUE TITLE
[BUG] Instructions for compiling toplevels ?

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#1299]
Are there instructions somewhere on how you are supposed to compile a toplevel ? I couldn't find that mentioned on the website. 

It seems something changed and my old runes no longer work. For example [1]. I'm not sure why I added a `--no-runtime` in these. Maybe I can remove that and the corresponding `+runtime.js` but there is also this `+toplevel.js` and  `+dynlink.js` that I'm no longer sure about. 

Can't all that be solve by simply linking againt the toplevel library maybe ? 

[1]: 
```
> '/Users/dbuenzli/.opam/4.14.0/bin/js_of_ocaml' 
'-o' '/private/tmp/bla/_b0/brzo/ocaml-top-html/a.js' 
'--extern-fs' '--toplevel' '--no-runtime' 
'--export' '/private/tmp/bla/_b0/brzo/ocaml-top-html/top_mod_names' 
'+runtime.js' '+toplevel.js' '+dynlink.js' 
'/private/tmp/bla/_b0/brzo/ocaml-top-html/a.out'
/Users/dbuenzli/.opam/4.14.0/bin/js_of_ocaml: Error: Fl_package_base.No_such_package("runtime.js", "")
```

**Comment by hhugo** [comment]
Quick answer:
Related to https://github.com/ocsigen/js_of_ocaml/pull/978.

Remove `-no-runtime` and and the explicit `+runtime.js`. 

I could look at a longer answer after I'm back at a computer.

**Comment by hhugo** [comment]
The two other `+file.js` files  are still required. See https://github.com/ocsigen/js_of_ocaml/blob/master/toplevel/examples/lwt_toplevel/dune

**Comment by dbuenzli** [comment]
Thank you, that worked. 

I guess once a final plan is figured out for linking additional js the two other files could simply be added to the `META` file of `js_of_ocaml-toplevel` so that higher up, in build systems, linking against that library and specifying `--toplevel` is sufficient.
