### ISSUE TITLE
[PERF] Dominance frontier calculation appears to be O(n^2)

### ISSUE THREAD

**Issue by TyOverby** [ocsigen/js_of_ocaml#1300]
A large jsoo application I've encountered at work spends about 9 minutes compiling with js_of_ocaml using direct-compilation (separate compilation is _much_ faster).  Profiling the compiler shows that almost all of this time is spent in [generate.ml, specifically computing dominance frontiers](https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/generate.ml#L637).

I believe that the issue is that although dominance frontier calculation can be done for the whole program in one pass, the implementation in generate.ml will compute the frontier for each node individually, resulting in no opportunity to share results.

**Comment by TyOverby** [comment]
I suspect that there’s something super linear going on here because a from-scratch separate-compilation build of the same project spends ~20x less time doing dominance frontier calculation

**Comment by hhugo** [comment]
Can you share some code reproducing the issue ? What's the size of the bytecode file ? Have you tried `--disable inline` ?

**Comment by TyOverby** [comment]
> Can you share some code reproducing the issue?

Sadly I can not

> What's the size of the bytecode file?

112MB

> Have you tried `--disable inline`?

I have not, though I can try it out and see what happens.  I should point out that it's using direct-compilation, but doesn't use any of the other "optimization" flags.

**Comment by TyOverby** [comment]
From debugging this a few weeks ago, I remember that the primary issue was that there is an enormous singly-linked-list in the dominator tree that it spends most of its time traversing.  I believe that this might be the list of constants and globals or maybe the toplevel statements?

**Comment by TyOverby** [comment]
>> Have you tried --disable inline?

>I have not, though I can try it out and see what happens. I should point out that it's using direct-compilation, but doesn't use any of the other "optimization" flags.

It appears to make no difference

**Comment by TyOverby** [comment]
>  remember that the primary issue was that a region of the dominator tree is effectively just a singly-linked list

Because of this, I think the dominator tree depth was somewhere on the order of ~100,000

**Comment by TyOverby** [comment]
The same is true for jsoo link

**with --sourcemap**: 5.00s
**without --sourcemap**: 0.5s 
**without --sourcemap and all input .js files don't have a sourcemap comment**: 0.08s

**Comment by TyOverby** [comment]
This one doesn't surprise me as much; most of what I _want_ jsoo-link to do is stitch-up sourcemaps correctly, but I wasn't expecting a full order of magnitude

**Comment by hhugo** [comment]
> without --sourcemap: 0.5s
> without --sourcemap and all input .js files don't have a sourcemap comment: 0.08s

#1313 should reduce this difference.

> with --sourcemap: 5.1s
> without --sourcemap: 0.5s

It would be interesting to get numbers about the size of the debug info.
Can you check the impact of #1313 on these timings ? I suspect it won't change much.

**Comment by hhugo** [comment]
> Passing --sourcemap makes basically every pass in the compiler dramatically slower, including codegen.

passing --sourcemap forces the debug info to be read and used. You can achieve the same thing with `--debug-info` or ``--pretty``.

Could you report timings when using `--debug-info` and `--pretty` separately ?

I suspect that https://github.com/ocsigen/js_of_ocaml/blob/9ea685219b3210f73dcf48c66a19b79ed8a3fa19/compiler/lib/parse_bytecode.ml#L400 is what cost you the most (triggered by `--debug-info` and `--source-map`, but not `--pretty`). It creates lots of "artificial" blocks for the purpose of holding more debug-info.
The change was Introduced in https://github.com/ocsigen/js_of_ocaml/commit/08124c05888dc6cd33d4fa261dcd9803e6864b77https://github.com/ocsigen/js_of_ocaml/commit/08124c05888dc6cd33d4fa261dcd9803e6864b77.

https://github.com/ocsigen/js_of_ocaml/blob/9ea685219b3210f73dcf48c66a19b79ed8a3fa19/compiler/lib/generate.ml#L1359 is where we map the pc of a block to its location info.

If my understanding is correct, we should be able to disconnect how we track debug infos from how we split blocks. Maybe @vouillon has more to say about this.

**Comment by TyOverby** [comment]
> Can you check the impact of https://github.com/ocsigen/js_of_ocaml/pull/1313 on these timings ? I suspect it won't change much.

I'll try it out
