### ISSUE TITLE
[BUG?] cannot find file 

### ISSUE THREAD

**Issue by maxtori** [ocsigen/js_of_ocaml#1304]
**Describe the bug**
the compiler cannot find the files given from the command line (at the commit 38d4f14 on master) :
```
js_of_ocaml -o test.bc.js test_stubs.js test.bc-for-jsoo
-> Error: cannot find file 'test_stubs.js'.
```

**Expected behavior**
The compiler should find the file and compile it with the bytes compiled from the ocaml code

**Versions**
js_of_ocaml#38d4f149123df96fef54dfdbec6fcfe9853b9218
ocaml.4.14.0

**Comment by hhugo** [comment]
Can you try with `./test_stubs.js` instead.

**Comment by hhugo** [comment]
I think the behavior was changed in https://github.com/ocsigen/js_of_ocaml/pull/1276

**Comment by maxtori** [comment]
I hqve tried `./test_stubs.js` but it doesn't work either

**Comment by maxtori** [comment]
to reproduce:
dune file:
```
(executable
 (name test)
 (modules test)
 (js_of_ocaml (javascript_files ./test_stubs.js))
 (modes js))
```
test.ml:
```
external test : unit -> unit = "test"
let () = test ()
```
test_stubs.js:
```
//Provides: test
function test() {
  joo_global_object.console.log("Hello world!")
}
```

**Comment by hhugo** [comment]
In your repro case, `dune` rewrite the filename to just ` test_stubs.js.

**Comment by hhugo** [comment]
I think the correct fix is
```diff
diff --git a/compiler/lib/fs.ml b/compiler/lib/fs.ml
index ef14459ad3..4e5495af4c 100644
--- a/compiler/lib/fs.ml
+++ b/compiler/lib/fs.ml
@@ -25,10 +25,10 @@ let rec find_in_path_rec paths name =
       if Sys.file_exists file then Some file else find_in_path_rec rem name
 
 let find_in_path paths name =
-  if Filename.is_implicit name && not (String.equal name ".")
-  then find_in_path_rec paths name
-  else if Sys.file_exists name
+  if Sys.file_exists name
   then Some name
+  else if Filename.is_implicit name && not (String.equal name ".")
+  then find_in_path_rec paths name
   else None
 
 let rec concat dir filename =
```

Do you want to test it and fix you PR if it works ?

**Comment by maxtori** [comment]
sure I will test it

**Comment by maxtori** [comment]
ok, no problem, I will close this issue.

**Comment by hhugo** [comment]
Can you confirm you problem is fixed with master ?

**Comment by maxtori** [comment]
yes everything works fine!
