### ISSUE TITLE
[BUG] caml_js_get should not be assumed to be pure

### ISSUE THREAD

**Issue by alainfrisch** [ocsigen/js_of_ocaml#1310]
**Describe the bug**
The dead code elimination will happily remove the call to a property getter (using caml_js_get) if the result is unused.  But accessing the property can trigger arbitrary code, so the optimization is not sound.  We have observed a bug in our application (only in on-dev mode!), due to a DOM property being accessed only for its side-effect (namely, accessing `offsetHeight` to force a reflow).

````ocaml
type t

external get: t -> string -> t = "caml_js_get"
external get_glb: unit -> t = "get_glb"
external set_glb: t -> unit = "set_glb"

let () =
  set_glb (get (get_glb()) "foo");
  ignore (get (get_glb()) "bar")
````

generates:

````javascript
    set_glb(get_glb(0)[caml_string_of_jsbytes("foo")]);
    get_glb(0);
````

Any code triggered in the getter for the "bar" property will not be executed as it should.

**Versions**
js_of_ocaml 4.00; ocaml 4.14.1

**Comment by alainfrisch** [comment]
I'm also confused that caml_js_delete is also assumed to be pure enough, leading to:
````ocaml
type t

external get_glb: unit -> t = "get_glb"
external delete: t -> string -> unit = "caml_js_delete"

let () = delete (get_glb()) "baz"
````
being simply compiled to:
````javascript
    get_glb(0);
````

While `caml_js_get` is "usually" pure-enough, this is never the case for `caml_js_delete`.  Shouldn't both be declared as `Mutator` primitives instead of `Mutable`?

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/commit/0239708
