### ISSUE TITLE
Compiler: rewrite control flow logic in generate.ml

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#1336]
Maybe we should consider rewriting this code based on this nice paper from last ICFP: [Beyond Relooper: recursive translation of unstructured control flow to structured control flow, Norman Ramsey](https://dl.acm.org/doi/abs/10.1145/3547621)

**Comment by hhugo** [comment]
suggested by @vouillon in https://github.com/ocsigen/js_of_ocaml/pull/1333#issuecomment-1322284306

**Comment by vouillon** [comment]
One point to consider is that they use `break` instead of setting a variable to jump to the appropriate block of the dominance frontier.
Indeed, one can use `break` to jump outside a JavaScript block:
```
a:{ ... break a; ...}
```

**Comment by hhugo** [comment]
> One point to consider is that they use `break` instead of setting a variable to jump to the appropriate block of the dominance frontier. Indeed, one can use `break` to jump outside a JavaScript block:
> 
> ```
> a:{ ... break a; ...}
> ```

Could you explain a bit what you have in mind ? I guess you could nest blocks, one per exit node of the frontier ..

An alternative I see it to add a single block per frontier but keep the variable saying where we come from. Or mix the two depending on the size of the frontier.

**Comment by vouillon** [comment]
That's the idea, yes. But also you don't have to compute explicitly the dominance frontier then. You can traverse recursively the dominator tree, inserting blocks to be able to jump to children that have several predecessors.
And by sorting children in reverse postorder (on the control flow graph), we can ensure that they are compiled in the right order  (that you only jump forward).
