### ISSUE TITLE
JSOO toplevel at ocsigen.org: misleading error message for unknown module

### ISSUE THREAD

**Issue by jeffsco** [ocsigen/js_of_ocaml#1345]
When I use a nonexistent module in the JSOO toplevel (first JSOO example on the website) I get a confusing error message. For example if I forget to open Js_of_ocaml I see this for the (nonexistent) Regexp module:

    OCaml version 4.14.0
    Compiled with Js_of_ocaml version 4.1.0+9cb30b7
    # let re = Regexp.regexp_case_fold "a";;
    Line 1:
    Error: Corrupted compiled interface
        /home/runner/work/js_of_ocaml/js_of_ocaml/_opam/lib/ocaml/regexp.cmi

(I just verified this at ocsigen.org a few minutes ago.)

**Comment by hhugo** [comment]
Solved on master by https://github.com/ocsigen/js_of_ocaml/pull/1343

see https://ocsigen.org/js_of_ocaml/dev/manual/files/toplevel/index.html
