### ISSUE TITLE
Core_kernel support

### ISSUE THREAD

**Issue by andrewray** [ocsigen/js_of_ocaml#137]
In case you dont read it, there is a bit of a discussion going on over at;

https://groups.google.com/forum/#!forum/ocaml-core

about getting core_kernel into shape for js_of_ocaml.

You might perhaps have some good ideas for how to do this cleanly.

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/444

**Comment by hhugo** [comment]
http://ocsigen.org/js_of_ocaml/2.8/manual/core_async_kernel
