### ISSUE TITLE
Syntax for `new%js` is incorrect in API documentation

### ISSUE THREAD

**Issue by glondu** [ocsigen/js_of_ocaml#1376]
The following page:

  https://ocsigen.org/js_of_ocaml/latest/api/js_of_ocaml/Js_of_ocaml/Js/index.html

uses the syntax `new%js c (e1, ..., en)` for calling a constructor whereas it seems to be `new%js c e1 ... en` now (in particular, when n=0, it is just `new%js c`).

**Comment by hhugo** [comment]
Fixed by a2aa561b0c83be5c946336a330a6ed9b553f02ad
