### ISSUE TITLE
Value too large for defined data type when using --source-map

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#1418]
Hi folks,

when trying to use `--source-maps` in https://github.com/ejgallego/coq-lsp/pull/433 (coq-lsp, a successor to jsCoq) I get:
```
/home/egallego/.opam/dev-coq-lsp/bin/js_of_ocaml: Error: Cannot read content of /home/egallego/research/coq-lsp/_build/default/vendor/coq/vernac/.
Sys_error("Value too large for defined data type")
```
jsoo 5.0.1

**Comment by dbuenzli** [comment]
What's the invocation ? Isn't that an error masquerading as another one it seems you are reading a directory (final `.`).

**Comment by ejgallego** [comment]
Invocation is regular build for bc.js file with dune (in release mode):
``` 
(executable
 (name coq_lsp_worker)
 (modes js)
 (preprocess
  (pps js_of_ocaml-ppx))
 (js_of_ocaml
  (javascript_files
   js_stub/mutex.js
   js_stub/unix.js
   js_stub/coq_vm.js
   js_stub/interrupt.js
   marshal-arch.js)
  (flags
   :standard
   (:include .extraflags)
   --dynlink
   +dynlink.js
   +toplevel.js
   --enable with-js-error
   --enable debuginfo
   --no-inline
   --debug-info
;   --source-map
   --setenv
   PATH=/bin))
 (link_flags -linkall -no-check-prims)
 ; The old makefile set: -noautolink -no-check-prims
 (libraries zarith_stubs_js js_of_ocaml-lwt yojson controller))

```

**Comment by hhugo** [comment]
What is the content of `.extraflags` ?

**Comment by hhugo** [comment]
ping @ejgallego

**Comment by hhugo** [comment]
Can you provide the actual command that is failing using `dune build --verbose` ? Maybe we a backtrace ?

**Comment by ejgallego** [comment]
Yes, I will do so later today, thanks!

**Comment by ejgallego** [comment]
I'm much afraid I failed to get a backtrace :( This is with jsoo 5.0.1, OCaml 4.14.0:
```
$ (cd _build/default/controller-js && OCAMLRUNPARAM=b /home/egallego/.opam/dev-coq-lsp/bin/js_of_ocaml --debug=main --dynlink +dynlink.js --source-map --setenv PATH=/bin -o coq_lsp_worker.bc.js /home/egallego/.opam/dev-coq-lsp/lib/zarith_stubs_js/biginteger.js /home/egallego/.opam/dev-coq-lsp/lib/zarith_stubs_js/runtime.js /home/egallego/.opam/dev-coq-lsp/lib/bigstringaf/runtime.js /home/egallego/.opam/dev-coq-lsp/lib/base/base_internalhash_types/runtime.js /home/egallego/.opam/dev-coq-lsp/lib/base/runtime.js js_stub/mutex.js js_stub/unix.js js_stub/coq_vm.js js_stub/interrupt.js coq_lsp_worker.bc-for-jsoo)
....
Specialize js...
Dead-code...
There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives:
  unix_realpath

/home/egallego/.opam/dev-coq-lsp/bin/js_of_ocaml: Error: Cannot read content of /home/egallego/research/coq-lsp/_build/.
Sys_error("Value too large for defined data type")
```

However I think I found the cause, this is coming from the kernel, likely some file size limit or OCaml is not able to write files large enough.

**Comment by ejgallego** [comment]
Note I'm using a 64 bits switch here.

**Comment by ejgallego** [comment]
Still no backtrace after manually compiling jsoo, seems this error even confuses the runtime? No idea, but backtraces are being properly recorded (double checked)

**Comment by hhugo** [comment]
If you share the bytecode program, i could take a closer look.

Another question, is this a regression or something new.

**Comment by ejgallego** [comment]
Thanks. bc.js file here: https://x80.org/tmp/coq_lsp_worker.bc.js.gz

It's been ages I tried this with jsCoq, so unsure if that was ever working.

**Comment by hhugo** [comment]
I was able to reproduce the issue by compiling the PR mentioned above.

It seem that coq sometimes emit bad locations. See that the following code fragment mentions a directory instead of a file. I'll push a fix in jsoo, but there might be something to fix coq as well. 
```
   function _oI_(l, param, loc){
     /*<<vernac/g_vernac.mlg + /home/hugo/.opam/4.14.0/lib/coq-core/vernac/g_vernac.ml:387:59>>*/ return l;
    /*<<vernac/g_vernac.mlg + /home/hugo/.opam/4.14.0/lib/coq-core/vernac/g_vernac.ml:387:60>>*/ }
    /*<</home/hugo/.opam/4.14.0/lib/coq-core/vernac/:2:33>>*/ var
     /*<</home/hugo/.opam/4.14.0/lib/coq-core/vernac/:2:33>>*/ _oJ_ = 0,
    _oK_ = 0;
   function _oL_(param, loc){
     /*<</home/hugo/.opam/4.14.0/lib/coq-core/vernac/:0:0>>*/ return 0;
    /*<</home/hugo/.opam/4.14.0/lib/coq-core/vernac/:0:2>>*/ }
```

**Comment by hhugo** [comment]
Fixed by https://github.com/ocsigen/js_of_ocaml/pull/1423

**Comment by hhugo** [comment]
@ejgallego, can you confirm that the fix is enough for you ?

**Comment by ejgallego** [comment]
Thanks a lot @hhugo for the analysis and sorry for misreading your request :/ I've opened a but upstream so Coq's preprocessor can be fixed.

Sourcemaps seem to be generated now, thanks a lot!
