### ISSUE TITLE
[BUG] Regression using Digestif through Js_of_ocaml

### ISSUE THREAD

**Issue by xvw** [ocsigen/js_of_ocaml#1435]
Using `js_of_ocaml 5.1.1+git-e1a0914` for a project reported at [Tezos](https://tezos.com) we noticed what we belive is a regression. In [this repository](https://github.com/xvw/jsoo-mirage-regression) you can find three different switches (`4.x.x`, `5.0.x` and `5.1.x`) that compile but two works (`4.x.x` and `5.0.x`) and the other (`5.1.x`) fails to run (it raise an exception during the program execution). The project use [tezos-base58](https://ocaml.org/p/tezos-base58/latest) (that relay on [digestif](https://ocaml.org/p/digestif/latest) which seems to be the cause of the problem). I understand that this outcome seems very specific, but I suppose it must occur, potentially, in other projects.

> The name of the project, containing `regression` may sound a bit harsh but I didn't know what to name it. And it is likely that I have misunderstood the new linking strategy and therefore it is only a problem of settings and flags.

All projects are compiled with OCaml `5.0.0` but I have the impression that this is not significant (and it is possible to easily modify projects to use `4.14.x`).

### A very dumb program as an example
The example program is not very interesting, but it explicitly shows the dependency on `tezos-base58` (and thus `digestive` by extension):

```ocaml
open Js_of_ocaml

let () =
  let ()      = Firebug.console ## log (Js.string "start") in
  let prefix  = "\006\161\159" in
  let address = "tz1gptNykuiTaYvGECzLNPDbZ9ybcQxwHhD4" in
  let encoded = Tezos_base58.encode ~prefix address in
  let message = Format.asprintf "%a" Tezos_base58.pp encoded in
  let ()      = Firebug.console ## log (Js.string message) in
  ()
```

Which is associated with this `dune file`:

```scheme
(executable
 (name main)
 (js_of_ocaml (flags :standard))
 (modes js)
 (promote (until-clean))
 (libraries zarith_stubs_js digestif.ocaml tezos-base58)
 (preprocess (pps js_of_ocaml-ppx)))
```

And which should display, in the browser console, the following lines:

```
[main.bc.js:46976:28] start
[main.bc.js:46988:28] VLHNPBT4V4x4cYBTPb6SHPTnju...
```

### `4.x.x` and `5.0.x` (succeed)
The first two examples work very well and correctly display the two expected messages in the console.
- [project for 4.x.x](https://github.com/xvw/jsoo-mirage-regression/tree/main/4.x.x)
- [project for 5.0.x](https://github.com/xvw/jsoo-mirage-regression/tree/main/5.0.x)

### `5.1.x` (failure)
Even if the project compiles perfectly, running the program via `index,html` generates this error.

- [project for 5.1.x](https://github.com/xvw/jsoo-mirage-regression/tree/main/5.1.x)

```
 Uncaught TypeError: s.charCodeAt is not a function
    caml_string_unsafe_get file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:1072
    caml_string_get64 file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:8830
    le64_to_cpu file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:28256
    caml_call2 file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:28781
    with_outlen_and_key file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:29372
    with_outlen_and_bytes_key file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:29387
    caml_call4 file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:35362
    init file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:35711
    caml_call1 file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:35347
    Make file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:35404
    Make_BLAKE2 file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:35719
    <anonymous> file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:36436
    <anonymous> file:///home/xvw/Projects/perso/jsoo-mirage-regression/5.1.x/src/main.bc.js:37030
main.bc.js:1072:51
```

Since the error **only** occurs with a version of `js_of_ocaml >= 5.1.x`, that's why I have a hunch that it's a regression. I hope it's just a configuration issue though. 

Thanks in advance!

**Comment by hhugo** [comment]
Fixed by https://github.com/mirage/digestif/pull/144

**Comment by xvw** [comment]
Wow, so fast ! Thank you very much

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/23564

New version of digestif in opam-repo is being processed, closing.
