### ISSUE TITLE
[BUG] New js parser fails to parse some js that old parser supported

### ISSUE THREAD

**Issue by phated** [ocsigen/js_of_ocaml#1440]
**Describe the bug**
I tried upgrading Grain's binaryen.ml bindings to jsoo 5.1 and it crashes with failure to parse the binaryen.js file. I still need to create a reproduction that doesn't have the whole (large) js file to comb through but I wanted to preemptively open this issue. 

**Expected behavior**
Should be able to parse es5 code that was supported by 5.0

**Versions**
Ocaml 4.14
Jsoo 5.1

**Comment by hhugo** [comment]
Where is the `binaryen.js` file you're talking about ? Looking at https://github.com/AssemblyScript/binaryen.js/blob/main/index.js, there are some fat arrows that were not supported by the previous parser.

**Comment by phated** [comment]
We actually have a custom es5 build at https://github.com/grain-lang/libbinaryen/blob/main/binaryen.es5.js

**Comment by hhugo** [comment]
Are you able to give more information ? Do you know what construct makes the parser unhappy ? Can jsoo successfully parse the es6 version of the file ?

**Comment by vouillon** [comment]
The issue is that `of` is not accepted as a label (nor are `get`, `set`, `from`, `async`).
```
of:{
break of
}
```

**Comment by hhugo** [comment]
Thanks @vouillon, should be easy to fix. Probably just a one-liner in js_parser.mly

**Comment by phated** [comment]
I'm not sure when I'll have time. We are pushing hard for the next 3 weeks to finish a grain release and we might just have to stay on the older jsoo

**Comment by phated** [comment]
Preliminary tests seem to indicate @vouillon's fix worked! I'm pinning the commit in our CI right now to check across our matrix.
