### ISSUE TITLE
The value of a --custom-header is not placed in the begining of the file [BUG]

### ISSUE THREAD

**Issue by modlfo** [ocsigen/js_of_ocaml#1441]
**Describe the bug**

The value passed using the `--custom-header` is not placed in the beginning of the file. For example:

```js_of_ocaml --custom-header="#!/usr/bin/env node" main.bc``` 

This produces the following code where the header is in the third line
```
// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.1.1
#!/usr/bin/env node
(function(a){typeof .......
```

**Expected behavior**
That the first line of the file is the header and any other text comes after.
```
#!/usr/bin/env node
// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.1.1
```

This produces the following error when running the code:
```
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
F/home/leonardo/main.js:3
#!/usr/bin/env node
^
```

**Versions**
Version of packages used to reproduce the bug
Ocaml 4.14.0
js_of_ocaml version=5.1.1

**Comment by hhugo** [comment]
Thanks, should be relatively easy to fix. The custom header is handled in `driver.ml`, the other header is generated in `bin-js_of_ocaml/compile.ml`. I think we should move the custom header handling to `compile.ml`. @modlfo, would you be interested by trying to fix this yourself?

**Comment by modlfo** [comment]
Hi @hhugo  I gave it a look and I'm not familiar at all with the js_of_ocaml code. It does not look very straightforward for me.

**Comment by hhugo** [comment]
@modlfo, I can provide guidance if you want to spend time on this.
The code inserting the custom header can be removed from https://github.com/ocsigen/js_of_ocaml/blob/8ba629711ba12cbda2001cae02f62f92d21f1778/compiler/lib/driver.ml#L190 and added around that line https://github.com/ocsigen/js_of_ocaml/blob/8ba629711ba12cbda2001cae02f62f92d21f1778/compiler/bin-js_of_ocaml/compile.ml#L39.

**Comment by modlfo** [comment]
Thank you for fixing it. I was going to give it a try last weekend but you were faster.
