### ISSUE TITLE
[BUG] function compiles wrong

### ISSUE THREAD

**Issue by EntireTwix** [ocsigen/js_of_ocaml#1462]
### Describe the bug

the **.ml**
```ocaml
open Float

type bool =
| True
| False

let bool_to_num = function
| True -> Float.one
| False -> Float.zero
```
compiles to 
```js
function bool_to_num(param){ 
    return param ? zero : one; 
}
```

### Expected behavior
```js
function bool_to_num(param){ 
    return param ? one : zero; 
}
```

### Versions
Version of packages used to reproduce the bug
(ocamlc 4.14.0, js_of_ocaml 5.2.0)

apologies if I'm missing something obvious and this is not an error.

**Comment by OlivierNicole** [comment]
This code is in fact correct: the custom `bool` variant that you define is such that `True` will be represented by `0` and `False` by `1`, therefore inverting the usual convention that zero means false. You can see this if you compile the following:
```ocaml
let x = bool_to_num (Sys.opaque_identity True)
```
(I add `Sys.opaque_identity` to prevent inlining which would render the output less clear.)
Resulting in:
```js
function bool_to_num(param){
  return param ? Stdlib_Float[1] /* Float.zero */ : Stdlib_Float[2] /* Float.one */;
}
var x = bool_to_num(0);
```
`True` is compiled to `0` and the result is `1.0` as expected.

**Comment by EntireTwix** [comment]
ah I see, thanks
