### ISSUE TITLE
Compiler: Lower level Code.Switch

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#1495]
`Code.Switch` currently deal with both immediate and block/tagged values.
I feel we could simplify things a bit by adding an explicit condition on `is_int` and have `Switch` just dispatch on a variable immediate value

In other words, I means turning 
```
B1: Switch(x,A1,A2)
```

Into
```
B1: Cond(isInt x, B2, B3)
B2: Switch(x, A1)
B3: let x' = tag x; Switch (x', A2)
```

**Comment by hhugo** [comment]
@vouillon, any opinions?

**Comment by vouillon** [comment]
Indeed, that might be simpler. Though we don't have a `tag x` expression.

**Comment by hhugo** [comment]
fixed by https://github.com/ocsigen/js_of_ocaml/pull/1499
