### ISSUE TITLE
Support for OCaml 5.1.1

### ISSUE THREAD

**Issue by Octachron** [ocsigen/js_of_ocaml#1534]
The upcoming version 5.1.1 of the compiler introduces a new primitive `caml_initialize_zstd` which is not yet supported `js_of_ocaml`.

This primitive aims to switch the compiler marshall library to compressed mode explicitly to circumvent the frailty of dead symbol elimination in native linker.

I have the impression (see https://github.com/ocsigen/js_of_ocaml/commit/bfaa9649e4dbff625eadf41bca6e2e2ed5e24dd1) that `js_of_ocaml` doesn't need such circonvolutions and can implement the new primitive with 
```js
 var zstd_initialize =  (function () {})
```

**Comment by hhugo** [comment]
I think we can do better. Ideally we could avoid adding zstd decompression logic if initialization is not done.

**Comment by Octachron** [comment]
Ah yes, indeed, I was looking at the C implementation that returns `Val_unit` for `true`.

It is true that the vanilla compiler is indeed only using compression once `caml_zstd_initialize` by using hooks in marshal.
I am not sure if this is needed with the better dead code elimination in `js_of_ocaml`?

At this point I defer to your expertise to know what makes sense for `js_of_ocaml`.

**Comment by hhugo** [comment]
jsoo doesn't support compression, only decompression for now. The js marshal logic currently depend unconditionally on zstd. We should follow the same pattern the compiler uses.

**Comment by hhugo** [comment]
@Octachron, the compiler uses `Val_unit` for `true` and `false`.
```
CAMLprim value caml_zstd_initialize(value vunit)
{
  caml_extern_compress_output = caml_zstd_compress;
  caml_intern_decompress_input = caml_zstd_decompress;
  return Val_unit;
}

#else

CAMLprim value caml_zstd_initialize(value vunit)
{
  return Val_unit;
}

#endif
```
