### ISSUE TITLE
[BUG] Regression in generated code: 'There is no containing label named "x"'

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#1547]
**Describe the bug**
As part of the [Melange playground](https://melange.re/v2.1.0/playground/), we create a version of ocamlformat that we can run on the browser.

When updating to the most recent version of jsoo, we noticed an error when creating this JS version of ocamlformat: https://github.com/melange-re/melange-re.github.io/actions/runs/7139925249/job/19444213740#step:15:44

The error comes from [esbuild](https://esbuild.github.io/), I paste below some details.

<details>
  <summary>Part of the error (click to open)</summary>
  
```
There is no containing label named "b"
17821|  11:var
17822|  h=a[1],c=h[1];if(typeof
17823|  c!=="number"&&14===c[0]){if(c[2])break b;if(h[4])break b;var
   |                                         ^
17824|  i=a[2],f=i[1];if(typeof
17825|  f!=="number"&&9===f[0]){if(i[4])break b;return [0,[14,c[1],[0,f[1]]],b[2],b[3],b[4]]}break b}break b;case

There is no containing label named "b"
17821|  11:var
17822|  h=a[1],c=h[1];if(typeof
17823|  c!=="number"&&14===c[0]){if(c[2])break b;if(h[4])break b;var
   |                                                         ^
17824|  i=a[2],f=i[1];if(typeof
17825|  f!=="number"&&9===f[0]){if(i[4])break b;return [0,[14,c[1],[0,f[1]]],b[2],b[3],b[4]]}break b}break b;case

There is no containing label named "b"
17823|  c!=="number"&&14===c[0]){if(c[2])break b;if(h[4])break b;var
17824|  i=a[2],f=i[1];if(typeof
17825|  f!=="number"&&9===f[0]){if(i[4])break b;return [0,[14,c[1],[0,f[1]]],b[2],b[3],b[4]]}break b}break b;case
   |                                        ^
17826|  18:var
17827|  d=a[1];if(!d)break b;var
```
</details>

## Debugging notes

- The error only happens with using `profile=release` but it does not occur with `profile=dev`.
- It only happens when trying to process large programs, like ocamlformat or the melange compiler. I have not been able to reproduce or isolate using small programs.
- After dissecting back in time through the past commits of jsoo, we found the regression starts happening after commit 29c693ba166962725d209123bd80bd1793c7ff78 (#1496), with 3ddba6b92048d798fd270d06b66dee15f04d4179 being the last commit that works fine.
- One thing I noticed in the generated code is that there are two nested `b` labels, see the extracted section of the generated code below:

<details>
  <summary>Section of generated minified JS that causes the failure (click to open)</summary>
  
```js
function q(g, b) {
  var a = b[1];
  b: if (typeof a !== "number")
    switch (a[0]) {
      case 7:
        var q = a[2],
          r = a[1],
          t = bS(r, function (a) {
            var c = a[3],
              d = a[2],
              b = a[1];
            b: if (c) {
              var h = c[1],
                e = h[1];
              if (typeof e !== "number")
                switch (e[0]) {
                  case 0:
                    if (h[4]) break b;
                    if (tp(b[1], [0, e[1][1]])) return [0, b, d, 0];
                    break b;
                  case 11:
                    if (d) break b;
                    var i = c[1],
                      k = i[1],
                      l = k[1],
                      f = l[1];
                    if (typeof f !== "number" && 0 === f[0]) {
                      if (l[4]) break b;
                      if (i[4]) break b;
                      var m = k[2],
                        n = f[1][1];
                      if (j && tp(b[1], [0, n]))
                        return [0, b, [0, m], 0];
                      break b;
                    }
                    break b;
                }
            }
            return [0, b, d, o(eR, c, p(g[33], g))];
          });
        return [0, [7, t, q], b[2], b[3], b[4]];
      case 11:
        var h = a[1],
          c = h[1];
        if (typeof c !== "number" && 14 === c[0]) {
          if (c[2]) break b; /* <--- error triggered here */
          if (h[4]) break b;
          var i = a[2],
            f = i[1];
          if (typeof f !== "number" && 9 === f[0]) {
            if (i[4]) break b;
            return [0, [14, c[1], [0, f[1]]], b[2], b[3], b[4]];
          }
          break b;
        }
        break b;
      case 18:
        var d = a[1];
        if (!d) break b;
        var k = d[2];
        if (!k) break b;
        if (!k[2]) break b;
        var l = dm(d),
          e = l[1];
        d: {
          e: if (typeof e !== "number" && 5 === e[0]) {
            var n = e[1][1];
            if (0 !== n[0]) break e;
            if (s(n[1], d1)) break e;
            if (e[2]) break e;
            if (l[4]) break e;
            var m = 1;
            break d;
          }
          var m = 0;
        }
        if (!m) break b;
        var u = b6(o8(b6(d)));
        return [0, [9, u], b[2], b[3], b[4]];
    }
  return Cs(g, b);
}
```
</details>

**Expected behavior**
Js_of_ocaml should generate code that is usable by other JavaScript tooling.

**Versions**
See section "Debugging notes" above about commits.

**Comment by hhugo** [comment]
The duplicated labels are not really duplicated because there are not inside the same function. They belong to two different (yet nested) functions.

**Comment by jchavarri** [comment]
Right, looking at the non-minified version I can see similar labeling, so I think my hypothesis is not correct. Will try to find some repro or more information, if there is anything I can test, please lmk. On 8 Dec 2023, at 23:53, hhugo ***@***.***> wrote:﻿
The duplicated labels are not really duplicated because there are not inside the same function. They belong to two different (yet nested) functions.

**Comment by jchavarri** [comment]
I tried with both esbuild 0.14.54 and 0.19.8 and saw the same error. I am noticing now that somewhere in the process with [vite](https://vitejs.dev/) (which is the tool driving esbuild), the top level `b` label is being removed. I'm going to close this as it seems an issue with some JS tooling rather than jsoo. Sorry for the distraction.

**Comment by hhugo** [comment]
Could you point to issues you end up opening if/once you figure out who's responsible for the deletion ?

**Comment by jchavarri** [comment]
It seems the problem is in rollup (another module bundler, i am not sure why vite uses two module bundlers 😞 )

Repro:

- Go to rollup playground, [loading the snippet](https://rollupjs.org/repl/?version=4.7.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwcShnJTJDJTIwYiklMjAlN0IlNUNuJTIwJTIwdmFyJTIwYSUyMCUzRCUyMGIlNUIxJTVEJTNCJTVDbiUyMCUyMGIlM0ElMjBpZiUyMCh0eXBlb2YlMjBhJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiklNUNuJTIwJTIwJTIwJTIwc3dpdGNoJTIwKGElNUIwJTVEKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTIwNyUzQSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBxJTIwJTNEJTIwYSU1QjIlNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwciUyMCUzRCUyMGElNUIxJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHQlMjAlM0QlMjBiUyhyJTJDJTIwZnVuY3Rpb24lMjAoYSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwYyUyMCUzRCUyMGElNUIzJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGQlMjAlM0QlMjBhJTVCMiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBiJTIwJTNEJTIwYSU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYiUzQSUyMGlmJTIwKGMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGglMjAlM0QlMjBjJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBlJTIwJTNEJTIwaCU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAodHlwZW9mJTIwZSUyMCElM0QlM0QlMjAlNUMlMjJudW1iZXIlNUMlMjIpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHN3aXRjaCUyMChlJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDAlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaCU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKHRwKGIlNUIxJTVEJTJDJTIwJTVCMCUyQyUyMGUlNUIxJTVEJTVCMSU1RCU1RCkpJTIwcmV0dXJuJTIwJTVCMCUyQyUyMGIlMkMlMjBkJTJDJTIwMCU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDExJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGklMjAlM0QlMjBjJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBrJTIwJTNEJTIwaSU1QjElNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbCUyMCUzRCUyMGslNUIxJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGYlMjAlM0QlMjBsJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjBmJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDAlMjAlM0QlM0QlM0QlMjBmJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAobCU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGklNUI0JTVEKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBtJTIwJTNEJTIwayU1QjIlNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbiUyMCUzRCUyMGYlNUIxJTVEJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChqJTIwJTI2JTI2JTIwdHAoYiU1QjElNUQlMkMlMjAlNUIwJTJDJTIwbiU1RCkpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjBiJTJDJTIwJTVCMCUyQyUyMG0lNUQlMkMlMjAwJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVCMCUyQyUyMGIlMkMlMjBkJTJDJTIwbyhlUiUyQyUyMGMlMkMlMjBwKGclNUIzMyU1RCUyQyUyMGcpKSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjAlNUI3JTJDJTIwdCUyQyUyMHElNUQlMkMlMjBiJTVCMiU1RCUyQyUyMGIlNUIzJTVEJTJDJTIwYiU1QjQlNUQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDExJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGglMjAlM0QlMjBhJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjJTIwJTNEJTIwaCU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAodHlwZW9mJTIwYyUyMCElM0QlM0QlMjAlNUMlMjJudW1iZXIlNUMlMjIlMjAlMjYlMjYlMjAxNCUyMCUzRCUzRCUzRCUyMGMlNUIwJTVEKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChjJTVCMiU1RCklMjBicmVhayUyMGIlM0IlMjAlMkYqJTIwJTNDLS0tJTIwZXJyb3IlMjB0cmlnZ2VyZWQlMjBoZXJlJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChoJTVCNCU1RCklMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwaSUyMCUzRCUyMGElNUIyJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGYlMjAlM0QlMjBpJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjBmJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDklMjAlM0QlM0QlM0QlMjBmJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaSU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjAlNUIxNCUyQyUyMGMlNUIxJTVEJTJDJTIwJTVCMCUyQyUyMGYlNUIxJTVEJTVEJTVEJTJDJTIwYiU1QjIlNUQlMkMlMjBiJTVCMyU1RCUyQyUyMGIlNUI0JTVEJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTIwMTglM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwZCUyMCUzRCUyMGElNUIxJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFkKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBrJTIwJTNEJTIwZCU1QjIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoIWspJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFrJTVCMiU1RCklMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbCUyMCUzRCUyMGRtKGQpJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGUlMjAlM0QlMjBsJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBkJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGUlM0ElMjBpZiUyMCh0eXBlb2YlMjBlJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDUlMjAlM0QlM0QlM0QlMjBlJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbiUyMCUzRCUyMGUlNUIxJTVEJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCgwJTIwISUzRCUzRCUyMG4lNUIwJTVEKSUyMGJyZWFrJTIwZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChzKG4lNUIxJTVEJTJDJTIwZDEpKSUyMGJyZWFrJTIwZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChlJTVCMiU1RCklMjBicmVhayUyMGUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAobCU1QjQlNUQpJTIwYnJlYWslMjBlJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMG0lMjAlM0QlMjAxJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwZCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbSUyMCUzRCUyMDAlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFtKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjB1JTIwJTNEJTIwYjYobzgoYjYoZCkpKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUIwJTJDJTIwJTVCOSUyQyUyMHUlNUQlMkMlMjBiJTVCMiU1RCUyQyUyMGIlNUIzJTVEJTJDJTIwYiU1QjQlNUQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMHJldHVybiUyMENzKGclMkMlMjBiKSUzQiU1Q24lN0QlNUNucSgxJTJDJTIwMiklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0FmYWxzZSU3RCU3RA==) with a failing function
- Change `treeshake` option on the right from `false` to `true`
- See how the top level `b` label disappears

**Comment by jchavarri** [comment]
https://github.com/rollup/rollup/issues/5292
