### ISSUE TITLE
[FEATURE REQUEST] Ellipse method for canvas API

### ISSUE THREAD

**Issue by FayCarsons** [ocsigen/js_of_ocaml#1552]
Hi! I am currently designing a creative coding library for OCaml, and I'd like it to be able to target the browser via the HTML canvas API. I've got a prototype working but I've hit a bit of a wall with rendering ellipses specifically: the ellipse method of the rendering context is missing. I would be happy to do the work to add it myself, but would probably need some guidance.

**Comment by hhugo** [comment]
You need to add the missing method to `canvasRenderingContext2D` in  https://github.com/ocsigen/js_of_ocaml/blob/0965d78747b12f3b15b2a86f2b7c888525a70001/lib/js_of_ocaml/dom_html.ml#L1753 

You should be able to copy and adjust signature found in other methods.
Don't forget to edit the mli file as well (`dom_html.mli`)

**Comment by FayCarsons** [comment]
@hhugo Filed a PR! Do I need to add this to the Changelog in my branch? I noticed the CI failed because I hadn't.

**Comment by hhugo** [comment]
I've merged your PR, Thanks for the contribution.
