### ISSUE TITLE
Formatting and linting the runtime with Biome

### ISSUE THREAD

**Issue by smorimoto** [ocsigen/js_of_ocaml#1583]
https://biomejs.dev

**Comment by smorimoto** [comment]
We should consider upgrading the runtime to ES6 at the same time. Most ECMAScript runtimes already support ES6, and there are many performance and runtime size benefits.

**Comment by hhugo** [comment]
> there are many performance and runtime size benefits

What performance benefits do you have in mind ?

**Comment by smorimoto** [comment]
I meant ECMAScript runtime performance: http://incaseofstairs.com/six-speed

**Comment by smorimoto** [comment]
It's actually more faster. I think we need to verify the actual jsoo runtime with something like JSBench: https://jsben.ch

**Comment by hhugo** [comment]
> It's actually more faster.

Can you be a bit more specific ?

**Comment by smorimoto** [comment]
I will prepare some benchmarks 🙂

**Comment by hhugo** [comment]
@smorimoto, do you want to keep this issue open ?

**Comment by smorimoto** [comment]
No 🙃
