### ISSUE TITLE
[BUG] binding properties are incorrectly minified

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#1586]
**Describe the bug**
Consider this piece of code:
```Javascript
function f (x) {
  let {toto} = x;
  return toto
}
```
It is minified into:
```Javascript
function
f(a){let{b}=a;return b}
```
which is not correct.

**Expected behavior**
Js_of_ocaml 5.4.0 outputs this result which is correct 
```Javascript
function
f(a){let{toto:b}=a;return b}
```

**Versions**
This is with Js_of_ocaml 5.6.0.

**Comment by hhugo** [comment]
Culprit is https://github.com/ocsigen/js_of_ocaml/blame/df7fe22450a1b52bd81d38142277e4abc61179e0/compiler/lib/js_traverse.ml

**Comment by vouillon** [comment]
I think that `Prop_ident (i, e)` should be handled the same way as `Prop_binding (PNI id, (BindingIdent i, e))` (where `i = S {name = id; _}`) when renaming variables.
