### ISSUE TITLE
Assertion fails in lib/parse_bytecode.ml

### ISSUE THREAD

**Issue by johnwhitington** [ocsigen/js_of_ocaml#1599]
**Describe the bug**

I see:

```
js_of_ocaml -q nodestubs.js cpdfzlib.js cpdfcrypt.js coherentpdf.byte
js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "compiler/lib/parse_bytecode.ml", line 870, characters 31-37: Assertion failed
```

To reproduce, download https://coherentpdf.com/tmp/jsbug.tar.gz and run `make`.

I have not yet tried to reduce to a minimal failing case. Obviously willing to, but I wanted to see if it rang any bells first, and what you suggest I try.

**Versions**

ocamlc 4.14.2, js_of_ocaml 5.7.1, MacOS.

**Comment by hhugo** [comment]
Can you test #1600 ?

**Comment by johnwhitington** [comment]
This works. Thanks for the prompt fix!
