### ISSUE TITLE
[BUG] jsoo's `Int64.of_string` fails while ocaml's does not

### ISSUE THREAD

**Issue by bzy-debug** [ocsigen/js_of_ocaml#1665]
## Describe the bug

With the same input, jsoo's `Int64.of_string` fails while ocaml's succeeds.

code example:

```ocaml
let () =
  Printf.printf "%Ld" (Int64.of_string "0u17965325103354776697")
```

### How to reproduce

check out https://github.com/bzy-debug/jsoo-int64-bug

## Expected behavior
jsoo prints the same value as ocaml

## version

```
ocaml 5.2.0
js_of_ocaml 5.8.2
```

**Comment by hhugo** [comment]
Thanks, fix in #1666
