### ISSUE TITLE
32 bits architectures: Cannot load js_of_ocaml-ppx_deriving_json: this object file uses unsafe features

### ISSUE THREAD

**Issue by balat** [ocsigen/js_of_ocaml#1667]
While releasing Ocsigen Toolkit, Opam CI fails on arm32 and x86_32 with the following error:
```
Cannot load js_of_ocaml-ppx_deriving_json: this object file uses unsafe features
```
Do you have an idea how to solve this?

See: https://github.com/ocaml/opam-repository/pull/26467

**Comment by hhugo** [comment]
My hunch is that this is specific to bytecode (arm32 and x86_32 cannot use native with ocaml5).

**Comment by hhugo** [comment]
The resolution should probably live inside ppx_deriving or ppxlib

**Comment by balat** [comment]
Thanks
