### ISSUE TITLE
[BUG] Marshalling problems in > 4.0.0 (jsCoq / coq-lsp)

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#1668]
Dear JSOO devs,

we are seeing some issues with JSOO > 4.0.0 in jsCoq, in particular when trying to read back a marshalled .vo file.

The error we get is "File "_vendor+v8.20+32bit/coq/lib/objFile.ml", line 110, characters 11-17: Assertion failed."

[This assertion](https://github.com/coq/coq/blob/v8.20/lib/objFile.ml#L105-L113) fails:

```ocaml
 let () = assert (Int64.equal (LargeFile.pos_in ch) (Int64.add s.pos s.len)) in
```

So maybe the regression is not in `Marshall`. Note that the files read are small in size.

`git bisect` points to:

[Runtime: update io.js, fix md5.js: 78ba544fb3dbcdb3437feafd43a8bdf6cba0d954](https://github.com/ocsigen/js_of_ocaml/commit/78ba544fb3dbcdb3437feafd43a8bdf6cba0d954)

which makes sense given the Coq code above.

This on OCaml 4.12, 32bit.

Thanks for all your help.

**Comment by hhugo** [comment]
> Seems like `Marshall` double-counted the number of bytes read, as in **bad** we have: 828 = 16 + 406 * 2

Yes, it was double counting.
