### ISSUE TITLE
unable to open the ocsigen website

### ISSUE THREAD

**Issue by tusharxoxoxo** [ocsigen/js_of_ocaml#1701]
i am trying to access the website but it ain't opening, i tried opening the website last week also, but still it's not opening
![image](https://github.com/user-attachments/assets/315845ed-6c34-4961-9fab-f6c7b58b95ba)
http://ocsigen.org/js_of_ocaml/

**Comment by hhugo** [comment]
I cannot reproduce, could this be due to some firewall restriction on your side ?
