### ISSUE TITLE
[FEATURE REQUEST] Audit/modernize Dom_html

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#1719]
Mouse events properties has been changed from int to float (see https://github.com/ocaml-wasm/wasm_of_ocaml/issues/105). There may be other similar changes.

We can probably remove some `optdef` a well now that IE is long gone.

We should check whether we are missing some widely implemented methods and properties.

**Comment by hhugo** [comment]
@vouillon, Do you have time to do more of this before the 6.0 release ? or should we keep it for later ?

**Comment by vouillon** [comment]
See #1768.

**Comment by hhugo** [comment]
Fixed by #1769
