### ISSUE TITLE
Source Maps Support/Documentation.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#188]
I tried the -sourcemap flag and expected to see the original OCaml code in each of the original .ml files in the Chrome file explorer. Instead, I saw all of the code (including libraries) inside of my `main.js` file (and saw no `.ml` files). The code was still completely unreadable. Is there documentation for generating proper source maps? What level of support is currently there?

**Comment by jordwalke** [comment]
I've been able to get source maps working after looking at whitequark's js_of__ocaml-example project. I found some workflow issues and maybe a small bug, but I'll make separate issues for them.

**Comment by fxfactorial** [comment]
@jordwalke perhaps `jsoo` can add ppx attribute automatically to code, surely the ppx extensions have access to all the relevant location information/etc.
