### ISSUE TITLE
Revise requestAnimationFrame

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#196]
The interface is now mostly [settled](http://www.w3.org/TR/animation-timing/) and includes cancellation, here's the current [browser support](http://caniuse.com/#feat=requestanimationframe). A simple polyfill (and links to more complex ones) can be found [here](https://gist.github.com/paulirish/1579671).

I may give it a shot later, but one question, do you include polyfills as plain js somewhere or you simply reimplement them in OCaml ?

**Comment by hhugo** [comment]
fix by  https://github.com/ocsigen/js_of_ocaml/commit/c94e16ca38e912e980a541da4800147ca23942fa
