### ISSUE TITLE
Using typed arrays?

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#237]
We may want to use typed arrays for float arrays and mutable strings. They should be faster than JavaScript arrays for large arrays and strings.

An issue is compatibility with older browsers

Also, typed arrays have a large memory overhead (> 120 bytes / array vs 48 bytes / array with V8 and Spidermonkey on a 64bit machine) and are costly to allocate. This is probably not a problem for strings: mutable strings tend to be reasonably large buffers. But a program might use arrays (or record of floats, as we cannot tell them apart) for complex numbers or small vectors...

**Comment by hhugo** [comment]
https://github.com/ocaml/ocaml/pull/163

**Comment by hhugo** [comment]
[Runtime: use typedArray when mutating string](https://github.com/ocsigen/js_of_ocaml/commit/43b903437fa5f26aca1f3beec0639f1893208406)
