### ISSUE TITLE
focus() missing from Dom_html.​element?

### ISSUE THREAD

**Issue by unhammer** [ocsigen/js_of_ocaml#247]
http://ocsigen.org/js_of_ocaml/api/Dom_html.inputElement-c has the focus and blur methods, but it seems like they should be on Dom_html.​element – see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.focus

**Comment by bmillwood** [comment]
I've noticed this -- in particular I want to focus `buttonElement`s (which is an easier / simpler change)
