### ISSUE TITLE
Make js library with js_of_ocaml

### ISSUE THREAD

**Issue by jmineraud** [ocsigen/js_of_ocaml#248]
Hello,

I would like to know if it would be possible to make javascript libraries from Ocaml code using jsoo ?

Best Regards,

Julien

**Comment by hhugo** [comment]
We need to describe this usecase in the manual. I'll leave the issue open as a reminder.
 
To do that, you need to export values into the global object (Js.Unsafe.gobal)
Here is a quick example: 

```
(* define the interface of mylib *)
class type mylib = object
  method add : (float -> float -> float) Js.callback Js.writeonly_prop
  method abs: (float -> float) Js.callback Js.writeonly_prop
  method zero : float Js.prop
end

let mylib : mylib Js.t =
  let open Js.Unsafe in
  global##mylib <- obj [||];
  global##mylib

let _ =
  mylib##add <- Js.wrap_callback (fun x y ->  x +. y);
  mylib##abs <- Js.wrap_callback (fun x -> abs_float x);
  mylib##zero <- 0.
```

you can then use the lib from JavaScript with
```
mylib.abs(mylib.add(4,-5.2))
```

**Comment by jmineraud** [comment]
Great thanks

**Comment by vouillon** [comment]
You can also build an object directly, rather than filling its properties after the fact:
```ocaml
let _ =
  let add = Js.wrap_callback (fun x y ->  x +. y) in
  let abs = Js.wrap_callback (fun x -> abs_float x) in
  let zero = 0. in
  let open Js.Unsafe in
  global##mylib <-
    obj [|("add", inject add); ("abs", inject abs); ("zero", inject zero)|];
```

**Comment by jmineraud** [comment]
Great this is useful

**Comment by Drup** [comment]
Note that the new ppx syntax makes creating such objects quite easier.

**Comment by Drup** [comment]
(and it was backported by @hhugo to camlp4, but not sure about the documentation)

**Comment by hhugo** [comment]
more precisely, you can now write
```
let _ =
  Js.Unsafe.global##mylib <- jsobject
    method add x y = x +. y
    method abs x = abs_float x
    val zero = 0.
  end
```

**Comment by jordwalke** [comment]
Maybe some day there can be a mode that allows you to (instead of writing to the global object) write to the "exports" field. This is the standard for exporting values in modular javascript packages and makes the library compatible with CommonJS which can then be used anywhere (on the server naturally via `node`) or in a browser via `browserify` (which converts `CommonJS` packages to be run in the browser).  It will also be natural to host these libraries that "export" fields on `npm`'s hosting as a result.

**Comment by Drup** [comment]
Do you have some more precise doc on that ?

**Comment by jordwalke** [comment]
It's surprisingly difficult to find a good overview doc, but basically here is how people create modules in JS that adhere to `CommonJS`:

- Create a folder called `MyProject/`
- Have a `package.json` that lists a bunch of information such as project name/version and dependencies.
- By default, `MyProject/index.js` is the thing that is "loaded" as the `MyProject` module. When other modules depend on ours, they do `require('MyProject')` and at runtime that is evaluated to the contents of `index.js` in the following way. Fields that you "export" in `index.js` become available on `require('MyProject')`. So if inside of `index.js` you do `exports.blah = "hi";`, then another package can do `require('MyProject').blah` which will be the value `"hi"`.
- There's a way to have it not assume your main module entrypoint is in `index.js` and customize which file actually contains the main module entrypoint.
- Some people do `module.exports = {...}` to export several things at once but that is not standard (though it works everywhere).

Here's a helpful doc about `package.json`.

https://docs.npmjs.com/files/package.json


Maybe someone could take this all the way and allow seamless integration with node :D which would allow JS to rely on OCaml modules and OCaml to rely on JS dependencies via `CommonJS`. See one step in that direction here: https://github.com/jordwalke/CommonML

**Comment by Drup** [comment]
> So if inside of index.js you do exports.blah = "hi";, then another package can do require('MyProject').blah which will be the value "hi".

Right, that's what I wanted to know. "export" (with quotation marks) is not a very precise description. :)

So, if I understand correctly, in the case of jsoo:
```ocaml
let export (field : string) val = JS.Unsafe.set (Js.Unsafe.variable "require") field val
```
should do the trick.

Then 
```ocaml 
let _ =
  export "mylib" jsobject
    method add x y = x +. y
    method abs x = abs_float x
    val zero = 0.
  end
```

The require function is pretty much untypable without more meta information (and the usual jsoo FFI should work fine there).

**Comment by jordwalke** [comment]
In your example:

    let export (field : string) val = JS.Unsafe.set (Js.Unsafe.variable "require") field val

Did you mean to say `"exports"` instead of `"require"`?

**Comment by Drup** [comment]
Indeed!

**Comment by jordwalke** [comment]
That should work, I believe.

**Comment by SGrondin** [comment]
I'm playing around with js_of_ocaml for the first time and I'm very happy to see that this is being considered. Being able to export things the Node way is HUGE. Unfortunately the docs completely ignore it and there are so few examples online, I'm still not able to figure it out. There's also no documentation about the ppx extensions and I'm completely stuck trying to compile Drup's example!

Anyway, just my 2c.

**Comment by Drup** [comment]
The ppx is still in the dev version for a good reason, you need OCaml trunk to use it.

The camlp4 syntax extension is documented [here](http://ocsigen.org/js_of_ocaml/dev/manual/library).

**Comment by hhugo** [comment]
- `cat file.ml`
```
let _ = Js.Unsafe.global##.mymath :=
    object%js
      method add x y = x +. y
      method abs x = abs_float x
      val zero = 0.
    end
```
- `ocamlfind ocamlc -linkpkg -package js_of_ocaml -package js_of_ocaml.ppx file.ml -o file.byte`
- `js_of_ocaml file.byte --pretty`

**Comment by hhugo** [comment]
http://ocsigen.org/js_of_ocaml/2.8/manual/export

**Comment by ranjanified** [comment]
> You can also build an object directly, rather than filling its properties after the fact:
> 
> ```ocaml
> let _ =
>   let add = Js.wrap_callback (fun x y ->  x +. y) in
>   let abs = Js.wrap_callback (fun x -> abs_float x) in
>   let zero = 0. in
>   let open Js.Unsafe in
>   global##mylib <-
>     obj [|("add", inject add); ("abs", inject abs); ("zero", inject zero)|];
> ```

Still a beginner, but this thing I have been looking for almost a week now. Thanks a lot!!! Looks like with `jsoo`, these nuggets are significantly useful, given someone runs into them with quite a fortune.
