### ISSUE TITLE
list of examples in the toplevel

### ISSUE THREAD

**Issue by Drup** [ocsigen/js_of_ocaml#252]
The list of examples in the toplevel is now weirdly formated. My guess would be broken CSS. @hhugo can you take a very quick look and/or tell me where to look ?

**Comment by hhugo** [comment]
I don't see anything weird on my side. It might have been a temporary issue with external css resources (bootstrap).

**Comment by Drup** [comment]
I still have the issue, [see here](https://i.imgur.com/Ylc7Owh.png).

**Comment by Drup** [comment]
I'm using firefox 35.

**Comment by hhugo** [comment]
It really looks like bootstrap is not loaded

**Comment by Drup** [comment]
Ah ! I think I found out the issue ! 

I load github in https, but bootstrap is fetched on http and firefox righfully forbid mixed content.

**Comment by hhugo** [comment]
fixed by 0838756c28c27089c6f6f9888b84739bb950bee3
