### ISSUE TITLE
Sourcemaps should relativize `sources` field.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#257]
When generating an `app.map` file, my source maps are relative to the file system root directory. I'm not sure why this would be different than what an ocamlbuild plugin would produce, but I'm manually compiling my files and the JS output.

The `sources` field contains a list of files such as:

    "/Users/me/MyProject/_build_folder/MyProject/src/file.ml",

From within `/Users/me/MyProject/`, I run the following command:

    js_of_ocaml  --source-map --debug-info --pretty --noinline ./_build_folder/MyProject/myProject.out -o ./app.js

Which produces 

    /Users/me/MyProject/app.js
    /Users/me/MyProject/app.map

I then run a web server from within this same directory (`/Users/me/MyProject/`), but source maps cannot be loaded because `app.map` lists original source files from file system root. Since a server is required to serve source maps, and it since it would be dangerous to run a web server from your filesystem root, this issue would come up for anyone that uses absolute paths for locations (and absolute paths make tooling in other parts of the toolchain much easier).

I believe if you encounter absolute paths, they should be printed relative to the output `js` file.

**Comment by jordwalke** [comment]
I just discovered that another option (at least in Chrome), is to prefix `file://` to the absolute path, and the browser source maps will be loaded from disk without needing to be served through the web server.

**Comment by jordwalke** [comment]
I actually found that as long as your `sourceMappingURL` is relative to the `.js` file (like `./myFile.map`), then the absolute form of the URL works fine.

**Comment by jordwalke** [comment]
I just realized that absolute paths in the `sources` field only works when reading the file from disk, not when hosting the `.js/html` from a server. I have compiled my `.cmo` files with absolute locations embedded in them, and there's not much I can do about that. Is this where `js_of_ocaml` gets the locations from?  Should there be an option to also inline the file contents as well (I believe there is a way to do that)? And/or (more easily) should `js_of_ocaml` relativize them like it does the reference to `./x.map`?

**Comment by vouillon** [comment]
If I remember right, the sourcemap spec allows file contents to be inlined in sourcemaps, but Chrome does not support that.

**Comment by vouillon** [comment]
There are several issues here:
1. We are using the paths given by the OCaml compiler, unchanged. But they may not correspond to the actual position of the ml files. For instance, for the standard library, we only have the file name, not a path to the .ml files in lib/ocaml. Also, sometimes, the .ml files are not available at all (in fact, that's often the case for librairies).
2. Even if we can find the full paths of the .ml files, these paths might not be served by the Web browser.
3. Web browsers do not behave gracefully when they do not find a source file. For instance, Chrome outputs an error on the console and shows a blank page. I think it would be better if it reverted to showing the generated JavaScript code in this case.

So, I think the source paths should be rewritten based on a list of search paths. Source files that are not found should probably not be included in the sourcemap. Maybe there should be an option to copy all source files to a given directory as well, where the Web server can find them?

I'm not sure we want to build that into Js_of_ocaml. A separate tool might be more convenient.

**Comment by gasche** [comment]
There was [work by Josh Watzman](https://github.com/ocaml/ocaml/pull/14) to add compilation-time filesystem path information in the debug information, which iirc was merged into 4.02. Could this be of any use here?

**Comment by jordwalke** [comment]
I believe Chrome supports the `sourcesContent` field (js_of_ocaml outputs an empty `sources_content` with an underscore).

Also, I feel that inlining the source content would make an excellent default for `js_of_ocaml` because then the default will be guaranteed to work out of the box (especially since (as @vouillon mentioned - Chrome does not degrade nicely when it doesn't work, and since we have no way to know *where* the file will be served from - it's the only way we can guarantee they will work).

As a second step, I could also imagine having an optional flag that is used for serious development. Something like `-server-will-be-ran-from /Users/me/where/run/web/server/`. Then, if `js_of_ocaml` can do one of two things:

1. Relativize the source files locations from the `-server-will-be-ran-from` option *if the locations are in fact within that directory*
2. Throw an error saying that it isn't possible to relativize the source files because they aren't within the server root. This is nice because it's clear the user is trying to use source maps, and `js_of_ocaml` has an opportunity to help diagnose the issue of *why* - because Chrome isn't helping us out here.

 This combination of default/option makes the default case "just work", and gives users feedback about *why* when it doesn't.

Thoughts?

**Comment by vouillon** [comment]
Indeed, `sourcesContents` seems supported. I'm not sure why I thought is was not...

**Comment by hhugo** [comment]
most of this has been answered by https://github.com/ocsigen/js_of_ocaml/pull/266 with explanation in https://github.com/ocsigen/js_of_ocaml/issues/264
