### ISSUE TITLE
Missing primitives when using curl and str 

### ISSUE THREAD

**Issue by alifirat** [ocsigen/js_of_ocaml#263]
Hello, 

In one of my project, I'm using the package curl and str and when I compile with js_of_ocaml, I have  some warnings saying there is missing primitives = 

  js_of_ocaml --disable genprim foo.byte
Missing primitives:
  helper_curl_easy_cleanup
  helper_curl_easy_duphandle
  helper_curl_easy_getinfo
  helper_curl_easy_init
  helper_curl_easy_perform
  helper_curl_easy_setopt
  helper_curl_global_init
  re_search_forward
  re_string_match

The helper primitives are caused by the use of curl and I'm asking if there is way to fix that.

**Comment by hhugo** [comment]
cross reference http://stackoverflow.com/questions/29122160/js-of-ocaml-missing-primitive-when-calling-ocurl-and-str

**Comment by alifirat** [comment]
Now, I'm using the XmlHttpRequest of js_of_ocaml to fix that. When I try to get the cookie with using 
 let cookie = match r.XmlHttpRequest.headers "Set-Cookie" , I have the following error in Chromium "Refused to get unsafe header "Set-Cookie". 

The probleme is from chromium or the cookie is not in the header response ?

**Comment by hhugo** [comment]
http://www.w3.org/TR/XMLHttpRequest/#the-getresponseheader()-method
```
client . getResponseHeader(header)
Returns the header field value from the response of which the field name matches header, unless the field name is Set-Cookie or Set-Cookie2.
```
