### ISSUE TITLE
Generate absolute paths to standard libraries in source maps.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#264]
Does `js_of_ocaml` know where the standard libraries that were compiled with the `.cmo` are located? If so, I believe the source maps should output the absolute paths. If not, could there be an option to tell `js_of_ocaml` where we believe they are located so that the source maps reflect this? It's really jarring when stepping through the Chrome debugger (by pressing "step over/step in" etc) and then a blank file pops up because the standard library isn't found. Imagine stepping through the debugger on something like `List.map myMapper lst`. It will eventually invoke `myMapper` and you want to step through all the standard library until it reaches `myMapper`, but you have to hit the "step over/step into" several times on a blank screen until you finally see your function's implementation.

As I mentioned in another issue, absolute paths have their own challenges (if absolute paths are given, then while debugging local `.html` files without a web server, the same origin policy will *not* restrict you from viewing the source maps. If serving your `.html` files from a web server, the same origin policy *will* restrict you from viewing them. Some other solution needs to be created for absolute paths in general with `js_of_ocaml`. But for this issue, just getting the standard library to include the absolute paths in the source maps is a good start and might be easy).

**Comment by hhugo** [comment]
Js_of_ocaml knows the path where cmos were compiled (standard library included).
using opam, the standard library is compiled in  `~/.opam/4.02.1/build/ocaml/stdlib`.
This path is useless unless you  set `OPAMKEEPBUILDDIR=true` so that opam does not remove temporary build directory.

Also, we can get more than one path so we have to inspect the file system to compute a single absolute path.
ie.  
```
modules : Lwt
paths   : ~/.opam/4.02.1/build/lwt.2.4.8/_build, ~/.opam/4.02.1/build/lwt.2.4.8/_build/src/core
```

It might be interesting to have ocaml register the path of cmos at link times.
We could then use `*.cmt` that have been installed next to `*.cmo`.

**Comment by hhugo** [comment]
https://github.com/ocaml/ocaml/pull/157

**Comment by hhugo** [comment]
@jordwalke #266 and the ocaml patch above should fix this.
Embedding sourcesContent inside sourcemap seems to be broken (could be due to wrong encoding).

**Comment by jordwalke** [comment]
It is probably related to encoding. We embed source map content inside of sourcemaps in react native as part of the core developer flow.

**Comment by hhugo** [comment]
sourcesContent now works on #266.

**Comment by jordwalke** [comment]
:+1:  Amazing.

**Comment by hhugo** [comment]
- source file that are not to be found are not included in sourcemap anymore.
- one can add search path using `-I` option.
   - because the stdlib path is part of search paths already
   - and because ocaml install the source files of the stdlib, we get location the stdlib out of the box.
- all paths are absolute.

**Comment by hhugo** [comment]
I've added an experiment on supporting `sourceRoot`.

Providing `--source-map-root ./sources`, js_of_ocaml will pretend all sources are located in `./sources`. The sourcemap will look like:

```
  "sources":
 ["./sources/stdlib.js",
  "./sources/mlString.js",
  "./sources/ieee_754.js",
  "./sources/int64.js",
  "./sources/lexing.ml",
  "./sources/buffer.ml",
  "./sources/camlinternalFormat.ml",
```
js_of_ocaml will also display the following info:
```
Source-map info: run 'sh wiki.make-sourcemap-links.sh' to create links to sources in ./sources
``` 

where `wiki.make-sourcemap-links.sh` contains the following.
```
#! /bin/bash
mkdir -p ./sources
ln -s /home/hugo/local/src/js_of_ocaml/examples/wiki/../../runtime/stdlib.js ./sources/stdlib.js
ln -s /home/hugo/local/src/js_of_ocaml/examples/wiki/../../runtime/mlString.js ./sources/mlString.js
ln -s /home/hugo/local/src/js_of_ocaml/examples/wiki/../../runtime/ieee_754.js ./sources/ieee_754.js
ln -s /home/hugo/local/src/js_of_ocaml/examples/wiki/../../runtime/int64.js ./sources/int64.js
ln -s /home/hugo/local/src/js_of_ocaml/examples/wiki/../../runtime/lexing.js ./sources/lexing.js
ln -s /home/hugo/.opam/4.02.1+32bit/lib/ocaml/buffer.ml ./sources/buffer.ml
ln -s /home/hugo/.opam/4.02.1+32bit/lib/ocaml/camlinternalFormat.ml ./sources/camlinternalFormat.ml
```

**Comment by jordwalke** [comment]
Sounds like all this should work well!

**Comment by hhugo** [comment]
#266 merged

**Comment by jordwalke** [comment]
It doesn't seem like the `-I` is being used for inline sourcemaps:

Here's an example command:

    js_of_ocaml -I /Users/me/github/Project/node_modules/Blah/src/ --source-map --source-map-inline --debug-info --pretty --linkall /Users/me/github/Project/_build_ocamlc_debug/Project/main.out -o ./app.js

The inlined source maps in `app.js` do not include the source files in the directory specified by `-I`.

Have you seen this?

**Comment by jordwalke** [comment]
Hmm, it actually might just be the case that source maps still don't work for me on the latest js_of_ocaml. I'll find more details.
