### ISSUE TITLE
Uncaught Not_found_exception with ghost locations

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#269]
When using Camlp4 (for instance, with Eliom), we can get events at locations that do not make sense:
```File "ghost-location", line 1, characters 0-0:```
In this case, the call to `chop_extension`  in `Parse_bytecode.find_loc` raises an uncaught `Not_found` exception.
I think we should just ignore events when the field loc_ghost of the location is true.

Also, I'm concerned about the amount of computation now done in Parse_bytecode.

**Comment by hhugo** [comment]
All` Not_found` exceptions are catch in `Parse_bytecode.find_loc`.
Do you mean the amount of computation in Parse_bytecode.Debug ?

**Comment by vouillon** [comment]
Indeed, that's an invalid argument exception.
