### ISSUE TITLE
Extend library to return properties of an object, or iterate on them

### ISSUE THREAD

**Issue by alainfrisch** [ocsigen/js_of_ocaml#270]
It would seem natural to expose in Js or Js.Unsafe some ways to iterate on all properties of an object.  This could be easily implemented by writing manually some JS code such as:

```
for (var property in object) {
    if (object.hasOwnProperty(property)) {
        ...
    }
}
```

and binding it to OCaml, but this would be a useful addition to js_of_ocaml's runtime and library.

**Comment by hhugo** [comment]
This is available here https://github.com/alainfrisch/gen_js_api/blob/master/ojs_runtime.js#L11

**Comment by alainfrisch** [comment]
As you can imagine, I was aware of it :)

Btw, I think that most primitives in ojs_runtime would be generally useful for js_of_ocaml users.

**Comment by hhugo** [comment]
would this be enough https://github.com/ocsigen/js_of_ocaml/blob/master/lib/js.mli#L306 ?

**Comment by little-arhat** [comment]
@hhugo shouldn't the function return `js_string t js_array t`? Otherwise, using `array_get` we will have `js_string optdef` and we can't do much with plain `js_srting` without `t`, aren't we?

**Comment by hhugo** [comment]
This is indeed a typo, fixed, thanks.

**Comment by hhugo** [comment]
Reopen if `Js.object_keys` is not enough for you use case.
