### ISSUE TITLE
Extend library to support wrapping of variadic functions

### ISSUE THREAD

**Issue by sbriais** [ocsigen/js_of_ocaml#273]
It would be useful to have defined in Js.Unsafe module a function

wrap_function: (any array -> any) -> any  
(or wrap_function: (any -> any) -> any)
where the argument of the function to be wrapped represent the "arguments" array.

That would allow to define variadic functions on the OCaml side.

**Comment by vouillon** [comment]
This is missing, indeed.

I think we also want variants of `Js.wrap_callback` and `Js.wrap_meth_callback` which expect a given number of arguments, following the JavaScript semantics for missing or extra arguments.

**Comment by alainfrisch** [comment]
>  think we also want variants of Js.wrap_callback and Js.wrap_meth_callback

Indeed!  We have added both OCaml->JS function wrappers (variadic + strict arity) for our gen_js_api project:

https://github.com/alainfrisch/gen_js_api/blob/master/ojs_runtime.js

**Comment by mfp** [comment]
I've been using modified `caml_js_wrap_callback` and `caml_js_wrap_meth_callback` functions for a long time. I just rebased my patch atop 2.5, and was about to submit a pull request when I bumped into this issue. Here's the freshly rebased patch

    From f3e35223b50e59372e047e31a92068e01bcbbafe Mon Sep 17 00:00:00 2001
    From: Mauricio Fernandez <mfp@acm.org>
    Date: Mon, 27 Apr 2015 13:48:11 +0200
    Subject: [PATCH 2/2] Support variadic callbacks.

    Needed in APIs like Node.js's that do things like (quoting from docs)

      var fs = require('fs');

      fs.unlink('/tmp/hello', function (err) {
        if (err) throw err;
        console.log('successfully deleted /tmp/hello');
      });
    ---
     runtime/jslib_js_of_ocaml.js | 20 ++++++++++----------
     1 file changed, 10 insertions(+), 10 deletions(-)

    diff --git a/runtime/jslib_js_of_ocaml.js b/runtime/jslib_js_of_ocaml.js
    index e57b3c6..716a935 100644
    --- a/runtime/jslib_js_of_ocaml.js
    +++ b/runtime/jslib_js_of_ocaml.js
    @@ -82,22 +82,22 @@ function caml_js_new(c, a) {
     //Requires: caml_call_gen,raw_array_copy
     function caml_js_wrap_callback(f) {
       return function () {
    -    if(arguments.length > 0){
    -      return caml_call_gen(f, raw_array_copy(arguments));
    -    } else {
    -      return caml_call_gen(f, [undefined]);
    -    }
    +    var args = (arguments.length > 0) ? raw_array_copy(arguments) : [undefined];
    +    while (f.fun) f = f.fun;
    +    var d = f.length - args.length;
    +    for (var i = 0; i < d; i++) args.push(undefined);
    +    return caml_call_gen(f, args);
       }
     }
     //Provides: caml_js_wrap_meth_callback const
     //Requires: caml_call_gen,raw_array_cons
     function caml_js_wrap_meth_callback(f) {
       return function () {
    -    if (arguments.length > 0) {
    -      return caml_call_gen(f,raw_array_cons(arguments,this));
    -    } else {
    -      return caml_call_gen(f,[this,undefined]);
    -    }
    +    var args = (arguments.length > 0) ? raw_array_cons(arguments, this) : [this, undefined];
    +    while (f.fun) f = f.fun;
    +    var d = f.length - args.length;
    +    for (var i = 0; i < d; i++) args.push(undefined);
    +    return caml_call_gen(f, args);
       }
     }
     //Provides: caml_js_equals mutable
    -- 
    1.8.5.2

It's been a long time since I wrote it, but I believe it was safe under the assumption that function application is total in Javascript.

**Comment by mfp** [comment]
It seems that the following is also needed (in my original code caml_js_wrap_callback still used `Array.prototype.slice`):


    -- runtime.js.orig	2015-04-28 12:14:29.977537309 +0200
    +++ runtime.js	2015-04-28 12:56:16.003511397 +0200
    @@ -2595,10 +2595,11 @@
     
     ///////////// Core
     
     //Provides: raw_array_sub
     function raw_array_sub (a,i,l) {
    +  if (l <= 0) return [];
       var b = new Array(l);
       for(var j = 0; j < l; j++) b[j] = a[i+j];
       return b
     }
