### ISSUE TITLE
Compiler seems to assume immutable arrays

### ISSUE THREAD

**Issue by alainfrisch** [ocsigen/js_of_ocaml#274]
Consider the code below:

````
let () =
  let a = [| Js.Unsafe.inject 123 |] in
  Array.unsafe_set a 0 (Js.Unsafe.inject 42);
  Js.Unsafe.fun_call (Js.Unsafe.variable "add") a
````

This generates JS code which calls "add" with 123, not 42 as one would expect:

````
     num_123_w_=123,
     ....
    [0,num_123_w_][0+1]=42;
    add(num_123_w_);
````
(I used Array.unsafe_set only to get simpler code; same problem with Array.set.)

Is there some built-in magic that requires the array argument to fun_call (and others) to be a fresh array?

**Comment by vouillon** [comment]
Indeed, we are assuming a constant argument array when optimizing Javascript function calls and similar primitives (see `specialize_js.ml`) . We should probably just disable the optimization when the array is not constant.
