### ISSUE TITLE
Incorrect creation of SVG elements in Tyxml_js.

### ISSUE THREAD

**Issue by pveber** [ocsigen/js_of_ocaml#276]
Elements created via `Tyxml_js.Svg` constructors do not appear in the browser. This is because they are created using `createElement`, as can be seen [here](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/tyxml/tyxml_js.ml#L87) and [there](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/tyxml/tyxml_js.ml#L92) in conjunction with [this](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/tyxml/tyxml_js.ml#L102). Instead, they should be created using `createElementNS` using the SVG namespace. This is done correctly in [Dom_svg](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/dom_svg.ml#L1450).

**Comment by pveber** [comment]
This bug's also affecting eliom client library, which [uses Tyxml_js](https://github.com/ocsigen/eliom/blob/master/src/lib/eliom_content_core.client.ml#L253). Not all F, D and R variants of Eliom_content.Svg seem to be affected, but in any case, I witnessed Html5.R.svg not working while Html5.F.svg did.

I tried to patch Tyxml_js, but I'm stuck with a typing issue. The Html5 module is defined like this:
```
module Svg = Svg_f.Make(Xml)
module Html5 = Html5_f.Make(Xml)(Svg)
```
where the `Xml` module used to define `Svg` and `Html5` has to be the same. But if they are the same, the same `Xml.node` and `Xml.leaf` will be used, and so use the same namespace, resulting in the problem I'm describing. Any suggestion?

**Comment by Drup** [comment]
I just pushed a commit to show you how it's done. The commit is a bit butchered up because apparently, `Dom_html.document` is not castable to `Dom_svg.document` and so I can't use `Dom_svg.createElement`. I have to copy the method. If you could investigate that and fix the issue (and pick the commit), that would be much nicer and I would merge.

**Comment by pveber** [comment]
Thanks a lot! I start working on this!

**Comment by pveber** [comment]
The [specification](http://www.w3.org/TR/SVG/struct.html#InterfaceSVGDocument) of `SVGDocument` shows that there are additional fields like `title`, which is correctly reflected by the [type](http://www.w3.org/TR/SVG/struct.html#InterfaceSVGDocument) in `Dom_svg`. Because of these fields, the cast can only be made from `Dom_svg.document` to `Dom.document`. Worse than this, the same spec says that in case of an embedded SVG element, there is no object of type SVGDocument available, only when the SVG element is the root element of the document. So at best in your code you could check the existence of an SVGDocument to use `Dom_svg.createElement` but you'd have to fallback to `Dom_html.document##createElement` for embedded SVG elements. So I guess your current code is the best we can hope (without touching tyxml itself, more on that later).

So I tested your patch and it still did not work, because the SVG element (for an embedded SVG) is created using `Html5.svg`, which again does not use the correct name space. Here's a (very ugly) addition to your patch that completely solves the issue (for me):
```ocaml
(* Here nothing changes *)
module Xml_Svg = struct
  include Xml

  let leaf ?(a=[]) name =
    let e =
      Dom_html.document##createElementNS(Dom_svg.xmlns, Js.string name) in
    attach_attribs e a;
    (e :> Dom.node Js.t)

  let node ?(a=[]) name children =
    let e =
      Dom_html.document##createElementNS(Dom_svg.xmlns, Js.string name) in
    attach_attribs e a;
    List.iter (fun c -> ignore (e##appendChild(c))) children;
    (e :> Dom.node Js.t)

end

module Svg = Svg_f.Make(Xml_Svg)
module Html5 = struct
  include Html5_f.Make(Xml)(Svg)

  let svg ?(xmlns = "http://www.w3.org/2000/svg") ?a children =
    let a =
      Xml_Svg.string_attrib "xmlns" xmlns
      :: Xml_Svg.string_attrib "xmlns:xlink" "http://www.w3.org/1999/xlink"
      :: (match a with None -> [] | Some a -> a)
    in
    Svg.toelt (Svg.svg ~a children)
end
```

Maybe there is a simpler and prettier way to fix all this, I don't know for sure. The only one I could think of would be to change the signature Xml_sigs.T in Tyxml, and add an optional argument:
```ocaml
val leaf : ?ns:string -> ?a:attrib list -> ename -> elt
val node : ?ns:string -> ?a:attrib list -> ename -> elt list_wrap -> elt
```
which would allow Xml implementations to do something special if there's a namespace provided. Maybe that's a delicate change to make, but since this is an optional argument most of the time user code should be left unchanged. And after all it doesn't feel too odd for an XML constructor to be able to specify namespace, right?

Anyway, I'm ready to make a patch for whaever solution you consider is best. Thanks a lot for the support!

**Comment by Drup** [comment]
Adding namespaces to leaf and node, doesn't help here, since it will still be the wrong namespace. It may be a good idea in general, though. It will only break libraries instantiating tyxml's functor, which is pretty much only eliom and jsoo at the moment, so no problem here.

I think a better solution is to fix tyxml so that the svg function in `Html5` calls the constructors from `Svg` instead. Especially since it's already half doing that ....

**Comment by Drup** [comment]
> Because of these fields, the cast can only be made from Dom_svg.document to Dom.document.

Maybe `Dom_svg.createElement` should take a `Dom.document` instead of a `Dom_svg.document`, then.

**Comment by pveber** [comment]
> I think a better solution is to fix tyxml so that the svg function in Html5 calls the constructors from Svg instead. Especially since it's already half doing that ....

Now that tyxml is fixed in that respect (ocsigen/tyxml#73), your initial fix is nearly OK (there is a small fix to add in module R I think). Let me submit a PR right away. Just one question, though. Regarding:

> Maybe Dom_svg.createElement should take a Dom.document instead of a Dom_svg.document, then.

I find this is a good idea, especially since there is currently no "official" way to create a Dom_svg.document, which makes Dom_svg.createElement a bit useless right now. Should I add this change to the PR and make the corresponding simplifications in f0df4d5?

**Comment by Drup** [comment]
Yes.

**Comment by pveber** [comment]
Finally I did not made the modification on Dom_svg. The reason is I was not sure what should be the type of the first argument of createElement. If it is a Dom_svg.document (current situation) we can't use the create function in an HTML document. Conversely, if it is a Dom_html.document, the create function cannot be used in an SVG document. The correct type should be Dom_svg.element Dom.document, and I think there should be an alias for it in Dom_svg, like svg_capable_document, and a constructor that would find the appropriate implementation of the object.

BTW, I'm wondering about the correctness of Dom_html.document: it's implemented as window##document, but what happens if the document is an SVG?

**Comment by Drup** [comment]
> The correct type should be Dom_svg.element Dom.document, and I think there should be an alias for it in Dom_svg

I think so too.

> BTW, I'm wondering about the correctness of Dom_html.document: it's implemented as window##document, but what happens if the document is an SVG?

That's a known issue, which also appears in node.js.
