### ISSUE TITLE
Remove warning when caml_js_var is called on "qualified" identifier

### ISSUE THREAD

**Issue by alainfrisch** [ocsigen/js_of_ocaml#277]
It the compiler detects a call to caml_js_var  (a.k.a Js.Unsafe.variable) with an argument containing dots, it gives a warning such as:

    Warning: "foo.y" should be written (Js.Unsafe.variable "foo")##y

but the code parses and interpret the qualified identifier properly (and so does the runtime function).  So what's wrong with it?

Moreover, the error message can be misleading for people who bind the primitive directly and don't use the js_of_ocaml's FFI.

**Comment by vouillon** [comment]
Historically, at some point, `Js.Unsafe.variable` was used with arguments containing dots as this was convenient, though this was undocumented and incorrect code could be generated. So, we added a warning and changed the compiler to generate correct code. We also added more general functions `Js.Unsafe.js_expr` and `Js.Unsafe.pure_js_expr` as alternatives.

Going forward, we could:
- deprecate `Js.Unsafe.variable`,
- turn the warning into an error,
- remove the warning (and document that this is correctly handled),
- or define `Js.Unsafe.variable` as an alias for `Js.Unsafe.pure_js_expr`.

Which would you prefer?

**Comment by alainfrisch** [comment]
If there is no performance downside of using pure_js_expr instead of variable (there is at least a tiny gain related to avoiding the check at runtime when the primitive is not eliminated), it seems reasonable to redefine variable as an alias for pure_js_expr and also mark it as deprecated (i.e. 1  + 4).  If the treatment is different, I'd go for 3.  I don't like 2, because the error is not well-defined, it depends on how clever the compiler is to detect that a function is indeed a call to a specific primitive.
