### ISSUE TITLE
Why do SVG elements like rect or circle have read only properties?

### ISSUE THREAD

**Issue by pveber** [ocsigen/js_of_ocaml#281]
The type `rectElement` in `Dom_svg` is:
```ocaml
and rectElement = object
  inherit element
[...]
  method x : animatedLength t readonly_prop
  method y : animatedLength t readonly_prop
[...]
end
```
which means that the properties `x` and `y` cannot be changed. Is this intended?

**Comment by hhugo** [comment]
That's what the spec says : https://developer.mozilla.org/en-US/docs/Web/API/SVGRectElement

**Comment by pveber** [comment]
That's true indeed! But how is it then that it is very frequent to see those attributes modified (e.g. in d3)? I just checked on a console, there's no problem to modify those attributes in practice...

**Comment by pveber** [comment]
For reference, I just mention that those attributes can (of course) still be modified using the `setAttribute` method of (SVG) elements. I'm guessing that sticking to the specification is of some importance, and that the type won't change (not sure really what'd be the best to do here). Thanks for the reply!

**Comment by vouillon** [comment]
I don't think you can modify these attributes. Here is what I get in a Chrome console (and I get basically the same with Firefox):
```
> r = document.createElementNS('http://www.w3.org/2000/svg','rect');
  <rect>​</rect>​
> r.x=33;
  33
> r.x.baseVal.value;
  0
> r.setAttributeNS(null, "x", 5);
  undefined
> r.x.baseVal.value;
  5
> r.x.baseVal.value=7;
  7
> r.x.baseVal.value;
  7
```
I think d3 provides helper functions to manipulate these attributes.

Anyway, what @hhugo meant is that the `Dom_svg` module was written from the spec. If actual implementations differ from the spec, we need to update this module. Also, it has not really been tested, so I would not be surprised if it contained a few bugs.

**Comment by pveber** [comment]
Well thanks, I feel I understand the matter much better now. Since the 'x' attribute cannot be anything (it has to follow the SVG specification), we have to use a "smart"-setter, that maintains the correct structure in the field. This includes checking type or parsing:
```
> r = document.createElementNS('http://www.w3.org/2000/svg','rect');
> r.setAttribute("x","R")
  undefined
  Unexpected value R parsing x attribute.
```
Thanks again!
