### ISSUE TITLE
Big integers are truncated

### ISSUE THREAD

**Issue by ztlpn** [ocsigen/js_of_ocaml#285]
I am having trouble using [bin_prot library](https://github.com/janestreet/bin_prot) with js_of_ocaml. The following code:
```
Printf.printf "Size: %d\n" (Bin_prot.Size.bin_size_int64 (Int64.of_int 0x8000))
```
when run in the browser produces `Size: 9` instead of correct `Size: 5`. Here is the relevant block of bin_prot source code: https://github.com/janestreet/bin_prot/blob/master/lib/size.ml#L16-L22

js_of_ocaml compiler produces a bunch of warnings:
```
Warning: integer overflow: integer 0xffffffff truncated to 0xffffffff; the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 truncated to 0x80000000; the generated code might be incorrect.
Warning: integer overflow: integer 0x100000000 truncated to 0x0; the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 truncated to 0x80000000; the generated code might be incorrect.
Warning: integer overflow: integer 0x100000000 truncated to 0x0; the generated code might be incorrect.
Warning: integer overflow: integer 0x80000000 truncated to 0x80000000; the generated code might be incorrect.
```
and in this case the generated code is indeed incorrect. The most obvious solution is to get rid of big integers in the source code but it is in third-party library and thus not easily modifiable. Am I out of luck?

**Comment by ztlpn** [comment]
As a side note, printing hex representations of integers in the warnings is a bit misleading in this case because they are exactly the same (but integers themselves and their signed decimal representations differ)

**Comment by Drup** [comment]
Integers are not 64 bits in javascript, so yes, you will have to change bin_prot I think. Note that they way it's currently done in bin_prot could be considered a bug, given how hostile to cross-compilation (and js_of_ocaml) it is.

**Comment by hhugo** [comment]
There are some work in progress to solve this inside core & co (including bin_prot).
https://github.com/janestreet/core_kernel/pull/8.
The easiest workaround for now is to use a 32bit compiler `opam switch 4.02.1+32bit`

**Comment by hhugo** [comment]
error message improved by https://github.com/ocsigen/js_of_ocaml/commit/f39398b473223bf00be3224ae85d83d68c412113

**Comment by hhugo** [comment]
http://ocsigen.org/js_of_ocaml/2.8/manual/core_async_kernel
