### ISSUE TITLE
Sourcemaps no longer work after upgrading to master from 2.5

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#289]
I thought I'd give the new inline sourcemaps a try:

Previously, sourcemaps were working splendingly on 2.5, except for all those issues regarding the stdlib, and absolute paths. I know that inlining the sourcemaps and source contents would solve all those problems, but after upgrading they don't seem to work at all.

`CommonML` is has a nice "one click" project build with js compilation that is useful for testing source maps on, so I'll give easy instructions on how to reproduce the issue I'm seeing:

   0. Make sure latest `nodejs` `0.12.0` is installed (only tested on Mac OS X).
   1. git clone https://github.com/jordwalke/CommonML
   2. cd CommonML/ExampleProjects/MyProject
   3. npm install
   4. node ../../build.js --forDebug=true --jsCompile=true
   6. In Chrome, open ./webAppRoot/index.html

On the `OPAM` `js_of_ocaml` `2.5`, this works great and you can see the sourcemaps and add breakpoints in the debugger in Chrome etc. Even without the inline source maps, on the old version, this works beautifully except for two things:

1. You cannot host the js from a server because the source maps were listed as absolute file paths (but works fine if only loading the html page from disk).
2. Stdlib sourcemaps don't work.

![commonmlanotherexampledependencyismissing](https://cloud.githubusercontent.com/assets/977348/7443128/6f91a380-f0ea-11e4-94ac-b2dd0561a1d9.png)

Now after upgrading, those two things should be fixed but instead, source maps no longer work at all.

You can try adding the  `--source-map-inline` option by editing the `CommonML` `build.js` file:

    vim ../../build.js
    # Add the option around line `1410` where we call `js_of_ocaml`.

![afterupgrading](https://cloud.githubusercontent.com/assets/977348/7443130/7c86e1cc-f0ea-11e4-8dc4-ae704cc624f0.png)

After doing so, here's the command that is executed:

`js_of_ocaml --source-map --source-map-inline --debug-info --pretty --linkall --noinline /Users/jwalke/github/CommonML/ExampleProjects/MyProject/_build_ocamlc_debug/MyProject/myProject.out -o ./app.js`

**Comment by jordwalke** [comment]
The build scripts will log all of the `ocamlc` and `js_of_ocaml` commands that are executed so can replay each operation to see if `js_of_ocaml` is doing something wrong or if the issue is simply that my build scripts are doing something wrong.

**Comment by jordwalke** [comment]
I just tried again using the steps above, and still - almost everything doesn't work - with or without inline sourcemaps.

The one thing that does work now is the built in standard libraries - so it's finding those paths okay. I looked at the .map file (and the inline base64 encoded maps) when I supply `-I` params (absolute), and none of the files are even detected. The steps above reproduce reliably.

**Comment by jordwalke** [comment]
Did you ever figure this out? I'm curious if you have a standard sample project that you use to test source maps/debugging.

**Comment by hhugo** [comment]
I have been using sourcemap recently with no issue. Do you still experience the same behavior ?

**Comment by jordwalke** [comment]
I haven't tried since, but the only thing that has changed was some relatively minor changes in `js_of_ocaml` in the newer versions. My build scripts haven't changed, and the parameters I'm passing haven't changed so I didn't think to try again. I will though, just to double check. The likely explanation is that something changed with how `js_of_ocaml` finds directories etc. I believe there were some commits intended to make things better, but it might have made it worse for the specific ways I happen to be compiling.

(This makes me thing it would be nice to have a generic config file for all of the tooling for OCaml including merlin, js_of_ocaml, opam which specifies where docs, source, build artifacts, and dependencies are).

I can try to upgrade again just to make sure.

**Comment by jordwalke** [comment]
I just confirmed that it still doesn't work. My source files are no longer listed in the `.map` file that is output. All of my compilation commands that were used to generate the output were specified using absolute paths (not sure if that's relevant).

**Comment by jordwalke** [comment]
Here's an example of how my files are compiled, and then how `js_of_ocaml` is invoked. The source maps have no mention of my compiled modules,  but in the previous version of `js_of_ocaml`, they did.

```
ocamlc.opt -w -30 -w -40 -bin-annot -c -bin-annot -g  -no-alias-deps -w -49 -I ./_build_byte_debug/CommonMLAnotherExampleDependency/publicInnerModules -I ./_build_byte_debug/CommonMLAnotherExampleDependency/privateInnerModules -I ./_build_byte_debug/CommonMLAnotherExampleDependency ./_build_byte_debug/CommonMLAnotherExampleDependency/commonMLAnotherExampleDependency.mli ./_build_byte_debug/CommonMLAnotherExampleDependency/commonMLAnotherExampleDependency.ml
ocamlc.opt -w -30 -w -40 -bin-annot -c -bin-annot -g  -I ./_build_byte_debug/CommonMLAnotherExampleDependency/publicInnerModules -I ./_build_byte_debug/CommonMLAnotherExampleDependency/privateInnerModules -I ./_build_byte_debug/CommonMLAnotherExampleDependency -open CommonMLAnotherExampleDependency -o ./_build_byte_debug/CommonMLAnotherExampleDependency/publicInnerModules/m_CommonMLAnotherExampleDependency__AnotherExampleMod -intf-suffix .mli -intf ./src/index/anotherExampleMod.mli -o ./_build_byte_debug/CommonMLAnotherExampleDependency/publicInnerModules/m_CommonMLAnotherExampleDependency__AnotherExampleMod -intf-suffix .mli -impl ./src/index/anotherExampleMod.ml

ocamlc.opt -o ./_build_byte_debug/CommonMLAnotherExampleDependency/commonMLAnotherExampleDependency.out -g ./_build_byte_debug/CommonMLAnotherExampleDependency/commonMLAnotherExampleDependency.cmo  ./_build_byte_debug/CommonMLAnotherExampleDependency/publicInnerModules/m_CommonMLAnotherExampleDependency__AnotherExampleMod.cmo

mkdir -p ./_build_byte_debug_js

js_of_ocaml  --source-map --no-inline --debug-info --pretty --linkall ./_build_byte_debug/CommonMLAnotherExampleDependency/commonMLAnotherExampleDependency.out -o ./_build_byte_debug_js/app.js

```

**Comment by hhugo** [comment]
I was able to reproduce your issue. Should be fixed in the new release.

**Comment by hhugo** [comment]
fixed by https://github.com/ocsigen/js_of_ocaml/commit/5cfa8fc5849afbd49e4aa117dd03e90f5863206d

**Comment by hhugo** [comment]
reopen if needed

**Comment by hhugo** [comment]
Forgot to push a file..  Ill do it later

**Comment by jordwalke** [comment]
Thank you, Hugo. I'll update my project and I will let you know if it worked correctly. Curious, could you explain the difference between what you were doing, and what I was doing?
