### ISSUE TITLE
With sourcemaps "step Over" steps over too much.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#290]
Suppose you have code like this:

    let _ = 
      let a =
        if Random.int 10 > 4 then "biggerThanFour" else "smallerThanFour" in
      let b = someOtherFunction () in
      print_string (a ^ b)

If I place a breakpoint on the line with  `Random.int`, I can step over the call into `Random.int`, and I can step over the `let b = ` line.
![screen shot 2015-05-02 at 6 19 21 pm](https://cloud.githubusercontent.com/assets/977348/7443338/cb84140e-f0f7-11e4-8eb5-59ebf8c91a6e.png)
But when stepping over the `let b =` line, it also steps over the `print_string` line.

However, when I repeat the experiment, but instead of stepping *over* the `let b =` line, I step *into* it and then back out of it:
![screen shot 2015-05-02 at 6 20 37 pm](https://cloud.githubusercontent.com/assets/977348/7443342/f464a398-f0f7-11e4-8087-704ac3f34c89.png)

I end up at the correct place - on the `print_string` line.

**Comment by vouillon** [comment]
The code generated for the last two lines is:
```
print_string_P_(_L_(_ac_,someOtherFunction_$_(0)));
```
So, I think what happens is that the debugger sees only one line here.

On the other hand, there is enough debugging information that the debugger can tell that on returning from `someOtherFunction` you arrive one the `print_string` line.

**Comment by vouillon** [comment]
I'm changing the semantics of the `--no-inline` option so that the call to `someOtherFunction` remains in a different statement. That should fix this issue.

**Comment by jordwalke** [comment]
Awesome! I think there's just a handful of little bumps like this that if fixed would make debugging a pleasant experience. I'll keep filing issues for the opportunities I find.
