### ISSUE TITLE
A way to inspect "local variables"

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#291]
It's really difficult (even when not inlined/minified) to inspect variables when debugging with source maps. It's almost impossible to tell which variables that are in scope (in JS) correspond to the variables in scope in the original code.

Some way to make this *possible* (even if not totally elegant) would be a huge help. Perhaps this is a huge undertaking, but I am curious about at least starting a discussion about how difficult it would be.

If this is incredibly difficult, I'm curious if a better/more complete approach to debugging would be to get the standard `ocamldebug` protocol to work with a system like `OBrowser` - even if only to debug the programs (while still using js_of_ocaml to run production code).

On the other hand, if reliable step-through and inspection of variables is possible with js_of_ocaml I think it would be much better to stick with the current approach. What's currently implemented is actually not half bad - aside from a couple improvements. I think developers could actually become fairly productive debugging with source maps! :D

**Comment by vouillon** [comment]
Do you have any idea of what we could do ?

We could try to preserve as much as possible the initial OCaml variable names (appending a suffix only if necessary), and prefix the JavaScript variable that are introduced by the compiler so that they are clearly separated. Do you think that would help?

**Comment by jordwalke** [comment]
I think that sounds like an improvement. I would have to see a demo, but usually dev tools autocomplete variable names, so the prefix is a good start.

Is there some way to distinguish varName_blah as the argument of the function I'm currently inside of in the original source?

**Comment by hhugo** [comment]
- when compiling with `--disable shortvar` (by default when using `--pretty`), js_of_ocaml tries to preserve as much as possible the initial OCaml variable names.
- when source-map is enabled, together with [resolve variable names](https://umaar.com/dev-tips/96-resolve-variable-names/) in chrome DevTools, one can inspect variable even if variable names are mangled.

**Comment by jordwalke** [comment]
"resolve variable names" looks really great. I had no idea Chrome dev tools supported that.

**Comment by hhugo** [comment]
"resolve variable names" is quite experimental. see how to Enable Hidden/Secret DevTools Experiments http://islegend.com/development/how-to-enable-devtools-experiments-within-google-chrome/

**Comment by hhugo** [comment]
shift shift shift shift shift shift
