### ISSUE TITLE
PUT requests with XmlHttpRequest.perform

### ISSUE THREAD

**Issue by pveber** [ocsigen/js_of_ocaml#293]
`XmlHttpRequest.perform` is a very convenient function, but is alas limited to GET and POST HTTP requests. However PUT/DELETE methods are necessary to access some REST API. Would a patch on this be considered? If so, what direction would be preferred? I see two options for now:
1. add a `http_method` optional argument
2. replace `get_args`, `post_args` and `form_args` (and maybe `content_type`) by a (polymorphic) variant argument like ``[ `GET of (string * string) list | `POST of (string * string) list * (string * string) list | ... ]``.

The first option seems easier (and less invasive), but some combinations of arguments would be invalid (like a `` `GET`` method with non-empty `post_args`).

**Comment by Drup** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/287 ? :)

**Comment by pveber** [comment]
Amazing, thanks!
