### ISSUE TITLE
bootstrapping js_of_ocaml, ocaml toolchain in nodejs

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#298]
like typescript, it would be nice to get rid of ocaml dependency

**Comment by Drup** [comment]
That's already done. We have a js_of_ocaml toplevel (sources are in the js_of_ocaml repository) and OCamlPro did the same for the whole compiler. I don't have a link for that though, @lefessan ?

**Comment by hhugo** [comment]
http://edit.ocamlpro.com/. It does nothing after I log in.

**Comment by hhugo** [comment]
@lefessan
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://gmail.login.persona.org') does not match the recipient window's origin ('https://login.persona.org').`
