### ISSUE TITLE
Bug with Graphics_js on Firefox

### ISSUE THREAD

**Issue by OCamlPro-Bozman** [ocsigen/js_of_ocaml#305]
Hi !

We notice that with a certain configuration with Firefox, the `open_graph` function open a new window with the old tabs and not a blank page.

Maybe a quick fix would be to not open a new window with empty url, but with "about:blank".

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/commit/173bb108205a6f873f90cc4458bb12d98f5a8d18
