### ISSUE TITLE
Flowtype as an example

### ISSUE THREAD

**Issue by m1sta** [ocsigen/js_of_ocaml#306]
Any chance you could get flowtype working via javascript (node.js)?

**Comment by Drup** [comment]
But ... flowtype is already written in OCaml. You don't need to go through javascript.

I think I don't understand what you want. :(

**Comment by m1sta** [comment]
Flowtype is written in ocaml, but it's used by javascripters. There are a lot of people who would love a port of flow in javascript. It could act as an example for how to write node.js modules using oCaml.

**Comment by Drup** [comment]
This is really not the right repository for such a project. You should talk to flowtype people. They are already well aware of js_of_ocaml and use it for various purposes. cc @avikchaudhuri
