### ISSUE TITLE
Dynlink support?

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#307]
Hi all,

first of all, thanks for js_of_ocaml and all other amazing tools.

Is there any plan on getting Dynlink.loadfile to work under js_of_ocaml?

I'd be curious to know how hard do you think it'd be, and what the required changes are.

Update: After using --toplevel I was able to make a bit of progress, now stuck at #308 , which breaks binary data read.

Thanks.

Best regards,
Emilio

**Comment by hhugo** [comment]
I'll push an example with Dynlink.loadfile in the toplevel later today.

**Comment by hhugo** [comment]
you can try `Dynlink.loadfile "/static/test_dynlink.cmo"` (https://github.com/ocsigen/js_of_ocaml/blob/master/toplevel/test_dynlink.ml)
see http://is.gd/Y9oFpY

**Comment by ejgallego** [comment]
Thank you so much hugo for fixing this request, and sorry for the long delay in replying.

I have used the dynlink support to implement dynamic loading of Coq plugins and so far seems to work very well!

However some plugins are > 1Mib bytecode files, so the compiler itselfs struggles a bit, I'll think a bit on how to integrate pre-compiled cmos into the dynlink chain.

Regards,
E.

**Comment by ejgallego** [comment]
I have been thinking of using this approach:

Modify caml_reify_bytecode so that it performs a md5sum of the input bytecode and compares it with an array of precompiled bytecode, avoiding the call to `compile` if there is a match.

Do you think this approach could be sensible?

Thanks,
E.
