### ISSUE TITLE
Provide the runtime for str 

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#315]
translate https://github.com/ocaml/ocaml/blob/trunk/otherlibs/str/strstubs.c to JavaScript

**Comment by Drup** [comment]
Can we not, and tell everyone to use re instead ? :)

(half-kidding)

**Comment by hhugo** [comment]
Or we do _AND_ tell everyone not to use it (and use re instead).
It seems to be relatively cheap to add and leads to a much better support of the standard ocaml distribution (only missing support for threads and Unix)

**Comment by Drup** [comment]
I know, that's why I was kidding. :)

**Comment by hhugo** [comment]
half-kidding!

**Comment by chrismamo1** [comment]
I would like to interject that [Humane_re](http://rgrinberg.com/blog/2014/05/23/humane-re-intro/) is a thing of beauty.

**Comment by hhugo** [comment]
We might be able to close this one soon. Support is on its way.
