### ISSUE TITLE
Get symbol table

### ISSUE THREAD

**Issue by marklrh** [ocsigen/js_of_ocaml#316]
Is there an existing API under ``/compiler`` that can (indirectly) get a symbol table of a JavaScript program? I glanced through the source code and it seems there isn't one?

**Comment by hhugo** [comment]
What do you mean by `a symbol table of a JavaScript program` ?

**Comment by marklrh** [comment]
@hhugo i mean the symbol table that will be built during the semantic analysis phase of a compiler

**Comment by hhugo** [comment]
Are you talking about JavaScript only (JavaScript minifier ) ? (or the compilation from OCaml bytecode to JavaScript).
What kind of information do you expect from this symbol table ?

**Comment by marklrh** [comment]
I'm really sorry I did not make my questions clear.
1) yes, I am talking about JavaScript only
2) function declaration, inside function declaration, there could be parameters, local variable declaration, etc. well, actually I am not 100% sure what I want now, I'm just wondering if ``js_of_ocaml/compiler`` has already done something similar.

**Comment by hhugo** [comment]
Have a look at https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/js_traverse.mli
You can use the ast mapper `freevar` to get parameters and local variable definition.
function declaration should be easy to add on top of that.

There is unfortunately not much documentation in the part of the compiler - let me know if you need more help on this.

What are you trying the do ?
