### ISSUE TITLE
js_of_ocaml fails to compile toplevel

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#318]
```
js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "generate.ml", line 1110, characters 8-14: Assertion failed
```
against latest trunk

**Comment by hhugo** [comment]
can you give more details ? ocaml version ? js_of_ocaml version ? command line ?

**Comment by bobzhang** [comment]
js_of_ocaml master
ocaml trunk
 
I inspected its output, its length is 2

 | Extern "caml_alloc_dummy_function", [Pc (Code.Var ..) ; Pc (Code.Var .. )] ->

will provide more information when I come back

**Comment by bobzhang** [comment]
This is full command line:
```
js_of_ocaml --toplevel --no-cmis -I /bb/mbigc/mbig2899/bgit/dist/refroot/amd64/opt/bb/lib64/mlfi/compiler-libs -I /bb/mbigc/mbig2899/bgit/dist/refroot/amd64/opt/bb/lib64/mlfi -I /bb/mbigc/mbig2899/bgit/dist/refroot/amd64/opt/bb/lib64/mlfi/lwt -I /bb/mbigc/mbig2899/bgit/dist/refroot/amd64/opt/bb/lib64/mlfi -I /bb/mbigc/mbig2899/bgit/dist/refroot/amd64/opt/bb/lib64/mlfi/js_of_ocaml --file outcometree.cmi:/cmis --file topdirs.cmi:/cmis --file toploop.cmi:/cmis --disable shortvar +weak.js +toplevel.js +nat.js toplevel.byte

```

**Comment by bobzhang** [comment]
thanks for the quick fix! now it proceeds, but I got a runtime error:

```
 Fatal error: Toplevel bytecode executable is corruptedjs_print_stderr @ toplevel.js:145
```

FYI, for small binaries, the generated code is correct

**Comment by hhugo** [comment]
I was able to compile a toplevel with ocaml trunk and to run it with https://github.com/ocsigen/js_of_ocaml/commit/1d1f1112bcab81be71dcc5d4ff69682db25d56e0.
You get your error because you're not linking with dynlink.js (ie:`+dynlink.js`)
