### ISSUE TITLE
The values of mouse_x and mouse_y in Graphics_js.status are not correct on Chrome

### ISSUE THREAD

**Issue by esumii** [ocsigen/js_of_ocaml#321]
The values of mouse_x and mouse_y in Graphics_js.status are not correct on Chrome (mine is version 43.0.2357.124 on Windows 8.1) when the page including the canvas is scrolled.

**Comment by hhugo** [comment]
I was not able to reproduce this issue. but I was able to get a different incorrect result when the size of the canvas is different from the apparently size. (e.g. canvas.width <> canvas.style.width).

Should be fixed by #321
