### ISSUE TITLE
MlString.prototype

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#323]
I saw this is such code in runtime/mlString.js

```js
MlString.prototype = { toString : ... }
```
Is this intentional? (instead of code below)

```js
MlString.prototype.toString = ...
```

I got some weird behavior when I am playing with js runtime since we reset prototype, some built-in properties are lost

**Comment by bobzhang** [comment]
Any follow up?

**Comment by vouillon** [comment]
I did not give much thought about that. You should consider OCaml as opaque datastructures and only access them through the functions defined in `mlString.js`. Then, I don't see how you can get any weird behavior.

**Comment by bobzhang** [comment]
Thanks for the info.
If it is not intentional, would you mind change it to a more idiomatic way, using `MlString.prototype.toString` instead?
