### ISSUE TITLE
indexedDB API

### ISSUE THREAD

**Issue by Drup** [ocsigen/js_of_ocaml#324]
@talex5 started the implementation on https://github.com/talex5/cuekeeper/blob/master/js/indexedDB.mli
It would be nice to complete it and add it to jsoo.

**Comment by talex5** [comment]
Note: this has moved to
https://github.com/talex5/irmin-indexeddb/blob/master/lib/iridb_js_api.ml

**Comment by hhugo** [comment]
Can be documented in #1217
