### ISSUE TITLE
jsoo_minify sometimes pollutes the global namespace

### ISSUE THREAD

**Issue by wiml** [ocsigen/js_of_ocaml#329]
Sometimes `jsoo_minify` will move a value out of the scope it was found in and assign it to a new, randomly-named global variable. This seems like it runs the risk of colliding with other javascript. I'm not sure exactly what causes it to do this, but the shortest case I've found is:

```javascript
(function(e){
    return [ "", "" ];
}(0));
```

which minifies to:

```javascript
var
b="";(function(a){return[b,b]}(0));
```

**Comment by vouillon** [comment]
This is due to constant sharing. Indeed, this should be disabled for `jsoo_minify`.

As a workaround, you can use the `--disable share` option.
