### ISSUE TITLE
ppx version of deriving_json

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#335]
We probably want the ppx syntax extension to be compatible with camlp4 one - so that one can use the ppx syntax together with a lib written with the camlp4 syntax.
@vouillon @balat can you confirm ?

I don't think this can be achieved with ppx_deriving -  @whitequark ?

for reference, the deriving (camlp4) syntax generate modules with the following signature:

```
  (** The signature of the JSON class. *)
module type Json = sig
  type a
  val t: a t
  val write: Buffer.t -> a -> unit
  val read: Deriving_Json_lexer.lexbuf -> a
  val to_string: a -> string
  val from_string: string -> a
  (**/**)
  val match_variant: [`Cst of int | `NCst of int] -> bool
  val read_variant: Deriving_Json_lexer.lexbuf -> [`Cst of int | `NCst of int] -> a
end
```

and use functors to dead with type parameters.

**Comment by hhugo** [comment]
@vouillon @balat


@whitequark

**Comment by whitequark** [comment]
@hhugo In principle, ppx_deriving does not restrict the generated code in almost any way. It allows a deriver to return an arbitrary structure, which a module of course is: https://github.com/whitequark/ppx_deriving/blob/master/src/ppx_deriving.mli#L25-L28

**Comment by whitequark** [comment]
Note that there's already https://github.com/whitequark/ppx_deriving_yojson/issues. If this is just an ocsigen-internal matter, why not switch to that completely? I don't recall any non-ocsigen library using the deriving package.

**Comment by Drup** [comment]
@hhugo there are no issues with that, I just haven't got around to implement it yet. It's on the TODO list. It can perfectly be done with ppx_deriving.

@whitequark js_of_ocaml's deriving_json is very specific and correspond roughtly to "marshal in json". It's not at all the same purpose than ppx_deriving_yojson.

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/364
