### ISSUE TITLE
js_of_ocaml output invalid syntax to google closure-compiler

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#337]
several erros:

```
toplevel.js:11517: ERROR - Parse error. identifier is a reserved word
int(ima,imb,imc){return anR(il8(0,ima,imb,imc))}function
^
```

```
ifan.js:831: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate languag\
e_in option.
                oname : objname.toString(),
```

**Comment by vouillon** [comment]
`int` was a reserved keyword in ECMAScript 3. I'm not sure any browser ever checked for that.

Can we have a bit more context regarding the second error. I don't see how js_of_ocaml can output a trailing comma in an object literal.

**Comment by vouillon** [comment]
The first error is fixed by commit e3461369af7e321def7d329b83fae15e35642506.

**Comment by hhugo** [comment]
not related to js_of_ocaml but to iocamljs https://github.com/andrewray/iocamljs/blob/9540447a0b54aa61f1416c5812698affee2d4b24/kernel.js#L143
@andrewray

**Comment by bobzhang** [comment]
indeed, thanks for the fix
