### ISSUE TITLE
Blank page with IE 10 browser

### ISSUE THREAD

**Issue by slegrand45** [ocsigen/js_of_ocaml#339]
Hi,

The code below works fine with Firefox and Chrome. But not with IE 10. I get a js error "Membre introuvable" (french message) and a blank page. 

```ocaml
open Lwt.Infix

let form =
  Tyxml_js.Html5.(form [
    input ~a:[
      a_input_type `Text ;
      a_id "name" ;
      a_name "name" ;
      a_value "John" ;
    ] ();
    button ~a:[
      a_button_type `Submit ;
    ] [ pcdata "Send" ]
  ])

let main _ =
  let node =
    Js.Opt.get(Dom_html.document##getElementById(Js.string "app"))
      (fun () -> assert false)
  in
  let () = Dom.appendChild node (Tyxml_js.To_dom.of_form (form)) in
  Lwt.return ()

let _ = Lwt_js_events.onload () >>= main
```

```html
<!doctype html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>TEST</title>
	</head>
	<body>
		<div id="app"></div>
		<script src="application.js"></script>
	</body>
</html>
````

Application built with those commands :
```shell
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,js_of_ocaml,js_of_ocaml.syntax,js_of_ocaml.tyxml,tyxml -syntax camlp4o application.byte
js_of_ocaml +weak.js --opt 3 -o application.js application.byte
```

**Comment by vouillon** [comment]
It is possible that IE10 switched to IE 7 compatibility mode, as your page was served locally.

IE7 does not allow to set the `name` and `type` attributes of an `input` element after the fact.

See http://stackoverflow.com/questions/13284083/ for how to prevent IE10 to switch to compatibility mode.

**Comment by slegrand45** [comment]
Thanks for your answer. I added a `X-UA-Compatible` meta directive in the `<head>` part. And i checked that the browser mode is "IE10" with a document mode set to "norms" with the development tools (F12 key). So it seems that the compatibility mode is not activated. Nonetheless i have still the error.

**Comment by slegrand45** [comment]
I made an other test with one of the vm available at http://dev.modern.ie/tools/vms/ . And it works ok on IE10... My bad. Sorry for the false report.
