### ISSUE TITLE
Discrepancy between Firefox and Chromium

### ISSUE THREAD

**Issue by slegrand45** [ocsigen/js_of_ocaml#349]
This example below works well with Firefox 40 (displays "Hello world"). But it doesn't work with Chromium 44.0.2403.89:

```ocaml
open Lwt.Infix
open Tyxml_js

let view =
  Html5.(div ~a:[] [
    (* if you remove the "~a:[]", this code works with Chromium *)
    Html5.(section ~a:[a_style "visibility: visible;"] [
      pcdata "Hello world"
    ])
  ])

let main _ =
  let doc = Dom_html.document in
  let parent =
    Js.Opt.get (doc##getElementById(Js.string "test"))
      (fun () -> assert false)
  in
  Dom.appendChild parent (Tyxml_js.To_dom.of_div view) ;
  Lwt.return ()

let _ = Lwt_js_events.onload () >>= main
```

With Chromium, the DOM doesn't seem to be modified at all. But if you remove the "~a:[...]" part, then it works like with Firefox.

The Chromium console shows the message:
```
 "Uncaught TypeError: Cannot set property style of #<Element> which has only a getter".
```

**Comment by hhugo** [comment]
It happens when setting style in `strict mode`. We probably need to parse the string to set individual properties.

```
(function (){"use strict"; return document.body.style = "visibility: visible;"})()
```

**Comment by hhugo** [comment]
We should use the cssText property

**Comment by hhugo** [comment]
thanks

**Comment by hhugo** [comment]
can you confirm it fixes your issue

**Comment by slegrand45** [comment]
Indeed, it now works with Firefox and Chrome (not tested with IE). Thank you very much! That was really a fast fix :-) !

**Comment by balat** [comment]
Do we need to do the same in tyxml?

**Comment by vasilisp** [comment]
I think we do need to do the same in `Eliom_client`. It would be nice if `Tyxml_js` exported some utilities for reactive updates, so that Eliom gets all the special cases for free. In fact, I was adapting bf36419448fd1b46fc5d290ce4ff6f4456abfd71 to Eliom just now: ocsigen/eliom@1588284f223e6d47e018f32b063930bbd1309bdc.

**Comment by vasilisp** [comment]
@hhugo, just updating the attribute and letting the property update fail (via `iter_prop_protected`) seems to have the effect we want. We tried this on the Eliom side (ocsigen/eliom@7c2f09995961e5e249a2abf1c566545967016106). Is there any good reason to set the cssText property? Maybe attempting to update the property should happen only in special cases (e.g., for #346), not by default?

**Comment by Drup** [comment]
> I think we do need to do the same in Eliom_client. It would be nice if Tyxml_js exported some utilities for reactive updates, so that Eliom gets all the special cases for free. In fact, I was adapting bf36419 to Eliom just now: ocsigen/eliom@1588284.

Isn't that already partially done ?

**Comment by hhugo** [comment]
It is partially done for reactiveList of element, not for attributes.
I don't have a good story for when to set props vs attributes.

Some properties (ie. `value`, `checked`) are not mapping html attribute with the same name.
attrib(value) <-> prop(defaultValue) 
attrib(checked) <-> prop(defaultChecked)

For those attributes/properties, we should probably set the attribute at node construction time, and set the property later when the signal gets updated.

It may make sense to also provide additional attribute `a_defaultValue`, `a_defaultChecked`
See comments in react (facebook): https://github.com/facebook/react/blob/ba81b60ad8e93b747be42a03b797065932c49c96/src/renderers/dom/client/wrappers/ReactDOMInput.js#L32
