### ISSUE TITLE
js_array#map is less polymorphic than expected.

### ISSUE THREAD

**Issue by kik** [ocsigen/js_of_ocaml#350]
"map" method can not make a bool array from int array because the "map"  method has type ('a -> 'a) -> 'a js_array.
```ocaml
open Js

let xs : int js_array t = Unsafe.js_expr "foo"

let ys = xs##map (fun a _ _ -> a + 1) (* ok *)
let zs = xs##map (fun a _ _ -> a > 1) (* error *)
```

Changing definition of class type "js_array" as follows does not work.
```ocaml
-method map :  ('a -> int -> 'a js_array t -> 'b) -> 'b js_array t meth
+method map : 'b. ('a -> int -> 'a js_array t -> 'b) -> 'b js_array t meth
```
This change causes error:
```
# File "js.mli", line 270, characters 15-75:
# Error: The universal type variable 'b cannot be generalized:
#        it escapes its scope.
```

At Japanese stackoverflow, Jacques Garrigue told me that such recursive type is forbidden because it makes type inference too difficult.
http://ja.stackoverflow.com/q/14191/10849

I think, like "array_get" and "array_set",  adding a function "array_map" is easy workaround.

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/commit/84bdd35fc0e89baa79d88c6525746b3022e4cf06
