### ISSUE TITLE
ppx documentation

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#353]
It seems that 21 days ago a new version of js_of_ocaml was released, it would have been nice to have announced it somewhere. Besides by reading the release notes it seems that this version has `ppx` support but this doesn't seem to be documented anywhere. It would also be nice to provide hints on how to migrate from `camlp4` to `ppx`.

**Comment by Drup** [comment]
I was planing to writing the email, but unfortunately got distracted. Will do asap.

Documentation is [here](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/ppx/ppx_js.mli) (CI is using 4.02.1, hence why it's not on the website). 

To migrate, just use https://github.com/janestreet/camlp4-to-ppx, it should work out of the box.
