### ISSUE TITLE
Unable to uncheck checkbox with Tyxml_js.R.Html5

### ISSUE THREAD

**Issue by slegrand45** [ocsigen/js_of_ocaml#354]
Hi,

The example below shows the problem. If the user press Enter in the input field, the checkbox should be unchecked. The DOM tree is indeed modified but the checkbox remains checked. Seems a similar problem to #346.

```ocaml
open Lwt.Infix
open Tyxml_js

let (rs, rf) = React.S.create true

let html =
  Html5.(div [
    input ~a:[
      a_input_type `Text ;
      a_onkeypress (fun evt -> if evt##keyCode = 13 then rf false; true) ;
    ] ();
    input ~a:( (R.filter_attrib (a_checked `Checked) (React.S.map (fun v -> v) rs)) :: [
      a_input_type `Checkbox ;
    ]) ();
  ])

let main _ =
  let doc = Dom_html.document in
  let parent =
    Js.Opt.get (doc##getElementById(Js.string "test"))
      (fun () -> assert false)
  in
  Dom.appendChild parent (Tyxml_js.To_dom.of_div html) ;
  Lwt.return ()

let _ = Lwt_js_events.onload () >>= main
```

**Comment by hhugo** [comment]
I cannot reproduce this behavior with my setup [using this code in toplevel] (https://ocsigen.org/js_of_ocaml/dev/files/toplevel/index.html#code=b3BlbiBMd3QuSW5maXgKb3BlbiBUeXhtbF9qcwoKbGV0IChycywgcmYpID0gUmVhY3QuUy5jcmVhdGUgdHJ1ZQoKbGV0IGh0bWwgPQogIEh0bWw1LihkaXYgWwogICAgaW5wdXQgfmE6WwogICAgICBhX2lucHV0X3R5cGUgYFRleHQgOwogICAgICBhX29ua2V5cHJlc3MgKGZ1biBldnQgLT4gaWYgZXZ0IyNrZXlDb2RlID0gMTMgdGhlbiByZiBmYWxzZSBlbHNlIHJmIHRydWU7IHRydWUpIDsKICAgIF0gKCk7CiAgICBpbnB1dCB%2BYTooIChSLmZpbHRlcl9hdHRyaWIgKGFfY2hlY2tlZCBgQ2hlY2tlZCkgKFJlYWN0LlMubWFwIChmdW4gdiAtPiB2KSBycykpIDo6IFsKICAgICAgYV9pbnB1dF90eXBlIGBDaGVja2JveCA7CiAgICBdKSAoKTsKICBdKQoKbGV0IG1haW4gXyA9CiAgbGV0IGRvYyA9IERvbV9odG1sLmRvY3VtZW50IGluCiAgbGV0IHBhcmVudCA9CiAgICBKcy5PcHQuZ2V0IChkb2MjI2dldEVsZW1lbnRCeUlkKEpzLnN0cmluZyAidG9wbGV2ZWwtZXhhbXBsZXMiKSkKICAgICAgKGZ1biAoKSAtPiBhc3NlcnQgZmFsc2UpCiAgaW4KICBEb20uYXBwZW5kQ2hpbGQgcGFyZW50IChUeXhtbF9qcy5Ub19kb20ub2ZfZGl2IGh0bWwpIDsKICBMd3QucmV0dXJuICgpCgpsZXQgcnVuX3RoaXMgPSBtYWluICgpOzsK)

The checkbox switches from checked to unchecked.
However, If you (un)check the box by clicking on it, the signal will not be updated. You'll need to synchronize it manually.

**Comment by slegrand45** [comment]
I should have mentioned it at first but i see the problem with the dev version of js_of_ocaml. My configuration is the following:

```
js_of_ocaml : development version
lwt : 2.5.0
react : 1.2.0
reactiveData : 0.1
tyxml : 3.5.0
```

But indeed it works ok with the 2.6 version.

**Comment by hhugo** [comment]
I believe the link from my previous post is using the dev version.

**Comment by slegrand45** [comment]
Ok. That's strange. All i can say is that on my side if i use the development version (master branch) of js_of_ocaml the example doesn't work. If i switch to the latest stable version (2.6) of js_of_ocaml, the example works as expected (when you press Enter in the input field, the checkbox is unchecked).

**Comment by hhugo** [comment]
works with chrome, fails with firefox

**Comment by slegrand45** [comment]
Thank you!
