### ISSUE TITLE
Marshaling loops on cyclic values

### ISSUE THREAD

**Issue by Tchou** [ocsigen/js_of_ocaml#359]
The following code snippet loops and eventually crashes the browser:

``` ocaml
type loop = { mutable pointer : loop option }
let l = { pointer = None }
let () = l.pointer <- Some l

let s = Marshal.to_string l []
let () = Firebug.console ## log (Js.string s)
```

compiled with:

``` shell
ocamlfind ocamlc -package js_of_ocaml,js_of_ocaml.syntax -syntax camlp4o foo.ml -linkpkg
js_of_ocaml a.out
```

and loaded by itself in a web page.
If js_of_ocaml's implementation of Marshal is not supposed to serialize cyclic values (the Json serialization does not either it seems), I think it should be prominently documented (glancing at the source code, desierialzing cyclic values seems implemented).

**Comment by hhugo** [comment]
There is only a partial support for `Marshal.to_string` mostly due technical limitation (ie. cannot distinguish between float `1.` and int `1`). Cycle value is not supported (yet). We should document or take some time to implement it.
