### ISSUE TITLE
A silent error

### ISSUE THREAD

**Issue by xvw** [ocsigen/js_of_ocaml#361]
I'm not sure it's a real mistake but this : 

```ocaml
    let line_style =
      "display:flex;"
      ^ "width:100%";
      ^ "flex-direction:row;"
      ^ "flex: 1;"
```

Compile without errors. 
(`^ "width:100%;"` instead of `^ "width:100%";`). 
Thanks.

**Comment by vasilisp** [comment]
Somewhat surprisingly, your code gets accepted by `camlp4o` (without loading JSOO or other extensions), and it gets translated to this:

```ocaml
let line_style =
  ("display:flex;" ^ "width:100%") ^ ("flex-direction:row;" ^ "flex: 1;")
```

Basically the semicolon before the caret is ignored. I think this is a valid issue, but for Camlp4, not for JSOO :).

**Comment by gasche** [comment]
Well formally this is valid as per the BNF [grammar](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html) saying that `<expr>;` is a valid expression, here the expression being `"width:100%";`. Camlp4o uses a different parsing order (and different priorities) than the buit-in parser, and in this particular case it gives un-intuitive results.

**Comment by hhugo** [comment]
closing as this is not related to js_of_ocaml
