### ISSUE TITLE
What is the type error nonsense output. 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#365]
I'm trying to convert the following JS code to jsoo.

```javascript
var http = require('http');

const PORT=8080; 

function handleRequest(request, response){
    response.end('It Works!! Path Hit: ' + request.url);
}
var server = http.createServer(handleRequest);

server.listen(PORT, function(){
    console.log("Server listening on: http://localhost:%s", PORT);
});
```

Okay, so let's go by the guide...

```ocaml
(* Assume this is module Http *)
class type incoming_message = object
  method httpVersion : Js.js_string Js.readonly_prop
end

class type server_response = object
  method url : Js.js_string Js.readonly_prop
end

class type server = object
  method listen : int -> (unit -> unit) -> unit Js.meth
end

class type http = object
  method methods : Js.js_string Js.js_array Js.readonly_prop
  method createServer :
    (incoming_message Js.t -> server_response Js.t -> unit) ->
    server Js.t Js.meth
end

let require () : http Js.t =
  Js.Unsafe.fun_call (Js.Unsafe.js_expr "require") [|Js.Unsafe.inject Js.string "http"|]
```

and the actual usage of the code

```ocaml
let () =
  let http = Http.require () in
  let our_server = http##createServer(fun a b -> print_endline "Handled request") in
  our_server##listen(8080, (fun () -> print_endline "started server"))
```

I think I have looked up everything correctly, but now I get this useless type error for my last line usage of `our_server...`

```shell
Error: This expression has type int -> (unit -> unit) -> unit Js.meth
       but an expression was expected of type int -> 'jsoo_29529091 Js.meth
       Type (unit -> unit) -> unit Js.meth is not compatible with type
         'jsoo_29529091 Js.meth 
```

What is this `jsoo_29529091 Js.meth` item? Where am I wrong? I want to use these syntax extensions if possible, this is ppx.

**Comment by vouillon** [comment]
I don't see what you are doing wrong, as this works for me, except that I had to add some parenthesis in the definition of function ```require```: ```Js.Unsafe.inject (Js.string "http")```

However, you should use ```Js.wrap_callback``` to turn OCaml functions into functions that can be called from JavaScript call. (Otherwise, your code may no longer work if we change the way we compile OCaml functions.)

**Comment by fxfactorial** [comment]
Use `Js.wrap_callback` for what? the `require` function? If I do that then the signature changes, can you provide the correct code sample?

This compile error just really confuses me, I'm using jsoo 2.6 in an _oasis project, the invocation is 

```shell
make
ocaml setup.ml -build 
Finished, 0 targets (0 cached) in 00:00:00.
+ /Users/Edgar/.opam/working/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package js_of_ocaml -package js_of_ocaml.ppx -I tests -I src -o tests/server.cmo tests/server.ml
File "tests/server.ml", line 6, characters 2-20:
Error: This expression has type int -> (unit -> unit) -> unit Js.meth
       but an expression was expected of type int -> 'jsoo_29529091 Js.meth
       Type (unit -> unit) -> unit Js.meth is not compatible with type
         'jsoo_29529091 Js.meth 
Command exited with code 2.
Compilation unsuccessful after building 9 targets (2 cached) in 00:00:00.
E: Failure("Command ''/Users/Edgar/.opam/working/bin/ocamlbuild' src/nodejs.cma tests/server.byte -tag debug' terminated with error code 10")
make: *** [build] Error 1
```

**Comment by vouillon** [comment]
I don't understand either. The actual type of the method ```int -> (unit -> unit) -> unit Js.meth``` is unified with the expected type of the method ```int -> 'a Js.meth```. So it looks like you are using the method ```listen``` with a single argument. But in your code there are two arguments.

**Comment by vouillon** [comment]
Here is how to use ```Js.wrap_callback```:
````ocaml
module Http = struct
  class type incoming_message = object
    method httpVersion : Js.js_string Js.readonly_prop
  end

  class type server_response = object
    method url : Js.js_string Js.readonly_prop
  end

  class type server = object
    method listen : int -> (unit -> unit) Js.callback -> unit Js.meth
  end

  class type http = object
    method methods : Js.js_string Js.js_array Js.readonly_prop
    method createServer :
      (incoming_message Js.t -> server_response Js.t -> unit) Js.callback ->
      server Js.t Js.meth
  end

  let require () : http Js.t =
    Js.Unsafe.fun_call (Js.Unsafe.js_expr "require")
      [|Js.Unsafe.inject (Js.string "http")|]
end

let () =
  let http = Http.require () in
  let our_server =
    http##createServer
      (Js.wrap_callback (fun a b -> print_endline "Handled request")) in
  our_server##listen
    (8080, Js.wrap_callback (fun () -> print_endline "started server"))
````

**Comment by fxfactorial** [comment]
Okay, thank you for the example usage of `Js.callback`. 

FWIW I still get this type error, same thing basically
```shell 
make
ocaml setup.ml -build 
Finished, 0 targets (0 cached) in 00:00:00.
+ /Users/Edgar/.opam/working/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package js_of_ocaml -package js_of_ocaml.ppx -I tests -I src -o tests/server.cmo tests/server.ml
File "tests/server.ml", line 14, characters 2-20:
Error: This expression has type
         int -> (unit -> unit) Js.callback -> unit Js.meth
       but an expression was expected of type int -> 'jsoo_29529091 Js.meth
       Type (unit -> unit) Js.callback -> unit Js.meth
       is not compatible with type 'jsoo_29529091 Js.meth 
Command exited with code 2.
Compilation unsuccessful after building 9 targets (3 cached) in 00:00:00.
E: Failure("Command ''/Users/Edgar/.opam/working/bin/ocamlbuild' src/nodejs.cma tests/server.byte -tag debug' terminated with error code 10")
make: *** [build] Error 1
```

Just to be clear then, this is not a bug with my code but with what, either ppx? Or `js_of_ocaml`?

**Comment by Drup** [comment]
@vouillon The bug appears only with ppx, it seems

**Comment by mfp** [comment]
FWIW, it compiles fine with the camlp4 syntax extension:



    $ ocamlfind ocamlc -g -annot -bin-annot -I src -package js_of_ocaml -package js_of_ocaml.syntax -syntax camlp4o -c nodejs.ml 
    $ ocamlfind ocamlc -g -annot -bin-annot -I src -package js_of_ocaml -package js_of_ocaml.syntax -syntax camlp4o -i nodejs.ml 
    module Http :
      sig
        class type incoming_message =
          object method httpVersion : Js.js_string Js.readonly_prop end
        class type server_response =
          object method url : Js.js_string Js.readonly_prop end
        class type server =
          object
            method listen : int -> (unit -> unit) Js.callback -> unit Js.meth
          end
        class type http =
          object
            method createServer :
              (incoming_message Js.t -> server_response Js.t -> unit) Js.callback ->
              server Js.t Js.meth
            method methods : Js.js_string Js.js_array Js.readonly_prop
          end
        val require : unit -> http Js.t
      end

**Comment by Drup** [comment]
@fxfactorial That's because you are using the camlp4 syntax with ppx. The proper way to write the last line is : 
```ocaml
  our_server##listen
    8080 (Js.wrap_callback (fun () -> print_endline "started server"))
```

**Comment by fxfactorial** [comment]
@Drup @mfp Awesome, I will try this tonight, much appreciated.
