### ISSUE TITLE
Typing JS Objects correctly

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#367]
Say we have a javascript function like 

```javascript
foo.thing(200, {"a":10, ...})
```

But the problem being the second argument is an arbitrary JS object, how can I capture that in a signature? 

I thought maybe something that captures this idea? 

```ocaml
method thing : int -> <..> Js.t -> unit Js.meth
```

I also consider saying making the second argument of type `Js.json` but even for that I'm not even sure how to construct values of type `Js.json`. (Also appreciate an example of that)

**Comment by vasilisp** [comment]
There is a `Js.Unsafe` module that defines an `any` type, to which everything can be coerced. I don't know whether it is a good idea to use it.

I think you are not supposed to construct a `Js.json`, there is just one (`Js._JSON`) that can be used to marshal/un-marshal other objects.

**Comment by fxfactorial** [comment]
@vasilisp  I also considered using the `any` type, but then what would I pass that would make sense? A string representation of the intended json? 

Is there anything I can do now to make this signature work?

**Comment by vasilisp** [comment]
You could use unsafe features to produce the objects. Your example would be:
```ocaml
Js.Unsafe.obj [|"a", Js.Unsafe.inject 10 (* ... *) |]
```

You could in principle also produce JSON strings and unmarshal them as `any`. I guess it depends on what you want to achieve.

**Comment by fxfactorial** [comment]
Thank you, back to my original main point, I want this signature, 
```ocaml 
method thing : int -> <..> Js.t -> unit Js.meth
```
to work. I'll try using `any`, see if it helps.

**Comment by fxfactorial** [comment]
Okay, the `any` approach works, but I wish it could be a bit more type safe than just `any`

**Comment by hhugo** [comment]
This works as expected using camlp4 syntax.
```
class type t = object method log : int -> < .. > Js.t -> unit Js.meth end
let x : t Js.t = Js.Unsafe.global##console
let () = x##log(3, jsobject val x = 123 end);;
```
the ppx version would look like
```
class type t = object method log : int -> < .. > Js.t -> unit Js.meth end
let x : t Js.t = Js.Unsafe.global##.console
let () = x##log 3 (object%js val x = 123 end);;
```
