### ISSUE TITLE
Correct signature and typing for an object with new invocation and mutating variables?

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#368]
Two questions:

Say we have this piece of JS code to translate. 

```javascript
var place_holder = null
var b = require("some_module")

place_holder = new b({"foo":800, "bar":600});
```

1) How could one go about writing the appropriate bindings? I want to use the ppx extension of `new%js` as well. I tried the technique of implementing the `call` method, but the code did not end up work
2)  Mutation. Should I do:
```ocaml

let place_holder = ref Js.null in 

place_holder := Js.Opt.return (new%js...)
```
3) Say a method has a signature of: `method foo : Js.js_string Js.t -> unit Js.meth` 
    3.1) Why do I have to wrap the `js_string` with `Js.t`? Obviously its a `JS` object, so why the redundancy 
   3.2) Why can't it just be a `string`?

**Comment by hhugo** [comment]
1) 
```
class type t = object
  method foo : Js.js_string Js.t -> unit Js.meth
end

let b : (< height : int Js.readonly_prop; width : int Js.readonly_prop > Js.t -> t Js.t) Js.constr =
  Js.Unsafe.js_expr "require(\"some_module\")";;

let place_holder = new%js b (object%js val foo = 800 val bar = 600 end);;

let () = place_holder##foo(Js.string "asda")
```

2) What's the purpose of the mutation here ?

3) see "Typing Javascript objects" at http://ocsigen.org/js_of_ocaml/2.6/manual/library

3.1) There is no redundancy here. `_ Js.t` and `js_string` do not overlap in any way.
`js_string` is not the type of a javascript object. Js objects have type `_ Js.t`

3.2) Can't be `string` because JavaScript strings are not compatible with ocaml ones.

**Comment by fxfactorial** [comment]
Excellent, will try this out later.

**Comment by fxfactorial** [comment]
Ah!! It works, excellent!. 

Two questions: 

1) What is the difference between `eval_string` and `js_expr`? 
2) If I want to do this trick with multiple different possible inputs, say the constructor can sometimes take a function instead of an object, then does that mean I have to make multiple top level definitions? Does the syntax trick of `_` only work with method names?
