### ISSUE TITLE
Module packing question.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#370]
I was examining the output of `js_of_ocaml` and I noticed that some portions of the code that pack/unpack/repack first class modules, end up copying the entire module into a new record (represented by an Array in JS). This has performance issues as well as unexpected/unpredictable behavior in terms of reference identity.

    let fstClass = ((module PackThis): (module IntoThisType))

In some cases, I found that the resulting module would be copied into a new Array. Is this happening at the byte code level (and thus carried over by js_of_ocaml) or is this something that js_of_ocaml is doing?

If this is inherent in first class modules (and not the fault of js_of_ocaml), it is rather disappointing. First class modules are a simple way to achieve structural subtyping on values in OCaml, but I don't think they can claim such when achieving structural subtyping of a value requires creating a *new* value in memory that is not referentially identical to the previous.

**Comment by Drup** [comment]
Pretty sure that's the semantic of first class modules, yes. It copies on type constraints.

**Comment by jordwalke** [comment]
It seems strange that, the following would ever be true for any `x`, for any `y`.

   (x: y) != x


I feel like every other use of type constraints is purely an assertion verified by the type system, not having anything to do with runtime behavior.

**Comment by gasche** [comment]
There are two semantically equivalent (in absence of a physical equality operator, which has some sort of bad side-effects) and "extremal" way to implement subtyping: one is to have subtyping be a no-op, and be flexible at lookup time (if subtyping allows for example to reorder fields, you may not know for sure at which offset to lookup any field), the other is to implement subtyping as a copy that returns an object containing only the restricted field, in some canonical order, and have the lookup offset statically computed from the type.

In OCaml, modules are assumed to be subtyped relatively rarely, and accessed a lot. The latter implementation choice, which makes subtyping a bit costly, but access very fast, is more desirable under these assumptions. Whether you use first-class modules or not, having different programming patterns where subtyping coercions are used a lot more often than accesses, then yes you will suffer. But there is always a compromise to make.

To summarize: no, subtyping does not have to be a no-op, it depends on the design choices in your runtime system (for example a subtyping relation `int :> float` may a no-op or not depending on runtime representation choices). That's something that is well-understood in research on typing coercions.

Note that *not* doing a copy of the object would also have interesting implications in term of garbage collection. If you keep a record with fields that are not hidden fin their static types, you may retain their value in the liveset where they should not -- and that has been an issue for users in practice, see duplicate issues [PR#5098](http://caml.inria.fr/mantis/view.php?id=5098), [PR#5932](http://caml.inria.fr/mantis/view.php?id=5932)). In other words, if you want subtyping to be a runtime no-op, then you need the GC strategy to depend on typing information -- whereas here subtyping has a runtime semantics that depends on typing information, and this allows a GC on less-typed value representations.

**Comment by hhugo** [comment]
Thanks @gasche  for this precise answer. I'm closing the issue now. Consider moving this to some Q&A
