### ISSUE TITLE
Typing JS function to OCaml signature, varargs.

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#373]
Say you have a JavaScript function whose semantics that the first argument be a string and the second argument be vararg, aka

```foo.on("something", arg1, arg2, .. argn)```

How could one express this in a method signature ? Is there any way to get a handle on the `arguments` variable?

**Comment by vasilisp** [comment]
Given that OCaml generally doesn't have variable-argument functions or methods (and for good reasons), `js_of_ocaml` cannot do much better than allow you to pass an array `[|arg1; ...; argn|]` as the last argument.

I guess you need to use `Js.Unsafe.call` or `Js.Unsafe.fun_call` to wrap your `foo.on` as a function that accepts a string and an array. You would internally prepend the string on the array, and pass the result to JS.

**Comment by dbuenzli** [comment]
> How could one express this in a method signature ? Is there any way to get a handle on the arguments variable?

It's difficult to answer without more details about what exactly you need to express. But there are various ways of expressing functions which accept a variable number of arguments in OCaml and/or operate according to format-string like structures. You can have a look at [this webpage](http://mlton.org/Fold), you may also find [the functional unparsing](http://www.brics.dk/RS/98/12/BRICS-RS-98-12.pdf) paper by Danvy to be interesting.

**Comment by Drup** [comment]
@dbuenzli But before that, let's just try with plain lists, just in case. :]

**Comment by fxfactorial** [comment]
@vasilisp Okay, I will have to find a solution...somehow. 

@dbuenzli What more details? 

I have a JS object foo and I wish I could write a class type like this.

```ocaml

class foo = object
method on : Js.js_string Js.t -> 'a Js.t varargs -> unit Js.meth
```

**Comment by dbuenzli** [comment]
If the string is typewise unrelated to the varargs and that the varargs are uniform as is suggested by the signature you wrote then @drup's suggestion of a list makes sense.

**Comment by fxfactorial** [comment]
@dbuenzli So I can replace the varargs with a `'a Js.t list` and it will work alright? Will try.

**Comment by dbuenzli** [comment]
You'll have to wrap as @vasilisp suggested.

**Comment by fxfactorial** [comment]
@dbuenzli Okay, can anyone provide an end to end example? If I wrap it as a function then it will be ugly and I lose the "OO" of the object. (Just one method ends up being a function?)

**Comment by Drup** [comment]
You should abstract the "OO" away anyway. Don't stick to the jsoo API, it's very low level and not designed to be convenient to program in. You should create an overlay that fits OCaml idioms.

**Comment by fxfactorial** [comment]
@Drup Debatable and not something I want to do at the moment.

**Comment by fxfactorial** [comment]
@Drup Okay, after thinking about it some more I think you're right. It will make for a more pleasant API...but will involve a lot more coding that I originally planned on doing.

**Comment by dbuenzli** [comment]
You may want to check https://github.com/LexiFi/gen_js_api though it doesn't seem it was ever formally released.

**Comment by fxfactorial** [comment]
@dbuenzli I did, it looks like too much hassle for me to just install it, I'll take @Drup's advice, will lead to a much nicer experience/codebase.
