### ISSUE TITLE
Js_of_ocaml broken with OCaml trunk

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#374]
https://github.com/ocaml/ocaml/commit/aaeda7763bca8402cb2e53bdb57a456a04ada04b
breaks an invariant used in the js_of_ocaml compiler https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/parse_bytecode.ml#L1672

The following code should reveal the issue.
```
let () =
  let i = Random.int 2 in
  let (_x, _y) =
      try (* pushtrap *)
        if i = 0
        then
          (1, 1) (* poptrap A;  *)
        else (2, 2) (* poptrap B; *)
      with _ -> (3, 3)
  in
  ()
```

**Comment by hhugo** [comment]
@vouillon, @gasche, @alainfrisch

**Comment by alainfrisch** [comment]
I don't know much about how js_of_ocaml works.  Can you explain which invariant is expected?  I don't think this new optimization, for instance, is the first case where a staticfail can cross a try..with handler.  This could already happen with the recent "match with exception" construction, I think.

**Comment by hhugo** [comment]
I'm not very familiar with this part of the code base, but from what I understand, we expect a unique `poptrap` for every `pushtrap` (meaning there is a single continuation after the try-catch).

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/377
