### ISSUE TITLE
Actual working example and clarification on PPX + Deriving

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#376]
I want to use deriving with PPX. 

Issue 1.

on opam there are three things for deriving, `deriving`, `deriving-ocsigen`, `ppx_deriving`. Pretty sure the first two are camlp4 based, but does `ppx_deriving` play nicely with jsoo? Docs are silent on the matter. 

Issue 2.

Trying to get it working with this example, 
```ocaml
type g = {title : string option; age : int option; } deriving (Json)

let () =
  let str = Json.output<g> {title = Some "hello"; age = Some 123} in
  print_endline (Js.to_string str)
```

And trying all kinds of compiling, with no success. Also does deriving work for arbitrary types? Also unclear from docs. Will an option of None become a JavaScript null?

Would appreciate a self contained example like mine along with complication command.

**Comment by Drup** [comment]
Yes, it works well with jsoo. There is nothing special to do.

**Comment by fxfactorial** [comment]
@Drup Nothing special to do means I just use package `js_of_ocaml.ppx` and it works, or I need to include `ppx_deriving` in my `-packages` argument to `ocamlfind`

**Comment by Drup** [comment]
Ah, you want deriving (Json) to work, not just general deriving. That's a different matter. See https://github.com/ocsigen/js_of_ocaml/pull/364

**Comment by fxfactorial** [comment]
@Drup Okay, so this isn't merged yet, but once it will, will my example work? What does option become?
