### ISSUE TITLE
Error handling, need a f : (exn -> Js.error)

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#378]
I've noticed that try/with expressions catch JS exceptions, like typeError correctly, but I'm having to do stuff like so:

```ocaml
try
  //something that can throw
with _ -> // handle issue
```

I've tried getting a handle on the exception as a Js value but its of type `exn` and I don't see anything in `js_of_ocaml` to convert an OCaml exception as a Js.error. 

Ideally I guess id be something like this

```ocaml
try
  //something that can throw
with e -> Js.of_exn e 
///more code
```

Also curious, is it possible for the try/with expression to directly give back Js.errors instead of ocaml exceptions? Perhaps an addition for the ppx extension?

**Comment by hhugo** [comment]
JavaScript exception are wrapped in the exception `Js.Error js_error`

**Comment by fxfactorial** [comment]
Excellent, just tried it and worked as expected. I love js_of_ocaml more and more.
