### ISSUE TITLE
How to properly catch a 404? 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#379]
I'm trying to handle the error of a bad `XmlHttpRequest`. Since I'm using ppx, I initially thought that 

```ocaml
try%lwt
...
with ...
```

would work, but it doesn't. Seems like it just needs to be implemented. 

I then tried something like

```ocaml
let do_request () =
  let open Lwt in
  let open XmlHttpRequest in
  Lwt.catch begin fun () ->
    get "http://localhost:8080/code" >>= fun frame ->
    Lwt.return frame.contents
  end

    begin fun exn ->
      print_endline "CODE QUERY DIDNT WORK";
      Lwt.return ""
    end
```

But this doesn't catch the error either, the documentation doesn't say it raises an exception and a cursory glance of the source code doesn't say anything about exceptions for this, just for crappy headers.

So how can I properly catch a 404?

**Comment by hhugo** [comment]
have a look at the field `code` in `http_frame`

**Comment by fxfactorial** [comment]
Ah, that was stupid on my part. I kept thinking it was an exception since I was seeing 
`GET http://localhost:8080/cod 404 (Not Found)` in the console. 

I wonder if there's a way to turn that off, is that a Browser responsibility or can JS code turn that off?
