### ISSUE TITLE
Broken compilation with 4.01

### ISSUE THREAD

**Issue by Kakadu** [ocsigen/js_of_ocaml#382]
In this [commit](https://github.com/ocsigen/js_of_ocaml/commit/ebf7150f41c64ac0e18e9f89d1e565b6c3115414#diff-3855a136aa4cac3ff7f51d41b1d169b2R48)

````
File "tyxml/tyxml_js.mli", line 48, characters 13-48:
Error: The signature constrained by `with' has no component named W
make[1]: *** [tyxml/tyxml_js.cmi] Error 2
````

**Comment by vasilisp** [comment]
Js_of_ocaml master currently depends on TyXML master. Sorry for the inconvenience.
