### ISSUE TITLE
Check OCaml compiler change : is it compatible with Js_of_ocaml  ?

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#384]
following https://github.com/ocsigen/js_of_ocaml/issues/374

New bytecode pattern introduce by @trefis https://github.com/ocaml/ocaml/pull/305
might break important invariant in the js_of_ocaml compiler.

We should figure out if js_of_ocaml can support this change before the feature makes its way into trunk. @vouillon, would you have time to look at it ?

**Comment by alainfrisch** [comment]
Is the invarariant broken by ocaml/ocaml#305 exactly the same as the one causing #374?

**Comment by hhugo** [comment]
It believe not but I didn't spend much time trying to figure this out.
```
$ compiler/js_of_ocaml test.cmo --no-runtime -disable check-magic-number
[Warning] long options with a single '-' are now deprecated. Please use '--' for the following options: -disable
compiler/js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "generate.ml", line 1401, characters 8-14: Assertion failed
Raised at file "generate.ml", line 1401, characters 8-53
Called from file "generate.ml", line 1631, characters 4-62
Called from file "generate.ml", line 1509, characters 10-128
Called from file "generate.ml", line 1631, characters 4-62
Called from file "generate.ml", line 1509, characters 10-128
Called from file "generate.ml", line 1794, characters 4-88
Called from file "generate.ml", line 1826, characters 12-45
Called from file "generate.ml", line 1836, characters 10-32
Called from file "driver.ml", line 83, characters 26-31
Called from file "driver.ml", line 83, characters 26-31
Called from file "driver.ml", line 83, characters 26-31
Called from file "driver.ml", line 83, characters 26-31
Called from file "driver.ml", line 83, characters 26-31
Called from file "driver.ml", line 83, characters 26-31
Called from file "jsoo_compile.ml", line 39, characters 9-13
Re-raised at file "jsoo_compile.ml", line 39, characters 44-45
Re-raised at file "jsoo_compile.ml", line 45, characters 10-13
Called from file "jsoo_compile.ml", line 112, characters 6-300
```

the other invariant breakage was multiple poptrap for a single pushtrap.
and was failing in one of the two locations: 
https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/parse_bytecode.ml#L1678
https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/generate.ml#L1359
It should be fixed by https://github.com/ocsigen/js_of_ocaml/pull/377

**Comment by vouillon** [comment]
Js_of_ocaml is currently assuming that there is a single continuation after a `try ... with ...`
With https://github.com/ocaml/ocaml/commit/aaeda7763bca8402cb2e53bdb57a456a04ada04b, we have several possible continuations when no exception is raised, while with ocaml/ocaml#305 we have several continuations after an exception is caught.
We already have the machinery to deal with this (for `&&`,  for instance), so we should be able to deal with that.
