### ISSUE TITLE
Redundant removeChildren call?

### ISSUE THREAD

**Issue by slegrand45** [ocsigen/js_of_ocaml#386]
At https://github.com/ocsigen/js_of_ocaml/blob/master/lib/tyxml/tyxml_js.ml#L232, there is a call to the `removeChildren` function. I was wondering if this call is indeed necessary? Because there is already a `removeChildren` call at https://github.com/ocsigen/js_of_ocaml/blob/master/lib/tyxml/tyxml_js.ml#L225 for the `Set` action.

If my understanding is right, the fact that there is this call to `removeChildren` in the `update_children` function would cancel the benefits of the diffing patch proposed by @vasilisp (see https://github.com/ocsigen/reactiveData/pull/12).

**Comment by vasilisp** [comment]
`update_children` is called _just once_, as an initialization step. The node is subsequently managed reactively. IIRC we need the `removeChildren` call there, e.g., for server-side-produced children before the client-side reactive updates start.

With the diffing patch, we will be trigerring the `Patch` case in `merge_msg` where `removeChildren` does not happen.

I have certainly tested `Tyxml_js.R` with the diffing patch, and I think it works as expected :).

**Comment by slegrand45** [comment]
Ok, i didn't get it was only call on an initialization step... :blush: Sorry for the noise. Thank you very much for your clarification.
