### ISSUE TITLE
Add examples that integrate with JS code

### ISSUE THREAD

**Issue by nathancarter** [ocsigen/js_of_ocaml#387]
All the examples in the `examples` subfolder are exclusively in OCaml.  None of the `.html` files includes any JavaScript code at all.  This is a unique subset of the expected applications of `js_of_ocaml`; I would think that many applications will include some code in OCaml and some in JavaScript.

For instance, my situation is that I have a large and existing app in JavaScript, and I want to compile an existing OCaml library so that my app can use it.  I would think that there would be many similar use cases, especially since [JS is among the most popular of languages](http://sogrady-media.redmonk.com/sogrady/files/2014/01/lang-rank-114-wm.png).  But the examples folder seems to focus exclusively on the (possibly rare?) case in which the entire app will be written exclusively in OCaml.

Thus this issue requests extending the examples folder with examples that show how to access compiled OCaml from in-page JavaScript.  I did find [this article](http://reversemicrowave.me/blog/2015/04/20/js_of_ocaml-pwdgen/) that gave me some brief tips on how to do it, but that page confesses that it's not very experienced, and may not be doing it the correct way.  An official example would be good, and with some supporting documentation even better.

I checked the existing docs [here](http://ocsigen.org/js_of_ocaml/2.6/manual/) but the JS-OCaml connections discussed there seem to be only in the other direction:  If you have an existing JS library you need to access from OCaml, not the reverse.

**Comment by Drup** [comment]
Hum, I feel like the question is more about how to do reverse-FFI. I think @jordwalke did some work to simplify this kind of scheme with https://github.com/jordwalke/CommonML

This piece of code given in the blog post you linked is exactly the right way to do it:

```ocaml
let m = Js.Unsafe.obj [| |] in
Js.Unsafe.global##pwdGen <- m;

let js_generate tpl_string dict =
(* ... *)
in

m##generate <- Js.wrap_callback js_generate;
```

We would welcome a contribution adding an example and/or documentation that presents this. ;)

**Comment by hhugo** [comment]
http://ocsigen.org/js_of_ocaml/2.8/manual/export

**Comment by nathancarter** [comment]
Thank you!
