### ISSUE TITLE
Big_int.square_big_int returns 4294967296

### ISSUE THREAD

**Issue by jacquev6** [ocsigen/js_of_ocaml#389]
Hello,

`string_of_big_int (square_big_int unit_big_int)` returns "4294967296". I've verified that in Firefox (Ubuntu and MacOS) and Safari (MacOS). I've isolated a minimal reproducible example in [this gist](https://gist.github.com/jacquev6/7704bdff13faaf8dbb40).

Running `./make.sh` prints:

    unit (is 1): 1
    mult unit unit (is 1): 1
    square unit (should be 1 but is 4294967296): 1

but opening `bug.html` in a browser prints (in the console):

    unit (is 1): 1
    mult unit unit (is 1): 1
    square unit (should be 1 but is 4294967296): 4294967296

Thanks!

**Comment by jacquev6** [comment]
Just verified using node.js as well:

    $ nodejs bug.js 
    unit (is 1): 1
    mult unit unit (is 1): 1
    square unit (should be 1 but is 4294967296): 4294967296

**Comment by vouillon** [comment]
That should be fixed now.
Thanks for the bug report!
