### ISSUE TITLE
Problem with inlining

### ISSUE THREAD

**Issue by smondet** [ocsigen/js_of_ocaml#393]
I'm not sure yet where is exactly the issue, the same code works fine with the `--no-inline` and doesn't without (the presence of `--debug-info` and `--pretty` does not seem to influence).

When clicking on this link:
https://github.com/hammerlab/ketrew/blob/collapse-still-running-state/src/client-joo/target_table.ml#L981
which is calling this function:
https://github.com/hammerlab/ketrew/blob/collapse-still-running-state/src/client-joo/single_client.ml#L949
The call to the "set function" of the `Tab.t list React.Signal.t` 
(https://github.com/hammerlab/ketrew/blob/collapse-still-running-state/src/client-joo/single_client.ml#L966)
throws an exception instead of doing what was expected (the signal is defined with a custom `?eq` argument to avoid comparing on closures and such).

<img width="404" alt="screenshot 2015-12-28 19 21 11" src="https://cloud.githubusercontent.com/assets/617111/12027671/34d3d9aa-ad98-11e5-8ebd-8da47b735ca6.png">

And:

```
js_of_ocaml --version
2.6
```

**Comment by vouillon** [comment]
Given the stack trace, I suspect you are applying `React.S.map` to the `tabs` signal to get a new signal, but without a custom `?eq` argument. Then, the error occurs when comparing successive elements of this new signal.

This happens probably in function `Single_client.Html.render`.

I don't understand why the `--no-inline` flag would make a difference, though.

**Comment by smondet** [comment]
Indeed with `~eq:(fun _ _ -> false)` argument this issue gets fixed.

Maybe `--no-inline` creates one more indirection that makes a physical equality return `false` instead of `true` (many `==`s in [react.ml](https://github.com/dbuenzli/react/blob/master/src/react.ml))?
