### ISSUE TITLE
Stack_overflow exception

### ISSUE THREAD

**Issue by rlepigre** [ocsigen/js_of_ocaml#410]
We are having trouble with a Stack_overflow exception that we cannot trace... There is no
problem with the OCaml version and the stack size is reasonable. Other than polymorphic hash and equality function, are there other possible cause for such an error? Is there support for debuging of some kind in js_of_ocaml? For instance, is there a way to print a backtrace?

**Comment by hhugo** [comment]
Common culprit is that tail call is not optimized in general. You may face the same issue as https://github.com/ocsigen/js_of_ocaml/issues/357

You can use `Js.debugger ()` (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/debugger) to set a breakpoint.

You should be able to print to callstack with the following
```
Firebug.console##error (new%js Js.error_constr (Js.string ""))
```

**Comment by rlepigre** [comment]
OK, then that's a real problem. Our program relies on a parser combinator libraries with many self-recursive functions. Is there a deep technical reason for js_of_ocaml not to optimize tail calls? Would it be difficult to patch it?

**Comment by michipili** [comment]
I also have the same problem and the same questions.! :) It would be nice to hear about the possibly technical reasons why tail calls are not optimised?

(Also, I am a bit confused by the latter. I have zero knowledge about the zinc machine, but I would have expected the tail optimisation to occur before the generation of byte-code. Can anyone comment on this?)

**Comment by michipili** [comment]
If I understand correctly, the file `js_tailcall.ml` is missing the following implementation, right?

```
module While : TC = struct
  let rewrite _closures _get_prim = failwith "todo"
end
```

**Comment by hhugo** [comment]
http://ocsigen.org/js_of_ocaml/2.8/manual/tailcall
