### ISSUE TITLE
ppx generates badly typed code

### ISSUE THREAD

**Issue by zoggy** [ocsigen/js_of_ocaml#416]
Hello,

Current version of ppx processor generates code for method calls which does not compile.

Example:
````
$ cat > j.ml
let doc = Dom_html.window##document;;
^D
$ ocamlfind ocamlc -c -package js_of_ocaml.ppx j.ml
File "j.ml", line 1, characters 10-35:
Error: This expression has type
         Dom_html.document Js.t Js.readonly_prop =
           < get : Dom_html.document Js.t > Js.gen_prop
       but an expression was expected of type 'jsoo_32b5ee21 Js.meth
````
Examples could make use of the ppx extension to detect these problems as soon as possible.

**Comment by hhugo** [comment]
the ppx syntax for property access is `##.`
```let doc = Dom_html.window##.document```

**Comment by hhugo** [comment]
note that the syntax for method call has changed as well.
camlp4 `x##m(a,b,c)` translates to ppx `x##m a b c` or `x##(m a b c)`
