### ISSUE TITLE
XmlHTTPRequest and POST requests to send raw data

### ISSUE THREAD

**Issue by zoggy** [ocsigen/js_of_ocaml#417]
Hello,

The provided `perform_*` functions in XmlHttpRequest allow to send data with POST or PUT requests but only as (key, value) pairs.

Would you accept a patch to add an additional `RawData of string` constructor to type `Form.form_contents` and make the `perform_*` handle it ?

**Comment by zoggy** [comment]
This seems related to https://github.com/ocsigen/js_of_ocaml/pull/301

**Comment by dinosaure** [comment]
:+1:

**Comment by hhugo** [comment]
fixed in #301 I guess
