### ISSUE TITLE
Question: What is the minimum version of jsoo that provides ppx support?

### ISSUE THREAD

**Issue by rgrinberg** [ocsigen/js_of_ocaml#419]
Downstream packages that depends on jsoo and use its ppx extension would like to set the jsoo accordingly to reflect this.

**Comment by Drup** [comment]
Opam has the answer ;)
```
% opam show -f depends js_of_ocaml.2.5
cmdliner & base-unix & ocamlfind >= 1.5.1 & lwt >= 2.4.4 & menhir & camlp4 & ocamlbuild
% opam show -f depends js_of_ocaml.2.6   
cmdliner & base-unix & ocamlfind >= 1.5.1 & lwt >= 2.4.4 & menhir & cppo & camlp4 & base64 & (base-no-ppx | ppx_tools) & ocamlbuild
```

**Comment by rgrinberg** [comment]
I see. Thanks!

Also, why is jsoo still dependent on camlp4? Shouldn't it be a depopt?

**Comment by Drup** [comment]
The syntax extension is used internally and we don't want to break compat with previous ocaml version just yet. 

If you *really* don't want camlp4, you can use camlp4toppx on js_of_ocaml's itself, it should give you a ppx version.

**Comment by rgrinberg** [comment]
That answers everything. Thanks again.

**Comment by samoht** [comment]
> The syntax extension is used internally and we don't want to break compat with previous ocaml version just yet.

Any short-tem plan to switching to ppx internally and make `camlp4` a depopt?

**Comment by Drup** [comment]
Probably with 4.03. @hhugo, @vouillon what do you think ?
