### ISSUE TITLE
Question: about int64 encoding

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#421]
it seems js_of_ocaml using `24, 24, 16` to encode `64` ints, this seems a bit strange, it seems to save some computation(especially for mul), but do you actually do some benchmarking?

**Comment by hhugo** [comment]
@vouillon, do you know where this representation comes from ?

**Comment by vouillon** [comment]
We have not performed any benchmarking.

Indeed, it makes implementing multiplication much simpler. That was probably the main reason for this implementation.

On 32-bit architectures, V8 use a special representation to store 31-bit signed integers. Using two 32-bit integers in this case is probably more expansive.
