### ISSUE TITLE
Wrong syntax in doc

### ISSUE THREAD

**Issue by Tyruiop** [ocsigen/js_of_ocaml#426]
It seems there might be an issue in the doc of this page https://ocsigen.org/js_of_ocaml/api/Lwt_js_events on the "Defining a thread that waits for ESC key on an element" example which uses the camlp4 lwt syntax.

**Comment by hhugo** [comment]
Can you be more precise ? what is the issue ?

**Comment by vasilisp** [comment]
I think that the issue is mixing Camlp4 bindings (`lwt x = e in e'`) with PPX JS attributes (`e##.x`). It should be fixed by 8523fef.
