### ISSUE TITLE
raise Js.Error throwing array

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#427]
How to throw javascript error (created from `Js.jserror_constr`) to caller?

I have test function:

```
let test_raise () =
  raise @@ Js.Error (new%js Js.error_constr (Js.string "test"))
```

And it gets translated into something like:

```
function test_raise_f4_(param_a_)
     {var
       _b_=str_test_a8_,
       _c_=new jsoo_2c7d0868_aZ_(_b_),
       _d_=[0,Error_aw_,_c_];
      return function(_a_){throw _a_}(_d_)}
```

and so not the error itself gets thrown, but the array `[0, [248, MlString_D_, 5], Error:test]`. I've tried wrapping function with `Js.wrap_callback` and such, hoping they may do some sort of conversion, but they didn't.

Is this intended behaviour? How to properly throw jserror to caller?

**Comment by little-arhat** [comment]
This can be of course solved with smth like

```
let throw:(Js.error Js.t -> 'a) = Js.Unsafe.pure_js_expr "caml_raise_constant"
let test_raise () =
  throw @@ new%js Js.error_constr (Js.string "test")
```

but I wonder, whether this is preferable solution.

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/blob/master/lib/js.mli#L511
