### ISSUE TITLE
JavaScript literal object containing field `type`

### ISSUE THREAD

**Issue by lostman** [ocsigen/js_of_ocaml#428]
I was trying to create an object like this:
```
var input = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  type: 'scatter'
};
```
Using object syntax and `ppx_js`:
```
let input = object%js
    val x    = [|1; 2; 3; 4|]
    val y    = [|10; 15; 13; 17|]
    val type = "scatter"
end
```
But this doesn't work because `type` is a restricted keyword.

Would it be possible to specify a mapping between JS and OCaml using a `ppx` annotation?
```
object%js
    val type_ [@property "type"] = "scatter"
end
```

**Comment by hhugo** [comment]
this is already handled 
```
let input = object%js
    val x    = [|1; 2; 3; 4|]
    val y    = [|10; 15; 13; 17|]
    val type_ = "scatter"
end
```
see http://ocsigen.org/js_of_ocaml/2.7/manual/library -> "Method name and underscore"

**Comment by lostman** [comment]
I tried variations with underscores (string literals need to be converted, right?):
```
let input = object%js
    val type_ = Js.string "scatter"
    val x    = Array.of_list xs
    val y    = Array.of_list ys
    val mode = Js.string "lines+markers"
end
console##log input;
```
And the result object is:
```
Object {type_: "scatter", x: Array[23], y: Array[23], mode: "lines+markers"}
```
```
❯ js_of_ocaml --version
2.7
```

**Comment by Drup** [comment]
@hhugo It works for method calls, but I'm afraid I didn't implemented it for object creation. 
@lostman I'll try to fix it when I have time.

**Comment by lostman** [comment]
@Drup Thanks!

**Comment by hhugo** [comment]
solved by https://github.com/ocsigen/js_of_ocaml/pull/443
