### ISSUE TITLE
Can't find js_of_ocaml.tyxml

### ISSUE THREAD

**Issue by antoine1fr** [ocsigen/js_of_ocaml#434]
I understand a js_of_ocaml.tyxml library should be linked in order to use the Tyxml_js module. However, I can't find such a library with ocamlfind.

I have installed tyxml after js_of_ocaml just to be sure opam did correctly rebuild js_of_ocaml and it is the case.

There's no .cma files related to Tyxml in the installation folder:

```
$ ls `ocamlfind query js_of_ocaml`/*.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/compiler.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/logger.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/graphics.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/ocamlbuild_js_of_ocaml.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/js_of_ocaml.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/ppx_deriving_json.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/jsoo_findlib_support.cma
/home/antoine/.opam/4.02.3/lib/js_of_ocaml/ppx_js.cma
```

Is there some environment variable to set in order to build tyxml support when installing js_of_ocaml?

**Comment by vasilisp** [comment]
I think you need to install `reactiveData` as well.

**Comment by antoine1fr** [comment]
Aaah thank you! :)
