### ISSUE TITLE
bug in caml_int64_bits_of_float 

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#440]
`Int64.bits_of_float(5.6177910464447372E+306) = 9196350439090552832L` OK
`Int64.bits_of_float(1.1235582092889474E+307) = 9196350439090552832L ` WRONG

**Comment by vouillon** [comment]
```caml_frexp_float``` is probably wrong as well...

**Comment by hhugo** [comment]
using `Math.log2(x)` instead of `Math.LOG2E*Math.log(x)` solves the issue. https://github.com/ocsigen/js_of_ocaml/blob/master/runtime/ieee_754.js#L28

Apparently, there is no support for Math.log2 in IE https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log2

**Comment by hhugo** [comment]
It works for me in chrome, but not in nodejs

**Comment by hhugo** [comment]
What do you think about
```
//Provides: jsoo_floor_log2
var log2_ok = Math.log2 && Math.log2(1.1235582092889474E+307) == 1020
function jsoo_floor_log2(x) {
    if(log2_ok) return Math.floor(Math.log2(x)) 
    var i = 0;
    if (x == 0) return -Infinity;
    if(x>=1) {while (x>=2) {x/=2; i++} }
    else {while (x < 1) {x*=2; i--} };
    return i;
}
```

**Comment by hhugo** [comment]
fixed by https://github.com/ocsigen/js_of_ocaml/commit/3dbdb7a86bea6e87fc9e04e3b4966da4fb25983e

**Comment by bobzhang** [comment]
would you use typedarray instead if it is available
