### ISSUE TITLE
Provide Object.keys or other method for iteration

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#455]
There is currently no way to get all keys of arbitrary javascript object or iterate through them, but this functionality come handy from time to time. One can use `Js.Unsafe.meth_call`, but not all browsers have this functionality. It seems, that good it would be useful to have `keys` available in jsoo runtime (with appropriate  [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Polyfill)).

What do you think?

**Comment by little-arhat** [comment]
This would be helpful for https://github.com/little-arhat/ppx_jsobject_conv and for several internal project we're working on at this moment. It seems, that adding js polyfill in each of this projects is not very elegant solution. Another option would be to create tiny separate package with polyfill and wrapper, but as far I know, there is currently no way to add js file to `js_of_ocaml` automatically, if some `findlib` package was used.

**Comment by little-arhat** [comment]
Any updates on this? Or maybe there is a way to instruct `js_of_ocaml` to automatically add `+package/somefile.js` when input bytecode built with certain `package`? This would allow do create tiny package, providing functionality from #456.

**Comment by hhugo** [comment]
similar proposal https://github.com/ocsigen/js_of_ocaml/issues/270.

**Comment by Drup** [comment]
Note that eliom already relies on `keys` being available (through the usage of [Jstable](https://github.com/ocsigen/js_of_ocaml/pull/398)).
