### ISSUE TITLE
Export additional functions from the PPX

### ISSUE THREAD

**Issue by AngryLawyer** [ocsigen/js_of_ocaml#460]
I've a PPX that outputs `object%js` code; currently, I have to make sure that PPXes are run in a specific order to make it work.

This would be much easier if more parts of ppx_js were exported, so that this code could be transformed in my PPX without having to rely on users to put things in the right order.

**Comment by Drup** [comment]
I was going to do that, when I realized it's already there! [`Ppx_js`](http://ocsigen.org/js_of_ocaml/2.7/api/Ppx_js) is exposed in the ocamlfind library `js_of_ocaml.ppx.internal`.

**Comment by AngryLawyer** [comment]
Ah! Amazing! I didn't realise that Ast_mapper.mapper actually contained the stuff needed for doing the parsing. You are a star!
