### ISSUE TITLE
Seemingly serious bug, jsoo not generating top level side effect code?

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#462]
I'm doing more jsoo bindings and I'm getting what seems to be a serious bug.

Basically I have top level code in a module that is a package.

```ocaml
(* foo.ml *)
let () = print_endline "hello"
```

and then I link this package into another program which consists of

```ocaml
open Foo

let () = print_endline "world"
```

But when I run it on node then I don't get the top level effect of foo.ml, looking through the generated JS doesn't even yield hits on the `"hello"` string, so did jsoo optimize out the call all together?

the project is here: 
https://github.com/fxfactorial/tv_js

simply call make and then `node app.js` 

(I hope this is some mistake of mine)

**Comment by hhugo** [comment]
`_build/example/app.byte` has the same behavior.
`open Foo` does not force `Foo` to be linked.

**Comment by fxfactorial** [comment]
@hhugo its a top level side effect..., why is it not linked and how to disable this? 

(Another question, how do I not link in jsoo's code like its `XMLHTTPRequest` code and other stuff,  is that covered by --no-runtime?)

**Comment by Drup** [comment]
> how do I not link in jsoo's code like its XMLHTTPRequest code

It's not linked if you don't use it.

**Comment by fxfactorial** [comment]
Okay, it seems that this was a spurious issue then.
