### ISSUE TITLE
Question: best practices for reading json file resource and manipulation

### ISSUE THREAD

**Issue by nickbetteridge** [ocsigen/js_of_ocaml#465]
I'm trying to work out how to read a local json resource, manipulate it and then save it to local storage.

1. Is using something like ezjsonm the best way to go with js_of_ocaml for manipulating json or is there a better way to deal with json when using js_of_ocaml?

2. I feel stupid asking this but how do I load a json file resource using js_of_ocaml - or is this just a matter of doing a Pervasives.open_in <relative filename> with js_of_ocaml doing the fetch from the website?

Ah, I almost feel ready to write a little example for the js_of_ocaml website :)

**Comment by little-arhat** [comment]
Hi, for 1) you may want to try https://github.com/little-arhat/ppx_jsobject_conv which allows you to generate conversion functions to/from javascript objects. Then, you can use something like this: https://github.com/little-arhat/ppx_jsobject_conv/blob/master/src_test/test.ml#L8 to parse json string to javascript object.

**Comment by nickbetteridge** [comment]
Thanks for that - it looks fast , and the sooner all of the ppx stuff gets released, the  better :) - I'm really looking for something that holds the json data in a tree, can be manipulated, read and written.
On the otherhand, ppx_jsobject_conv looks ideal for rpc - can't wait to use it

**Comment by nickbetteridge** [comment]
2. XmlHttpRequest - examples has plenty of use cases - something about reading the documentation!
