### ISSUE TITLE
Why are window##.{inner,outer}{Width,Height} optdef?

### ISSUE THREAD

**Issue by sagotch** [ocsigen/js_of_ocaml#468]
```
method innerWidth : int Js.optdef Js.readonly_prop
method innerHeight : int Js.optdef Js.readonly_prop
method outerWidth : int Js.optdef Js.readonly_prop
method outerHeight : int Js.optdef Js.readonly_prop
```

According to https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight#Specification and
https://drafts.csswg.org/cssom-view/#dom-window-innerheight, these methods should return 0 if there is no viewport.

**Comment by vasilisp** [comment]
Probably because some old browsers ([like IE < 9](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth#Browser_compatibility)) do not provide them. The code is from 2012, but I guess it still a good idea to be cautious.

**Comment by sagotch** [comment]
Yeah okay, that was what I thought, bur support for old browsers make js_of_ocaml less easy to use because of all these opt/optdef.

If support for old browsers is a real concern, you can close this. issue.

**Comment by hhugo** [comment]
I would vote for dropping compatibility with ie < 9 when it's not convenient.
@balat, @vouillon, any thought ?

**Comment by copy** [comment]
+1 for dropping compatibility with ie < 9.

One addition: These properties should be float, see https://drafts.csswg.org/cssom-view/#changes-from-2011-08-04 (can happen in practice on zoomed pages and on mobile browsers).

**Comment by balat** [comment]
I would also vote for dropping compatibility with old IE ...
