### ISSUE TITLE
You found a bug: File "parse_bytecode.ml", line 546, characters 10-16: Assertion failed

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#469]
Trying to compile jsCoq with ocaml 4.03.0 and js_of_ocaml master:

```
js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "parse_bytecode.ml", line 546, characters 10-16: Assertion failed
```

This is a large build, let me know if you need more details.

**Comment by ejgallego** [comment]
https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/parse_bytecode.ml#L546

**Comment by ejgallego** [comment]
This looks indeed a problem with the 4.03.0 generated bytecode. #458

**Comment by hhugo** [comment]
Thanks for the report.
Seems to be similar to https://github.com/ocsigen/js_of_ocaml/issues/374

**Comment by ejgallego** [comment]
Indeed. Test file attached:
```
js_of_ocaml  --toplevel --nocmis +nat.js +weak.js +dynlink.js +toplevel.js ../lib-js/mutex.js ../lib-js/unix.js ../lib-js/coq_vm.js ../lib-js/byte_cache.js jscoq.byte
warning: free variables in primitive code "caml_json" (/home/egallego/.opam/4.03.0/lib/js_of_ocaml/polyfill/json2.js:522)
vars: TypeError
warning: overriding primitive "caml_reify_bytecode"
  old: /home/egallego/.opam/4.03.0/lib/js_of_ocaml/toplevel.js:44
  new: /home/egallego/research/jscoq/coq-js/../lib-js/byte_cache.js:14
warning: free variables in primitive code "caml_reify_bytecode" (/home/egallego/research/jscoq/coq-js/../lib-js/byte_cache.js:14)
vars: console
js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "parse_bytecode.ml", line 546, characters 10-16: Assertion failed
```

Byte file at https://x80.org/rhino-coq/jscoq.byte.bz2

**Comment by hhugo** [comment]
Can you provide a version of `jscoq.byte` with debug informations ?

**Comment by ejgallego** [comment]
Sure, will do tomorrow! Will

```
--pretty --noinline --disable shortvar --debug-info
```

suffice?

**Comment by hhugo** [comment]
no, I mean compiling with `ocamlc -g`

**Comment by ejgallego** [comment]
Oh indeed!! It seems I was :sleeping: New version at: 

https://x80.org/rhino-coq/jscoq-debug.byte.bz2

I've tried to compile all the deps in debug mode, let me know if some of them are not properly linked.

**Comment by hhugo** [comment]
Can you provide details on how to compile jscoq to reproduce the issue ?
opam switch, version of jscoq, ...

**Comment by ejgallego** [comment]
Sure! It is a pretty standard compilation process, as outlined in the [jsCoq README](https://github.com/ejgallego/jscoq#how-to-installbuild), please file bug reports if the instructions are bad.

The switch is the standard `4.03.0` plus the `4.03.0+32bits` found in the repository.

Then, we roughly do:
* Compile Coq with the 32bit switch.
* Compile jsCoq with 32bit switch.
* Call js_of_ocaml in the 64bit switch as the build needs more than 4GiB RAM

Thanks! E.

**Comment by hhugo** [comment]
Can you test with the branch https://github.com/ocsigen/js_of_ocaml/tree/test_jscoq

**Comment by ejgallego** [comment]
Thanks for your help @hhugo , it will take me a couple of days.

**Comment by ejgallego** [comment]
I was able to do a very quick build. Now it builds, but unfortunately loading in the browser crashes with:

```
jscoq.js:1462 Uncaught 0,248,Invalid_argument,-4,Array.blit
```

**Comment by ejgallego** [comment]
This branch should allow to build with 4.03.0 
https://github.com/ejgallego/jscoq/tree/4.03-tmp

**Comment by hhugo** [comment]
This is due to weak / ephemeron being broken with js_of_ocaml & ocaml 4.03.
I'll fix that

**Comment by hhugo** [comment]
I've updated the branch https://github.com/ocsigen/js_of_ocaml/tree/test_jscoq with a fix for weak.
It fixes `jscoq.js:1462 Uncaught 0,248,Invalid_argument,-4,Array.blit`

**Comment by ejgallego** [comment]
Cool, thanks @hhugo , I was able to boot jsCoq and it seems to work fine.

[Now I'm battling a different issue :D ]:
```
Anomaly: Uncaught exception (Invalid_argument
  "The dynlink.cma library cannot be used inside the OCaml toplevel").
Please report.
```

**Comment by ejgallego** [comment]
Oh sorry if my comment was not clear, I think this is a totally different issue due to commit:

ocaml/ocaml@8e6606d729a825af29d2080db2b5bb9fcdabf02f

So jscoq seems to work fine now, but the dynamic loading doesn't.

**Comment by ejgallego** [comment]
Yeah so jscoq is working fine if I add `Sys.interactive := false` to the start. I wonder whether it is being set to true thou... I don't call `JsooTop.initialize` anywhere I could see.

BTW, I got the message in stderr: `More than 2 => 3` , I cannot trace its origin.

**Comment by hhugo** [comment]
I've remove the debug message.  It has been pushed by mistake

**Comment by ejgallego** [comment]
After some more testing it seems stable enough with 4.03.0, thanks!
