### ISSUE TITLE
bad error message from the toplevel

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#471]
http://ocsigen.org/js_of_ocaml/2.7/files/toplevel/index.html

I tried this:

```
0xffff_fffffffn;;
exc during Lwt.async: Loc.Exc_located(_, _)
```

on this website https://try.ocamlpro.com/

```
# 0xffff_fffffffn
File "", line 1, characters 0-15:
Error: Integer literal exceeds the range of representable integers of type nativeint
```

btw, do you have a 64 bit repl

**Comment by hhugo** [comment]
thanks

**Comment by hhugo** [comment]
There is no 64bit repl, js_of_ocaml always uses native javascript integers
