### ISSUE TITLE
[FEATURE REQUEST] [syntax] ideas: having `#?` property ready

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#473]
so people can write code like

``` ocaml
x#?b#?c#?d
```

when property `b`, `c` are nullable which is quite common in js context

**Comment by Drup** [comment]
It would be `##?`, but yes, we could add something like that. What would be the exact typing ?

**Comment by little-arhat** [comment]
Since Js.OPT is a monad, one can use smth like this already:

```
let (>>=) = Js.Optdef.bind in
  obj##.someProperty
  >>= (fun pr -> pr##.otherProperty)
  >>= (fun op -> op##.final)
```

or nicer with [ppx_let](https://github.com/janestreet/ppx_let): 

```
let%bind pr = obj##.someProperty in
let%bind op = pr##.otherProperty in
  return op##.final
```

**Comment by bobzhang** [comment]
`#?` is much lighter weight than monadic syntax and nullable is quite common in js, my 2 cents

**Comment by Drup** [comment]
Just to make it clear, in `x##?foo`, `x` is the optional object ?

**Comment by bobzhang** [comment]
`x` is the object which has an optional property `foo`, so x is having type similar to 

```ocaml
<foo: _ Js.opt , ... > Js.t
```

**Comment by Drup** [comment]
And so, what does it returns when the property is not defined ?

**Comment by Drup** [comment]
(Or alternatively, just explain exactly which typing/semantics you want, instead of making me guess :p)

**Comment by bobzhang** [comment]
https://msdn.microsoft.com/en-us/library/dn986595.aspx

Ah my bad, so it should be like
```js
x??y 
--->
x === null_or_undefined ? undefined : x.y
```

**Comment by Drup** [comment]
Right, so the object is the one undefined. I'll consider it.

**Comment by hhugo** [comment]
It seems that the trend is to move to other binding strategy, `brr` and `gen_js_api`.
Maybe we should not add more syntax to our ppx.
