### ISSUE TITLE
jsoo as an API

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#479]
Can js_of_ocaml provide an API? Like compiler-libs.

Desired 

Given an OCaml string of OCaml code, compile to a JavaScript string and various variations of this.

**Comment by hhugo** [comment]
I'm confused, js_of_ocaml already export its compiler as a library `js_of_ocaml.compiler`.
Can you elaborate what you're trying to achieve. It seems that what you're describing is done in the toplevel (using `js_of_ocaml.compiler` and `compiler-libs`)

**Comment by fxfactorial** [comment]
Oh my bad, I didn't know about it. Any quick easy places to look for examples?
