### ISSUE TITLE
"Index out of bounds" error

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/js_of_ocaml#485]
Consider the following program, `foo.ml`:

```ocaml
let () = (ref None) := Some (CSS.Color.(string_of_t (rgb 0 0 0 ~a:0.)))
```

I am trying to compile `foo.ml` in the standard fashion:

```
ocamlfind ocamlc -linkpkg -package js_of_ocaml foo.ml -o foo.byte
js_of_ocaml foo.byte
```

`js_of_ocaml` fails with

```
js_of_ocaml: Error: Invalid_argument("index out of bounds")
```

**Comment by vasilisp** [comment]
2.7 works fine. I will try to bisect (unless you @hhugo have any immediate insights).

**Comment by hhugo** [comment]
I'll looking at it now.

**Comment by hhugo** [comment]
What version of OCaml are you running ?

**Comment by vasilisp** [comment]
4.02.3, haven't tested anything else.

**Comment by vasilisp** [comment]
I get the same error with 4.03.

**Comment by hhugo** [comment]
Fixed. Thanks for the report.
