### ISSUE TITLE
`Json.unsafe_input` and MlStrings

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#489]
Dear jsoo devs,

would you consider extending the api of the `Json` module so that `unsafe_input` maps JSON strings to `Js.string Js.t` instead of the current patching done?

Best, E.

**Comment by hhugo** [comment]
Are you aware of `Js._JSON.parse` ?

**Comment by ejgallego** [comment]
Thanks, let me have a look.

**Comment by hhugo** [comment]
I'm assuming this has been solved.
