### ISSUE TITLE
suggestion: use `#=` instead of `:=` for js property set

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#492]
I tried `:=` but found a priority issue:

``` ocaml
ignore @@ x##propperty := 3 
```

parsed as

``` ocaml
(ignore @@ x##property) :=  3
```

for backward compatibility you can support both but encourage `#=` instead

**Comment by hhugo** [comment]
@drup, @vouillon, @balat, @vasilisp, any opinion on this ?

**Comment by Drup** [comment]
I'm not very enthousiastic, I really like the fact that we are not taking more syntax namespace here, and `:=` is also quite intuitive.

**Comment by vasilisp** [comment]
I am not enthusiastic either. `#=` doesn't mean anything to me at first glance. Also, the priority issue is not specific to JSOO, and parsing it as `ignore @@ (x##property := 3)` is not much more intuitive.

**Comment by bobzhang** [comment]
Just my 2 cents: ppx is fundamentally buggy, overriding an existing syntax is error prone, and it gives users an illusion that it is of `ref` type, but it is not, also you have priority issues too. 
I am not familiar with how jsoo ppx works, suppose you have a read-only property returned and it happens to be `ref`, will it still work (should not ) in such case?

**Comment by Drup** [comment]
> I am not familiar with how jsoo ppx works, suppose you have a read-only property returned and it happens to be ref, will it still work (should not ) in such case?

`x ##. y := z` will not work, indeed. 

But honestly, have you *ever* come across that ? The main reason to put things in properties is to pass it to the js side, and javascript is not going to understand your reference anyway. I don't think people have been confused by the `:=` in the context of jsoo (the fact that there is an alien operator that starts with `#` might help).

**Comment by bobzhang** [comment]
It's up to you make a judgement, I don't like redefining the semantics of an existing syntax, and my experience is that ppx is error prone, I would try to make it as safe as I can. FYI, I chose `#=` for property assignment in BuckleScript
