### ISSUE TITLE
Iterating on arrays using for-in causes problem

### ISSUE THREAD

**Issue by chenglou** [ocsigen/js_of_ocaml#494]
Our company polyfilled Array's prototype to disallow accidental for-in loop on arrays and throws when that's the case. There's such usage of for-in in the jsoo generated output (`for(var c in caml_ml_out_channels)`, [here](https://github.com/ocsigen/js_of_ocaml/blob/000fc4712becd356a672b3bae0064e31595675d2/runtime/io.js#L101)). Is it possible to change that into a normal for loop?

cc @jordwalke

**Comment by jordwalke** [comment]
Thanks @hhugo !
