### ISSUE TITLE
Provide one JavaScript string from entire compilation process, given js_of_ocaml based input code 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#499]
Similar/Related to https://github.com/ocsigen/js_of_ocaml/issues/498, I want this functionality 

```ocaml

type 'compile_js program = <main: (unit -> 'compile_js) Js.readonly_prop> Js.t

let javascript_from_ocaml (prog : 'code program) = "123"

let () =
  let long_js_string = javascript_from_ocaml (object%js
      val main = fun () ->
        print_endline "!23"
    end)
  in
  print_endline long_js_string
```

You expect an object that just expects one field, then given that main method, js_of_ocaml blindly calls it and whatever javascript that would have been generated by that function call becomes the resultant string, aka everything included from that, so all the generated JS but as one long string. 

This would be an amazing functionality (I digged through the top level but would prefer something directly provided by jsoo).

**Comment by hhugo** [comment]
I'm not sure what you're asking for. What part of the ocaml source do you want to compile to JavaScript ? `print_endline "!23"` only ? what should be evaluated when ?
--> [MetaOcaml](http://okmij.org/ftp/ML/MetaOCaml.html)

**Comment by fxfactorial** [comment]
For example, in the image on the left, we wrote OCaml code, and the generated javascript was the image on the right.  In the api I desire, I write OCaml code that otherwise would have been intended to be compiled to byte code, then to JS via js_of_ocaml, but now I get it directly as a string. 
<img width="340" alt="screen shot 2016-07-27 at 12 26 49 am" src="https://cloud.githubusercontent.com/assets/3036816/17167241/f6903d7e-5390-11e6-90f0-51cb9cea1708.png">
<img width="570" alt="screen shot 2016-07-27 at 12 26 52 am" src="https://cloud.githubusercontent.com/assets/3036816/17167245/fa0b6a64-5390-11e6-8d90-e38b12ed03a3.png">

**Comment by hhugo** [comment]
What would you expect in this case ?
```
let some_string = "hello"
let some_fun : string -> unit = ....

let long_js_string = javascript_from_ocaml (object%js
      val main = fun () ->
        some_fun ( some_string ^ "!23") 
    end)
  in
```

**Comment by fxfactorial** [comment]
I should have been clear, it shouldn't be possible reference values outside of the syntax extension (Assume that such a ppx exists). Any input values to the environemtn need to be expilcily passed in with some optional parameter of sorts.

**Comment by hhugo** [comment]
In your example, `print_endline` would also need to be explicitly passed ...
Do you have a real (detailed enough) use case for this ?

**Comment by fxfactorial** [comment]
https://gist.github.com/fxfactorial/8f59fd3e45cc82231263a58bb4e71af1

**Comment by fxfactorial** [comment]
as a gist, https://gist.github.com/fxfactorial/8f59fd3e45cc82231263a58bb4e71af1

**Comment by fxfactorial** [comment]
@hhugo Nevermind. I've realized that js_of_ocaml is not the right community for my OCaml compiled to JavaScript needs.

**Comment by hhugo** [comment]
enjoy !
