### ISSUE TITLE
Using ppx along with a string at runtime to make an object 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#501]
Besides having to use Js.Unsafe, is there a way to have this work? 

```ocaml
let foo = fun key thing -> 
  (object%js val key = thing##.bar##.baz end)
in
```

I'd like to keep the convenience of ppx.

**Comment by Drup** [comment]
If I understand you correctly, you want to change the key dynamically ? You can't really typecheck that statically (at least not with js_of_ocaml's type encoding).

**Comment by fxfactorial** [comment]
Not change, but make a new object on the fly with the field `key` given by the string `key`, otherwise I have to do: `Js.Unsafe.obj [(Js.string key), Js.Unsafe.inject thing##.bar##.baz]`

**Comment by Drup** [comment]
Yes, that's what I meant. Could you try to give a type to your `foo` function ?

**Comment by fxfactorial** [comment]
```
val foo : string -> 'a Js.t -> 'a Js.t
```

**Comment by Drup** [comment]
As you guess yourself, that type is very unsafe, so it won't be provided by the ppx (the goal of the ppx is precisely to only produce well typed expressions).

**Comment by fxfactorial** [comment]
That is a little lame...I view the ppx as a convenience in addition to the type safe expressions produced.

**Comment by Drup** [comment]
To be honest, regardless of the type safety issues (which are already a deal breaker for me), I'm not even sure how you would implement that. 

It means the translation of `object%js key = <expr> end` depends wether `key` is in scope or not. That is an extremely dodgy semantics *and* it's pretty much impossible to implement that correctly with a ppx (walking the parsetree to do name resolution by hand is very brittle, and don't get me started on things like module opening). 

Maybe we can provide more `Js.Unsafe` convenience functions (although I'm not sure which, in this case), but that feature, as you presented it, will not be in the ppx.

**Comment by fxfactorial** [comment]
Okay, I see your case, you're right. Thanks!
