### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#508]
http://es6-features.org

related to
- #1031 
- #1017
- #989 
- #972

**Comment by dannywillems** [comment]
Something new about ES6 support?

**Comment by hhugo** [comment]
no. I don't have time to work on this now. What's your use case ?

**Comment by dannywillems** [comment]
No real use case for the moment but as lots of popular JavaScript frameworks switch to ES6 (like React and ReactNative), it would be great to have ES6 support.
I would like to begin a binding to ReactNative and use the ES6 interface is easier.

**Comment by hhugo** [comment]
One way would be to rely on some external javascript parser (https://github.com/facebook/flow ?)

**Comment by kevinji** [comment]
Just for comparison: BuckleScript also [compiles to ES5](https://bucklescript.github.io/docs/en/browser-support-polyfills), but supports [ES6 modules](https://bucklescript.github.io/docs/en/import-export).

**Comment by jmcarthur** [comment]
WeakSet and WeakMap seem exciting to me.

**Comment by hhugo** [comment]
How are WeakSet and WeakMap related to this issue ? My understanding is that one can already use them to write bindings.

**Comment by hhugo** [comment]
I'm fact, they are already used in the jsoo runtime.
See https://github.com/ocsigen/js_of_ocaml/blob/09d5731241917577e9c16b6a0063c23baae00df8/runtime/marshal.js#L435

**Comment by jmcarthur** [comment]
Ah, I had thought the reason js_of_ocaml didn't support Weak was just because JavaScript doesn't support any form of weak references, but maybe I'm just wrong. Maybe it's just that either (1) things were different in the past or (2) WeakMap/WeakSet are somehow not sufficiently powerful.

**Comment by hhugo** [comment]
Indeed, the ocaml weak reference semantic cannot be implemented using weak map / weak set

**Comment by jmcarthur** [comment]
Oh, I see, WeakMap and WeakSet are not what I expected them to be. Their _keys_ are weak!

I have now also learned about WeakRef, but it looks like browser support is still quite limited.

**Comment by kanishka-work** [comment]
Do you have a roadmap for supporting the browser based module loading, as noted in the first feature of this page: https://vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling ?

**Comment by jasongitmail** [comment]
It might be worth revisiting this in 2021.

Because the output uses Common JS, it can be difficult to integrate with existing projects that use modern, ES6 style JavaScript. ES6 would also allow the JS to work client-side or server-side by default, since browsers now have broad ES6 support.

**Comment by hhugo** [comment]
One could try to port new js feature implemented in https://github.com/returntocorp/pfff/blob/develop/lang_js/parsing/parser_js.mly

**Comment by hhugo** [comment]
> Oh, I see, WeakMap and WeakSet are not what I expected them to be. Their _keys_ are weak!
> 
> I have now also learned about WeakRef, but it looks like browser support is still quite limited.

WeakRef are now used to implement the ocaml weak semantic.

**Comment by hhugo** [comment]
#1386 allows to parse utf8 identifier.
