### ISSUE TITLE
caml_sys_get_argv crashes when used in nw.js

### ISSUE THREAD

**Issue by pirbo** [ocsigen/js_of_ocaml#510]
Node-webkit fills joo_global_object.process.argv with an array of length 1 containing all the command line. (There may be a bug there)
```function caml_sys_get_argv () {``` does
  ```
if(g.process
     && g.process.argv
     && g.process.argv.length > 0) {
    var argv = g.process.argv
    //nodejs
    main = argv[1];
    args = raw_array_sub(argv,2,argv.length - 2);
  }
```
Of course ```raw_array_sub(argv,2,-1)``` fails loudly!
I don't mind not having the argv when using nw.js (I use it so that my users can open their app by a double click so I never expect any command line argument) but I'll recommend to do at least ``` && g.process.argv.length > 1) {```

**Comment by hhugo** [comment]
Thanks for the report.
During my experiment, I always saw at least two args `node` and `myjsfile.js`. The code was trying to filter out the javascript interpreter.  
I will apply the suggested fix but I wonder if there is better way to achieve this.
