### ISSUE TITLE
Compatibility with 4.04.0 ?

### ISSUE THREAD

**Issue by damiendoligez** [ocsigen/js_of_ocaml#520]
Is js_of_ocaml 2.8.1 compatible with OCaml 4.04.0+beta2 ?

js_of_ocaml builds OK on OCaml 4.04 but then I try to compile the `c3` package (version 0.3.0) and I get this error:

```
js_of_ocaml: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "util.cppo.ml", line 419, characters 42-47: Pattern matching failed
```

**Comment by hhugo** [comment]
2.8.1 is not compatible. Master should be - see https://github.com/ocsigen/js_of_ocaml/commit/c7231696b4c167dd1df66914609c8a1b1ee01344

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/7390

**Comment by hhugo** [comment]
2.8.2 about to be released https://github.com/ocaml/opam-repository/pull/7405
