### ISSUE TITLE
Merging of runtime-wip branch

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#522]
Hello!

Are there any plans to merge it? I currently use my own fork with this banch merged (https://github.com/little-arhat/js_of_ocaml/tree/2.8.2-with-runtime-wip) to use `Js.arguments` and other var-args related methods. It would be nice to have `js_of_ocaml` version in opam.

**Comment by hhugo** [comment]
This branch has not been tested. Is everything working fine for you ? It will be merged at some point, I just need to get back at it.

**Comment by little-arhat** [comment]
Yes, everything works fine and worked for 2.8.1 with this bracnh merged, too.

**Comment by hhugo** [comment]
done
