### ISSUE TITLE
`make -C tests` fails

### ISSUE THREAD

**Issue by bmillwood** [ocsigen/js_of_ocaml#523]
It could be this is actually just me running them incorrectly, in which case I'll change the issue title to "unclear how to run tests correctly" :)

Firstly, they fail early if you don't have deriving installed (even though you can compile the library without it). I installed that, and then:

```
$ make
[... a bunch of stuff ...]
$ make -C tests
make:_ Entering directory '/home/ben/code/ocaml/js_of_ocaml/tests'
TERM=dumb ocaml -noprompt -I ../lib -I ../lib/deriving_json -init ppx_init.ml -ppx ../lib/ppx/ppx_js -ppx "/home/ben/.opam/4.03.0/lib/ppx_deriving/ppx_deriving ../lib/ppx/ppx_deriving_json.cma" < ppx/write_prop.ml 2>&1 | tail -n +15 > ppx/write_prop.result
diff ppx/write_prop.result ppx/write_prop.expected
1,2d0
< /home/ben/.opam/4.03.0/lib/ppx_deriving/ppx_deriving_runtime.cma: loaded
< /home/ben/.opam/4.03.0/lib/ppx_deriving/./ppx_deriving: activated
make: *** [Makefile:49: ppx/test_write_prop] Error 1
rm ppx/write_prop.result
make: Leaving directory '/home/ben/code/ocaml/js_of_ocaml/tests'
```

That's not so interesting (seems like that `tail -n +15` just needs to be `tail -n +17`) so I also attach [a gist of what happens when you tell make not to stop on the first failure](https://gist.github.com/bmillwood/c479033c2fe50fad6720b59c6420e89f)

(also is it just me or should the diffs have `-u` passed to them, for unified context? I can never read non-unified diffs)

My OCaml version is:

```
$ ocaml -version
The OCaml toplevel, version 4.03.0
```

Let me know if there's anything else I can provide that would help.

**Comment by hhugo** [comment]
one need to call `jbuilder runtest`
