### ISSUE TITLE
Possible wrong code generated with Js.Optdef.map and localStorage

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#526]
Hi,

I think I've encountered bug with code like this:

``` ocaml

let () =
  let storage = Dom_html.window##.localStorage in
  let opt = Js.Optdef.map storage (fun s ->
                            Firebug.console##log (Js.string "storage present, writing");
                            s##setItem (Js.string "none") (Js.string "none")) in
  let is_some = Js.Optdef.test opt in
  Firebug.console##log_4 (Js.string "test:") (Js.bool is_some) (Js.string "opt:") opt
```

Build:

```
ocamlfind ocamlc -linkpkg -package js_of_ocaml -package js_of_ocaml.ppx toto.ml -o a.byte
js_of_ocaml a.byte -o a.js
```

When running generated code with `node` I get `test: false opt: undefined` which is correct, since localStorage is not present in node. At the same time, I get `test: false opt undefined` in Chrome, together with `console.log` from function: `storage present, writing`. Value is also written to localStorage and can be queried back.

If I return `Js._true` or anything other than `unit` from inside function everything works as expected: `Js.Optdef.test` returns `true` on value and `false` on `undefined`.

**Comment by hhugo** [comment]
The issue comes from returning `s##setItem ...`.
The generated javascript looks like` return s.setItem(a,b)` where `s.setItem` returns `undefined`.

**Comment by hhugo** [comment]
Note that the following should work (returning unit explicitly)
```ocaml

let () =
  let storage = Dom_html.window##.localStorage in
  let opt = Js.Optdef.map storage (fun s ->
                            Firebug.console##log (Js.string "storage present, writing");
                            s##setItem (Js.string "none") (Js.string "none");
                            ()) in
  let is_some = Js.Optdef.test opt in
  Firebug.console##log_4 (Js.string "test:") (Js.bool is_some) (Js.string "opt:") opt
```

**Comment by little-arhat** [comment]
Yes, I understand this, but right now `Js.Optdef` is doing automatic `flattening`. In OCaml you can have `Some None`, while with `Js.Optdef.map` this will become `undefined` in some cases. Shouldn't we check return value of `f` in `map` and do smth to prevent flattening?
