### ISSUE TITLE
Difference in multiplication between native/byte and jsoo

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#530]
I've noticed that integer multiplication uses `Math.imul` which implements 32 bit integer multiplication.
However, this causes very different behavior than when executing integer multiplication on a 64 bit machine in `ocamlopt`/`ocamlc`. I discovered the issue when running [ReLayout](https://github.com/jordwalke/ReLayout) in a JS environment (layout computations were different for the jsoo target), and I tracked it down to a multiplication that only overflowed when compiled to JS (due to using `Math.imult`). 

Should `jsoo` strive to create the same behavior as `ocamlopt`/`ocamlc`? Perhaps it's difficult to detect the architecture in JS engines, but could `jsoo` accept a parameter such as `--simulate32` or `--simulate64`?

**Comment by jordwalke** [comment]
My main concern would be that in some places, computations behave more similar to 32 bit `ocamlc`, but behave more like 64 bit `ocamlc` in other places.

**Comment by hhugo** [comment]
JavaScript integers are 32 bits (rather than 31 bits or 63 bits in the native ocaml runtime).
I'm not aware of any javascript engine with native 64bit integers.
Do you have an example in mind where things behave more like 64bit ?

**Comment by jordwalke** [comment]
This example:
```
Math.imul(-100000000, -50000)
> 658067456
-100000000 * -50000
> 5000000000000
```

**Comment by hhugo** [comment]
`-100000000 * -50000` is a multiplication on floats.

**Comment by jordwalke** [comment]
I see. I read up on JavaScriptCore's NaNBoxing and now it makes more sense.

**Comment by jordwalke** [comment]
@hhugo I'm curious if you've thought of a way to get a larger integer range for the compiled output. I know that asm.js only has 32bit integer casts with `| 0`, but if you were to give that up, what's the easiest way you can think of to increase the range to 53 bits. (I know we'll never get `63` bits in JS).

**Comment by hhugo** [comment]
- implement functions for 53bit int arithmetic (handling overflow might not be trivial)
- update arithmetic expressions in the runtime
- update code gen to use the new functions

**Comment by hhugo** [comment]
Or just don't use `int` when you need more than 31bits. Note that `base` has a `Int63` module.

**Comment by jordwalke** [comment]
> Or just don't use `int` when you need more than 31bits. Note that `base` has a `Int63` module.

Not everyone uses base, and so I'm asking more about a solution that will help the compiler help arbitrary programs

> implement functions for 53bit int arithmetic (handling overflow might not be trivial)

Overflow in native ocaml just rolls over - is behavior even defined in that case? I imagine rolling into JavaScript's floating point range would be just as acceptable as perfectly recreating ocaml's integer overflow behavior, right?

**Comment by hhugo** [comment]
From https://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html

> Integers are Sys.int_size bits wide. All operations are taken modulo 2Sys.int_size. They do not fail on overflow.

Here are some examples in the compiler distribution
- https://github.com/ocaml/ocaml/blob/trunk/stdlib/stdlib.ml#L111
- https://github.com/ocaml/ocaml/blob/trunk/stdlib/string.ml#L53
