### ISSUE TITLE
Properties with multiple underscores

### ISSUE THREAD

**Issue by Aaylor** [ocsigen/js_of_ocaml#538]
When trying to access constant that have multiple underscores, it seems that the part of the constant name after the last underscore disappears in the generated javascript file.

I took a look on the byte file, and those constants appears with their full qualified name. I guess that the problem is during the compilation from the bytecode to the javascript.

With this small example:
```ocaml
let jsmodule = Js.Unsafe.global

let cst1 = jsmodule##._CONSTANT
let cst2 = jsmodule##._UNDERSCORE_CONSTANT
let cst3 = jsmodule##._CONSTANT_MULTIPLE_UNDERSCORE
let cst4 = jsmodule##.TRY_THIS_WAY
```

I compile the OCaml file and compile to javascript using the following command line :
```
$ ocamlfind ocamlc -g -o test.byte -package js_of_ocaml -package js_of_ocaml.ppx -linkpkg test.ml
$ js_of_ocaml --debug-info --pretty --disable=deadcode,genprim test.byte
```

At the creation part of constants in the javascript, it gives me (I let only the interesting part, the whole file will be included in the provided zip):

```js
var cst1 = function(t0,param){return t0.CONSTANT}(jsoo_obj,_e1_);
var cst2 = function(t1,param){return t1.UNDERSCORE}(jsoo_obj,_e2_);
var cst3 = function(t2,param){return t2.CONSTANT_MULTIPLE}(jsoo_obj,_e3_);
var cst4 = function(t3,param){return t3.TRY_THIS}(jsoo_obj,_e4_);
```

I also found that the string value of my constants are truncated from the last undescore.

```js
caml_new_string("TRY_THIS");
caml_new_string("CONSTANT_MULTIPLE");
caml_new_string("UNDERSCORE");
caml_new_string("CONSTANT");
```

I did not find anything about this in the documentation...

Version: *js_of_ocaml 2.8.2*

The complete version of the test file: [test.zip](https://github.com/ocsigen/js_of_ocaml/files/576921/test.zip)

**Comment by hhugo** [comment]
See Method name and underscore in http://ocsigen.org/js_of_ocaml/2.8.3/manual/library

**Comment by Aaylor** [comment]
Oh... Thanks.

As you differentiate properties and methods in other part of the documentation, I thought this part was only applying for methods, not for properties...

Sorry for the inconvenience!
