### ISSUE TITLE
Should window##open_ return opt?

### ISSUE THREAD

**Issue by little-arhat** [ocsigen/js_of_ocaml#542]
Hi, currently `window##open_` assumes that browser can always open popup window. However, if popup was blocked, `window##open_` may return `null`. Should we change signature to reflect that?

From https://developer.mozilla.org/en-US/docs/Web/API/Window/open : 

```
How can I tell when my window was blocked by a popup blocker?
With the built-in popup blockers of Mozilla/Firefox and Internet Explorer 6 SP2, you have to check the return value of window.open(): it will be null if the window wasn't allowed to open. However, for most other popup blockers, there is no reliable way.
```

**Comment by hhugo** [comment]
Yes, I think the signature should be updated. PR welcome.
