### ISSUE TITLE
Use .exe extension when using native Windows ports

### ISSUE THREAD

**Issue by alainfrisch** [ocsigen/js_of_ocaml#544]
When targetting native Windows ports, the build system should produce .exe executables.

Setting `EXEEXT := .exe` in Makefile.conf does not work, because e.g. COMPILER is assigned before.  Passing on command-line (make ... EXEEXT=.exe) works, though.

Arguable, the Makefile could define the correct value automatically, either by parsing the output of `ocaml -config` or by including OCaml's installed Makefile.config.

**Comment by hhugo** [comment]
what are the possible results of `ocamlc -config` on windows ?

**Comment by bobzhang** [comment]
to make life easier, we just always use `.exe`

**Comment by alainfrisch** [comment]
> ocamlc -config 

The `system` line can take these values:

````
~/ocaml/trunk/config $ grep SYSTEM Makefile.*
Makefile.mingw:SYSTEM=mingw
Makefile.mingw64:SYSTEM=mingw64
Makefile.msvc:SYSTEM=win32
Makefile.msvc64:SYSTEM=win64
````
