### ISSUE TITLE
ocamlbuild plugin,  `package` tags are incorrectly parsed

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#547]
On [this line](https://github.com/ocsigen/js_of_ocaml/blob/1262e7d312834485b33b62cb12d7bd25faf4e377/ocamlbuild/ocamlbuild_js_of_ocaml.ml#L45). The contents of `package()` tags should be further parsed as a sequence of ids delimited by space or commas. I.e. they can be: 
```
package(PKG)
package(PKG1 PKG2...)
package(PKG1, PKG2, ...)
```
This results in incorrect further invocations for example:
```
ocamlfind: Package `otfm uutf js_of_ocaml' not found
Failure:
  Error while running: ocamlfind query "-format" "pkg_%p" "-r" "js_of_ocaml" "uchar" "result" "otfm uutf js_of_ocaml" "gg" "bytes".
```
This obscure syntax has been blessed by @gasche [here](https://github.com/dbuenzli/topkg/issues/69#issuecomment-248146831) (TBH they make the broken syntax rules of `_tags` files more bearable).

**Comment by gasche** [comment]
Note that ocamlbuild does not attempt to pass the package argument, it just passes it to `ocamlfind` unchanged -- thus importing the ocamlfind semantics. The reason why the code you show doesn't work is that it passes the `package(...)` arguments to `ocamlfind query`, which expects a `package_name` and not a `package_name_list`. It would be fairly reasonable, I think, to ask Gerd to have ocamlfind consistently support package lists (one could argue that the current state is inconsistent), and the code would magically work again without any logic in js_of_ocaml.

**Comment by gasche** [comment]
P.S.: If you have a proposal for a nicer syntax for `_tags` file, feel free to open an issue on the ocamlbuild directory. (We would need a way to support both syntaxes, though.)

**Comment by dbuenzli** [comment]
> P.S.: If you have a proposal for a nicer syntax for _tags file, feel free to open an issue on the ocamlbuild directory. (We would need a way to support both syntaxes, though.)

I think it's preferable to keep it as it is. In fact it's rather the line-based parsing rules (and some of the error reports IIRC) that are annoying. I don't know how ambiguous it is, but not having to use backlashes for multi-line definitions would be nice.

**Comment by dbuenzli** [comment]
That said I still think a fix would be better in the plugin here, it's clearly a violation of the `ocamlfind query` synopsis and changing the latter so that each positional argument is potentially a list of packages seems a bit strange.

**Comment by gasche** [comment]
I don't disagree, except on the "a bit strange": `ocamlfind query` already supports multi-package queries (the results are just unioned) so it would be a natural (trivial) extension.
