### ISSUE TITLE
`:=` vs `<-` for JS property set

### ISSUE THREAD

**Issue by avnik** [ocsigen/js_of_ocaml#548]
I can be wrong, but looks like ppx and camlp4 syntax extension have little difference here:  ppx provide `:=`, but camlp4 syntax -- `<-`

**Comment by hhugo** [comment]
Correct. There are actually many differences:

property access: `o##prop` (camlp4) vs `o##.prop` (ppx)
property setter : `o##prop <- expr` (camlp4) vs `o##.prop := expr` (ppx)
method calls: `o##meth(a1,a2, a3)` (camlp4) vs `o##meth a1 a2 a3` (ppx)
`jsnew` vs `new%js`
`jsobject` vs `object%js`

The js_of_ocaml codebase was recently translated from camlp4 to ppx.

What is your question/issue ?

**Comment by avnik** [comment]
I thought, that both camlp4 and ppx implement same syntax sugar.
So possible I tried to merge two examples, which originally used different sugars, and it distract me.
