### ISSUE TITLE
` Tyxml_js.R.Html5.node` is missing

### ISSUE THREAD

**Issue by samoht** [ocsigen/js_of_ocaml#555]
Hey, I am trying to use tyxml_js and react, which is working great. The only thing that I need (and haven't found how to do it properly) is to embed reactive nodes into normal (arbitrary) nodes.

 @Drup told me that there is a function `R.node` in eliom, so that seems possible. 

e.g. I would like the `button` function in [there](https://github.com/samoht/bew/blob/518c1ea2a995ea73ca5264eb1079f065193ddcc2/react/react_client.ml#L176) to not be aware of react at all, and do something like:

```ocaml
  R.node (S.map (fun loading -> Button.v (onclick t `Fetch) ~basic:true ~loading [fetch]) loading)
```

or something similar.

**Comment by samoht** [comment]
Note, I can achieve something a bit similar to what I would like to by writing:

```ocaml
R.div (RList.from_signal (S1.l1 (fun loading -> [...])))
```

Which is not very light and add an intermediate `div` element that would be great to avoid.

**Comment by vouillon** [comment]
It is not possible to implement that with `Tyxml_js`, as HTML elements are directly Dom elements. 

Eliom adds a layer of indirection: it first builds an OCaml datastructure. This makes it possible to implement a function `R.node`.
