### ISSUE TITLE
jsoo fails to compile using the bucklescript-patched ocaml compiler

### ISSUE THREAD

**Issue by dysinger** [ocsigen/js_of_ocaml#557]
This may be an issue with the way BS patched the complier, I'm sure. I just wanted to file a bug so that it is tracked.

Steps to repro:

```
opam switch -A 4.02.3+buckle-master 4.02.3-bs-jsoo
opam install js_of_ocaml

....

[ERROR] The compilation of js_of_ocaml failed at "make build".                                                                                                                    [23/139]
Processing 19/19: [js_of_ocaml: ocamlfind remove]
#=== ERROR while installing js_of_ocaml.2.8.4 =================================#
# opam-version 1.2.2
# os           linux
# command      make build
# path         /home/user/.opam/4.02.3-bs-jsoo/build/js_of_ocaml.2.8.4
# compiler     4.02.3+buckle-master
# exit-code    2
# env-file     /home/user/.opam/4.02.3-bs-jsoo/build/js_of_ocaml.2.8.4/js_of_ocaml-10131-4db571.env
# stdout-file  /home/user/.opam/4.02.3-bs-jsoo/build/js_of_ocaml.2.8.4/js_of_ocaml-10131-4db571.out
# stderr-file  /home/user/.opam/4.02.3-bs-jsoo/build/js_of_ocaml.2.8.4/js_of_ocaml-10131-4db571.err
### stdout ###
# [...]
# echo "let git_version = \"\"" >> compiler_version.ml.tmp
# if cmp -s compiler_version.ml.tmp compiler_version.ml; then rm compiler_version.ml.tmp; else mv compiler_version.ml.tmp compiler_version.ml; fi
# ocamlfind ocamlc -g  -w +A-4-7-9-37-38-41-44-45-58 -I +compiler-libs -safe-string -package cmdliner -package base64 -package yojson -package findlib -c compiler_version.mli
# ocamlfind ocamlopt -g -w +A-4-7-9-37-38-41-44-45-58 -I +compiler-libs -safe-string -package cmdliner -package base64 -package yojson -package findlib -for-pack Compiler -g -c compiler_
version.ml
# cppo util.cppo.ml -o util.ml -V OCAML:`ocamlc -version`
# ocamlfind ocamlc -g  -w +A-4-7-9-37-38-41-44-45-58 -I +compiler-libs -safe-string -package cmdliner -package base64 -package yojson -package findlib -c util.mli
# ocamlfind ocamlopt -g -w +A-4-7-9-37-38-41-44-45-58 -I +compiler-libs -safe-string -package cmdliner -package base64 -package yojson -package findlib -for-pack Compiler -g -c util.ml
# Makefile:121: recipe for target 'util.cmx' failed
# make[1]: Leaving directory '/home/user/.opam/4.02.3-bs-jsoo/build/js_of_ocaml.2.8.4/compiler'
# Makefile:13: recipe for target 'compiler' failed
### stderr ###
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml, /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml, /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml, /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml, /home/user/.opam/4.02.3-bs-jsoo/lib/ocaml/compiler-libs
# File "util.cppo.ml", line 477, characters 4-19:
# Error: The constructor Const_pointer expects 2 argument(s),
#        but is applied here to 1 argument(s)
# make[1]: *** [util.cmx] Error 2
# make: *** [compiler] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install js_of_ocaml 2.8.4
```

**Comment by dysinger** [comment]
I wanted to use jsoo & bs side by side. It would be fun to be able to do that for comparison/experiments. An example: https://github.com/reasonml/rebel/blob/master/examples/multiple-entrypoint/package.json

**Comment by dysinger** [comment]
Git master at current 654c2572daa04bea8629092d49bb5f6222264b54 also fails

**Comment by Drup** [comment]
cc @bobzhang

**Comment by bobzhang** [comment]
It is due to that recent jsoo also depends on some lambda representation, are you interested in accepting patches?

**Comment by hhugo** [comment]
Js_of_ocaml started to depend on some lambda representation with the 2.8.* branch (june 2016).
There is already some conditional compilation around that part of the code. contribution welcome.

**Comment by dysinger** [comment]
It would be really slick if JSOO worked along side Bucklescript & Reason on BS' patched compiler

**Comment by bobzhang** [comment]
I will prepare patches later

**Comment by dysinger** [comment]
Is the patch difficult? I thought I only saw one error in arity for a function call.

**Comment by bobzhang** [comment]
Not really, I don't have time to look at it yet, hope I can get it out next week

**Comment by TheSpyder** [comment]
Installing bucklescript from NPM side steps this issue; it will use the patched 4.02.3 compiler if the switch is active, or just build one in-place if not.

Once bucklescript is compiled through the NPM module it doesn't depend on opam at all, so as long as newer stdlib functions are avoided the same project can be compiled with both bucklescript and js_of_ocaml just fine. I've separated my code so the bulk is in a pure ocaml core, with a folder for JSOO interop and another for BS interop.

**Comment by anmonteiro** [comment]
Ran into this too.

My workaround was to `opam switch 4.03.0` and `opam install js_of_ocaml` and then copy the `~/.opam/4.03.0/bin/js_of_ocaml` to some place in my `$PATH` before switching to BuckleScript's patched Ocaml.

**Comment by hhugo** [comment]
I've included a patch. see https://github.com/ocsigen/js_of_ocaml/commit/796279c1dc212e046f8666254c8dedadd2b06239
There is not automatic discovery for bucklescript. One would need to manually uncomment https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/jbuild#L47

**Comment by hhugo** [comment]
Closing. Please reopen if still needed.
