### ISSUE TITLE
Add Dom_html.Keyboard_code.of_key_code

### ISSUE THREAD

**Issue by martindemello** [ocsigen/js_of_ocaml#558]
I'm writing some code using ocaml-vdom, which simply returns keydown events as a raw keycode. It would be very useful to convert to Keyboard_code.t from Dom_html, but right now that only exposes Keyboard_code.of_event.

Could we also add a Keyboard_code.of_key_code function? I'd be happy to send in a pull request.

**Comment by vouillon** [comment]
Sure, pull requests are welcome!

**Comment by martindemello** [comment]
sorry, i neglected to follow up on the promise of a PR! i have this in my code, because `try_key_code_normal` doesn't cover everything:

````
  let run_next value f = function
    | Unidentified -> f value
    | v -> v

  let of_key_code code =
    Unidentified
    |> run_next code try_key_code_left
    |> run_next code try_key_code_right
    |> run_next code try_key_code_normal
````
