### ISSUE TITLE
Browser Toplevel does not accept uppercase K

### ISSUE THREAD

**Issue by Quarkbeast** [ocsigen/js_of_ocaml#562]
If one tries to write an uppercase K in the ocaml toplevel interpreter (http://ocsigen.org/js_of_ocaml/2.8.3/files/toplevel/index.html) using the shift key no uppercase K is printed. Instead the toplevel is reset as if one had pressed Ctr-K. If one uses Caps-lock instead the problem does not occure.

**Comment by hhugo** [comment]
Thanks for the report
