### ISSUE TITLE
Depends on ppx_driver 113.33.04 which is only available for OCaml 4.02

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#566]
For more recent versions of OCaml, only ppx_driver 113.33.02 is available.

**Comment by hhugo** [comment]
Is this optional deps  breaking anything ?
I eventually plan to get rid of the driver inside js_of_ocaml.
JaneStreet would then be responsible for releasing a version of the ppx_js_driver compatible with ppx_driver.

**Comment by vouillon** [comment]
Yes, it's a problem. You cannot install both ppx_driver and js_of_ocaml simultaneously since the optional dependency must be satisfied in this case:
```
The following dependencies couldn't be met:
  - js_of_ocaml -> ppx_driver
Your request can't be satisfied:
  - js_of_ocaml.dev is in conflict with ppx_driver.113.09.00
  - js_of_ocaml.dev is in conflict with ppx_driver.113.24.00
  - js_of_ocaml.dev is in conflict with ppx_driver.113.33.00+4.03
  - js_of_ocaml.dev is in conflict with ppx_driver.113.33.01+4.03
  - js_of_ocaml.dev is in conflict with ppx_driver.113.33.02+4.03
```

**Comment by vouillon** [comment]
js_of_ocaml seems to compile with ppx_driver.113.33.02. So maybe the dependency can be relaxed a bit?

**Comment by hhugo** [comment]
Are you aware of anyone using `ppx_js_driver` ?
https://github.com/ocaml/opam-repository/pull/8685 (https://github.com/ocaml/opam-repository/pull/8685/files#diff-0956e1a2459de4d6f09403daaf09571dL5) should fix the issue by removing `js_of_ocaml.ppx_driver`  and `js_of_ocaml.async_js` from js_of_ocaml

**Comment by hhugo** [comment]
fixed by https://github.com/ocaml/opam-repository/pull/8734
