### ISSUE TITLE
Error: Unresolved internal primitive: %caml_js_opt_meth_call

### ISSUE THREAD

**Issue by Armael** [ocsigen/js_of_ocaml#573]
How to reproduce:

```
opam install gen_js_api
git clone https://github.com/Armael/gen_js_api_helloworld
cd gen_js_api_helloworld
make
```

The jsoo invocation fails with:
```
js_of_ocaml --pretty -o test.js +gen_js_api/ojs_runtime.js test.byte
js_of_ocaml: Error: Unresolved internal primitive: %caml_js_opt_meth_call
make: *** [Makefile:7: all] Error 1
```

**Comment by hhugo** [comment]
Thanks for the report, will look at this later this week

**Comment by hhugo** [comment]
What versions ? Ocaml ? Js_of_ocaml ?

**Comment by Armael** [comment]
OCaml 4.04.0, js_of_ocaml 2.8.4. I couldn't figure how to pin the git version of jsoo.

**Comment by hhugo** [comment]
partially solved by https://github.com/ocsigen/js_of_ocaml/commit/936feb8c1df845e1d47ab7142e8330b0ca35a326.
I've updated the compiler to be more robust. However the code generated by gen_js_api is not doing what you expect, see bellow. 
```
let (foo : int -> unit) =
  fun x1  -> ignore (Ojs.call (Ojs.int_to_js x1) "foo" [||]) 
```
I would suggest to reopen your issue on gen_js_api.

**Comment by hhugo** [comment]
I think you want 
```
val foo : int -> unit
[@@js.global]
```

**Comment by Armael** [comment]
Oh, thanks for the patch & the debugging. I'll reopen the issue on gen_js_api.
