### ISSUE TITLE
Overriding non-primitive functions

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#587]
Hi,

Assume my code uses the Str module in just one place:

```
let f s =
  Str.split (Str.regexp "[ \t]+") s
```

This causes `js_of_ocaml` to complain:

```
There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives:
  re_search_forward
  re_string_match
```

It's easy to implement that function in Javascript. It's much harder to replicate `re_search_forward` and `re_string_match`, though.

Can I override the function `f` with a custom Javascript implementation? I couldn't find anything in the manual.

**Comment by vasilisp** [comment]
Is the code supposed to compile against `js_of_ocaml` only? If yes, you can use a JavaScript `f` either directly via `Js.Unsafe`, or by defining it as a primitive and declaring it as `external`. See

https://ocsigen.org/js_of_ocaml/2.8.4/manual/library ("Calling Javascript functions")
https://ocsigen.org/js_of_ocaml/2.8.4/manual/linker (" Provide your own JavaScript")

If you want the code to also run on the traditional backends, one option is to use conditional compilation (_e.g._, `cppo`) or conditional linking of different modules implementing `f`.

**Comment by vasilisp** [comment]
Also, the `Regexp` module should already offer what you want, so there is no strong need for external Javascript :).

**Comment by cpitclaudel** [comment]
Thanks, I saw these two sections :) As you guessed, I'm in the latter case — I'm compiling an existing desktop application.  Conditional linking sounds good :)
