### ISSUE TITLE
--file options complain about not finding files

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#588]
I'm trying to build a pseudo file system. I wrote this in mini.ml:

```
let a = 1
```

then I ran `ocamlc -g -o mini.byte mini.ml`, and finally:

```
echo input > input.txt
js_of_ocaml --extern-fs --file=input.txt --ofs=test mini.byte
```

But I get an error:

```
js_of_ocaml: Error: file 'input.txt' not found
```

What am I doing wrong?

**Comment by hhugo** [comment]
Try adding "-I ."

**Comment by cpitclaudel** [comment]
Very nice, thanks. This now compiles! Does this plug naturally into open_in calls? Or do I need to do something specific to access that virtual file system?

**Comment by hhugo** [comment]
open_in should work. The file should be located in /static/

**Comment by cpitclaudel** [comment]
It works perfectly. For future reference, the only thing left I had to figure out was that when saving as an external file with --ofs, the file isn't automatically referenced by the output of js_of_ocaml, so it has to be loaded too (`node -r filesystem.js compiled_program.js`)

**Comment by cpitclaudel** [comment]
Thanks for all your help!
