### ISSUE TITLE
Missing package js_of_ocaml.tyxml if deriving and reactiveData are not installed (although normally not required)

### ISSUE THREAD

**Issue by miredo** [ocsigen/js_of_ocaml#590]
If deriving and/or (?) reactiveData are not installed, the package js_of_ocaml.tyxml is not created.

Here are some command line requests that may help to understand the problem:

$ opam list
Installed packages for 4.04.1:
atd                         1.2.0  Parser for the ATD data format description language
atdgen                     1.10.0  Generates efficient JSON serializers, deserializers and validators
base-bigarray                base  Bigarray library distributed with the OCaml compiler
base-bytes                   base  Bytes library distributed with the OCaml compiler
base-threads                 base  Threads library distributed with the OCaml compiler
base-unix                    base  Unix library distributed with the OCaml compiler
base64                      2.1.2  For OCaml
bin_prot           113.33.00+4.03  A binary protocol generator
biniou                     1.0.13  Binary data format designed for speed, safety, ease of use and backward compatibility as protocols evolve
camlp4                     4.04+1  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                    1.0.0  Declarative definition of command line interfaces for OCaml
conf-m4                         1  Virtual package relying on m4
conf-which                      1  Virtual package relying on which
core               113.33.02+4.03  Industrial strength alternative to OCaml's standard library
core_kernel        113.33.02+4.03  Industrial strength alternative to OCaml's standard library
cppo                        1.5.0  Equivalent of the C preprocessor for OCaml programs
easy-format                 1.2.0  High-level and functional interface to the Format module of the OCaml standard library
fieldslib               113.24.00  Syntax extension to define first class values representing record fields, to get and set record fields, iterate and fold over all fields of a record and create new record values
js_of_ocaml                 2.8.4  Compiler from OCaml bytecode to Javascript
lwt                         3.0.0  Monadic promises and concurrent I/O
markup                      0.7.4  Error-recovering functional HTML5 and XML parsers and writers
menhir                   20170509  LR(1) parser generator
ocamlbuild                 0.11.0  OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlbuild-atdgen           0.1.0  Atdgen plugin for OCamlbuild
ocamlfind                   1.7.1  A library manager for OCaml
ppx_assert              113.33.00  Assert-like extension nodes that raise useful errors on failure
ppx_bench          113.33.00+4.03  Syntax extension for writing in-line benchmarks in ocaml code
ppx_bin_prot       113.33.00+4.03  Generation of bin_prot readers and writers from types
ppx_compare        113.33.00+4.03  Generation of comparison functions from types
ppx_core           113.33.01+4.03  Standard library for ppx rewriters
ppx_custom_printf  113.33.00+4.03  Printf-style format-strings for user-defined string conversion
ppx_deriving                  4.1  Type-driven code generation for OCaml >=4.02
ppx_driver         113.33.00+4.03  Feature-full driver for OCaml AST transformers
ppx_enumerate      113.33.00+4.03  Generate a list containing all values of a finite type
ppx_expect         113.33.00+4.03  Cram like framework for OCaml
ppx_fail           113.33.00+4.03  Add location to calls to failwiths
ppx_fields_conv    113.33.00+4.03  Generation of accessor and iteration functions for ocaml records
ppx_here                113.33.00  Expands [%here] into its location
ppx_inline_test    113.33.00+4.03  Syntax extension for writing in-line tests in ocaml code
ppx_jane                113.33.00  Standard Jane Street ppx rewriters
ppx_let            113.33.00+4.03  Monadic let-bindings
ppx_optcomp        113.33.01+4.03  Optional compilation for OCaml
ppx_pipebang       113.33.00+4.03  A ppx rewriter that inlines reverse application operators `|>` and `|!`
ppx_sexp_conv      113.33.01+4.03  Generation of S-expression conversion functions from type definitions
ppx_sexp_message   113.33.00+4.03  A ppx rewriter for easy construction of s-expressions
ppx_sexp_value     113.33.00+4.03  A ppx rewriter that simplifies building s-expressions from ocaml values
ppx_tools                     5.0  Tools for authors of ppx rewriters and other syntactic tools
ppx_type_conv      113.33.02+4.03  Support Library for type-driven code generators
ppx_typerep_conv   113.33.00+4.03  Generation of runtime types from type declarations
ppx_variants_conv  113.33.00+4.03  Generation of accessor and iteration functions for ocaml variant types
re                          1.7.1  RE is a regular expression library for OCaml
react                       1.2.1  Declarative events and signals for OCaml
result                        1.2  Compatibility Result module
sexplib            113.33.00+4.03  Library for serializing OCaml values to and from S-expressions
topkg                       0.9.0  The transitory OCaml software packager
typerep                 113.24.00  typerep is a library for runtime types.
tyxml                       4.1.0  TyXML is a library for building statically correct HTML5 and SVG documents
tyxml-ppx                   4.1.0  Virtual package for tyxml's ppx
uchar                       0.0.1  Compatibility library for OCaml's Uchar module
uutf                        1.0.1  Non-blocking streaming Unicode codec for OCaml
variantslib             113.24.00  Part of Jane Street's Core library
yojson                      1.3.3  Yojson is an optimized parsing and printing library for the JSON format

$ ocamlfind query js_of_ocaml.tyxml
ocamlfind: Package `js_of_ocaml.tyxml' not found

Please find here the result of the compilation of js_of_ocaml:
[js_of_ocaml.compilation.txt](https://github.com/ocsigen/js_of_ocaml/files/1060576/js_of_ocaml.compilation.txt)

After I installed deriving and reactiveData, the package is successfully created:
$ opam install reactiveData deriving

$ ocamlfind query js_of_ocaml.tyxml
/home/nicolas/.opam/4.04.1/lib/js_of_ocaml

**Comment by vasilisp** [comment]
This is not very intuitive, but it is expected nevertheless. `reactiveData` is needed for `Tyxml_js.R`. Not sure about `deriving`.

In any case, the problem will go away with the upcoming modular JSOO 3.0 . The `js_of_ocaml-tyxml` package has hard dependencies on `tyxml` and `reactiveData`, so everything becomes clear and predictable.

**Comment by miredo** [comment]
Ok this makes sense. Sure using a specific package js_of_ocaml-tyxml will help. Thanks for the explanation
