### ISSUE TITLE
Runtime representation of arrays

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#603]
Hi there,

I'm trying to get a better picture of how js_of_ocaml works internally to prevent mistakes in my ZArith implementation.

I'm a bit confused by this bit in `caml_sys_get_argv`:

```
  var p = caml_js_to_string(main);
  var args2 = [0, p];
  for(var i = 0; i < args.length; i++)
    args2.push(caml_js_to_string(args[i]));
return [0, p, args2];
```

If I understand this correctly, the final array when Sys.argv is `[| "a.out", "--x", "--y" |]` will be `[0, caml_new_string("a.out"), [0, caml_new_string("a.out"), caml_new_string("--x"), caml_new_string("--y")]`.  Is that correct?

When I make a small program containing this array and compile it, js_of_ocaml produces this instead:

```
[0,
 caml_new_string("a.out"),
 caml_new_string("--x"),
 caml_new_string("--y"),
 caml_new_string("--z")]]
```

Are both of these valid?  Which one should I return from e.g. "unix_get_environment"?

**Comment by dbuenzli** [comment]
> I'm trying to get a better picture of how js_of_ocaml works internally to prevent mistakes in my ZArith implementation.

The [paper](https://www.irif.fr/~balat/publications/vouillon_balat-js_of_ocaml.pdf), if still accurate,  has a section about data type representations.

**Comment by hhugo** [comment]
`caml_sys_get_argv` returns `string * string array`. Ocaml blocks are represented JavaScript array with the first element used to store the tag.

**Comment by cpitclaudel** [comment]
Ah, of course! Makes perfect sense now. Thanks a lot :)
