### ISSUE TITLE
Help with a performance issue? (--opt 3 makes things slower)

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#604]
Hi there,

I'm running into a surprising issue.  When debugging I compile my project with `--pretty --source-map --debug-info --no-inline`.  When running in production I use `--opt 3` instead.

In terms of file size, `--opt 3` definitely does a great job: `2.1MB` down from `17MB`.  In terms of performance, though, things are more surprising: `7.2s` up from `6.8s`.

Am I doing something wrong? Why would `--opt 3` make the code slower?
(I can provide the code if it helps.  Let me know if this a topic for the mailing list rather than the tracker, too)

Thanks!

**Comment by hhugo** [comment]
JavaScript performances are pretty hard to predict because of the JIT compiler.
It's possible that too much inlining prevents some optimization to trigger.
What's your environment ? Chrome ? Firefox ? node ? what version ?  
I'd be happy to have a look at your code.

**Comment by cpitclaudel** [comment]
Wonderful, thanks a lot! The repo is at https://github.com/cpitclaudel/fstar.js , but please give me a day to build a minimal, self-contained example :)

I've noticed the problem in all three (Chromium 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1 (64-bit), FF 54.0, node v8.1.2), but I only did a precise experiment in node.

**Comment by cpitclaudel** [comment]
Sorry for never writing the small example; I've made a lot of progress on this on my own in the meantime, and overall using js_of_ocaml has been a very nice experience.  Thanks a lot for all the hard work!
