### ISSUE TITLE
Broken install with js_of_ocaml 3.0

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#613]
It seems the install is broken with js_of_ocaml on macOS. The utility `js_of_ocaml` is absent (`js_of_ocaml.exe` is installed), see https://github.com/dbuenzli/vg/pull/16 which makes the `js_of_ocaml-ocamlbuild` plugin fail. 

Also it would be nice to give dependents a few hints in the release notes on what has changed with the release 3.0 the current release notes are absolutely not useful.

**Comment by dbuenzli** [comment]
So I upgraded `jbuilder` to the latest beta and resintalled `js_of_ocaml-compiler` is there maybe a missing constraint on `jbuilder` ?

**Comment by dbuenzli** [comment]
> So I upgraded jbuilder to the latest beta

(from `1.0+beta10` to `1.0+beta11`)

**Comment by dbuenzli** [comment]
It doesn't seem to be related to `jbuilder`. My guess is that `js_of_ocaml-compiler.3.0` should be conflicting with `js_of_ocaml < 3.0` as those overwrite the binary installed by the former package and when you upgrade `js_of_ocaml` to 3.0 again `js_of_ocaml-compiler` is not reinstalled . The following sequence of `opam` installs can reproduce the problem:

```
opam install js_of_ocaml.3.0 js_of_ocaml-ocamlbuild-3.0 js_of_ocaml-compiler.3.0 js_of_ocaml-ppx.3.0
opam install js_of_ocaml.2.8.4
opam install js_of_ocaml.3.0
> js_of_ocaml --version
-bash: js_of_ocaml: command not found
opam reinstall js_of_ocaml-compiler.3.0
> js_of_ocaml --version
3.0
```

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/10620
