### ISSUE TITLE
Printexc.raise_with_backtrace not supported

### ISSUE THREAD

**Issue by nojb** [ocsigen/js_of_ocaml#619]
The primitive `%raise_with_backtrace` is missing.

**Comment by hhugo** [comment]
I've just reported the issue. See https://caml.inria.fr/mantis/view.php?id=7666

**Comment by nojb** [comment]
Thanks! I proposed a fix for the issue: https://github.com/ocaml/ocaml/pull/1465.

**Comment by hhugo** [comment]
We'll have to provide a dummy caml_restore_raw_backtrace

**Comment by hhugo** [comment]
fixed in ocaml/trunk https://github.com/ocaml/ocaml/pull/1557
