### ISSUE TITLE
How to use Topdirs.dir_load/Dynlink.loadfile with js files

### ISSUE THREAD

**Issue by SanderSpies** [ocsigen/js_of_ocaml#620]
I'm trying to move from dynamically loading `.cma/.cmo` files to loading "precompiled" `.js` files as mentioned here: https://github.com/ocsigen/js_of_ocaml/pull/480, however I have been unsuccessful so far. 

I'm using `Topdirs.dir_load Format.std_formatter foo_file` to load the files so they can be executed without giving a `Error: Reference to undefined global Foo'` error.

It's unclear however to me how this should work with JS files.

I did try to use `Dynlink.loadfile` but that resulted in: `The dynlink.cma library cannot be used inside the OCaml toplevel`. Note that I used `jsoo_mktop -package dynlink ...` for this.

This works for me when using `Topdirs.dir_load Format.std_formatter foo_file`:
`js_of_ocaml --file foo.cma --extern-fs -I . --ofs=fs.js`

but what I want to get to work is:

```
js_of_ocaml --pretty foo.cma
cat foo.js >> fs.js
```

Some guidance would be much appreciated.

**Comment by SanderSpies** [comment]
For now I solved this by wrapping everything in a single toplevel and not loading it dynamically.

**Comment by hhugo** [comment]
Once you have `foo.js`, you only need to have it loaded by the web browser by adding the proper script element to the page.

This is what `#load_js` is doing in #480.
```
Hashtbl.add Toploop.directive_table "load_js" (Toploop.Directive_string (fun name ->
    Js.Unsafe.global##load_script_ name));
```
where `load_script` is defined as
```
      function load_script(url){
        var fileref=document.createElement('script');
        fileref.setAttribute("type","text/javascript");
        fileref.setAttribute("src", prefix+(version==""?"":(version+"/"))+url);
        document.getElementsByTagName("head")[0].appendChild(fileref);
      }
```

**Comment by hhugo** [comment]
reopen if needed
