### ISSUE TITLE
Toplevel #use seems broken

### ISSUE THREAD

**Issue by timothee-haudebourg** [ocsigen/js_of_ocaml#625]
Hi,
I'm using JsooTop to build a toplevel web interface. A some point I need to load a file in the toplevel. To do that I use the toplevel directive `#use "/static/myfile.ml"`. This seems to execute fine until I try to call any of the functions defined in `myfile.ml` for which I get:
```
Exception: Js.Error TypeError: _g_ is undefined.
```
where `_g_` is not the name of my function. I think it refers to a js variable. Sometimes it's `_h_` instead.
Note that if I execute manually the content of the file instead of using #use, it works perfectly.

I'm using js_of_ocaml 3.0 with OCaml 4.03.0

**Comment by hhugo** [comment]
I'm not able to reproduce this. What's in your file /static/myfile.ml ?

**Comment by hhugo** [comment]
```
let oc = open_out "/static/test.ml";;
val oc : out_channel = <abstr>
output_string oc {| let f name = Printf.printf "hello %s !\n" name |};;
- : unit = ()
close_out oc;;
- : unit = ()
#use "/static/test.ml";;
val f : string -> unit = <fun>
f "js_of_ocaml";;
hello js_of_ocaml !
- : unit = ()
```

Reopen if needed.
