### ISSUE TITLE
fs.js not compatible with RequireJS

### ISSUE THREAD

**Issue by mroch** [ocsigen/js_of_ocaml#626]
https://github.com/ocsigen/js_of_ocaml/blob/1bc3f248d35c8a7e857f3952d24eab6b77bf025a/runtime/fs.js#L54-L58

this code assumes that if a global `require` function exists, then we must be in node where the `fs` module exists, but that's not true when using [RequireJS](http://requirejs.org/) in a browser.

also, since `MlNodeDevice`'s constructor eagerly calls `require('fs')`, it errors immediately at load time.

my use-case is https://flow.org/try

**Comment by haishengwu-okta** [comment]
looks like we need more general way to determine whether it's Node environment.
an quick search from stackoverflow might be useful: https://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js
