### ISSUE TITLE
`Async_kernel` example fails on the Toplevel

### ISSUE THREAD

**Issue by smondet** [ocsigen/js_of_ocaml#628]
In http://ocsigen.github.io/js_of_ocaml/#version=4.03.0

![image](https://user-images.githubusercontent.com/617111/32668517-da46890e-c60b-11e7-8776-b459d69522ff.png)

Here it shared:  https://is.gd/E7EEyz

**Comment by hhugo** [comment]
I've updated the toplevels (see https://github.com/ocsigen/js_of_ocaml/commit/c8391b525ec2fbc3b4e8514dffa1890d09afa93e).

I've removed the example from the list for now.

The (updated) example bellow should work:
```
Async_js.init();;
open Core_kernel;;
open Async_kernel;;
let rec countdown span =
  if Time_ns.Span.(span < zero)
  then begin
      print_endline "done";
      Deferred.unit
    end
  else begin
      Caml.Printf.printf "%fsec\n" (Time_ns.Span.to_sec span);
      let delay = Time_ns.Span.of_sec 1. in
      Clock_ns.after delay >>= fun () -> countdown Time_ns.Span.(span - delay)
    end;;
countdown (Time_ns.Span.of_sec 5.);;
```
