### ISSUE TITLE
[runtime] caml_sys_chdir seems broken

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#636]
In `fs.js`we have:
```javascript
function caml_sys_chdir(dir) {
  var root = resolve_fs_device(dir);
  if(root.device.exists(root.rest)) {
    caml_current_dir = root.base + dir.rest + "/"
    return 0;
  }
```
however, the `.base` attribute seems not to appear anywhere. This breaks my application (jsCoq) which calls `Sys.chdir` with a `MlFakeDevice` as a standard mount point.

I've changed this to `root.path` but then I see very weird behavior in other parts.

**Comment by ejgallego** [comment]
Also `dir.rest` seems to arrive undefined in my app.

**Comment by ejgallego** [comment]
So as a hack I've changed the line to:
```
    caml_current_dir = dir.c + "/"
```
and that seems to resurrect jsCoq; dunno what is the proper action path.

**Comment by hhugo** [comment]
Thanks for the report

**Comment by ejgallego** [comment]
Thanks to you for the quick fix; I confirm the fix does indeed work for jsCoq.
