### ISSUE TITLE
Unix.stat on autoloaded files

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#650]
Hi there,

I'm trying to use the register_autoload function to load data files lazily. One problem is that my code needs to compare modifications time, and although caml_fs_register seems to be able to register `MlFile`s, I wasn't able to find a similar feature for autoloads.

Is there an easy way for my javascript code to dynamically intercept file system calls an return an MlFile, rather than a string?

Thanks!

**Comment by cpitclaudel** [comment]
> caml_fs_register seems to be able to register MlFiles

Hm :/ This seems to have been true for caml_fs_register in 2.8.4 (the version that I was using), but not anymore.  And the caml_unix_time function seems to be gone, too.

Is there a workaround for this?

**Comment by cpitclaudel** [comment]
I imagine I found a workaround at the time, but I forget what I ended up doing.

**Comment by hhugo** [comment]
#1115 adds support for Unix.stat for node filesystem. With a bit of work it could be implemented for the in memory filesystem
