### ISSUE TITLE
What's the right way to use --export-runtime and --no-runtime?

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#651]
Hi there,

I'm trying to compile my library separately from the runtime, so I can work on each separately.
Building my code with --no-runtime, though, gives me a file that refers to globals (caml_new_string, etc);  is there a way to make the new code refer to `jsoo_global_object.jsoo_runtime.caml_new_string` instead? 

I see that the js_of_ocaml adds blocks like this one:

```
     caml_sys_is_directory=
      joo_global_object.caml_sys_is_directory !== undefined
       ?joo_global_object.caml_sys_is_directory
       :function()
         {caml_failwith("caml_sys_is_directory" + " not implemented")},
```

… but it doesn't do the same thing for caml_new_string.  Why is that? Am I doing this wrong?

**Comment by hhugo** [comment]
Is this still relevant ?

**Comment by cpitclaudel** [comment]
No idea, I completely forgot the context after 3 years.
