### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by xinzheyang** [ocsigen/js_of_ocaml#662]
https://ocsigen.org/js_of_ocaml/api/Json
a lot of API links don't work
And in http://ocsigen.org/js_of_ocaml/3.1.0/manual/overview the links on the side bar don't work either

**Comment by tinachen123** [comment]
I have the same issue, too! In this case, where else can I access the documentation of modules?

**Comment by vasilisp** [comment]
There is a [list of modules](https://ocsigen.org/js_of_ocaml/3.1.0/api/index_modules.html) if it helps. Unfortunately, the `Json` doc doesn't seem to be there. 

In any case, we are aware of the issues and working on them. CC @CelieArnaud :).

**Comment by hhugo** [comment]
This has been fixed, it seems.
