### ISSUE TITLE
Customizable tailcall_max_depth

### ISSUE THREAD

**Issue by cpitclaudel** [ocsigen/js_of_ocaml#665]
Hi there,

I there an easy way to customize max_tc_depth? Ideally, setting it to zero would disable the counting mechanism entirely.

I'm currently using a patch (https://github.com/cpitclaudel/js_of_ocaml/commit/e33e78c80a4157632643ee38e979d1ba9f221319) for that.

Thanks!

**Comment by cpitclaudel** [comment]
I updated the patch here: https://github.com/cpitclaudel/js_of_ocaml/commit/af0f5bf2e2db60c84b758723db5b808be3efaa29

It would be really nice to get a command-line parameter (ideally with the optimization that removes the branch when tailcall_max_depth is 0 :)

**Comment by hhugo** [comment]
There is `js_of_ocaml compile --set tc_depth=100`.
It's probably not documented.
It doesn't disable the optimization when set to 0.

**Comment by cpitclaudel** [comment]
Yes, that's the parameter that the patch I'm posted is using.

**Comment by hhugo** [comment]
Looking at this more closely, there is ` --set tc=none` that does exactly that.

**Comment by hhugo** [comment]
Sorry, I misunderstood, you want to disable the direct calls, not the trampoline.
