### ISSUE TITLE
Compiling lwt_unix and js_of_ocaml issue

### ISSUE THREAD

**Issue by reihan35** [ocsigen/js_of_ocaml#678]
Hi js_of_ocaml team 
I have a .ml file that I compile with the following command : 
`ocamlfind ocamlc voy_cons.ml -o voy_cons.byte -linkpkg -package l
wt_ppx -package js_of_ocaml -package js_of_ocaml-ppx -package lwt.unix -linkpkg`
and then : 
`js_of_ocaml --disable genprim voy_cons.byte` to transform to a javaScript file.
after this step I have these warnings : 
Missing primitives:
  lwt_libev_init
  lwt_libev_io_stop
  lwt_libev_loop
  lwt_libev_readable_init
  lwt_libev_stop
  lwt_libev_timer_init
  lwt_libev_timer_stop
  lwt_libev_unloop
  lwt_libev_writable_init
  lwt_unix_check_job
  lwt_unix_guess_blocking_job
  lwt_unix_init_notification
  lwt_unix_init_signals
  lwt_unix_iov_max
  lwt_unix_is_socket
  lwt_unix_recv_notifications
  lwt_unix_run_job_sync
  lwt_unix_self_result
  lwt_unix_set_signal
  lwt_unix_start_job
  lwt_unix_wait4
  unix_clear_nonblock
  unix_fstat
  unix_select
  unix_set_nonblock
  unix_waitpid

Befor using Lwt_unix sleep It was not a problem because the application worked well but now I have the following error in my browser and I dont know what to do :
`voy_cons.js:3004 Uncaught ReferenceError: lwt_unix_iov_max is not defined
    at voy_cons.js:3004
    at voy_cons.js:3190` 
Would you please help me ?

**Comment by vasilisp** [comment]
`lwt.unix` is an Lwt interface to functionality provided by Unix-like operating systems. Such functionality is not available via JavaScript, and thus you can't use `lwt.unix` with Js_of_ocaml. If all you need is a `sleep` function, there is `Lwt_js.sleep` (in the `js_of_ocaml-lwt` package).

**Comment by reihan35** [comment]
@vasilisp 
Ok Thanks a lot but when I tried to compile with the following commande : 
`ocamlfind ocamlc voy_cons.ml -o voy_cons.byte -linkpkg -package l
wt_ppx -package js_of_ocaml -package js_of_ocaml-ppx -package js_of_ocaml-lwt -package lwt.unix -linkpkg`
I have :  Package `js_of_ocaml-lwt' not found
so I tried installing it seperatly via opam but I have : 
The following dependencies couldn't be met:
  - js_of_ocaml-lwt -> lwt < 4.0.0
Your request can't be satisfied:
  - No package matches lwt<4.0.0.
However Lwt is installed.Do you have any idea ? Did you installed and compiled the same way ?
And do you know what I shoud do if I need to use other Lwt.unix functions ?

**Comment by hhugo** [comment]
You cannot mix `-package js_of_ocaml` and `-package lwt.unix`.

The latest version of Js_of_ocaml available on opam is not compatible with lwt 4.*.
Can you try downgrading lwt (`opam install lwt.3.3.0`). What version of ocaml are you using ?

**Comment by hhugo** [comment]
closing for now, reopen if you can provide more info.
