### ISSUE TITLE
Dom_html.location##reload() does not work :(

### ISSUE THREAD

**Issue by reihan35** [ocsigen/js_of_ocaml#681]
Hello js_of_ocaml team!
Would you guys please tell me why this does not work : 
`Dom_html.location##reload()` 
and returns : 
`Unbound value Dom_html.location`

while this works : 
Dom_html.window##alert(Js.string "hello")

Aren't they both objects in Dom_html module ? How should I solve this problem ? 

Thank you for your answers !

**Comment by hhugo** [comment]
the Dom_html module define `window`, not `location`.
`location` is a property of window though, you should use `Dom_html.window##.location##reload`
