### ISSUE TITLE
Setting up with Webpack

### ISSUE THREAD

**Issue by xvw** [ocsigen/js_of_ocaml#683]
Hi. 
I used Jsoo in my work to write a small component. 
This component depended on few function from a JavaScript's library, so we used webpack to restrict the interface of this library : 

```Javascript
import {fa, fb, fc} from 'my-external-lib'; 
export default {
   fa, fb, fc
}
```

Actually, the jsoo-library and the webpacked library are linked with to `<script>` but I imagine that it is possible to combine the two files into once. 

When I use `javascript_files` in my `dune` file, at the execution I have always the error `exports is not defined`. When I try to inject jsoo-file via Webpack, I have a Webpack error about the module `fs`. 

Is there a way to specify that the target of the compilation is exclusively for browser (and avoid the usage of `fs`) or did I miss something about the injection of javaScript file ? 

thanks à lot. 

Xavier.

**Comment by outkine** [comment]
I'm also facing this problem, caused by `require("fs")`. Why does JSOO need to use fs in the first place?

**Comment by outkine** [comment]
The fix proposed [here](https://github.com/webpack-contrib/css-loader/issues/447) worked for me. Add this to your webpack config:
```
  node: {
    fs: 'empty',
  },
```

**Comment by xvw** [comment]
Yes, but I think that it is ... pity. 
IMHO (without knowing what that implies, obviously), it would be nice to be able to specify a Runtime at JSOO.
