### ISSUE TITLE
Is it possible to load a cmis.js compiled separately to toplevel

### ISSUE THREAD

**Issue by thangngoc89** [ocsigen/js_of_ocaml#688]
Hello jsoo devs, I'm working on Sketch.sh (a playground for ReasonML and OCaml that uses jsoo's toplevel to evaluate code). I want to support loading modules to toplevel dynamically. I figured out how to do this in a single compilation thanks to this example https://github.com/ocsigen/js_of_ocaml/blob/master/toplevel/examples/lwt_toplevel_bin/Makefile 

It works nicely but I want to take a step further by allowing users to load their own `cmis.js` files to sketch.
For example `re` module, I can compile `re.cmis.js` using 

```sh
jsoo_mkcmis re
```

and load that to the html page. 
Currently, re cmi files (`re.cmi`, `re__Prce.cmi`) shows up in `/static/cmis` but it toplvel can't pick them up. It throws `unknown modules Re` .

I try to load all modules again using this function 

```ocaml
let load_cmis () =
  let env = !Toploop.toplevel_env in
  let cmis = Array.to_list (Sys.readdir "/static/cmis/") in
  List.iter (fun cmi -> (
    let cmi_name = String_compat.capitalize_ascii (Filename.chop_suffix cmi ".cmi") in
    try
      let _ = Env.lookup_module ~load:true (Lident cmi_name) env in
      ()
    with
    | _ -> () (* ignore the errors here for now *);
  )) cmis
```

But toplevel still can't pick it up. So I wonder if separately compiling `cmis.js` file is possible at all? 

Thank you very much

**Comment by hhugo** [comment]
The issue mention loading the cmi but does not mention how the implementation is linked.

1. The implementation is already part of the toplevel. This would indeed be an issue with expunge. adding `-export-package re` should solve this.
2. The implementation is loaded as bytecode (.cmo or .cma) using the `#load` directive. I would expect this to work.
3. The implementation is loaded as javascript (e.g loading in the page the result of `js_of_ocaml re.cma`). I gave this a try and it does not work.

**Comment by thangngoc89** [comment]
@hhugo Sorry for not providing information about how to load implementation. I didn't know about that at the time I opened this issue. With the help of @Drup I have been able to load `cmi` into the toplevel.

For implementation loading, here is what I tried:

1. This works perfectly. But my plan is to somehow allow folks to upload there packages or loading packages directly from opam so this won't scale :( 
2. Yes. This works. I compiled the main `toplevel` with `--extern-fs`. And then, for loading `re.cma, I compile with this command:

```
js_of_ocaml --wrap-with-fun=reLib --file seq.cma --file re.cma --extern-fs -I . re.cma --ofs=re.cma.js
```

This gives me a `re.cma.js` which I can load to browser and call `reLib(window)` to load `seq.cma` and `re.cma` into the pseudo filesystem. After that, inside toplevel, I call 

```
#load "seq.cma";;
#load "re.cma";;
```

This will load the library and I can now access it in toplevel. But this won't scale well because `#load "re.cma"` freezes the whole thread in 10 seconds.

3. This is what I really want to achieve. I compile `re.cma` again with 

```
js_of_ocaml --wrap-with-fun=reLib re.cma
```

And load it to browser as usual : `reLib(window)`. No errors but I still can't access `Re` module in toplevel.

For the record, this is the command I used to compile `toplevel` 

```
js_of_ocaml --toplevel --no-cmis --export toplevel.byte.export --dynlink --extern-fs +toplevel.js +dynlink.js +nat.js toplevel.byte
```

**Comment by hhugo** [comment]
Thanks for the details. I will take a look at 3 over the weekend.

**Comment by thangngoc89** [comment]
@hhugo Thank you very much

**Comment by hhugo** [comment]
I've pushed a fixed on master (https://github.com/ocsigen/js_of_ocaml/commit/8c7bb9b55e359f1520d2973ae0a0ef445c568ab0).
Let me know if that works for you.

**Comment by thangngoc89** [comment]
@hhugo thank you very much ! It's working correctly right now. I'm gonna explore all the possibilities of this.

**Comment by hhugo** [comment]
Perfect

**Comment by hhugo** [comment]
It would be awesome if you could come back here with your findings

**Comment by thangngoc89** [comment]
@hhugo You might be interested in this. Next release of sketch gonna be huge 

https://github.com/ocaml/opam-repository/issues/12517

**Comment by maiste** [comment]
Hi jsoo developers !
I'm working with @yurug on the Learn-ocaml platform. We are trying to do something similar to what thangncoc89 did: we want to allow the user to specify libraries, installed on his system, that he wants to import into his toplevel.

I've read a lot of issues about it but I still can't get how it works...
1. When I build my library in the way describes in [this issue](https://github.com/ocaml/opam-repository/issues/12517):
```sh
js_of_ocaml --wrap-with-fun=stringextCma --toplevel -I path-of-cmis --pretty path/to/stringext.cma -o stringext.cma.js
```
When I import it in the javascript console with `stringextCma(window)`, I get the following error:
```javascript 
TypeError: runtime is undefined
```
2. I'm trying to use the function, equivalent to `#load_js`, to load the content of the script but I get another error in the toplevel:
```sh
TypeError: bN[1].load_script is not a function
```
Learn-ocaml uses `jsoo 3.3.0` and `ocaml 4.05.0`. I'm sure I'm missing something  or I'm doing it the wrong way but I don't know what. Do you have any suggestion?
Thank you very much!
