### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by louisabraham** [ocsigen/js_of_ocaml#692]
I am totally not an user of jbuilder and have the following error when launching `make all`:

    jbuilder build @install @DEFAULT -j 8 --dev
    File "camlp4/pa_deriving_json/tests/jbuild", line 25, characters 11-54:
    Error: Unknown constructor diff
    make: *** [all] Error 1

`opam install js_of_ocaml js_of_ocaml-ppx` worked, but I would like to build `eval.js` in https://github.com/ocsigen/js_of_ocaml/tree/master/toplevel/eval

Can somebody help me to build this file?

**Comment by louisabraham** [comment]
```
$ opam --version
1.2.2
$ ocaml --version
The OCaml toplevel, version 4.04.2
$ jbuilder --version
1.0+beta16
```

**Comment by hhugo** [comment]
the `js_of_ocaml.opam` says

>   "jbuilder" {build & >= "1.0+beta17"}

Can you upgrade jbuilder and retry ?

**Comment by louisabraham** [comment]
Thank you, I did `opam upgrade` but then I realized I needed to do `opam update` first. It's compiling :)

**Comment by louisabraham** [comment]
Now I get:

    $ jbuilder --version
    1.1.1
    $ make all
    jbuilder build @install @DEFAULT -j 8 --dev
    File "ppx/ppx_deriving_json/lib/jbuild", line 8, characters 14-30:
    Error: Library "ppx_deriving.api" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
    File "ppx/ppx_deriving_json/lib/jbuild", line 9, characters 27-52:
    Error: Public library "ppx_tools" not found
    File "lib/tyxml/jbuild", line 6, characters 26-31:
    Error: Library "tyxml" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
          ocamlc camlp4/pa_js/lib/.pa_js.objs/pa_js.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /Users/louisabraham/.opam/4.04.2/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I camlp4/pa_js/lib/.pa_js.objs -I /Users/louisabraham/.opam/4.04.2/lib/ocaml/camlp4 -no-alias-deps -opaque -o camlp4/pa_js/lib/.pa_js.objs/pa_js.cmo -c -impl camlp4/pa_js/lib/pa_js.pp.ml)
    File "camlp4/pa_js/lib/pa_js.ml", line 29, characters 5-11:
    Error: Unbound module Camlp4
    make: *** [all] Error 1  
    mbpla:js_of_ocaml louisabraham$ make all
    jbuilder build @install @DEFAULT -j 8 --dev
    File "ppx/ppx_deriving_json/lib/jbuild", line 8, characters 14-30:
    Error: Library "ppx_deriving.api" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
    File "ppx/ppx_deriving_json/lib/jbuild", line 9, characters 27-52:
    Error: Public library "ppx_tools" not found
    File "lib/tyxml/jbuild", line 6, characters 26-31:
    Error: Library "tyxml" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
          ocamlc camlp4/pa_js/lib/.pa_js.objs/pa_js.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /Users/louisabraham/.opam/4.04.2/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I camlp4/pa_js/lib/.pa_js.objs -I /Users/louisabraham/.opam/4.04.2/lib/ocaml/camlp4 -no-alias-deps -opaque -o camlp4/pa_js/lib/.pa_js.objs/pa_js.cmo -c -impl camlp4/pa_js/lib/pa_js.pp.ml)
    File "camlp4/pa_js/lib/pa_js.ml", line 29, characters 5-11:
    Error: Unbound module Camlp4
    make: *** [all] Error 1  
    mbpla:js_of_ocaml louisabraham$ make all
    jbuilder build @install @DEFAULT -j 8 --dev
    File "ppx/ppx_deriving_json/lib/jbuild", line 8, characters 14-30:
    Error: Library "ppx_deriving.api" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
    File "ppx/ppx_deriving_json/lib/jbuild", line 9, characters 27-52:
    Error: Public library "ppx_tools" not found
    File "lib/tyxml/jbuild", line 6, characters 26-31:
    Error: Library "tyxml" not found.
    Hint: try: dune external-lib-deps --missing --profile dev @install @DEFAULT
          ocamlc camlp4/pa_js/lib/.pa_js.objs/pa_js.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /Users/louisabraham/.opam/4.04.2/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I camlp4/pa_js/lib/.pa_js.objs -I /Users/louisabraham/.opam/4.04.2/lib/ocaml/camlp4 -no-alias-deps -opaque -o camlp4/pa_js/lib/.pa_js.objs/pa_js.cmo -c -impl camlp4/pa_js/lib/pa_js.pp.ml)
    File "camlp4/pa_js/lib/pa_js.ml", line 29, characters 5-11:
    Error: Unbound module Camlp4
    make: *** [all] Error 1  

Are there some build requirements to install?

**Comment by louisabraham** [comment]
So I did:

    $ dune external-lib-deps --missing --profile dev @install @DEFAULT
    Error: The following libraries are missing in the default context:
    - base64 (optional)
    - deriving.syntax.common (optional)
    - higlo (optional)
    - higlo.ocaml (optional)
    - ppx_deriving.api
    - ppx_tools
    - reactiveData
    - tyxml
    Hint: try: opam install ppx_deriving ppx_tools reactiveData tyxml

and `opam install ppx_deriving ppx_tools reactiveData tyxml`.

Now I just get 

    $ make all
    jbuilder build @install @DEFAULT -j 8 --dev
          ocamlc camlp4/pa_js/lib/.pa_js.objs/pa_js.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /Users/louisabraham/.opam/4.04.2/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I camlp4/pa_js/lib/.pa_js.objs -I /Users/louisabraham/.opam/4.04.2/lib/ocaml/camlp4 -no-alias-deps -opaque -o camlp4/pa_js/lib/.pa_js.objs/pa_js.cmo -c -impl camlp4/pa_js/lib/pa_js.pp.ml)
    File "camlp4/pa_js/lib/pa_js.ml", line 29, characters 5-11:
    Error: Unbound module Camlp4
    make: *** [all] Error 1

**Comment by louisabraham** [comment]
On https://stackoverflow.com/questions/35259311/unbound-module-camlp4 I read

> Camlp4 was part of the official OCaml distribution until its version 4.01.0

Maybe `opam switch` will solve the problem? But since you put a dedicated camlp4 folder, I don't think I need to downgrade OCaml.

**Comment by louisabraham** [comment]
So, googling `js_of_ocaml Camlp4` gave me https://github.com/ocsigen/js_of_ocaml/blob/master/js_of_ocaml-camlp4.opam

`opam install js_of_ocaml-camlp4` solved the problem! All built successfully!
