### ISSUE TITLE
Missing primitives: caml_restore_raw_backtrace in OCaml 4.07.

### ISSUE THREAD

**Issue by pbiggar** [ocsigen/js_of_ocaml#693]
When compiling some code that uses `Caml.PrintExc.get_raw_backtrace`, my js_of_ocaml compile shows

```
Missing primitives:
  caml_restore_raw_backtrace
```

From reading the issues, it seems this was a bug that was regarded as fixed in #619, relying on a fix that was shipped in OCaml 4.07. However, this issue persists when using OCaml 4.07.0. (I'm using jsoo 3.2.0 as 3.2.1 doesn't appear to be in opam).

Thanks!

**Comment by hhugo** [comment]
Only the part in the compiler was fixed.
We still need to add this primitive in jsoo. (I just did that)

Regarding 3.2.1 missing from opam, did you run `opam update` ?

**Comment by pbiggar** [comment]
Thanks!

RE 3.20, https://opam.ocaml.org/packages/js_of_ocaml/ doesn't show 3.2.1, and also I just ran this now:

```
$ opam update && opam install js_of_ocaml.3.2.1

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>
[default] synchronised from https://opam.ocaml.org/2.0
Now run 'opam upgrade' to apply any package updates.
[ERROR] Package js_of_ocaml has no version 3.2.1.
```

**Comment by hhugo** [comment]
js_of_ocaml is split in multiple packages, js_of_ocaml.3.2.1 does not exists, but js_of_ocaml-compiler.3.2.1 does

**Comment by pbiggar** [comment]
Gotcha. Can confirm the 3.2.1 compiler did install. Thanks, and thanks for the fix!
