### ISSUE TITLE
js_of_ocaml broken inter-dependencies

### ISSUE THREAD

**Issue by yurug** [ocsigen/js_of_ocaml#694]
see https://github.com/ocaml/opam-repository/issues/12474.

**Comment by hhugo** [comment]
https://github.com/ocaml-sf/learn-ocaml/issues/77#issuecomment-413491331

**Comment by hhugo** [comment]
fixed in https://github.com/ocaml/opam-repository/pull/13123. 
Note that in general, js_of_ocaml-* packages don't have to be at the same version.
