### ISSUE TITLE
Is it possible to "undo" a toplevel phrase?

### ISSUE THREAD

**Issue by thangngoc89** [ocsigen/js_of_ocaml#698]
I would like to add block re-evaluation to Sketch because on large Sketch, it's super slow to re-run everything each time. I've been messing with `jsoo_runtime` without success. 

From what I observed, everytime I execute a new phrase, a new entry is added to `jsoo_runtime.caml_global_data` . So I tried to clone it into a new variable

```js
let global_data = jsoo_runtime.caml_global_data.slice()
```

try to executing another phrase (for example `let a = 1;;`) and then reassign global data:

```js
jsoo_runtime.caml_global_data = global_data
```

But `a` variable is still bounded. Did I miss something? Or such thing is not possible?

**Comment by hhugo** [comment]
How much undo do you want exactly ? A toplevel phrase can have many side effects.
Note that I don't think you want to play with the jsoo runtime for that. The toplevel maintains its state elsewhere. I think your question is not js_of_ocaml specific, you might get better answer with a wider audience

**Comment by thangngoc89** [comment]
I want to be able to rollback to a specific state, before executing a specific phrase. This is for caching untouched code block. some blocks could takes several seconds for executing and I hope to store the state of toplevel after those long blocks to improve the UI's responsiveness. 

 >  The toplevel maintains its state elsewhere. 
Could you please tell me where is that? I would love to take a look and hack on that

**Comment by hhugo** [comment]
I don't think this is possible, or at least difficult and probably inefficient. You would probably need to perform a deep copy of every single ocaml value (not only the value defined in the current toplevel), while preserving sharing.

**Comment by thangngoc89** [comment]
I see. thank you for your insights. performing a deep copy of all values is the fastest way to kill performances
