### ISSUE TITLE
Node.js and XMLHttpRequest

### ISSUE THREAD

**Issue by MaillPierre** [ocsigen/js_of_ocaml#707]
Trying to port a browser-based library to Node.js, i get errors during AJAX calls through XmlHttpRequest:
```
File "lib/xmlHttpRequest.ml", line 86, characters 2-8: Assertion failed
```

Is there an established method to be able to use xmlHttpRequest from ocaml code on a Node.js server ?

**Comment by MaillPierre** [comment]
I bypassed the problem with a custom xhr creation function:
```
let create_xhr () : xmlHttpRequest Js.t =
  let xmlHttpRequest =
    if Js.Optdef.test (Js.def Js.Unsafe.global##._XMLHttpRequest) then
      Js.Unsafe.global##._XMLHttpRequest 
      else if Js.Optdef.test (Js.def (Js.Unsafe.pure_js_expr "require('xmlhttprequest').XMLHttpRequest")) then 
      (Js.Unsafe.pure_js_expr "require('xmlhttprequest').XMLHttpRequest") else 
      assert false in
  let activeXObject = Js.Unsafe.global##.activeXObject in
  try new%js xmlHttpRequest with _ ->
  try new%js activeXObject (Js.string "Msxml2.XMLHTTP") with _ ->
  try new%js activeXObject (Js.string "Msxml3.XMLHTTP") with _ ->
  try new%js activeXObject (Js.string "Microsoft.XMLHTTP") with _ ->
  assert false
```

**Comment by Lupus** [comment]
I've ran into the same issue. @MaillPierre do you use your `create_xhr` directly? I'm trying to port some Cohttp based code and it dies because of missing XMLHttpRequest. All my attemepts to provide some runtime file to js_of_ocaml which sets global XMLHttpRequest to be `require('xmlhttprequest').XMLHttpRequest` failed so far. Forking Cohttp xhr Client module and modifying it sounds like a lot of maintenance burden. Isn't there a better solution?

**Comment by Lupus** [comment]
Another ugly workaround: create a file `xmlhttprequest_preload.js` with the following content:

```js
global.XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
```

Run your service as follows:

```
$ nodejs -r ./xmlhttprequest_preload.js your_service.bc.js
```

**Comment by Lupus** [comment]
@hhugo what if `create ()` will defined as external function with implementation in js_of_ocaml runtime as a primitive? This way users can override this primitive in their own runtime files and provide alternate implementation for Node.js.

**Comment by hhugo** [comment]
@Lupus, that sounds very good to me !
