### ISSUE TITLE
Why is the built JavaScript file so large?

### ISSUE THREAD

**Issue by ivanchean** [ocsigen/js_of_ocaml#708]
The content of my dune file is as follows:
```
(executable
  (name main)
  (libraries incr_dom)
  (js_of_ocaml)
  (preprocess (pps ppx_jane js_of_ocaml-ppx)))
```

After running the command as below, the target `main.bc.js` file size is nearly 12MB and includes more than 220,000 lines of code.
```
dune build { main.bc.js, index.html, style.css }
```

However, when I use `jbuilder`, the target `main.bc.js` file size is 1.1MB including 16,717 lines of code.
```
jbuilder build { main.bc.js, index.html, style.css }
```

| Package | Version | 
|:--- | :--- |
| ocaml | 4.07.0 |
| opam | 2.0.1 |
| js_of_ocaml | 3.2.0 |
| dune | 1.4.0 |

Why is the built JavaScript file so large ?

**Comment by dbuenzli** [comment]
I don't know the specifics of `dune` vs `jbuilder` but basically consult the build log and look the invocation of `js_of_ocaml`. If you want small outputs, avoid [options](http://ocsigen.org/js_of_ocaml/3.1.0/manual/options) like `--pretty` and `–debug-info`.  I suspect the differences are due to this.

**Comment by sagotch** [comment]
Probably a change of default behavior in different version of dune/jbuilder:

This (from https://dune.readthedocs.io/en/latest/jsoo.html) may be relevant. If I understood it properly, separate compilation is just appending javascript files (and, as it is said, without code elimination).

> Dune supports two modes of compilation

>    Direct compilation of a bytecode program to JavaScript. This mode allows js_of_ocaml to perform whole program deadcode elimination and whole program inlining.

>    Separate compilation, where compilation units are compiled to JavaScript separately and then linked together. This mode is useful during development as it builds more quickly.

> The separate compilation mode will be selected when the build profile is dev, which is the default.
> There is currently no other way to control this behaviour.

**Comment by ivanchean** [comment]
Thanks for your answers. I ran the following two commands and found that the __main.bc.js__ file compiled by these two commands is the same:

```bash
dune build { main.bc.js, index.html, style.css } --profile=release
```
```bash
jbuilder build { main.bc.js, index.html, style.css }
```

I am curious about why the built __main.bc.js__ file includes content such as Math.floor, getHours, etc. My __main.ml__ code is just a very simple demo code.

<img src="https://user-images.githubusercontent.com/16490377/47781427-9efba880-dd38-11e8-9a93-40ee057a9d44.png" width="400" />

I think that no matter which command is used, the built __main.bc.js__ code should be much smaller than the current one.

**Comment by dbuenzli** [comment]
A simple hello world doesn't contain all these things so that may be due to the library you are using. `js_of_ocaml` should perform dead code elimination but if a library has toplevel initialisation statements (e.g. `let () = ... `) that can't be eliminated. Check your dependencies.
