### ISSUE TITLE
Create bindings for JS library

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#718]
For learning purposes, I'm trying to create a very small example of jsoo bindings for an existing JavaScript library. To simplify, I'm using [`is-sorted`](https://github.com/dcousens/is-sorted), which just exports a function that given an array, returns a boolean value `true` if the input array is sorted.

Ideally, the bindings would work for jsoo apps running on Node or the browser. 

I'm taking inspiration from the bindings in the `virtual-dom` library in [`janestree/virtual-dom`](https://github.com/janestreet/virtual_dom/tree/master/lib).

A commit with these changes can be seen in https://github.com/jchavarri/hello-jsoo-esy/commit/62ab2216fdf678a3ebbffdc0243a96c7971c1d9d (uses  esy and Reason syntax).

The steps I followed are:

1. Create a `js` file that imports the module with `require` and exports both commonjs and global values:

```js
// isSorted.js
var isSorted = require('is-sorted');
global.IsSorted = isSorted;
module.exports = isSorted;
```

2. Process that file with `browserify` to create a compiled version `isSorted.compiled.js`.
3. Write the bindings in `is_sorted.ml` (or `IsSorted.re`), using the global exported from above:
```reason
let sorted: 'a array -> bool =
  fun a  ->
    Js.to_bool (
      Js.Unsafe.fun_call
        Js.Unsafe.global##.IsSorted
        [|(Js.Unsafe.inject (Js.array a))|]
    )
```
4. Configure dune:
```
(library
  (name IsSorted)
  (wrapped false)
  (js_of_ocaml (javascript_files "./isSorted.compiled.js"))
  (preprocess (pps js_of_ocaml-ppx))
)
```

5. Consume the bindings normally as any other module.

---

I wonder if this is the recommended approach? Consuming the library through the global JS namespace is dangerous, as if the user happens to overwrite `IsSorted` global value, any call to the bindings afterwards would break.

Is there a better way to create bindings, and / or any examples that I could take as guidance?

**Comment by hhugo** [comment]
cc @TyOverby

Having a way to better integrate with the js ecosystem would be nice.
It seems that many people have many different ideas to achieve that. I am unfortunately not familiar enough with this ecosystem. In particular, I'm very lost with the various technology arround bundle js files (browserify, webpack, commonjs, requirejs, amd, ..).

Have you considered no having js_of_ocaml do the bundling with external javascript libraries ?
That is:
- the ocaml code would rely on require `let is_sorted : sometype = require("is-sorted")`
- use browerify (or other tools) to bundle the ocaml program compiled to javascript and its javascript dependencies

**Comment by jchavarri** [comment]
I'm not sure if that would solve the problem. Are you suggesting that the person that handles the bundling is the bindings author? Or the bindings consumer? Ideally, the library author would declare the dependencies in `package.json` and use a mechanism that abstracts over `require` or `import`, so the library consumer can decide how those dependencies are handled. The main issue that I see is that there is no generic way to declare those dependencies in `jsoo`, the lib author has to choose between either `require` (commonjs) or `import` (es6). In BuckleScript there is `[@bs.module]` to abstract over this, although I understand there are many differences: https://bucklescript.github.io/docs/en/interop-cheatsheet#module

A project that allows to use a ppx to require JS modules is commonjs_of_ocaml: https://github.com/AngryLawyer/commonjs_of_ocaml/.

Kind of related, I was thinking today if jsoo could leverage [fastpack](https://github.com/fastpack/fastpack/) for this. Fastpack is 100% written in OCaml. If fastpack provided a "library mode" that could be used by jsoo, then the `[%js.require]` annotations mentioned above could potentially be resolved with fastpack. cc @andreypopp @zindel.

Another idea is to make the JS modules resolving engine part of Dune.... 🤔 It already handles the `javascript_files` part, so it seems natural to evolve in that direction.

**Comment by jchavarri** [comment]
@hhugo I have continued the explorations on how to bundle JS libraries to be used from jsoo.

Most libraries expose bundles in [UMD](https://github.com/umdjs/umd) format, which injects a property in the global object.

I've had some success loading UMD modules in jsoo, so if I'm writing bindings for example for `react-apollo` which provides a [UMD build](https://unpkg.com/react-apollo@2.5.6/react-apollo.umd.js), the bindings repo will have:
- `package.json` that points to the version of `react-apollo` the bindings depend on
- `node_modules` with the actual JS package
- `dune` with `(js_of_ocaml (javascript_files node_modules/react-apollo/react-apollo.umd.js))`

And that works fine, no Browserify needed, or any other indirection.

However, some umd bundles (like React 😅 ) include `use strict` at the top of the module (see https://unpkg.com/react@16.8.6/umd/react.development.js).

`use strict` works fine under the assumption that these modules will be loaded in the global scope / context, but because jsoo wraps all the resulting code to pass `joo_global_object`, the assignment to the global object fails: due to the strict mode, the "global `this`" is undefined.

I have a couple of questions:

1. Is the approach with umd ok or are there any downsides you can see?
2. Is there a way to fix the strict issue mentioned above? I'm thinking on a loading mode that doesn't wrap the JS module in any function, like `(js_of_ocaml (raw_module node_modules/react/umd/react.development.js))`

**Comment by jchavarri** [comment]
@Lupus asked on the OCaml discord about a public place to post the notes below, and I thought this issue would be a good place (and also take the opportunity to close it 🙂 ). This is the approach that ended up working for me, maybe it helps others.

**Note you can always pass the resulting JS bundle that js_of_ocaml + dune generates to Webpack or any other JS bundler, for any further processing.** 

Based on that, something I found that works well is the following:

- dune allows to specify a stanza `javascript_files` so that libraries can specify runtime js files: https://jbuilder.readthedocs.io/en/latest/dune-files.html?highlight=javascript_files#js-of-ocaml

- each module in your project that wraps over js files (say, some bindings library) adds a `.js` file that imports the JS modules you want and puts them under jsoo scope. For example, for some bindings to `crypto-js` lib, you would have a `crypto.js` file with
 
    ```js
    import sha256 from 'crypto-js/sha256’; // can use `require` as well
    joo_global_object.__LIB__crypto = sha256;
    ```

    and the dune file:

    ```dune
    (library
      (name crypto_js)
      (js_of_ocaml (javascript_files “./crypto.js”))
    )
    ``` 

- then, on the OCaml side, you would create bindings to that function using gen_js_api, e.g. in crypto.mli:

    ```ocaml
    val sha256: string -> string; [@@js.global "__LIB__crypto"]
    ```

And that’s it. Dune will leave any `import` and `require` statements in resulting js file, and webpack can then pick it up to solve all JavaScript dependencies as usual.

Upsides:
- Bindings authors don't need to bundle JS deps by themselves (using [browserify](https://github.com/janestreet/virtual_dom/blob/master/lib/package.json#L3)) or any other mechanisms
- `js_of_ocaml` doesn't need to process all the JS code from the JS libraries, which significantly reduces the build times and make dev experience lighter
- Users of bindings can still use js_of_ocaml, but still leverage all the features from JS bundlers, like [code splitting](https://reactjs.org/docs/code-splitting.html).

Downsides:
- Part of the burden is moved to consumers of the bindings, which have to make sure they download and handle the JS dependencies as well as OCaml dependencies.

There's an example of this kind of setup [in `jsoo-react`](https://github.com/jchavarri/jsoo-react/tree/677a75a5b64cc5d22c790e5dd3cafab382805e87/example) (`jsoo-react` is an ongoing effort to have React.js bindings for js_of_ocaml).

With the setup explained above, Node.js apps works just fine, and browser apps can use any existing bundler to resolve all `require`s included in resulting file generated by dune.

**Comment by hhugo** [comment]
Thank you for the writing. We should probably turn that into a document of some sort with more visibility

**Comment by tcoopman** [comment]
This, together with https://github.com/reason-in-barcelona/jsoo-react#with-webpack-or-any-javascript-bundler helped me get started with `jsoo`, `dune` and `node_modules`.
I must say that it was quite a big struggle to do something that seems like something a lot of people who use `jsoo` would want to do. Giving it more visibility would definitely be useful
