### ISSUE TITLE
"Error: cannot parse file" when JS file includes property named "default"

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#722]
When trying to parse this (in theory) valid JS file:

```
function test() {
  var t = {default: 5};
  return t.default;
}
```

passing it to `javascript_files` with Dune, I get the following error:

```
/Users/javi/.esy/3/i/opam__s__js__of__ocaml_compiler-3.2.1-c051fbc8/bin/js_of_ocaml: Error: cannot parse file
```

If I rename `default` to anything else, it works. It has to be done in both places though:

```
function test() {
  var t = {def: 5};
  return t.def;
}
```

Leaving `default` in either the object literal or the `return` statement will fail.

**Comment by jchavarri** [comment]
Another case that fails to parse:

```
Symbol.for;
```

**Comment by jchavarri** [comment]
And also:

```
var inst = {return: 2};
console.log(inst.return);
```

**Comment by jchavarri** [comment]
Another:

```js
var t = {};
t.delete = 2;
```

**Comment by hhugo** [comment]
This should be fixed on master. See https://github.com/ocsigen/js_of_ocaml/issues/713
.

**Comment by jchavarri** [comment]
Ah, cool! I hadn't seen that issue. I will test with master and report back 👍

**Comment by hhugo** [comment]
It seems that this is fixed.
