### ISSUE TITLE
Buffer deprecation warning

### ISSUE THREAD

**Issue by thangngoc89** [ocsigen/js_of_ocaml#726]
This is a deprecation warning of Node.js when using jsoo:

> DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the 
> Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

You can see details here : https://nodejs.org/api/buffer.html#buffer_new_buffer_string_encoding

This constructor has been deprecated since Node v6.0.0 and I think it would be safe to remove it right now since 6.x is in maintenance LTS

**Comment by corwin-of-amber** [comment]
I noticed that this was closed recently, have you decided not to fix it?

**Comment by hhugo** [comment]
I was closed automatically when I pushed the fix.
https://github.com/ocsigen/js_of_ocaml/commit/5de09db6b80f0969cf2529722af24b6544dcd37b

**Comment by corwin-of-amber** [comment]
Splendid! Waiting for next release then 😉
