### ISSUE TITLE
Incorrect code generated when pattern matching against "typeof"

### ISSUE THREAD

**Issue by sanduteo95** [ocsigen/js_of_ocaml#739]
The problem arises when generating JavaScript for a function such as:
```
let f x = match Obj.is_int x with
  | true -> print_string("true")
  | false -> print_string("false")

let _ = f (Obj.repr "test")
```

This checks if an object that is passed into `f` is an `int`, so in JavaScript it corresponds to checking if `typeof x === "number"` is `true`. 

`js_of_ocaml`, in turn, generates the following:
```
var match = typeof x === "number";
if (0 === match) {
// false case
}
```
The generate code is obviously not correct, since match will always be a boolean and `0 === match` will always evaluate to false.

The following code seems to work, so it's only when pattern matching against booleans that we see a problem:
```
let f x = if Obj.is_int x then print_string("true") else print_string("false")

let _ = f (Obj.repr "test")
```

Running version `3.3.0` of `js_of_ocaml`.

**Comment by hhugo** [comment]
Thanks for the report. I've pushed a fix on master
