### ISSUE TITLE
js_string and console.log

### ISSUE THREAD

**Issue by thery** [ocsigen/js_of_ocaml#750]
Hi,

I am using  `Js.string`  `Js.to_string` to convert `Ocaml` strings and `Javascript` strings.
When running the code everything seems ok except I got an echo of some strings on the console.
I had a look at the generated code and it seems that it comes from:

 
```
 function
  b6(a) {
    var
      b = c;
    if (b.process && b.process.stdout && b.process.stdout.write) b.process.stdout.write(a);
    else {
      if (a.charCodeAt(a.length - 1) == 10) a = a.substr(0, a.length - 1);
      var
        d = b.console;
      d && d.log && d.log(a)
    }
  }
```

is this something I should worry about? 
I am using `js_of_ocaml 3.3.0`

Thanks

**Comment by hhugo** [comment]
There is something in your program writting to stdout. Do you use print_endline anywhere? Can you share your code?

**Comment by thery** [comment]
You are right, mea culpa. I've added some debug I forgot. Sorry about that.
Thanks!
