### ISSUE TITLE
Package `js_of_ocaml.syntax' not found

### ISSUE THREAD

**Issue by fredlnl** [ocsigen/js_of_ocaml#751]
Hi,

the query 
`ocamlfind query js_of_ocaml.syntax`
returns 
ocamlfind: Package `js_of_ocaml.syntax' not found

Despite js_of_ocaml is installed. 
[opamlist.txt](https://github.com/ocsigen/js_of_ocaml/files/2904518/opamlist.txt)

Do you know how to solve this issue ?

**Comment by hhugo** [comment]
`js_of_ocaml.syntax` (the camlp4 syntax extension) has been moved to a separate package, `js_of_ocaml-camlp4`.
Note that this camlp4 syntax extension is not maintained anymore and was removed from the git repo recently.
I would encourage you to switch to the ppx syntax extension (`js_of_ocaml-ppx`)

**Comment by fredlnl** [comment]
Thank you,
I replace js_of_ocaml by js_of_ocaml-camlp4 in my ocamlbuild _tags,
and the conpilation succeed.
