### ISSUE TITLE
Why are numbers converted to scientific notation?

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#753]
Why is the number `1000` compiled into `1e3`?

I think I have to remove this assumption because in some languages, scientific notation produces a non integer type which are not `===`. For example in PHP `1e3 !== 1000` but `1e3 == 1000`.

I'm curious what the motivation was behind compiling `1000` into `1e3`. I think this could be moved into a minifier stage if the goal was to save some bytes.

**Comment by hhugo** [comment]
The goal was indeed to save some bytes.
For rehp, you most likely have your own version of `string_of_number` where you can implement whatever is needed without interfering with javascript, right ?

**Comment by jordwalke** [comment]
Correct, we do - and I've since customized it accordingly. Thanks I was just curious.
