### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by ejgallego** [ocsigen/js_of_ocaml#758]
Dear JSOO devs, it seems that OSX will remove 32 bit support in a near update.

Will that invariably mean that it won't be possible to develop with JSOO from a Mac anymore?

[related discussion https://github.com/ejgallego/jscoq/pull/41] Thanks!

**Comment by hhugo** [comment]
Js_of_ocaml doesn't really care about 32bit vs 64bit. JaneStreet has been using js_of_ocaml with 64bit for a long while now.
The responsibility is on you (or your dependencies) to generate bytecode that will not make assumptions about the size of integers.

**Comment by ejgallego** [comment]
Indeed you are right, I think I'll close this and it is really our fault.
