### ISSUE TITLE
When are things `caml_register_global`'d?

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#759]
I can't tell what items are registered via `caml_register_global`. Where do these things come from? I see that every module is registered via `caml_register_global`, but then a couple of other built-in exceptions are as well. Why do those built in exceptions get registered via globals but no other exceptions do? Is there anything else that is registered as a global besides these things?

Most importantly, is there a way to tell in `parse_bytecode.ml`, that a certain global being registered is a _module_ from some compilation unit?

**Comment by Drup** [comment]
I can't answer the 2nd question, but a "global identifier", in typechecker/compiler parlance, is anything which is in the toplevel scope. The only values that are globals are the builtin constructors (true, false, \dots), the builtin exceptions (the list is [here](https://github.com/ocaml/ocaml/blob/46f901bb947d2744c47e942c79a526bdc7a61e44/typing/predef.ml#L86-L98)) and the toplevel modules/compilation units.

All the other values (including the exceptions) belong to a module, which is already registered, so they don't need to be.

**Comment by jordwalke** [comment]
By looking at the jsoo implementation of parse_bytecode, there appears to be these global constants we're discussing. But then within that category, there are:

global constants that are "named values", and global constants that are not "named values". The "named values" appear to be module names that are registered, as well as the prebuilt exceptions. The non-named values appear to be strings. I am trying to figure out if these are the only "named values" or if there are other ones.

**Comment by hhugo** [comment]
`caml_register_global` is either the result of compiling the `SETGLOBAL` bytecode instuction (https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/parse_bytecode.ml#L1103)
or registering exceptions and constants (https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/parse_bytecode.ml#L2174)  
After looking at the ocaml compiler, I believe `SETGLOBAL` is only emitted to register modules/units. (grep for `Psetglobal`).

**Comment by jordwalke** [comment]
> After looking at the ocaml compiler, I believe SETGLOBAL is only emitted to register modules/units. (grep for Psetglobal).

That would make things much easier.  I think there should be a special node for these module registrations that different language backends in `rehp` can treat differently than registering global constants.
