### ISSUE TITLE
Internal error: "Invalid argument ("index out of bounds")" when compiling sedlex

### ISSUE THREAD

**Issue by benkonz** [ocsigen/js_of_ocaml#769]
# Expected Behavior

A .bc.js file should get created after running js_of_ocaml foo.bc on a compiled ocaml executable that uses sedlex.

# Actual Behavior

js_of_ocaml throws an Error: Invalid_argument("index out of bounds") while compiling

# Steps to reproduce

I've created a public repo here that demonstrates the issue: https://github.com/benkonz/js_of_ocaml_sedlex_bug

Essentially, when using several different lexical rules in sedlex, the js_of_ocaml compiler panics and throws an internal error while processing the bytecode. Removing all but one or two lexical rules fixes the issue, but makes sedlex unusable.

I suspect it has something to do with this: https://github.com/ocsigen/js_of_ocaml/commit/2f31b0a976385ef35f23dc182031aeb4f9e7c797#diff-dcaf86f731d3bdfb931e96a2734eab16R287

**Comment by hhugo** [comment]
Will merge the fix once the CI is green

**Comment by hhugo** [comment]
@benkonz, can you confirm you get the expected behavior ? that is, compilation works and running the code produces the expected result ?

**Comment by hhugo** [comment]
@benkonz, what makes you think it's related to https://github.com/ocsigen/js_of_ocaml/commit/2f31b0a976385ef35f23dc182031aeb4f9e7c797#diff-dcaf86f731d3bdfb931e96a2734eab16R287 ?

**Comment by benkonz** [comment]
> @benkonz, can you confirm you get the expected behavior ? that is, compilation works and running the code produces the expected result ?

I can confirm this fixes it. Thanks.

**Comment by benkonz** [comment]
> @benkonz, what makes you think it's related to [2f31b0a#diff-dcaf86f731d3bdfb931e96a2734eab16R287](https://github.com/ocsigen/js_of_ocaml/commit/2f31b0a976385ef35f23dc182031aeb4f9e7c797#diff-dcaf86f731d3bdfb931e96a2734eab16R287) ?

Just based on what the comment says: `Meanwhile, add guards to prevent Invalid_argument("index out of bounds")`. I didn't look at the stack trace of the error, so you probably know more than me.
