### ISSUE TITLE
Inconsistent treatment of lazy blocks

### ISSUE THREAD

**Issue by corwin-of-amber** [ocsigen/js_of_ocaml#772]
This OCaml program:
```ocaml
let lz = lazy ( List.map (fun x -> x * x) [8;9] )

let rec do_the_lazy_rec n =
    if n = 0 then [] else (Lazy.force lz) :: do_the_lazy_rec (n-1)

let _ =
    do_the_lazy_rec 8
```
when compiled, produces the following implementation of `do_the_lazy_rec`:
```js
function do_the_lazy_rec(n)
{ if(0 === n)return 0;
      var
       _e_=caml_obj_tag(lz),
       _d_=do_the_lazy_rec(n - 1 | 0),
       _f_=250 === _e_?lz[1]:246 === _e_?force_lazy_block(lz):lz;
      return [0,_f_,_d_]}
```
Notice that the tag is read before the recursive call, which then sets the lazy flag to `250`, but the evaluation of `_f_` is using the previous value (`246`) hence trying to invoke `lz[1]` again, although it is no longer a function.

**Comment by corwin-of-amber** [comment]
I would like to comment also, that the implementation of OCaml's `Lazy.force` primitive (as of 4.07.1) is using `Alias`, which is translated to assignment, and this is what's causing the different behavior.

**Comment by hhugo** [comment]
I suspect the issue is (at least partially) due to the fact that we treat `caml_obj_tag` as pure  https://github.com/ocsigen/js_of_ocaml/blob/master/runtime/stdlib.js#L214.
Could you try to remove the `const` annotation on this function in the runtime ?

**Comment by corwin-of-amber** [comment]
I may have done it wrong, but I get the exact same js output with and without the `const`.
My stdlib now looks like this:
```js
//Provides: caml_obj_tag
//Requires: MlBytes
function caml_obj_tag (x) { return (x instanceof Array)?x[0]:(x instanceof MlBytes)?252:1000; }
```

**Comment by hhugo** [comment]
Ok. I won't be able to look at this before next week.
You've mentioned OCaml 4.07.1. Is the code correct with earlier versions of ocaml?

**Comment by corwin-of-amber** [comment]
I haven't tested it on other versions, I only mentioned it for completeness and for future reference.

**Comment by hhugo** [comment]
@corwin-of-amber, something must have been wrong with your testing dropping the `const` bit. I think `const` it is the culprit here. I was able to reproduce the issue with the following steps.

```
$ cat a.ml 
let lz = lazy ( List.map (fun x -> x * x) [8;9] )

let rec do_the_lazy_rec n =
    if n = 0 then [] else (Lazy.force lz) :: do_the_lazy_rec (n-1)

let _ =
    do_the_lazy_rec 8
```

``` 
$ ocamlc -g -c a.ml
$ js_of_ocaml a.cmo -o a.without-runtime.js --pretty --no-runtime 
$ js_of_ocaml a.cmo -o a.with-runtime.js --pretty
```

```
$ cat a.without-runtime.js 
(function(joo_global_object)
   {"use strict";
    var runtime=joo_global_object.jsoo_runtime;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    function caml_call2(f,a0,a1)
     {return f.length == 2?f(a0,a1):runtime.caml_call_gen(f,[a0,a1])}
    var
     global_data=runtime.caml_get_global_data(),
     CamlinternalLazy=global_data.CamlinternalLazy,
     Stdlib_list=global_data.Stdlib__list,
     _a_=[0,8,[0,9,0]],
     lz=
      [246,
       function(_e_)
        {function _f_(x){return runtime.caml_mul(x,x)}
         return caml_call2(Stdlib_list[17],_f_,_a_)}];
    function do_the_lazy_rec(n)
     {if(0 === n)return 0;
      var
       _b_=do_the_lazy_rec(n - 1 | 0),
       _c_=runtime.caml_obj_tag(lz),
       _d_=250 === _c_?lz[1]:246 === _c_?caml_call1(CamlinternalLazy[2],lz):lz;
      return [0,_d_,_b_]}
    do_the_lazy_rec(8);
    var A=[0,lz,do_the_lazy_rec];
    runtime.caml_register_global(3,A,"A");
    return}
  (function(){return this}()));
```
```
$ cat a.with-runtime.js 
(function(joo_global_object)
   {"use strict";
    var runtime=joo_global_object.jsoo_runtime;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    function caml_call2(f,a0,a1)
     {return f.length == 2?f(a0,a1):runtime.caml_call_gen(f,[a0,a1])}
    var
     global_data=runtime.caml_get_global_data(),
     CamlinternalLazy=global_data.CamlinternalLazy,
     Stdlib_list=global_data.Stdlib__list,
     _a_=[0,8,[0,9,0]],
     lz=
      [246,
       function(_e_)
        {function _f_(x){return runtime.caml_mul(x,x)}
         return caml_call2(Stdlib_list[17],_f_,_a_)}];
    function do_the_lazy_rec(n)
     {if(0 === n)return 0;
      var
       _c_=runtime.caml_obj_tag(lz),
       _b_=do_the_lazy_rec(n - 1 | 0),
       _d_=250 === _c_?lz[1]:246 === _c_?caml_call1(CamlinternalLazy[2],lz):lz;
      return [0,_d_,_b_]}
    do_the_lazy_rec(8);
    var A=[0,lz,do_the_lazy_rec];
    runtime.caml_register_global(3,A,"A");
    return}
  (function(){return this}()));
```

**Comment by corwin-of-amber** [comment]
Thanks @hhugo, I can confirm that `--no-runtime` produces the correct ordering. I still haven't found the change that's required to `stdlib.js` that would produce correct code when the runtime is included. Is it possible that when running `_build/install/default/bin/js_of_ocaml`, it actually uses the OPAM-installed version of `stdlib.js` rather than the locally modified one?

**Comment by hhugo** [comment]
>  Is it possible that when running _build/install/default/bin/js_of_ocaml, it actually uses the OPAM-installed version of stdlib.js rather than the locally modified one?

Yes, it uses findlib to get the directory of the js_of_ocaml-compiler package.

**Comment by corwin-of-amber** [comment]
Alright! I changed `runtime.js` at the location reported by `ocamlfind query js_of_ocaml-compiler` and the correct ordering was generated.
