### ISSUE TITLE
File offset is unreliable in buffered output channels

### ISSUE THREAD

**Issue by corwin-of-amber** [ocsigen/js_of_ocaml#777]
In `caml_ml_pos_out` and `caml_ml_seek_out` (and their int64 variants), the file offset is manipulated directly, without taking into account data that has been written to the buffer and not flushed.

This causes the offset to be slightly off, and/or some consequent buffer data to be flushed in the wrong position.

I have a branch fixing this and will create a PR.

**Comment by hhugo** [comment]
I see similar behavor with the bytecode compiler.
The following program output `004`

```ocaml
    let oc = open_out "a.txt"
    let () = print_int (out_channel_length oc)
    let () = output_string oc "test"
    let () = print_int (out_channel_length oc)
    let () = flush oc
    let () = print_int (out_channel_length oc)
```

**Comment by hhugo** [comment]
Correction. I have similar behavior with the ocaml toplevel only.

**Comment by hhugo** [comment]
I'm not able to reproduce the problematic behavior anymore.
I've created a test in https://github.com/ocsigen/js_of_ocaml/pull/779

@corwin-of-amber, do you have any example in hand ?

**Comment by corwin-of-amber** [comment]
My example is a bit big (Coq's `.vo` serialization routine), but I will try to make a small test case based on that.

**Comment by hhugo** [comment]
> I'm not able to reproduce the problematic behavior anymore.

To be clear, I'm not able to observe any behavior difference between js_of_ocaml, bytecode and native code.

**Comment by corwin-of-amber** [comment]
Sure, I will test to see that the buggy behavior is not produced by the bytecode and native version of the code.

**Comment by corwin-of-amber** [comment]
This example is perhaps too smart for its own good, the bug can be seen at the first `pos_out` return value; I include the remainder for completeness' sake.

[chan_pos.ml.txt](https://github.com/ocsigen/js_of_ocaml/files/3117927/chan_pos.ml.txt)

In bytecode and native (32-bit), the output is
```
start=4
start=59
```

And it generates the following `out.txt`:
```
% hexdump out.txt
0000000 00 00 22 c4 00 00 00 2b 84 95 a6 be 00 00 00 0f
0000010 00 00 00 04 00 00 00 0c 00 00 00 0a a0 26 6f 75
0000020 74 70 75 74 a0 24 64 61 74 61 40 d1 58 c7 06 8e
0000030 72 93 46 91 09 16 8d 9c d1 f1 a9 00 00 00 61 84
0000040 95 a6 be 00 00 00 0e 00 00 00 04 00 00 00 0c 00
0000050 00 00 0a a0 24 6d 6f 72 65 a0 25 73 74 75 66 66
0000060 40 48 f9 73 62 b7 57 e7 60 4b 06 80 59 9f 63 89
0000070 f5
```

After running `js_of_ocaml chan_pos.exe && node chan_pos.js`, the output is
```
start=0
start=43
```

And this is the output file `out.txt`:
```
% hexdump out.txt
0000000 00 00 22 c4 00 00 00 00 84 95 a6 be 00 00 00 0f
0000010 00 00 00 00 00 00 00 0c 00 00 00 0a a0 26 6f 75
0000020 74 70 75 74 a0 24 64 61 74 61 40 00 00 00 2b 65
0000030 bc 74 12 ef 88 72 ce f8 6a 35 19 72 ac 1a 1a 00
0000040 00 00 00 84 95 a6 be 00 00 00 0e 00 00 00 00 00
0000050 00 00 0c 00 00 00 0a a0 24 6d 6f 72 65 a0 25 73
0000060 74 75 66 66 40 00 00 00 65 d5 3c 5c 7d 3a 42 09
0000070 b5 ca 83 56 e9 2b 25 61 16
```

With the fixed `io.js` from #778, the offsets are the same. The digests are still different, I only just noticed that and haven't yet figured out why.

**Comment by hhugo** [comment]
Thanks.
It seems to me that the fix is just to flush inside caml_ml_seek, like the c runtime does. https://github.com/ocaml/ocaml/blob/trunk/runtime/io.c#L242.

I've done that in https://github.com/ocsigen/js_of_ocaml/pull/779

**Comment by hhugo** [comment]
After adding your example, I saw that the other flushes were needed as well.
I'll merge the fix.
