### ISSUE TITLE
Automatically convert ocaml record to js object with deriving

### ISSUE THREAD

**Issue by goodmind** [ocsigen/js_of_ocaml#789]
Is this possible to achieve?

**Comment by hhugo** [comment]
It is possible to write a ppx converter to do that but I'm not aware of any existing code.
I can try to provide some guidance if you want to contribute.

**Comment by copy** [comment]
There's an existing ppx for this: https://github.com/little-arhat/ppx_jsobject_conv

**Comment by TyOverby** [comment]
There is a very similar ppx for python.  I'm not sure if this ppx is internal to Jane Street, but even if it is, I don't think that there should be any issue with open sourcing it.  We might be able to share a considerable amount of code!  I'll report back on Monday!

**Comment by hhugo** [comment]
Closing. see ppx_jsobject_conv
