### ISSUE TITLE
Differing behavior in printf float rounding

### ISSUE THREAD

**Issue by bcc32** [ocsigen/js_of_ocaml#796]
It appears that printf float rounding behavior is different between the regular runtime and the jsoo runtime:

```ocaml
let x = 10_000. /. 1024.
let () = printf "%g\n" x
```

The exact value is 9.765625.

- Native code prints `9.76562` (round half to even)
- JSOO prints `9.76563` (round half up)

**Comment by TyOverby** [comment]
I can reproduce this easily in the [js_of_ocaml toplevel](https://ocsigen.org/js_of_ocaml/3.1.0/manual/files/toplevel/index.html). 

There does not appear to be an issue with `printf "%f" x`.

The docs for `%g` say

> g or G: convert a floating-point argument to decimal notation, in style f or e, E (whichever is more compact). Moreover, any trailing zeros are removed from the fractional part of the result and the decimal-point character is removed if there is no fractional part remaining.

@bcc32: maybe I'm missing something, but I would expect `%g` to be identical to `%f` (for this example) in both native and JSOO.  Why does native do any rounding?

**Comment by hhugo** [comment]
The default precision for printing float is 6 (see https://github.com/ocaml/ocaml/blob/trunk/stdlib/camlinternalFormat.ml#L222).
The precision has different meaning for "%g" and "%f".

Quoting https://linux.die.net/man/3/sprintf
> This gives the minimum number of digits to appear for d, i, o, u, x, and X conversions, the number of digits to appear after the radix character for a, A, e, E, f, and F conversions, the maximum number of significant digits for g and G conversions

Both javascript and native round to nearest by default. The difference is about how they resolve the tie.

For native (https://www.gnu.org/software/libc/manual/html_node/Rounding.html)
> Round to nearest.
This is the default mode. It should be used unless there is a specific need for one of the others. In this mode results are rounded to the nearest representable value. If the result is midway between two representable values, the even representable is chosen
 
For JavaScript: I think x.toFixed(n) resolves tie away from zero

**Comment by TyOverby** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round$revision/1383484
