### ISSUE TITLE
Declaration of intent: Adding testability for sourcemap compilation

### ISSUE THREAD

**Issue by TyOverby** [ocsigen/js_of_ocaml#799]
I'm filing this issue so that hopefully no one else starts working on the same thing at the same time without knowing that I'm working on something similar.

My goal is to add helpers to the expect_test compilers test in a way that would permit us to easily write tests that take the compiled source map results and format them in a way that make for good expect tests.

**Comment by Drup** [comment]
@TyOverby Happy to see you working on that. I'm working on this: https://github.com/Drup/modulectomy 
It requires pretty good sourcemaps for declarations notably, and preferably for the optimized, minimized, final code:

**Comment by hhugo** [comment]
I don't think anything is going on on that front. Closing.
