### ISSUE TITLE
stdio redirection

### ISSUE THREAD

**Issue by dbuenzli** [ocsigen/js_of_ocaml#80]
I see that `printf`'s are automatically redirected to the browser console which is nice (`printf` is still my debugging tool of choice). 

Is that behaviour documented somewhere ? And is it possible to capture that output to redirect it somewhere else (e.g. to make it visible on the webpage). It couldn't find anything about that in the docs.

**Comment by nathancarter** [comment]
I cannot seem to make `set_channel_flusher` work.  Are there docs on this somewhere?  I searched but found none.

**Comment by hhugo** [comment]
What are you trying to do ? what do you mean by `I cannot seem to make set_channel_flusher work` ?

3 lines documentation here
https://github.com/ocsigen/js_of_ocaml/blob/master/lib/sys_js.mli#L24

As an example, it is used here https://github.com/ocsigen/js_of_ocaml/blob/master/toplevel/toplevel.cppo.ml#L350

**Comment by nathancarter** [comment]
My apologies; I'm just learning OCaml now, and it turns out my error was elsewhere.  But your pointers to the docs and example were helpful in isolating the problem!
