### ISSUE TITLE
Can't use externals with profile=prod

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#804]
If I have an external in `src/App.ml`:

```ocaml
external render : int -> unit = "render"
```

And compile with dune:

```
dune build --profile=prod ./src/App.bc.js
```

I get an error:

```bash
File "_none_", line 1:
Error: Error while linking src/App.cma(App):
The external function `render' is not available
```

I guess this is due to minification? Is there a work around?

**Comment by hhugo** [comment]
This is an error from the ocaml linker when generating `App.bc`.
Do you really need to use an external ? Can't you use `Js.Unsafe.variable` ?

The js_of_ocaml lib deals with externals by generating dummy stubs. see https://github.com/ocsigen/js_of_ocaml/blob/master/lib/js_of_ocaml/js_of_ocaml_stubs.c

**Comment by jchavarri** [comment]
@hhugo thanks! I didn't think about that. Adding stubs fixed the problem. (for anyone else interested, one has to add `(c_names NameOfModule)` to dune as well).

> Do you really need to use an external ?

I find much much easier to write JS bindings with externals than with the `Js.Unsafe` api 😅 It also helps me "think better", as there is a very clear boundary between the OCaml side and the JS side, so I can keep all the JS-only types in the JS side.
