### ISSUE TITLE
Expose a ppxlib-friendly version of jsoo ppx?

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#811]
I have an edge use case where I'm using jsoo ppx as a library. In rroo ppx, I build ast nodes that represent function applications of `##.` and feed the resulting expression to `Ppx_js`:

https://github.com/jchavarri/rroo/blob/83f071016bf3a46fe137f420a2c6af4925b5af32/ppx/Rroo_jsoo_ppx.re#L1145-L1162

This worked great so far. 🎉 

I am now [migrating rroo ppx to ppxlib](https://github.com/jchavarri/rroo/issues/5). I'm using `register_transformation` and try to avoid `Ast_mapper`, as I am trying to go "all-in" with ppxlib.

However, when reaching this case, I realized I needed a mapper. So I tried to migrate this specific "resolution" of `##.` with something like this:

```reason
Ppx_js.mapper.expr(
  Ocaml_common.Ast_mapper.default_mapper,
  [%expr bla ##. foo],
),
```

But I run into the problem of AST compatibility as soon as I try to use the resulting expression anywhere. As far as I understand, `Ppx_js.mapper.expr` produces expressions of one AST using omp, and this is, afaik, irreconcilable with the AST that ppxlib exposes.

Would there be a way for jsoo to expose a ppxlib friendly expression handler? Or is there a way to use jsoo ppx from a different ppx that uses ppxlib, without falling back to omp and `Ast_mapper` again?

@hhugo I am happy to move this issue somewhere else if it's not actionable from the jsoo side. 🙂 

cc @diml as this seems related to https://github.com/ocaml-ppx/ppxlib/issues/23.

**Comment by hhugo** [comment]
You should be able to get a mapper for whatever ast you need with:

```ocaml
module Converter =
  Migrate_parsetree.Versions.Convert (Migrate_parsetree.OCaml_407) (Ppxlib_ast.Selected_ast)

let mapper = Converter.copy_mapper Ppx_js.mapper
```

**Comment by jchavarri** [comment]
Oh wow, I didn't know about `Convert`, thanks!

Just to be sure, I would also need to pass `Ocaml_common.Ast_mapper.default_mapper` through `Converter` to use it, right?

```ocaml
let default_mapper = Converter.copy_mapper Ocaml_common.Ast_mapper.default_mapper
```

**Comment by hhugo** [comment]
I think you need just pass the ppx_js mapper directly
