### ISSUE TITLE
JS output size is much larger than expected

### ISSUE THREAD

**Issue by TyOverby** [ocsigen/js_of_ocaml#812]
When compiling a Hello World Incr_dom application using `dune --profile release`, a Javascript file of size 780KB is produced.

Granted, this does mean that all of `Core_kernel`,  `Async_js` and many other libraries are compiled into it, but I would expect the tree-shaker to do a much better job.  Is there something at the language or library level getting in the way of further optimizing binary sizes?

**Comment by hhugo** [comment]
One thing you can do is get rid of inline tests (https://github.com/janestreet/core_kernel/issues/74)

**Comment by TyOverby** [comment]
That moves it from 780KB to 766KB

**Comment by smuenzel** [comment]
Is the module_timer ppx (https://github.com/janestreet/ppx_module_timer) causing unnecessary code to be included or is that benign?
