### ISSUE TITLE
text_attr should have `X and `Y

### ISSUE THREAD

**Issue by aecepoglu** [ocsigen/js_of_ocaml#821]
As per https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text#Attributes , x and y are valid attributes for `<text>` and should be supported.

**Comment by hhugo** [comment]
This is already supported.
see `inherit textPositioningElement` (https://github.com/ocsigen/js_of_ocaml/blob/master/lib/js_of_ocaml/dom_svg.mli#L1242)
