### ISSUE TITLE
#trace directive in toplevel doesn't have any effects

### ISSUE THREAD

**Issue by thangngoc89** [ocsigen/js_of_ocaml#823]
When enable trace inside toplevel, it doesn't print out anything. Is this a limitation or a bug?

**Comment by dbuenzli** [comment]
Can't make it work here either but for other reasons it seems:
```
        OCaml version 4.07.1 -- courtesy of js_of_ocaml 3.4.0
 
# let rec fact x = if x < 1 then 1 else x * fact (x - 1);;
val fact : int -> int = <fun>
# #trace fact;;
fact is not a function.
```

**Comment by thangngoc89** [comment]
@dbuenzli You're right, not sure when the behavior changed.
https://sketch.sh/s/Z3XBFGtXbBvCOIxFN12gby/

**Comment by hhugo** [comment]
I'm fixing the error that @dbuenzli  reported.
I don't think `#trace` has ever been supported by jsoo (due to technical limitation)
