### ISSUE TITLE
Passing additional options to addEventListener

### ISSUE THREAD

**Issue by monstasat** [ocsigen/js_of_ocaml#824]
For now there is no way to pass additional options to `addEventListener` method of `eventTarget` class. Js_of_ocaml only provides [old-fashioned signature](https://github.com/ocsigen/js_of_ocaml/blob/0cea012cfd59173a9ce1ae655b6c9f35eef36ed3/lib/js_of_ocaml/dom.mli#L337) for `addEventListener`, where only `useCapture` flag can be passed. [Here](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) are the docs for options that can be passed to `addEventListener`. IMO, at least `passive` option should be also added to jsoo bindings (`Dom`, `Dom_html`, and `Lwt_js_events` modules). 

Are there any reasons why this is still not a part of jsoo? Would you accept a PR if I implement this feature?

**Comment by monstasat** [comment]
I've noticed that a corresponding PR (#801) already exists.
However, it lacks updates for `Lwt_js_events` modules.
As @facelesspanda mentions in his PR, options can be passed to `addEventListener` as a single object or as optional arguments. I think passing optional arguments is a better option, as we can check browser support for additional options like `passive` and `once` and ignore them if not supported.
As for the `Lwt_js_events` module, the `once` option seems redundant because event listener is added once again after every event occurrence, so we may need to add only `passive` and `use_capture` optional arguments to existing functions.

**Comment by hhugo** [comment]
#807 has been merged. PR welcome to add the corresponding feature in `Lwt_js_events`.

**Comment by monstasat** [comment]
PR #866 implements the `passive` feature for `Lwt_js_events`.
