### ISSUE TITLE
Runtime: implement caml_hash_string

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#864]
following https://github.com/ocaml/ocaml/pull/8878

**Comment by alainfrisch** [comment]
(Just to be clear: the OCaml PR hasn't been merged yet, and the name of the primitive might even change.  So it might be too early to merge this one.  But it's impressive how fast you are tracking changes to the OCaml runtime system in js_of_ocaml!)

**Comment by hhugo** [comment]
We now have tests that would detect whenever a new primitives is added. We don't need to keep that issue open.
