### ISSUE TITLE
Equality on Big_int should fail but doesn't

### ISSUE THREAD

**Issue by rumkeller** [ocsigen/js_of_ocaml#865]
```ocaml
$ cat big.ml
let n = Big_int.big_int_of_int 42 in
print_endline (if n = n then "yes" else "no")
```
This progam succeeds when compiled with `js_of_ocaml`:
```
$ ocamlfind ocamlc -package num -linkpkg -o big.byte big.ml
$ js_of_ocaml --pretty +nat.js big.byte
$ node big.js
yes
```
...but it raises an exception when compiled with `ocamlc`:
```
$ ocamlfind ocamlc -package num -linkpkg -o big big.ml
$ ./big
Fatal error: exception Invalid_argument("compare: abstract value")
2
```
```shell
$ js_of_ocaml --version
3.4.0
$ ocamlc --version
4.07.1
```

**Comment by rumkeller** [comment]
Perhaps this is a duplicate of #584.

**Comment by hhugo** [comment]
Big_int is not well supported (see https://github.com/ocsigen/js_of_ocaml/issues/320).
There is some work going on to support zarith fully (see https://github.com/ocsigen/js_of_ocaml/issues/586)

**Comment by hhugo** [comment]
I have a fix in https://github.com/ocsigen/js_of_ocaml/pull/889 and https://github.com/ocaml/num/pull/16.
Do you actually use the num library with js_of_ocaml ?

**Comment by hhugo** [comment]
Fixed by https://github.com/ocsigen/js_of_ocaml/pull/889
