### ISSUE TITLE
[BUG] String literals containing "</script>" and embedded Javascript interact badly

### ISSUE THREAD

**Issue by sbriais** [ocsigen/js_of_ocaml#898]
**Describe the bug**
```
echo 'let () = print_endline "hello </script>"' > helloscript.ml
ocamlc -o helloscript helloscript.ml
js_of_ocaml helloscript
echo '<!DOCTYPE html>' > helloscript.html
echo '<script>' >> helloscript.html
cat helloscript.js >> helloscript.html
echo '</script>' >> helloscript.html
```

Visiting `helloscript.html` produces an error in the browser.
(eg with Firefox we get Syntax Error "" literal not terminated before the end of the script) 

The bug occurs because of the "</script>" substring. 

**Expected behavior**
We expect js_of_ocaml to handle this case for us.

**Versions**
ocaml 4.08
js_of_ocaml 3.4.0

**Comment by alainfrisch** [comment]
Ref: https://stackoverflow.com/questions/28643272/how-to-include-an-escapedscript-script-tag-in-a-javascript-variable

 (one could also escape < or / in the JS string literals that contain `</script>`, using JS Unicode escape \u...).

**Comment by dbuenzli** [comment]
> We expect js_of_ocaml to handle this case for us.

To be honest I wouldn't qualify this as a bug. When you embed a language into another you are the one who is responsible to escape it properly.

**Comment by alainfrisch** [comment]
Right, but (1) the fix in js_of_ocaml would be quite simple (such as putting `/*<!--*/"..."/*-->*/` around all string literals -- or just the one containing `</script>` (modulo casing,etc); or emitting `<` in JS strings as `\u...`); (2) the workaround outside js_of_ocaml is a bit tedious since it needs to parsing JS syntax; (3) users could easily be faced with the problem, and this is likely to be reported as a deficiency of js_of_ocaml.

**Comment by dbuenzli** [comment]
I don't mind if `js_of_ocaml` wants to solve this (though this should likely under a flag, people rather want from jsoo to produce minimal outputs). 

However note that in general you may also have to link with foreign, non jsoo generated JavaScript which might have the same problem.

So you likely want to pass all of your js through some kind of escaper tool if you want to build html files with inline scripts.

**Comment by hhugo** [comment]
> When script or style data is the content of an element (SCRIPT and STYLE), the data begins immediately after the element start tag and ends at the first ETAGO ("</") delimiter followed by a name start character ([a-zA-Z]); note that this may not be the element's end tag. Authors should therefore escape "</" within the content. Escape mechanisms are specific to each scripting or style sheet language.
>
>ILLEGAL EXAMPLE:
> The following script data incorrectly contains a "</" sequence (as part of "</EM>") before the SCRIPT end tag:
> 
>     <SCRIPT type="text/javascript">
>       document.write ("<EM>This won't work</EM>")
>     </SCRIPT>
>
> In JavaScript, this code can be expressed legally by hiding the ETAGO delimiter before an SGML name start character:
> 
>     <SCRIPT type="text/javascript">
>       document.write ("<EM>This will work<\/EM>")
>     </SCRIPT>

Is it enough to turn `</` into `<\/` ?

**Comment by hhugo** [comment]
ref https://www.w3.org/TR/REC-html40/appendix/notes.html#notes-specifying-data

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/commit/cbadddc24841ca2a7d8f46da84d63a9c74fc224e

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/899
