### ISSUE TITLE
[FEATURE REQUEST] Should caml_compare_val be able to compare JS strings?

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#900]
If using external values, right now `caml_compare_val` will fail, but you might want to use polymorphic compare on external values. At the very least, I think strings are one data type for which we could compute a comparison if we detect the type is a JS string.

```
(typeof s === 'string' | s instanceof String)
```
(The later `instanceof` check is required to cover cases of `new String(s)`).

If the two items are both strings then comparison is `s2 === s2 ? 0 : s1 < s2 ? -1 : 1`

Is this a good idea?

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/896

**Comment by hhugo** [comment]
`s2 === s2 ? 0 : s1 < s2 ? -1 : 1` doesn't work when s1 or s2 are instanceof `String`

**Comment by hhugo** [comment]
To be clear, #896 will restore (most of) the behavior of jsoo before https://github.com/ocsigen/js_of_ocaml/pull/889, that is `do not raise on javsacript values`.

Now regarding comparison of JavaScript string, here is what JavaScript does:
- if one of the two arguments is a primitive string, `<`, `>`, `==`, `!=` will work as expected.
- if the two arguments are String objects,  `<`, `>` will work as expected, but `==` and `!=` will only check if objects are the same or not.

**Comment by hhugo** [comment]
#896 should now address your request in full.
