### ISSUE TITLE
Add support for unix_isatty

### ISSUE THREAD

**Issue by bandersongit** [ocsigen/js_of_ocaml#913]
The [Pastel text highlighting library](https://www.npmjs.com/package/@reason-native/pastel) uses Unix.isatty as part of the logic to determine whether the host terminal supports color. There aren't currently stubs for this so compiling with JSOO requires consumers to provide an implementation. You can see https://github.com/facebookexperimental/reason-native/issues/207 for an an example of this.

I see a couple possible naive approaches: 
a) bind Unix.stdin, Unix.stdout, Unix.stderr to NodeJS's process.stdin, process.stdout, Process.stderr and implement unix_isatty as `stream => stream. isTTY)
b) use NodeJS's tty.isatty( ) along with numeric file descriptors

However I have noticed that runtime's fs implementation has both node based and a non non based (fake) modules that it uses, so I could see doing something like that as well to have different behavior in a browser environment (for example I've verified that ansi escape sequences work in chrome's developer console, however none of the node js modules/functions I described are available in that environment)

**Comment by hhugo** [comment]
> ansi escape sequences work in chrome's developer console

Is that true ? I was not able to make this work.

I would probably go for (b), PR welcome

**Comment by bandersongit** [comment]
> > ansi escape sequences work in chrome's developer console
> 
> Is that true ? I was not able to make this work.

When I was first playing with Rely and JSOO a few months ago in chrome I was able to get this colorized output
![image](https://user-images.githubusercontent.com/5252755/68522933-a700f900-0266-11ea-8ed3-610d5f74222b.png)
 (the weird unicode character thing was fixed by https://github.com/ocsigen/js_of_ocaml/issues/798, but I had the screenshot lying around).

Also for a simpler example
![image](https://user-images.githubusercontent.com/5252755/68523064-322ebe80-0268-11ea-8c82-4129353c074c.png)


> I would probably go for (b), PR welcome

Sounds good, I'll make some time for this in the next several days.
