### ISSUE TITLE
Deriving Json: inline notation no longer supported?

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#918]
**Describe the bug**
An expression `[%derive.json: cookie_array]` no longer compiles:
```
File "src/lib/eliom_cookies_base.shared.ml", line 21, characters 28-39:
Error: Deriver json does not support inline notation
```

**Versions**
This compiles with Js_of_ocaml 3.4 but not Js_of_ocaml 3.5

**Comment by hhugo** [comment]
I think the syntax changed a little when we switch to ppxlib (https://github.com/ocsigen/js_of_ocaml/pull/809)

Try this syntax
```
[%json: cookie_array] 
```

**Comment by vouillon** [comment]
This seems to work, indeed, with the following changes:

before   |   now
---|---
`derive.json` | `json`
`derive.to_json` | `json_of`
`derive.of_json` | `of_json`

**Comment by hhugo** [comment]
I created #922 to document the syntax a bit.

It also include a change to allow `[%to_json]` in addition to `[%json_of]`.
This should make the transition easier and also keep some symmetry with names generated from `[@@deriving json]`

**Comment by hhugo** [comment]
I've added some documentation for upgrading to 3.5
https://github.com/ocsigen/js_of_ocaml/wiki/Upgrade-from-3.4.0-to-3.5.0

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/15312
