### ISSUE TITLE
Minor release 3.5.1

### ISSUE THREAD

**Issue by hhugo** [ocsigen/js_of_ocaml#919]
- [x] js_of_ocaml.deriving should not export `import.ml` #917
- [x] fix polymorphic compare with null and undefined https://github.com/ocsigen/js_of_ocaml/pull/920
- [x] #921 
- [x] document new syntax for ppx_deriving_json, #918, #922

**Comment by hhugo** [comment]
@vouillon, can you let me know when you're done testing eliom with the new js_of_ocaml

**Comment by vouillon** [comment]
I had to do the change in #921. I have not encountered any other issue.

**Comment by hhugo** [comment]
Why do you need 921? Is this related to eliom?

**Comment by vouillon** [comment]
This is not directly related to Eliom. At Be Sport, for separate compilation, we are building a binary containing all libraries using the `--dynlink` option and then each `cmo` file is compiled independently. With 3.5, you have to explicitly provide the list of modules to export, which does not seems very convenient.

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/15312

**Comment by hhugo** [comment]
> we are building a binary containing all libraries using the --dynlink option and then each cmo file is compiled independently.

How does that compare to building every single libraries independently ?
