### ISSUE TITLE
[BUG] Incompatibility with 4.09.0

### ISSUE THREAD

**Issue by adrien-n** [ocsigen/js_of_ocaml#936]
When building my code with a 4.09.0 compiler installed with opam, I get the following after cleaning and rebuilding:

    js_of_ocaml: Error: Bytecode version missmatch.
    js_of_ocaml: Error: Your ocaml bytecode and the js_of_ocaml compiler have to be compiled with the same version of ocaml.
    js_of_ocaml: Error: The Js_of_ocaml compiler has been compiled with ocaml version 4.09.0.
    js_of_ocaml: Error: Its seems that your ocaml bytecode has been compiled with a newer version of ocaml.

Installed packages:

    js_of_ocaml                   3.5.1       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-compiler          3.4.0       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-lwt               3.5.1       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-ocamlbuild        3.5.1       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-ppx               3.5.1       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-ppx_deriving_json 3.4.0       Compiler from OCaml bytecode to Javascript
    js_of_ocaml-tyxml             3.5.1       Compiler from OCaml bytecode to Javascript

When I try to "opam upgrade", I get:

    The following packages are not being upgraded because the new versions conflict with other installed packages:
      - js_of_ocaml-compiler.3.5.1
        ∗ eliom.6.9.2 is installed and requires js_of_ocaml-compiler (>= 3.3 & < 3.5)
      - js_of_ocaml-ppx_deriving_json.3.5.1
        ∗ eliom.6.9.2 is installed and requires js_of_ocaml-ppx_deriving_json (>= 3.3 & < 3.5)

Would that be the actual issue? Should the opam data be updated?

PS: sorry for the initial output of "opam upgrade js_of_ocaml-compiler" that you probably got in notifications: I mixed two compiler versions.

**Comment by hhugo** [comment]
js_of_ocaml-compiler 3.4.0, is not compatible with OCaml 4.09.
fixed in https://github.com/ocaml/opam-repository/pull/15498

**Comment by hhugo** [comment]
The change has been merged in opam. Thanks for the report.
