### ISSUE TITLE
How could JavaScript catch exceptions raised by OCaml?

### ISSUE THREAD

**Issue by chengtie** [ocsigen/js_of_ocaml#938]
I have a OCaml projet, which is later converted to JavaScript by `js_of_ocaml`. I wrap some functions like follows:

```
Js.Unsafe.global##.parseFile := Js.wrap_callback
    (fun s -> Js.string (E.parse_file (Js.to_string s)));
```

Then, in JavaScript, I could call `parseFile("abc")`.

In the OCaml code, for example, E.parse_file may raise exceptions by `failwith "this is why"`. I would like to know how to catch this exception in JavaScript code, and eventually catch `this is why`?

```
try {
  parseFile("abc")
}
catch(error) {
  ???
}
```

Additionally, how could JavaScript catch `exit 1` of OCaml?

**Comment by hhugo** [comment]
`try { } catch (e) { }` is the way to go for catching exception. (even ocaml one)

If you want to have control over the kind of exception raised to the JavaScript world. I suggest to catch the exception on the ocaml side and reraise a javascript Error.   
```ocaml
Js.Unsafe.global##.parseFile := Js.wrap_callback
    (fun s ->
      try
        Js.string (E.parse_file (Js.to_string s))
     with
     | Js.Error e -> Js.raise_js_error e
     | Failure s -> Js.raise_js_error (new%js Js.error_constr (Js.string s))
   );
```

with that, the javascript side just sees a JavaScript error.

```javascript
try {
  parseFile("abc")
}
catch(error) {
  console.log(error.toString())
}
```

`exit 1` will raise `Invalid_arg "Function 'exit' not implemented" in a web-browser. See implementation bellow [1]. Just add a new case when matching on the OCaml exception.


[1]
```javascript
function caml_sys_exit (code) {
  var g = joo_global_object;
  if(g.quit) g.quit(code);
  //nodejs
  if(g.process && g.process.exit)
    g.process.exit(code);
  caml_invalid_argument("Function 'exit' not implemented");
}
