### ISSUE TITLE
[FEATURE REQUEST] Futures support or interoperability

### ISSUE THREAD

**Issue by adrien-n** [ocsigen/js_of_ocaml#940]
Javascript futures are used in some APIs. I have no idea how to use such APIs without some compiler help or fairly big wrapper.

Is support for them planned? Is it even possible to integrate them cleanly?

**Comment by hhugo** [comment]
I suppose you're talking about `promise` here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

There exists https://github.com/aantron/repromise

There is another request for adding support for `promise` https://github.com/ocsigen/js_of_ocaml/issues/757

Why do you think compiler help is needed here ?

**Comment by adrien-n** [comment]
Yes, indeed, I was talking about promises. Sorry, I was reading an article and trying to make sense of the API terminology right before checking on the jsoo bug tracker and actually got even more confused by the article. :D 

I'm going to change the title of this PR and close it.

I'll have a look at repromise, thanks.
