### ISSUE TITLE
[FEATURE REQUEST] WebCrypto support

### ISSUE THREAD

**Issue by adrien-n** [ocsigen/js_of_ocaml#941]
I would like to use WebCrypto but there is currently no binding for it (it's still RC but it has been in browsers for several years). Proper bindings will probably depend upon #940 because basically all of the API returns futures. The JS API also uses quite a lot of strings for identification so there's some room for a friendlier API if wanted.

edit: I've started to use the API directly without proper bindings but I figured I should also create a ticket for tracking purposes.

**Comment by hhugo** [comment]
Contributions are welcome. Note that theses bindings could also easily live outside the js_of_ocaml project.

**Comment by adrien-n** [comment]
OK. I'll try to start that way.

BTW, it would probably be useful to expand the documentation to mention such external libs (including ones for promises). I'll try to draft something in the coming days.

**Comment by hhugo** [comment]
#https://github.com/ocsigen/js_of_ocaml/issues/1217

**Comment by dbuenzli** [comment]
It's not jsoo-style API but just in case `brr` has [support](https://erratique.ch/software/brr/doc/Brr_webcrypto/index.html) for webcrypto.

**Comment by hhugo** [comment]
Let's just document external bindings in #1217
