### ISSUE TITLE
Is nat.js included by default now?

### ISSUE THREAD

**Issue by corwin-of-amber** [ocsigen/js_of_ocaml#942]
We switched to 3.5.1. Now when specifying `+nat.js` on the command line, all the symbols in `nat.js` are reported as duplicates.
```
% js_of_ocaml +nat.js prog.cmo
warning: overriding primitive "initialize_nat"
  old: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:0
  new: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:0
warning: overriding primitive "MlNat"
  old: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:11
  new: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:11
warning: overriding primitive "caml_hash_nat"
  old: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:21
  new: /Users/corwin/.opam/jscoq+64bit/lib/js_of_ocaml-compiler/nat.js:21
warning: overriding primitive "nat_of_array"
```
etc.

**Comment by corwin-of-amber** [comment]
cc @ejgallego

**Comment by hhugo** [comment]
`nat.js` is now included by default, yes.

Also note that num was recently updated to behave properly with js_of_ocaml (see  
https://github.com/ocaml/num/pull/16)

**Comment by corwin-of-amber** [comment]
Thanks! That's pretty useful. I only suggest that you update the "Supported features" section of the main page to reflect this change.

<img width="721" alt="Screen Shot 2019-12-12 at 10 52 43" src="https://user-images.githubusercontent.com/704372/70697210-c78cfa80-1ccd-11ea-9521-8538388f8608.png">
