### ISSUE TITLE
[BUG] Marshal.to_string 3.14 [] raises Failure

### ISSUE THREAD

**Issue by kenichi-asai** [ocsigen/js_of_ocaml#958]
```
let str = Marshal.to_string 3. []
let len = String.length str
let _ = print_endline (string_of_int len)
```
The above program runs fine but replacing `3.` with `3.14` produces `0,248,Failure,-3,output_value: abstract value (number)` on Safari.  Is this a bug?

ocamlc 4.04.0, js_of_ocaml 3.5.2, Safari 12.1.2 on macOS Sierra

**Comment by hhugo** [comment]
From the readme
`marshalling of floats is not supported (unmarshalling works);`

Jsoo is not able to differentiate between floats with no decimal part and integer, explaining why marshaling `3.` doesn't raise (it would wrongly marshal it as int though)

**Comment by kenichi-asai** [comment]
Oh, I see.  Thank you.

I wanted to send OCaml values containing floats via socket.io, and tried to convert them into strings using Marshal module.  If I cannot use Marshal module, is there any other way to send OCaml values?

**Comment by dbuenzli** [comment]
> Marshal module

`Marshal` is very unsafe, make sure you go over the details mentioned in this [preamble](https://caml.inria.fr/pub/docs/manual-ocaml-4.09/libref/Marshal.html). This makes it unsuitable to be used in a distributed setting where you don't tightly control producers and consumers. Hence, in particular, on the web.

There are various serialisation technologies available in OCaml I think best for you is to ask for advice on https://discuss.ocaml.org/

**Comment by kenichi-asai** [comment]
Thank you.  Yes, I know `Marshal` is unsafe.  I tried to use it because it is in the standard library and thus I can use it without any installation.  (In my situation, I do have control over produces and consumers.)  I will ask in the caml mailing list; I prefer not to create one more account.

**Comment by dbuenzli** [comment]
> I prefer not to create one more account.

You can login with your github account.
