### ISSUE TITLE
[BUG] modules Js_of_ocaml.CSS.XXX are basically unusable

### ISSUE THREAD

**Issue by facelesspanda** [ocsigen/js_of_ocaml#965]
**Describe the bug**
The following value declaration
```ocaml
  module J = Js_of_ocaml
  let pxf f : J.Js.js_string J.Js.t = J.CSS.Length.(js (Px f))
```
fails to compile with the following error:
```
9 |   let pxf f : J.Js.js_string J.Js.t = J.CSS.Length.(js (Px f))
                                                        ^^^^^^^^^
Error: This expression has type js_t but an expression was expected of type
         J.Js.js_string J.Js.t
```

**Expected behavior**
The expression compiles because `J.CSS.Length.js_t = J.Js.js_string J.Js.t` 
(see https://ocsigen.org/js_of_ocaml/3.5.1/api/js_of_ocaml/Js_of_ocaml/CSS/Length/index.html#val-js )

**Versions**
Ocaml: 4.08.1
Js_of_ocaml: 3.4.0

**Comment by hhugo** [comment]
`type js_t = private Js.js_string Js.t`
The type error you are seen because the type alias is `private`. If you want to get a `js_string`, you can use explicit cohersion `(x :> Js.js_string Js.t)`. Please refer to the ocaml manual).

**Comment by hhugo** [comment]
Please reopen if my answer above doesnt address your issue

**Comment by facelesspanda** [comment]
Well there's nothing wrong with what you said. I knew the type was private. I should have been clearer, sorry: the issue is precisely that this type is private.

I thought the point of the `js` function of those CSS modules was to get a js-world value ready to be passed to things like `elt##.style##.lengthproperty`
I "bypassed/workedaround" the problem by calling `Js.string CSS.Length.(string_of_t (Px f))` directly, but I find that very unsatisfying.

I may try to find a way to make the API better later, and open a PR. Something like an explicit `js_string_of_t` function that returns a non-private `Js.js_string Js.t` value, maybe. Would make it useable.
