### ISSUE TITLE
Making js_of_ocaml compiler self-contained ?

### ISSUE THREAD

**Issue by nojb** [ocsigen/js_of_ocaml#966]
Currently the `js_of_ocaml` compiler requires the `runtime.js` to be installed alongside it. `dune` uses `ocamlfind` to locate `runtime.js`. This means that one needs to have `ocamlfind` to use `js_of_ocaml` and it means that you need to **install** `js_of_ocaml` in order to use it.

To avoid the dependency on `ocamlfind` on Windows I implemented a workaround for `dune` (https://github.com/ocaml/dune/pull/1467). However, I was wondering if you had given any thought to the idea of getting rid of the `runtime.js` file and simply including it as a string in the compiled compiler binary. A flags could be added to produce the file on standard output in case it is needed.

This would make the binary completely self-contained. If there is interest in this proposal I could look into implementing it (together with the necessary adaptations for `dune`). I recently implemented something very similar for `menhir` (which also depends on a "runtime" file like `runtime.js`) and it worked nicely.

**Comment by hhugo** [comment]
This seems reasonable.

Note that there are other runtime files sometime required and not included in `runtime.js`: `dynlink.js`, `toplevel.js`

**Comment by hhugo** [comment]
Work in progress https://github.com/ocsigen/js_of_ocaml/pull/978

**Comment by hhugo** [comment]
This is now done. I'll open a PR to cleanup dune rules later

**Comment by nojb** [comment]
Great, thanks! I will try to test it in a bit.

**Comment by hhugo** [comment]
https://github.com/ocaml/dune/pull/3375

**Comment by bobzhang** [comment]
@hhugo this looks great. 
It seems that `jsoo compile xx.byte` still relies on something from findlib so that I can not copy jsoo byte code to a different machine. 
There are two places where I found depend on findb:
- findlib.ml resolves findlib.conf directly, we can fake findlib.conf using OCAMLFINDLIBCONF though
- jsoo calls `Findlib.find_pkg_dir "stdlib"`, can this be called in a lazy style when it is really needed -- otherwise I guess this still brings in dependencies on findlib/stdlib/META file

**Comment by hhugo** [comment]
@bobzhang, the findlib dependency is optional ! You should be able to build without it.
Just remove the following lines in the dune file
```sexp
    (select findlib_support.ml from
     ;; Only link js_of_ocaml-compiler.findlib-support if it exists
     (js_of_ocaml-compiler.findlib-support -> findlib_support.empty.ml)
     (                                     -> findlib_support.empty.ml))
```

**Comment by bobzhang** [comment]
@hhugo that's exactly what I need. FYI, we have successful stories using the bytecode compiler https://github.com/BuckleScript/bucklescript/pull/4372 -- the motivation is less dependencies for the CI
