### ISSUE TITLE
[FEATURE REQUEST] More TypedArray conversions

### ISSUE THREAD

**Issue by Ngoguey42** [ocsigen/js_of_ocaml#969]
I'm currently using _Owl_ in the browser and I looked everywhere for a simple way to convert any `typedArray` to/from a `Genarray.t`.  The `bigstring` module only works for `1-dim`+`uint8` arrays :(. 
In the end I made my own `external` declaration to perform the conversions.

A series of functions like that could do the trick:
```ml
val float32Array_fromGenarray : (float, Bigarray.float32_elt, Bigarray.c_layout) Bigarray.Genarray.t -> Typed_array.float32Array Js.t
val float32Array_toGenarray : Typed_array.float32Array Js.t -> (float, Bigarray.float32_elt, Bigarray.c_layout) Bigarray.Genarray.t

val int16Array_fromGenarray : (int, Bigarray.int16_signed_elt, Bigarray.c_layout) Bigarray.Genarray.t -> Typed_array.int16Array Js.t
...

```

**Comment by hhugo** [comment]
PR welcome

**Comment by hhugo** [comment]
#970 has been merged, thanks
